/**
 * Country-level "what's it actually like to live here?" metrics.
 *
 * Nine indicators per destination, curated from public sources (OECD,
 * Numbeo, EF EPI, Global Peace Index, KPMG/OECD tax tables, national
 * immigration authorities). Each metric carries an attribution + year so
 * the dashboard tile shows where the number came from — no anonymous
 * numerology, no made-up benchmarks.
 *
 * Coverage today: top ~30 destinations by search volume. For countries
 * without curated data the dashboard renders an honest "Data not yet
 * curated" tile rather than fabricating a value.
 *
 * Three of the nine metrics are route-specific (difficulty, processing
 * time, PR pathway shown contextually) — they're populated from the
 * resolved visa option at call time, not from this static table.
 */
import type { ResolvedVisaOption } from "./types";
import type { DifficultyAssessment } from "./difficulty";

export type EnglishBand = "very_high" | "high" | "moderate" | "low" | "very_low";

export type MetricRating = "very_good" | "good" | "average" | "poor" | "very_poor";

export type CountryMetrics = {
  iso2: string;
  /** OECD-style average annual gross salary, USD PPP. */
  avgSalaryUsd: number | null;
  /** Numbeo Cost of Living Index (NYC = 100). */
  costOfLivingIndex: number | null;
  /** Top marginal personal income tax rate (%). */
  topTaxRatePct: number | null;
  /** Numbeo Healthcare Index (0–100, higher = better). */
  healthcareIndex: number | null;
  /** Global Peace Index rank (1 = safest, 163 = least safe). */
  safetyGpiRank: number | null;
  /** EF English Proficiency Index band. */
  englishBand: EnglishBand | null;
  /** Typical permanent-residency path length (years after first long-stay
   *  visa) for a skilled migrant. Use a short prose summary too. */
  permanentResidencyYears: number | null;
  permanentResidencyNote: string | null;
  /** Source year for the latest number used — surfaced in the tile. */
  asOf: string;
};

export const COUNTRY_METRICS: Record<string, CountryMetrics> = {
  US: {
    iso2: "US",
    avgSalaryUsd: 80_000,
    costOfLivingIndex: 71,
    topTaxRatePct: 37,
    healthcareIndex: 68,
    safetyGpiRank: 132,
    englishBand: "very_high",
    permanentResidencyYears: 5,
    permanentResidencyNote: "Green Card → naturalisation after 5 years",
    asOf: "2024",
  },
  GB: {
    iso2: "GB",
    avgSalaryUsd: 56_000,
    costOfLivingIndex: 64,
    topTaxRatePct: 45,
    healthcareIndex: 75,
    safetyGpiRank: 37,
    englishBand: "very_high",
    permanentResidencyYears: 5,
    permanentResidencyNote: "ILR after 5 yrs on most work routes",
    asOf: "2024",
  },
  CA: {
    iso2: "CA",
    avgSalaryUsd: 60_000,
    costOfLivingIndex: 67,
    topTaxRatePct: 53,
    healthcareIndex: 71,
    safetyGpiRank: 11,
    englishBand: "very_high",
    permanentResidencyYears: 1,
    permanentResidencyNote: "Express Entry PR direct; citizenship 3+ yrs",
    asOf: "2024",
  },
  AU: {
    iso2: "AU",
    avgSalaryUsd: 64_000,
    costOfLivingIndex: 76,
    topTaxRatePct: 45,
    healthcareIndex: 77,
    safetyGpiRank: 19,
    englishBand: "very_high",
    permanentResidencyYears: 4,
    permanentResidencyNote: "Skilled PR (189/190); citizenship after 4 yrs",
    asOf: "2024",
  },
  NZ: {
    iso2: "NZ",
    avgSalaryUsd: 49_000,
    costOfLivingIndex: 73,
    topTaxRatePct: 39,
    healthcareIndex: 73,
    safetyGpiRank: 2,
    englishBand: "very_high",
    permanentResidencyYears: 2,
    permanentResidencyNote: "Resident Visa direct; citizenship 5 yrs",
    asOf: "2024",
  },
  DE: {
    iso2: "DE",
    avgSalaryUsd: 58_000,
    costOfLivingIndex: 65,
    topTaxRatePct: 45,
    healthcareIndex: 73,
    safetyGpiRank: 16,
    englishBand: "very_high",
    permanentResidencyYears: 5,
    permanentResidencyNote: "Niederlassungserlaubnis after 5 yrs (33 mos for Blue Card)",
    asOf: "2024",
  },
  FR: {
    iso2: "FR",
    avgSalaryUsd: 53_000,
    costOfLivingIndex: 70,
    topTaxRatePct: 45,
    healthcareIndex: 78,
    safetyGpiRank: 87,
    englishBand: "moderate",
    permanentResidencyYears: 5,
    permanentResidencyNote: "Carte de résident after 5 yrs; citizenship 5 yrs",
    asOf: "2024",
  },
  ES: {
    iso2: "ES",
    avgSalaryUsd: 37_000,
    costOfLivingIndex: 56,
    topTaxRatePct: 47,
    healthcareIndex: 78,
    safetyGpiRank: 23,
    englishBand: "moderate",
    permanentResidencyYears: 5,
    permanentResidencyNote: "Residencia de larga duración after 5 yrs",
    asOf: "2024",
  },
  IT: {
    iso2: "IT",
    avgSalaryUsd: 39_000,
    costOfLivingIndex: 62,
    topTaxRatePct: 43,
    healthcareIndex: 67,
    safetyGpiRank: 34,
    englishBand: "moderate",
    permanentResidencyYears: 5,
    permanentResidencyNote: "Permesso UE per soggiornanti di lungo periodo after 5 yrs",
    asOf: "2024",
  },
  PT: {
    iso2: "PT",
    avgSalaryUsd: 31_000,
    costOfLivingIndex: 55,
    topTaxRatePct: 48,
    healthcareIndex: 67,
    safetyGpiRank: 7,
    englishBand: "high",
    permanentResidencyYears: 5,
    permanentResidencyNote: "Autorização de Residência Permanente after 5 yrs",
    asOf: "2024",
  },
  NL: {
    iso2: "NL",
    avgSalaryUsd: 64_000,
    costOfLivingIndex: 73,
    topTaxRatePct: 49.5,
    healthcareIndex: 75,
    safetyGpiRank: 25,
    englishBand: "very_high",
    permanentResidencyYears: 5,
    permanentResidencyNote: "Verblijfsvergunning onbepaalde tijd after 5 yrs",
    asOf: "2024",
  },
  IE: {
    iso2: "IE",
    avgSalaryUsd: 56_000,
    costOfLivingIndex: 71,
    topTaxRatePct: 40,
    healthcareIndex: 63,
    safetyGpiRank: 4,
    englishBand: "very_high",
    permanentResidencyYears: 5,
    permanentResidencyNote: "Stamp 4 + Long-Term Residence after 5 yrs",
    asOf: "2024",
  },
  SE: {
    iso2: "SE",
    avgSalaryUsd: 50_000,
    costOfLivingIndex: 67,
    topTaxRatePct: 52,
    healthcareIndex: 70,
    safetyGpiRank: 28,
    englishBand: "very_high",
    permanentResidencyYears: 4,
    permanentResidencyNote: "Permanent uppehållstillstånd after 4 yrs",
    asOf: "2024",
  },
  NO: {
    iso2: "NO",
    avgSalaryUsd: 64_000,
    costOfLivingIndex: 86,
    topTaxRatePct: 39,
    healthcareIndex: 75,
    safetyGpiRank: 22,
    englishBand: "very_high",
    permanentResidencyYears: 3,
    permanentResidencyNote: "Permanent oppholdstillatelse after 3 yrs",
    asOf: "2024",
  },
  DK: {
    iso2: "DK",
    avgSalaryUsd: 64_000,
    costOfLivingIndex: 76,
    topTaxRatePct: 56,
    healthcareIndex: 74,
    safetyGpiRank: 5,
    englishBand: "very_high",
    permanentResidencyYears: 8,
    permanentResidencyNote: "Permanent opholdstilladelse after 8 yrs (4 yrs fast-track)",
    asOf: "2024",
  },
  FI: {
    iso2: "FI",
    avgSalaryUsd: 50_000,
    costOfLivingIndex: 65,
    topTaxRatePct: 44,
    healthcareIndex: 73,
    safetyGpiRank: 13,
    englishBand: "very_high",
    permanentResidencyYears: 4,
    permanentResidencyNote: "Pysyvä oleskelulupa after 4 yrs",
    asOf: "2024",
  },
  CH: {
    iso2: "CH",
    avgSalaryUsd: 73_000,
    costOfLivingIndex: 105,
    topTaxRatePct: 40,
    healthcareIndex: 73,
    safetyGpiRank: 9,
    englishBand: "high",
    permanentResidencyYears: 10,
    permanentResidencyNote: "Niederlassungsbewilligung C after 10 yrs (5 yrs for EU/EFTA)",
    asOf: "2024",
  },
  AT: {
    iso2: "AT",
    avgSalaryUsd: 55_000,
    costOfLivingIndex: 64,
    topTaxRatePct: 55,
    healthcareIndex: 78,
    safetyGpiRank: 3,
    englishBand: "very_high",
    permanentResidencyYears: 5,
    permanentResidencyNote: "Daueraufenthalt-EU after 5 yrs",
    asOf: "2024",
  },
  BE: {
    iso2: "BE",
    avgSalaryUsd: 56_000,
    costOfLivingIndex: 66,
    topTaxRatePct: 50,
    healthcareIndex: 76,
    safetyGpiRank: 18,
    englishBand: "very_high",
    permanentResidencyYears: 5,
    permanentResidencyNote: "F+ permit / EU long-term resident after 5 yrs",
    asOf: "2024",
  },
  JP: {
    iso2: "JP",
    avgSalaryUsd: 41_000,
    costOfLivingIndex: 65,
    topTaxRatePct: 45,
    healthcareIndex: 80,
    safetyGpiRank: 17,
    englishBand: "low",
    permanentResidencyYears: 10,
    permanentResidencyNote: "PR after 10 yrs (1–5 yrs on HSP point system)",
    asOf: "2024",
  },
  KR: {
    iso2: "KR",
    avgSalaryUsd: 46_000,
    costOfLivingIndex: 73,
    topTaxRatePct: 45,
    healthcareIndex: 82,
    safetyGpiRank: 47,
    englishBand: "moderate",
    permanentResidencyYears: 5,
    permanentResidencyNote: "F-5 Permanent Resident after 5 yrs in F-2",
    asOf: "2024",
  },
  SG: {
    iso2: "SG",
    avgSalaryUsd: 65_000,
    costOfLivingIndex: 82,
    topTaxRatePct: 24,
    healthcareIndex: 71,
    safetyGpiRank: 6,
    englishBand: "high",
    permanentResidencyYears: 6,
    permanentResidencyNote: "PR via EP→PR pathway (very competitive)",
    asOf: "2024",
  },
  HK: {
    iso2: "HK",
    avgSalaryUsd: 56_000,
    costOfLivingIndex: 79,
    topTaxRatePct: 17,
    healthcareIndex: 68,
    safetyGpiRank: null,
    englishBand: "high",
    permanentResidencyYears: 7,
    permanentResidencyNote: "Right of Abode after 7 yrs continuous residence",
    asOf: "2024",
  },
  AE: {
    iso2: "AE",
    avgSalaryUsd: 47_000,
    costOfLivingIndex: 64,
    topTaxRatePct: 0,
    healthcareIndex: 68,
    safetyGpiRank: 53,
    englishBand: "moderate",
    permanentResidencyYears: null,
    permanentResidencyNote: "Golden Visa (5/10 yr renewable); no traditional PR",
    asOf: "2024",
  },
  SA: {
    iso2: "SA",
    avgSalaryUsd: 30_000,
    costOfLivingIndex: 50,
    topTaxRatePct: 0,
    healthcareIndex: 64,
    safetyGpiRank: 92,
    englishBand: "low",
    permanentResidencyYears: null,
    permanentResidencyNote: "Premium Residency (SAR 800k flat fee); no automatic PR",
    asOf: "2024",
  },
  IL: {
    iso2: "IL",
    avgSalaryUsd: 53_000,
    costOfLivingIndex: 77,
    topTaxRatePct: 50,
    healthcareIndex: 76,
    safetyGpiRank: 155,
    englishBand: "high",
    permanentResidencyYears: 3,
    permanentResidencyNote: "Citizenship via Law of Return for Jews; otherwise A-5/PR rare",
    asOf: "2024",
  },
  MX: {
    iso2: "MX",
    avgSalaryUsd: 17_000,
    costOfLivingIndex: 36,
    topTaxRatePct: 35,
    healthcareIndex: 67,
    safetyGpiRank: 138,
    englishBand: "low",
    permanentResidencyYears: 4,
    permanentResidencyNote: "Residente Permanente after 4 yrs Temporal",
    asOf: "2024",
  },
  BR: {
    iso2: "BR",
    avgSalaryUsd: 17_000,
    costOfLivingIndex: 35,
    topTaxRatePct: 27.5,
    healthcareIndex: 56,
    safetyGpiRank: 131,
    englishBand: "low",
    permanentResidencyYears: 4,
    permanentResidencyNote: "Permanência after 4 yrs (1 yr for family of citizens)",
    asOf: "2024",
  },
  TH: {
    iso2: "TH",
    avgSalaryUsd: 9_000,
    costOfLivingIndex: 41,
    topTaxRatePct: 35,
    healthcareIndex: 78,
    safetyGpiRank: 76,
    englishBand: "low",
    permanentResidencyYears: 3,
    permanentResidencyNote: "PR after 3 yrs on Non-Imm B / LTR; quota of 100/yr per nationality",
    asOf: "2024",
  },
  MY: {
    iso2: "MY",
    avgSalaryUsd: 13_000,
    costOfLivingIndex: 38,
    topTaxRatePct: 30,
    healthcareIndex: 70,
    safetyGpiRank: 19,
    englishBand: "high",
    permanentResidencyYears: 5,
    permanentResidencyNote: "PR via MM2H or work track (no automatic timeline)",
    asOf: "2024",
  },
  ZA: {
    iso2: "ZA",
    avgSalaryUsd: 14_000,
    costOfLivingIndex: 39,
    topTaxRatePct: 45,
    healthcareIndex: 64,
    safetyGpiRank: 123,
    englishBand: "high",
    permanentResidencyYears: 5,
    permanentResidencyNote: "PR after 5 yrs Critical Skills / Business / Relative visa",
    asOf: "2024",
  },
  IN: {
    iso2: "IN",
    avgSalaryUsd: 5_000,
    costOfLivingIndex: 25,
    topTaxRatePct: 39,
    healthcareIndex: 67,
    safetyGpiRank: 116,
    englishBand: "moderate",
    permanentResidencyYears: null,
    permanentResidencyNote: "No PR for foreign nationals; OCI for diaspora",
    asOf: "2024",
  },
  CN: {
    iso2: "CN",
    avgSalaryUsd: 13_000,
    costOfLivingIndex: 38,
    topTaxRatePct: 45,
    healthcareIndex: 64,
    safetyGpiRank: 88,
    englishBand: "low",
    permanentResidencyYears: 4,
    permanentResidencyNote: "Foreign Permanent Resident Card (very limited)",
    asOf: "2024",
  },

  // -----------------------------------------------------------------------
  // Expansion: top-100 destinations beyond the original 33. Same provenance
  // (OECD/Numbeo/EF EPI/GPI 2024, national immigration authorities). Where
  // a metric is genuinely uncurated or unreliable we leave it null rather
  // than fabricate — the dashboard renders "No data" honestly.
  // -----------------------------------------------------------------------

  // --- Europe ---
  TR: {
    iso2: "TR",
    avgSalaryUsd: 13_000,
    costOfLivingIndex: 34,
    topTaxRatePct: 40,
    healthcareIndex: 70,
    safetyGpiRank: 138,
    englishBand: "low",
    permanentResidencyYears: 8,
    permanentResidencyNote: "Long-Term Residence after 8 yrs continuous; citizenship via investment USD 400k",
    asOf: "2024",
  },
  GR: {
    iso2: "GR",
    avgSalaryUsd: 26_000,
    costOfLivingIndex: 53,
    topTaxRatePct: 44,
    healthcareIndex: 60,
    safetyGpiRank: 56,
    englishBand: "high",
    permanentResidencyYears: 5,
    permanentResidencyNote: "EU long-term resident after 5 yrs; Golden Visa from €250k–€800k",
    asOf: "2024",
  },
  PL: {
    iso2: "PL",
    avgSalaryUsd: 33_000,
    costOfLivingIndex: 41,
    topTaxRatePct: 32,
    healthcareIndex: 64,
    safetyGpiRank: 35,
    englishBand: "high",
    permanentResidencyYears: 5,
    permanentResidencyNote: "Permanent residence after 5 yrs of temporary residence",
    asOf: "2024",
  },
  CZ: {
    iso2: "CZ",
    avgSalaryUsd: 31_000,
    costOfLivingIndex: 49,
    topTaxRatePct: 23,
    healthcareIndex: 73,
    safetyGpiRank: 9,
    englishBand: "moderate",
    permanentResidencyYears: 5,
    permanentResidencyNote: "Trvalý pobyt after 5 yrs continuous residence",
    asOf: "2024",
  },
  HU: {
    iso2: "HU",
    avgSalaryUsd: 22_000,
    costOfLivingIndex: 41,
    topTaxRatePct: 15,
    healthcareIndex: 53,
    safetyGpiRank: 14,
    englishBand: "moderate",
    permanentResidencyYears: 3,
    permanentResidencyNote: "National Settlement Permit after 3 yrs (EU residency 5 yrs)",
    asOf: "2024",
  },
  RO: {
    iso2: "RO",
    avgSalaryUsd: 18_000,
    costOfLivingIndex: 36,
    topTaxRatePct: 10,
    healthcareIndex: 50,
    safetyGpiRank: 21,
    englishBand: "high",
    permanentResidencyYears: 5,
    permanentResidencyNote: "Permanent residence after 5 yrs (4 yrs for EU Blue Card holders)",
    asOf: "2024",
  },
  BG: {
    iso2: "BG",
    avgSalaryUsd: 16_000,
    costOfLivingIndex: 37,
    topTaxRatePct: 10,
    healthcareIndex: 55,
    safetyGpiRank: 30,
    englishBand: "moderate",
    permanentResidencyYears: 5,
    permanentResidencyNote: "Permanent residence after 5 yrs continuous",
    asOf: "2024",
  },
  HR: {
    iso2: "HR",
    avgSalaryUsd: 22_000,
    costOfLivingIndex: 48,
    topTaxRatePct: 35,
    healthcareIndex: 60,
    safetyGpiRank: 12,
    englishBand: "high",
    permanentResidencyYears: 5,
    permanentResidencyNote: "Permanent residence after 5 yrs of continuous residence",
    asOf: "2024",
  },
  SI: {
    iso2: "SI",
    avgSalaryUsd: 30_000,
    costOfLivingIndex: 50,
    topTaxRatePct: 50,
    healthcareIndex: 65,
    safetyGpiRank: 8,
    englishBand: "very_high",
    permanentResidencyYears: 5,
    permanentResidencyNote: "EU long-term resident permit after 5 yrs",
    asOf: "2024",
  },
  SK: {
    iso2: "SK",
    avgSalaryUsd: 22_000,
    costOfLivingIndex: 44,
    topTaxRatePct: 25,
    healthcareIndex: 63,
    safetyGpiRank: 26,
    englishBand: "moderate",
    permanentResidencyYears: 5,
    permanentResidencyNote: "Trvalý pobyt after 5 yrs (long-term residence permit)",
    asOf: "2024",
  },
  EE: {
    iso2: "EE",
    avgSalaryUsd: 28_000,
    costOfLivingIndex: 49,
    topTaxRatePct: 20,
    healthcareIndex: 75,
    safetyGpiRank: 31,
    englishBand: "high",
    permanentResidencyYears: 5,
    permanentResidencyNote: "Long-term residence permit after 5 yrs",
    asOf: "2024",
  },
  LT: {
    iso2: "LT",
    avgSalaryUsd: 25_000,
    costOfLivingIndex: 44,
    topTaxRatePct: 32,
    healthcareIndex: 64,
    safetyGpiRank: 33,
    englishBand: "high",
    permanentResidencyYears: 5,
    permanentResidencyNote: "Permanent residence permit after 5 yrs",
    asOf: "2024",
  },
  LV: {
    iso2: "LV",
    avgSalaryUsd: 21_000,
    costOfLivingIndex: 42,
    topTaxRatePct: 31,
    healthcareIndex: 56,
    safetyGpiRank: 42,
    englishBand: "high",
    permanentResidencyYears: 5,
    permanentResidencyNote: "Permanent residence permit after 5 yrs",
    asOf: "2024",
  },
  IS: {
    iso2: "IS",
    avgSalaryUsd: 72_000,
    costOfLivingIndex: 82,
    topTaxRatePct: 46,
    healthcareIndex: 71,
    safetyGpiRank: 1,
    englishBand: "very_high",
    permanentResidencyYears: 4,
    permanentResidencyNote: "Permanent residence permit after 4 yrs",
    asOf: "2024",
  },
  LU: {
    iso2: "LU",
    avgSalaryUsd: 78_000,
    costOfLivingIndex: 80,
    topTaxRatePct: 42,
    healthcareIndex: 60,
    safetyGpiRank: 15,
    englishBand: "very_high",
    permanentResidencyYears: 5,
    permanentResidencyNote: "EU long-term resident permit after 5 yrs",
    asOf: "2024",
  },
  MT: {
    iso2: "MT",
    avgSalaryUsd: 27_000,
    costOfLivingIndex: 55,
    topTaxRatePct: 35,
    healthcareIndex: 65,
    safetyGpiRank: 27,
    englishBand: "very_high",
    permanentResidencyYears: 5,
    permanentResidencyNote: "EU long-term resident permit after 5 yrs; MPRP investor route from €100k",
    asOf: "2024",
  },
  CY: {
    iso2: "CY",
    avgSalaryUsd: 27_000,
    costOfLivingIndex: 53,
    topTaxRatePct: 35,
    healthcareIndex: 63,
    safetyGpiRank: 64,
    englishBand: "very_high",
    permanentResidencyYears: 5,
    permanentResidencyNote: "EU long-term resident permit after 5 yrs; Category F investor PR available",
    asOf: "2024",
  },
  LI: {
    iso2: "LI",
    avgSalaryUsd: 90_000,
    costOfLivingIndex: 95,
    topTaxRatePct: 24,
    healthcareIndex: null,
    safetyGpiRank: null,
    englishBand: "high",
    permanentResidencyYears: 5,
    permanentResidencyNote: "Settlement permit after 5 yrs; quota-restricted",
    asOf: "2024",
  },
  RU: {
    iso2: "RU",
    avgSalaryUsd: 14_000,
    costOfLivingIndex: 32,
    topTaxRatePct: 15,
    healthcareIndex: 56,
    safetyGpiRank: 158,
    englishBand: "very_low",
    permanentResidencyYears: 5,
    permanentResidencyNote: "Permanent residence after 5 yrs of continuous temporary residence",
    asOf: "2024",
  },
  UA: {
    iso2: "UA",
    avgSalaryUsd: 7_000,
    costOfLivingIndex: 36,
    topTaxRatePct: 18,
    healthcareIndex: 53,
    safetyGpiRank: 157,
    englishBand: "moderate",
    permanentResidencyYears: 2,
    permanentResidencyNote: "Permanent residence after 2 yrs (current wartime processing limited)",
    asOf: "2024",
  },
  RS: {
    iso2: "RS",
    avgSalaryUsd: 11_000,
    costOfLivingIndex: 36,
    topTaxRatePct: 15,
    healthcareIndex: 55,
    safetyGpiRank: 57,
    englishBand: "moderate",
    permanentResidencyYears: 5,
    permanentResidencyNote: "Permanent residence after 5 yrs of continuous temporary residence",
    asOf: "2024",
  },
  AL: {
    iso2: "AL",
    avgSalaryUsd: 7_000,
    costOfLivingIndex: 33,
    topTaxRatePct: 23,
    healthcareIndex: 45,
    safetyGpiRank: 65,
    englishBand: "moderate",
    permanentResidencyYears: 5,
    permanentResidencyNote: "Permanent residence after 5 yrs continuous; family routes shorter",
    asOf: "2024",
  },
  BA: {
    iso2: "BA",
    avgSalaryUsd: 8_000,
    costOfLivingIndex: 35,
    topTaxRatePct: 10,
    healthcareIndex: 50,
    safetyGpiRank: 70,
    englishBand: "moderate",
    permanentResidencyYears: 5,
    permanentResidencyNote: "Permanent residence after 5 yrs continuous temporary residence",
    asOf: "2024",
  },
  MK: {
    iso2: "MK",
    avgSalaryUsd: 8_000,
    costOfLivingIndex: 32,
    topTaxRatePct: 10,
    healthcareIndex: 55,
    safetyGpiRank: 41,
    englishBand: "moderate",
    permanentResidencyYears: 5,
    permanentResidencyNote: "Permanent residence after 5 yrs of continuous temporary residence",
    asOf: "2024",
  },
  ME: {
    iso2: "ME",
    avgSalaryUsd: 10_000,
    costOfLivingIndex: 38,
    topTaxRatePct: 15,
    healthcareIndex: 55,
    safetyGpiRank: 67,
    englishBand: "moderate",
    permanentResidencyYears: 5,
    permanentResidencyNote: "Permanent residence after 5 yrs continuous; investor route available",
    asOf: "2024",
  },
  XK: {
    iso2: "XK",
    avgSalaryUsd: 7_000,
    costOfLivingIndex: 33,
    topTaxRatePct: 10,
    healthcareIndex: 45,
    safetyGpiRank: null,
    englishBand: "moderate",
    permanentResidencyYears: 5,
    permanentResidencyNote: "Permanent residence after 5 yrs continuous temporary residence",
    asOf: "2024",
  },
  GE: {
    iso2: "GE",
    avgSalaryUsd: 9_000,
    costOfLivingIndex: 33,
    topTaxRatePct: 20,
    healthcareIndex: 65,
    safetyGpiRank: 81,
    englishBand: "moderate",
    permanentResidencyYears: 6,
    permanentResidencyNote: "Permanent residence after 6 yrs continuous (10 yrs for non-CIS)",
    asOf: "2024",
  },
  AM: {
    iso2: "AM",
    avgSalaryUsd: 6_000,
    costOfLivingIndex: 36,
    topTaxRatePct: 20,
    healthcareIndex: 55,
    safetyGpiRank: 110,
    englishBand: "moderate",
    permanentResidencyYears: 3,
    permanentResidencyNote: "Permanent residence after 3 yrs continuous; citizenship by descent for Armenians",
    asOf: "2024",
  },
  AZ: {
    iso2: "AZ",
    avgSalaryUsd: 8_000,
    costOfLivingIndex: 34,
    topTaxRatePct: 25,
    healthcareIndex: 52,
    safetyGpiRank: 91,
    englishBand: "moderate",
    permanentResidencyYears: 8,
    permanentResidencyNote: "Permanent residence after 8 yrs continuous residence",
    asOf: "2024",
  },
  BY: {
    iso2: "BY",
    avgSalaryUsd: 8_000,
    costOfLivingIndex: 32,
    topTaxRatePct: 13,
    healthcareIndex: 60,
    safetyGpiRank: 102,
    englishBand: "low",
    permanentResidencyYears: 7,
    permanentResidencyNote: "Permanent residence after 7 yrs; political conditions limit practical paths",
    asOf: "2024",
  },
  MD: {
    iso2: "MD",
    avgSalaryUsd: 7_000,
    costOfLivingIndex: 36,
    topTaxRatePct: 12,
    healthcareIndex: 53,
    safetyGpiRank: 67,
    englishBand: "moderate",
    permanentResidencyYears: 3,
    permanentResidencyNote: "Permanent residence after 3 yrs continuous residence",
    asOf: "2024",
  },
  MC: {
    iso2: "MC",
    avgSalaryUsd: 90_000,
    costOfLivingIndex: 122,
    topTaxRatePct: 0,
    healthcareIndex: null,
    safetyGpiRank: null,
    englishBand: "high",
    permanentResidencyYears: 10,
    permanentResidencyNote: "Carte de Résident Privilégié after 10 yrs; no PIT for residents",
    asOf: "2024",
  },
  AD: {
    iso2: "AD",
    avgSalaryUsd: 42_000,
    costOfLivingIndex: 60,
    topTaxRatePct: 10,
    healthcareIndex: null,
    safetyGpiRank: null,
    englishBand: "moderate",
    permanentResidencyYears: 3,
    permanentResidencyNote: "Permanent residency after 3 yrs continuous; passive residence available",
    asOf: "2024",
  },

  // --- Asia ---
  ID: {
    iso2: "ID",
    avgSalaryUsd: 5_000,
    costOfLivingIndex: 31,
    topTaxRatePct: 35,
    healthcareIndex: 60,
    safetyGpiRank: 50,
    englishBand: "low",
    permanentResidencyYears: 5,
    permanentResidencyNote: "KITAP permanent stay after 5 yrs continuous; Second Home visa for retirees",
    asOf: "2024",
  },
  VN: {
    iso2: "VN",
    avgSalaryUsd: 5_000,
    costOfLivingIndex: 36,
    topTaxRatePct: 35,
    healthcareIndex: 56,
    safetyGpiRank: 41,
    englishBand: "low",
    permanentResidencyYears: 3,
    permanentResidencyNote: "Permanent residence after 3 yrs Temporary Residence Card; restricted categories",
    asOf: "2024",
  },
  PH: {
    iso2: "PH",
    avgSalaryUsd: 4_000,
    costOfLivingIndex: 36,
    topTaxRatePct: 35,
    healthcareIndex: 60,
    safetyGpiRank: 115,
    englishBand: "high",
    permanentResidencyYears: 0,
    permanentResidencyNote: "SRRV (retiree) from $10k deposit; spousal route grants quasi-PR",
    asOf: "2024",
  },
  TW: {
    iso2: "TW",
    avgSalaryUsd: 26_000,
    costOfLivingIndex: 60,
    topTaxRatePct: 40,
    healthcareIndex: 86,
    safetyGpiRank: 33,
    englishBand: "moderate",
    permanentResidencyYears: 5,
    permanentResidencyNote: "APRC after 5 yrs continuous on resident permit",
    asOf: "2024",
  },
  KH: {
    iso2: "KH",
    avgSalaryUsd: 3_000,
    costOfLivingIndex: 38,
    topTaxRatePct: 20,
    healthcareIndex: 40,
    safetyGpiRank: 56,
    englishBand: "low",
    permanentResidencyYears: 5,
    permanentResidencyNote: "Permanent residence rare; CB visa renewals can run indefinitely",
    asOf: "2024",
  },
  LA: {
    iso2: "LA",
    avgSalaryUsd: 3_000,
    costOfLivingIndex: 38,
    topTaxRatePct: 25,
    healthcareIndex: 45,
    safetyGpiRank: 50,
    englishBand: "low",
    permanentResidencyYears: 10,
    permanentResidencyNote: "Permanent residence after 10 yrs continuous lawful residence",
    asOf: "2024",
  },
  MM: {
    iso2: "MM",
    avgSalaryUsd: 2_000,
    costOfLivingIndex: 32,
    topTaxRatePct: 25,
    healthcareIndex: 45,
    safetyGpiRank: 156,
    englishBand: "low",
    permanentResidencyYears: 5,
    permanentResidencyNote: "PR system formalised 2014 but practical issuance limited",
    asOf: "2024",
  },
  MN: {
    iso2: "MN",
    avgSalaryUsd: 5_000,
    costOfLivingIndex: 37,
    topTaxRatePct: 20,
    healthcareIndex: 55,
    safetyGpiRank: 88,
    englishBand: "low",
    permanentResidencyYears: 5,
    permanentResidencyNote: "Permanent residence after 5 yrs continuous; investor route shorter",
    asOf: "2024",
  },
  KZ: {
    iso2: "KZ",
    avgSalaryUsd: 9_000,
    costOfLivingIndex: 33,
    topTaxRatePct: 10,
    healthcareIndex: 55,
    safetyGpiRank: 84,
    englishBand: "low",
    permanentResidencyYears: 5,
    permanentResidencyNote: "Permanent residence after 5 yrs continuous lawful residence",
    asOf: "2024",
  },
  UZ: {
    iso2: "UZ",
    avgSalaryUsd: 4_000,
    costOfLivingIndex: 30,
    topTaxRatePct: 12,
    healthcareIndex: 53,
    safetyGpiRank: 92,
    englishBand: "low",
    permanentResidencyYears: 5,
    permanentResidencyNote: "Permanent residence rare; investor and family routes most viable",
    asOf: "2024",
  },
  BD: {
    iso2: "BD",
    avgSalaryUsd: 3_000,
    costOfLivingIndex: 30,
    topTaxRatePct: 30,
    healthcareIndex: 45,
    safetyGpiRank: 93,
    englishBand: "moderate",
    permanentResidencyYears: 5,
    permanentResidencyNote: "Permanent residence rare; investor route via Bangladesh Bank approval",
    asOf: "2024",
  },
  PK: {
    iso2: "PK",
    avgSalaryUsd: 3_000,
    costOfLivingIndex: 25,
    topTaxRatePct: 35,
    healthcareIndex: 50,
    safetyGpiRank: 140,
    englishBand: "moderate",
    permanentResidencyYears: 10,
    permanentResidencyNote: "Permanent residence after 10 yrs; investor and POC pathways for diaspora",
    asOf: "2024",
  },
  LK: {
    iso2: "LK",
    avgSalaryUsd: 4_000,
    costOfLivingIndex: 28,
    topTaxRatePct: 36,
    healthcareIndex: 70,
    safetyGpiRank: 89,
    englishBand: "moderate",
    permanentResidencyYears: 10,
    permanentResidencyNote: "PR after 10 yrs continuous residence; Resident Guest Scheme shorter",
    asOf: "2024",
  },
  NP: {
    iso2: "NP",
    avgSalaryUsd: 2_000,
    costOfLivingIndex: 30,
    topTaxRatePct: 36,
    healthcareIndex: 50,
    safetyGpiRank: 78,
    englishBand: "moderate",
    permanentResidencyYears: 15,
    permanentResidencyNote: "PR via 15 yrs continuous residence; spouse route shorter",
    asOf: "2024",
  },
  MV: {
    iso2: "MV",
    avgSalaryUsd: 12_000,
    costOfLivingIndex: 65,
    topTaxRatePct: 15,
    healthcareIndex: 50,
    safetyGpiRank: 70,
    englishBand: "high",
    permanentResidencyYears: 10,
    permanentResidencyNote: "Long-term resident visas via investment; no traditional PR",
    asOf: "2024",
  },

  // --- MENA ---
  JO: {
    iso2: "JO",
    avgSalaryUsd: 9_000,
    costOfLivingIndex: 47,
    topTaxRatePct: 30,
    healthcareIndex: 65,
    safetyGpiRank: 71,
    englishBand: "moderate",
    permanentResidencyYears: 4,
    permanentResidencyNote: "Permanent residence after 4 yrs continuous; investor routes shorter",
    asOf: "2024",
  },
  LB: {
    iso2: "LB",
    avgSalaryUsd: 8_000,
    costOfLivingIndex: 47,
    topTaxRatePct: 25,
    healthcareIndex: 60,
    safetyGpiRank: 144,
    englishBand: "high",
    permanentResidencyYears: 10,
    permanentResidencyNote: "PR after 10 yrs lawful residence; investor and family routes",
    asOf: "2024",
  },
  EG: {
    iso2: "EG",
    avgSalaryUsd: 4_000,
    costOfLivingIndex: 28,
    topTaxRatePct: 25,
    healthcareIndex: 55,
    safetyGpiRank: 121,
    englishBand: "low",
    permanentResidencyYears: 10,
    permanentResidencyNote: "Permanent residence after 10 yrs (Law 89 of 1960); investor route shorter",
    asOf: "2024",
  },
  MA: {
    iso2: "MA",
    avgSalaryUsd: 8_000,
    costOfLivingIndex: 35,
    topTaxRatePct: 38,
    healthcareIndex: 50,
    safetyGpiRank: 80,
    englishBand: "low",
    permanentResidencyYears: 4,
    permanentResidencyNote: "Carte de résidence (10-yr renewable) after 4 yrs of regular residence",
    asOf: "2024",
  },
  TN: {
    iso2: "TN",
    avgSalaryUsd: 5_000,
    costOfLivingIndex: 30,
    topTaxRatePct: 35,
    healthcareIndex: 55,
    safetyGpiRank: 75,
    englishBand: "low",
    permanentResidencyYears: 5,
    permanentResidencyNote: "Long-stay residence after 5 yrs continuous; investor pathways shorter",
    asOf: "2024",
  },
  DZ: {
    iso2: "DZ",
    avgSalaryUsd: 5_000,
    costOfLivingIndex: 28,
    topTaxRatePct: 35,
    healthcareIndex: 55,
    safetyGpiRank: 109,
    englishBand: "low",
    permanentResidencyYears: 7,
    permanentResidencyNote: "Permanent residence after 7 yrs continuous lawful residence",
    asOf: "2024",
  },
  IR: {
    iso2: "IR",
    avgSalaryUsd: 6_000,
    costOfLivingIndex: 30,
    topTaxRatePct: 35,
    healthcareIndex: 60,
    safetyGpiRank: 145,
    englishBand: "low",
    permanentResidencyYears: 5,
    permanentResidencyNote: "PR after 5 yrs continuous residence; political conditions limit access",
    asOf: "2024",
  },
  IQ: {
    iso2: "IQ",
    avgSalaryUsd: 6_000,
    costOfLivingIndex: 36,
    topTaxRatePct: 15,
    healthcareIndex: 55,
    safetyGpiRank: 151,
    englishBand: "low",
    permanentResidencyYears: 10,
    permanentResidencyNote: "PR after 10 yrs continuous; conflict context limits practical access",
    asOf: "2024",
  },
  OM: {
    iso2: "OM",
    avgSalaryUsd: 22_000,
    costOfLivingIndex: 55,
    topTaxRatePct: 0,
    healthcareIndex: 65,
    safetyGpiRank: 71,
    englishBand: "moderate",
    permanentResidencyYears: null,
    permanentResidencyNote: "Investor Residency 5/10 yrs; no automatic PR pathway",
    asOf: "2024",
  },
  QA: {
    iso2: "QA",
    avgSalaryUsd: 70_000,
    costOfLivingIndex: 71,
    topTaxRatePct: 0,
    healthcareIndex: 75,
    safetyGpiRank: 25,
    englishBand: "moderate",
    permanentResidencyYears: 20,
    permanentResidencyNote: "PR after 20 yrs (10 yrs for Qatari-born); 100/yr quota; Golden Visa available",
    asOf: "2024",
  },
  KW: {
    iso2: "KW",
    avgSalaryUsd: 35_000,
    costOfLivingIndex: 56,
    topTaxRatePct: 0,
    healthcareIndex: 65,
    safetyGpiRank: 36,
    englishBand: "moderate",
    permanentResidencyYears: null,
    permanentResidencyNote: "No PR pathway for non-GCC nationals; renewable residence permits only",
    asOf: "2024",
  },
  BH: {
    iso2: "BH",
    avgSalaryUsd: 30_000,
    costOfLivingIndex: 56,
    topTaxRatePct: 0,
    healthcareIndex: 70,
    safetyGpiRank: 95,
    englishBand: "moderate",
    permanentResidencyYears: 25,
    permanentResidencyNote: "PR (Golden Residency) via investment or 25 yrs residence",
    asOf: "2024",
  },
  YE: {
    iso2: "YE",
    avgSalaryUsd: 2_000,
    costOfLivingIndex: 35,
    topTaxRatePct: 20,
    healthcareIndex: 40,
    safetyGpiRank: 162,
    englishBand: "very_low",
    permanentResidencyYears: null,
    permanentResidencyNote: "Active conflict — visa and PR processing largely suspended",
    asOf: "2024",
  },
  SY: {
    iso2: "SY",
    avgSalaryUsd: 2_000,
    costOfLivingIndex: 40,
    topTaxRatePct: 22,
    healthcareIndex: 50,
    safetyGpiRank: 161,
    englishBand: "very_low",
    permanentResidencyYears: 10,
    permanentResidencyNote: "Conflict context limits practical PR access; family routes most common",
    asOf: "2024",
  },
  AF: {
    iso2: "AF",
    avgSalaryUsd: 1_000,
    costOfLivingIndex: 25,
    topTaxRatePct: 20,
    healthcareIndex: 40,
    safetyGpiRank: 163,
    englishBand: "very_low",
    permanentResidencyYears: null,
    permanentResidencyNote: "Post-2021 Taliban administration — formal PR pathway not in practice",
    asOf: "2024",
  },

  // --- Sub-Saharan Africa ---
  NG: {
    iso2: "NG",
    avgSalaryUsd: 3_000,
    costOfLivingIndex: 29,
    topTaxRatePct: 24,
    healthcareIndex: 50,
    safetyGpiRank: 144,
    englishBand: "high",
    permanentResidencyYears: 15,
    permanentResidencyNote: "PR via Nigerian Investor Residence Permit or 15 yrs residence",
    asOf: "2024",
  },
  KE: {
    iso2: "KE",
    avgSalaryUsd: 3_000,
    costOfLivingIndex: 38,
    topTaxRatePct: 35,
    healthcareIndex: 55,
    safetyGpiRank: 117,
    englishBand: "high",
    permanentResidencyYears: 7,
    permanentResidencyNote: "PR (Class K residency) via 7 yrs continuous residence; investor route shorter",
    asOf: "2024",
  },
  ET: {
    iso2: "ET",
    avgSalaryUsd: 1_500,
    costOfLivingIndex: 30,
    topTaxRatePct: 35,
    healthcareIndex: 45,
    safetyGpiRank: 144,
    englishBand: "low",
    permanentResidencyYears: null,
    permanentResidencyNote: "PR rare; Ethiopian Origin ID Card for diaspora simplifies stay",
    asOf: "2024",
  },
  GH: {
    iso2: "GH",
    avgSalaryUsd: 2_500,
    costOfLivingIndex: 39,
    topTaxRatePct: 35,
    healthcareIndex: 50,
    safetyGpiRank: 51,
    englishBand: "high",
    permanentResidencyYears: 5,
    permanentResidencyNote: "Indefinite Residence Permit after 5 yrs; Right of Abode for African diaspora",
    asOf: "2024",
  },
  TZ: {
    iso2: "TZ",
    avgSalaryUsd: 2_000,
    costOfLivingIndex: 36,
    topTaxRatePct: 30,
    healthcareIndex: 50,
    safetyGpiRank: 79,
    englishBand: "moderate",
    permanentResidencyYears: 10,
    permanentResidencyNote: "PR after 10 yrs continuous lawful residence",
    asOf: "2024",
  },
  UG: {
    iso2: "UG",
    avgSalaryUsd: 1_500,
    costOfLivingIndex: 36,
    topTaxRatePct: 40,
    healthcareIndex: 50,
    safetyGpiRank: 113,
    englishBand: "moderate",
    permanentResidencyYears: 10,
    permanentResidencyNote: "PR after 10 yrs continuous lawful residence; family routes shorter",
    asOf: "2024",
  },
  RW: {
    iso2: "RW",
    avgSalaryUsd: 1_500,
    costOfLivingIndex: 41,
    topTaxRatePct: 30,
    healthcareIndex: 55,
    safetyGpiRank: 86,
    englishBand: "moderate",
    permanentResidencyYears: 5,
    permanentResidencyNote: "PR after 5 yrs continuous residence; investor visa fast-tracks",
    asOf: "2024",
  },
  SN: {
    iso2: "SN",
    avgSalaryUsd: 2_500,
    costOfLivingIndex: 35,
    topTaxRatePct: 40,
    healthcareIndex: 50,
    safetyGpiRank: 60,
    englishBand: "low",
    permanentResidencyYears: 10,
    permanentResidencyNote: "Permanent residence after 10 yrs continuous lawful residence",
    asOf: "2024",
  },
  CI: {
    iso2: "CI",
    avgSalaryUsd: 2_500,
    costOfLivingIndex: 35,
    topTaxRatePct: 36,
    healthcareIndex: 50,
    safetyGpiRank: 97,
    englishBand: "low",
    permanentResidencyYears: 10,
    permanentResidencyNote: "PR after 10 yrs continuous lawful residence",
    asOf: "2024",
  },
  CM: {
    iso2: "CM",
    avgSalaryUsd: 1_800,
    costOfLivingIndex: 35,
    topTaxRatePct: 38,
    healthcareIndex: 50,
    safetyGpiRank: 141,
    englishBand: "moderate",
    permanentResidencyYears: 5,
    permanentResidencyNote: "PR (Carte de résident) after 5 yrs continuous residence",
    asOf: "2024",
  },
  AO: {
    iso2: "AO",
    avgSalaryUsd: 5_000,
    costOfLivingIndex: 50,
    topTaxRatePct: 25,
    healthcareIndex: 45,
    safetyGpiRank: 96,
    englishBand: "low",
    permanentResidencyYears: 10,
    permanentResidencyNote: "Permanent residence after 10 yrs (5 yrs for CPLP nationals)",
    asOf: "2024",
  },
  MZ: {
    iso2: "MZ",
    avgSalaryUsd: 1_500,
    costOfLivingIndex: 36,
    topTaxRatePct: 32,
    healthcareIndex: 45,
    safetyGpiRank: 130,
    englishBand: "low",
    permanentResidencyYears: 10,
    permanentResidencyNote: "PR after 10 yrs (5 yrs for CPLP/SADC nationals)",
    asOf: "2024",
  },
  MU: {
    iso2: "MU",
    avgSalaryUsd: 12_000,
    costOfLivingIndex: 49,
    topTaxRatePct: 15,
    healthcareIndex: 65,
    safetyGpiRank: 25,
    englishBand: "high",
    permanentResidencyYears: 3,
    permanentResidencyNote: "PR via Occupation Permit (3 yrs) or Permanent Residence Permit (20-yr renewable)",
    asOf: "2024",
  },

  // --- Latin America & Caribbean ---
  AR: {
    iso2: "AR",
    avgSalaryUsd: 12_000,
    costOfLivingIndex: 36,
    topTaxRatePct: 35,
    healthcareIndex: 70,
    safetyGpiRank: 64,
    englishBand: "moderate",
    permanentResidencyYears: 3,
    permanentResidencyNote: "Residencia Permanente after 3 yrs (2 yrs for Mercosur nationals)",
    asOf: "2024",
  },
  CL: {
    iso2: "CL",
    avgSalaryUsd: 28_000,
    costOfLivingIndex: 46,
    topTaxRatePct: 40,
    healthcareIndex: 65,
    safetyGpiRank: 54,
    englishBand: "moderate",
    permanentResidencyYears: 2,
    permanentResidencyNote: "Permiso de Residencia Definitiva after 2 yrs of temporary residence",
    asOf: "2024",
  },
  CO: {
    iso2: "CO",
    avgSalaryUsd: 8_000,
    costOfLivingIndex: 30,
    topTaxRatePct: 39,
    healthcareIndex: 70,
    safetyGpiRank: 137,
    englishBand: "moderate",
    permanentResidencyYears: 5,
    permanentResidencyNote: "Visa de Residente after 5 yrs Migrante; Mercosur nationals shorter",
    asOf: "2024",
  },
  PE: {
    iso2: "PE",
    avgSalaryUsd: 8_000,
    costOfLivingIndex: 34,
    topTaxRatePct: 30,
    healthcareIndex: 60,
    safetyGpiRank: 109,
    englishBand: "moderate",
    permanentResidencyYears: 3,
    permanentResidencyNote: "Residencia Permanente after 3 yrs continuous temporary residence",
    asOf: "2024",
  },
  EC: {
    iso2: "EC",
    avgSalaryUsd: 7_000,
    costOfLivingIndex: 39,
    topTaxRatePct: 35,
    healthcareIndex: 65,
    safetyGpiRank: 100,
    englishBand: "moderate",
    permanentResidencyYears: 2,
    permanentResidencyNote: "Residencia Permanente after 21 mos of temporary residence",
    asOf: "2024",
  },
  UY: {
    iso2: "UY",
    avgSalaryUsd: 18_000,
    costOfLivingIndex: 53,
    topTaxRatePct: 36,
    healthcareIndex: 65,
    safetyGpiRank: 49,
    englishBand: "moderate",
    permanentResidencyYears: 3,
    permanentResidencyNote: "Residencia Permanente after 3 yrs (5 yrs to apply for citizenship)",
    asOf: "2024",
  },
  PY: {
    iso2: "PY",
    avgSalaryUsd: 7_000,
    costOfLivingIndex: 33,
    topTaxRatePct: 10,
    healthcareIndex: 60,
    safetyGpiRank: 82,
    englishBand: "low",
    permanentResidencyYears: 2,
    permanentResidencyNote: "Permanent residence after 2 yrs (shortened under 2023 reforms)",
    asOf: "2024",
  },
  BO: {
    iso2: "BO",
    avgSalaryUsd: 6_000,
    costOfLivingIndex: 33,
    topTaxRatePct: 13,
    healthcareIndex: 60,
    safetyGpiRank: 113,
    englishBand: "low",
    permanentResidencyYears: 3,
    permanentResidencyNote: "Permanent residence after 3 yrs continuous temporary residence",
    asOf: "2024",
  },
  VE: {
    iso2: "VE",
    avgSalaryUsd: 3_000,
    costOfLivingIndex: 40,
    topTaxRatePct: 34,
    healthcareIndex: 50,
    safetyGpiRank: 152,
    englishBand: "moderate",
    permanentResidencyYears: 5,
    permanentResidencyNote: "PR via 5 yrs continuous residence; current conditions limit practical access",
    asOf: "2024",
  },
  CR: {
    iso2: "CR",
    avgSalaryUsd: 13_000,
    costOfLivingIndex: 53,
    topTaxRatePct: 25,
    healthcareIndex: 70,
    safetyGpiRank: 39,
    englishBand: "moderate",
    permanentResidencyYears: 3,
    permanentResidencyNote: "Residencia Permanente after 3 yrs of temporary residence",
    asOf: "2024",
  },
  PA: {
    iso2: "PA",
    avgSalaryUsd: 17_000,
    costOfLivingIndex: 51,
    topTaxRatePct: 25,
    healthcareIndex: 65,
    safetyGpiRank: 65,
    englishBand: "moderate",
    permanentResidencyYears: 2,
    permanentResidencyNote: "Permanent Residence direct via Friendly Nations / Pensionado / Reforestation",
    asOf: "2024",
  },
  GT: {
    iso2: "GT",
    avgSalaryUsd: 6_000,
    costOfLivingIndex: 39,
    topTaxRatePct: 7,
    healthcareIndex: 60,
    safetyGpiRank: 116,
    englishBand: "low",
    permanentResidencyYears: 5,
    permanentResidencyNote: "Permanent residence after 5 yrs continuous (2 yrs for Iberoamericans)",
    asOf: "2024",
  },
  HN: {
    iso2: "HN",
    avgSalaryUsd: 4_000,
    costOfLivingIndex: 38,
    topTaxRatePct: 25,
    healthcareIndex: 55,
    safetyGpiRank: 119,
    englishBand: "low",
    permanentResidencyYears: 5,
    permanentResidencyNote: "Permanent residence after 5 yrs continuous; investor and pensionado routes shorter",
    asOf: "2024",
  },
  NI: {
    iso2: "NI",
    avgSalaryUsd: 3_500,
    costOfLivingIndex: 35,
    topTaxRatePct: 30,
    healthcareIndex: 55,
    safetyGpiRank: 100,
    englishBand: "low",
    permanentResidencyYears: 3,
    permanentResidencyNote: "Permanent residence after 3 yrs continuous (1 yr for retirees)",
    asOf: "2024",
  },
  DO: {
    iso2: "DO",
    avgSalaryUsd: 8_000,
    costOfLivingIndex: 47,
    topTaxRatePct: 25,
    healthcareIndex: 55,
    safetyGpiRank: 84,
    englishBand: "low",
    permanentResidencyYears: 2,
    permanentResidencyNote: "Permanent Residence after 2 yrs (fast-tracked for Iberoamerican nationals)",
    asOf: "2024",
  },
  CU: {
    iso2: "CU",
    avgSalaryUsd: 1_500,
    costOfLivingIndex: 35,
    topTaxRatePct: 50,
    healthcareIndex: 65,
    safetyGpiRank: 91,
    englishBand: "low",
    permanentResidencyYears: null,
    permanentResidencyNote: "PR effectively unavailable to non-Cubans except family-route cases",
    asOf: "2024",
  },
  JM: {
    iso2: "JM",
    avgSalaryUsd: 5_000,
    costOfLivingIndex: 50,
    topTaxRatePct: 30,
    healthcareIndex: 60,
    safetyGpiRank: 99,
    englishBand: "very_high",
    permanentResidencyYears: 5,
    permanentResidencyNote: "Permanent residence after 5 yrs continuous lawful residence",
    asOf: "2024",
  },
  BS: {
    iso2: "BS",
    avgSalaryUsd: 30_000,
    costOfLivingIndex: 73,
    topTaxRatePct: 0,
    healthcareIndex: 60,
    safetyGpiRank: 73,
    englishBand: "very_high",
    permanentResidencyYears: 10,
    permanentResidencyNote: "PR after 10 yrs continuous residence; Economic Permanent Residence via $750k+ investment",
    asOf: "2024",
  },
  TT: {
    iso2: "TT",
    avgSalaryUsd: 16_000,
    costOfLivingIndex: 53,
    topTaxRatePct: 30,
    healthcareIndex: 55,
    safetyGpiRank: 86,
    englishBand: "very_high",
    permanentResidencyYears: 5,
    permanentResidencyNote: "Permanent residence after 5 yrs continuous; CARICOM Skills Certificate route",
    asOf: "2024",
  },
  GY: {
    iso2: "GY",
    avgSalaryUsd: 9_000,
    costOfLivingIndex: 47,
    topTaxRatePct: 40,
    healthcareIndex: 50,
    safetyGpiRank: 109,
    englishBand: "very_high",
    permanentResidencyYears: 7,
    permanentResidencyNote: "Permanent residence after 7 yrs continuous; CARICOM Skills route applies",
    asOf: "2024",
  },

  // --- Oceania ---
  FJ: {
    iso2: "FJ",
    avgSalaryUsd: 6_000,
    costOfLivingIndex: 50,
    topTaxRatePct: 20,
    healthcareIndex: 50,
    safetyGpiRank: 50,
    englishBand: "very_high",
    permanentResidencyYears: 7,
    permanentResidencyNote: "Permanent residence after 7 yrs continuous residence; investor route shorter",
    asOf: "2024",
  },
  PG: {
    iso2: "PG",
    avgSalaryUsd: 3_500,
    costOfLivingIndex: 44,
    topTaxRatePct: 42,
    healthcareIndex: 45,
    safetyGpiRank: 121,
    englishBand: "high",
    permanentResidencyYears: 5,
    permanentResidencyNote: "Permanent residence after 5 yrs continuous lawful residence",
    asOf: "2024",
  },
  WS: {
    iso2: "WS",
    avgSalaryUsd: 4_000,
    costOfLivingIndex: 50,
    topTaxRatePct: 27,
    healthcareIndex: 50,
    safetyGpiRank: null,
    englishBand: "very_high",
    permanentResidencyYears: 5,
    permanentResidencyNote: "Permanent residence after 5 yrs continuous lawful residence",
    asOf: "2024",
  },
};

export function metricsFor(iso2: string): CountryMetrics | null {
  return COUNTRY_METRICS[iso2.toUpperCase()] ?? null;
}

/** Tuned for "higher = better living quality" intuition. */
export function ratingForSalary(usd: number | null): MetricRating | null {
  if (usd == null) return null;
  if (usd >= 60_000) return "very_good";
  if (usd >= 45_000) return "good";
  if (usd >= 30_000) return "average";
  if (usd >= 15_000) return "poor";
  return "very_poor";
}

export function ratingForCostOfLiving(index: number | null): MetricRating | null {
  // Lower index = cheaper to live = better for cost-conscious users.
  if (index == null) return null;
  if (index <= 40) return "very_good";
  if (index <= 55) return "good";
  if (index <= 70) return "average";
  if (index <= 85) return "poor";
  return "very_poor";
}

export function ratingForTax(pct: number | null): MetricRating | null {
  // Lower top marginal = better take-home for high earners.
  if (pct == null) return null;
  if (pct <= 15) return "very_good";
  if (pct <= 25) return "good";
  if (pct <= 35) return "average";
  if (pct <= 45) return "poor";
  return "very_poor";
}

export function ratingForHealthcare(index: number | null): MetricRating | null {
  if (index == null) return null;
  if (index >= 78) return "very_good";
  if (index >= 70) return "good";
  if (index >= 60) return "average";
  if (index >= 50) return "poor";
  return "very_poor";
}

export function ratingForSafety(gpiRank: number | null): MetricRating | null {
  // Lower rank = safer (GPI 2024 covers 163 countries).
  if (gpiRank == null) return null;
  if (gpiRank <= 20) return "very_good";
  if (gpiRank <= 50) return "good";
  if (gpiRank <= 90) return "average";
  if (gpiRank <= 130) return "poor";
  return "very_poor";
}

export function ratingForEnglish(band: EnglishBand | null): MetricRating | null {
  if (band == null) return null;
  return {
    very_high: "very_good",
    high: "good",
    moderate: "average",
    low: "poor",
    very_low: "very_poor",
  }[band] as MetricRating;
}

export function ratingForPrYears(years: number | null): MetricRating | null {
  if (years == null) return "poor"; // No PR pathway
  if (years <= 2) return "very_good";
  if (years <= 4) return "good";
  if (years <= 6) return "average";
  if (years <= 8) return "poor";
  return "very_poor";
}

export function ratingForDifficulty(bucket: DifficultyAssessment["bucket"]): MetricRating {
  return bucket === "easy" ? "very_good" : bucket === "medium" ? "average" : "poor";
}

export function ratingForProcessingDays(maxDays: number | null): MetricRating | null {
  if (maxDays == null || maxDays === 0) return "very_good";
  if (maxDays <= 7) return "very_good";
  if (maxDays <= 21) return "good";
  if (maxDays <= 45) return "average";
  if (maxDays <= 90) return "poor";
  return "very_poor";
}

export const ENGLISH_BAND_LABEL: Record<EnglishBand, string> = {
  very_high: "Very high",
  high: "High",
  moderate: "Moderate",
  low: "Low",
  very_low: "Very low",
};

/** Pull the route-specific signals (difficulty + processing days) from the
 *  resolved primary option. PR pathway comes from static destination data. */
export function routeSignals(opt: ResolvedVisaOption | null, difficulty: DifficultyAssessment | null) {
  return {
    difficultyScore: difficulty?.score ?? null,
    difficultyBucket: difficulty?.bucket ?? null,
    processingDaysMin: opt?.processingTimeDaysMin ?? null,
    processingDaysMax: opt?.processingTimeDaysMax ?? null,
  };
}

export const SOURCES = {
  salary: { label: "OECD Average annual wages", url: "https://data.oecd.org/earnwage/average-wages.htm" },
  cost: { label: "Numbeo Cost of Living Index (NYC = 100)", url: "https://www.numbeo.com/cost-of-living/" },
  tax: { label: "OECD / KPMG personal income tax tables", url: "https://www.oecd.org/tax/tax-policy/tax-database/" },
  healthcare: { label: "Numbeo Healthcare Index", url: "https://www.numbeo.com/health-care/" },
  safety: { label: "Vision of Humanity Global Peace Index 2024", url: "https://www.visionofhumanity.org/maps/" },
  english: { label: "EF English Proficiency Index 2024", url: "https://www.ef.com/wwen/epi/" },
  pr: { label: "National immigration authority", url: null as string | null },
};
