/**
 * Demonym map — ISO 3166-1 alpha-2 → adjective form ("British" not "United
 * Kingdom", "Chinese" not "China", "Indian" not "India"). Used wherever the
 * site is asking the user about their nationality (passport field, heat-map
 * title, "X passport holders" prose, etc).
 *
 * Keep destination phrasing as country names — "travelling to Japan", not
 * "travelling to Japanese". This map is purely for the passport / nationality
 * direction.
 */
export const NATIONALITY: Record<string, string> = {
  AD: "Andorran",
  AE: "Emirati",
  AF: "Afghan",
  AG: "Antiguan and Barbudan",
  AI: "Anguillan",
  AL: "Albanian",
  AM: "Armenian",
  AO: "Angolan",
  AQ: "Antarctic",
  AR: "Argentine",
  AS: "American Samoan",
  AT: "Austrian",
  AU: "Australian",
  AW: "Aruban",
  AX: "Åland Islander",
  AZ: "Azerbaijani",
  BA: "Bosnian and Herzegovinian",
  BB: "Barbadian",
  BD: "Bangladeshi",
  BE: "Belgian",
  BF: "Burkinabé",
  BG: "Bulgarian",
  BH: "Bahraini",
  BI: "Burundian",
  BJ: "Beninese",
  BL: "Saint Barthélemy",
  BM: "Bermudian",
  BN: "Bruneian",
  BO: "Bolivian",
  BQ: "Bonaire, Sint Eustatius and Saba",
  BR: "Brazilian",
  BS: "Bahamian",
  BT: "Bhutanese",
  BV: "Bouvet Island",
  BW: "Motswana / Tswana",
  BY: "Belarusian",
  BZ: "Belizean",
  CA: "Canadian",
  CC: "Cocos Islander",
  CD: "Congolese (DRC)",
  CF: "Central African",
  CG: "Congolese (Republic)",
  CH: "Swiss",
  CI: "Ivorian",
  CK: "Cook Islander",
  CL: "Chilean",
  CM: "Cameroonian",
  CN: "Chinese",
  CO: "Colombian",
  CR: "Costa Rican",
  CU: "Cuban",
  CV: "Cabo Verdean",
  CW: "Curaçaoan",
  CX: "Christmas Islander",
  CY: "Cypriot",
  CZ: "Czech",
  DE: "German",
  DJ: "Djiboutian",
  DK: "Danish",
  DM: "Dominican (Dominica)",
  DO: "Dominican",
  DZ: "Algerian",
  EC: "Ecuadorian",
  EE: "Estonian",
  EG: "Egyptian",
  EH: "Sahrawi",
  ER: "Eritrean",
  ES: "Spanish",
  ET: "Ethiopian",
  FI: "Finnish",
  FJ: "Fijian",
  FK: "Falkland Islander",
  FM: "Micronesian",
  FO: "Faroese",
  FR: "French",
  GA: "Gabonese",
  GB: "British",
  GD: "Grenadian",
  GE: "Georgian",
  GF: "French Guianese",
  GG: "Guernsey",
  GH: "Ghanaian",
  GI: "Gibraltarian",
  GL: "Greenlandic",
  GM: "Gambian",
  GN: "Guinean",
  GP: "Guadeloupean",
  GQ: "Equatorial Guinean",
  GR: "Greek",
  GS: "South Georgia and South Sandwich Islander",
  GT: "Guatemalan",
  GU: "Guamanian",
  GW: "Bissau-Guinean",
  GY: "Guyanese",
  HK: "Hongkonger",
  HM: "Heard and McDonald Islander",
  HN: "Honduran",
  HR: "Croatian",
  HT: "Haitian",
  HU: "Hungarian",
  ID: "Indonesian",
  IE: "Irish",
  IL: "Israeli",
  IM: "Manx",
  IN: "Indian",
  IO: "British Indian Ocean Territorian",
  IQ: "Iraqi",
  IR: "Iranian",
  IS: "Icelandic",
  IT: "Italian",
  JE: "Jersey",
  JM: "Jamaican",
  JO: "Jordanian",
  JP: "Japanese",
  KE: "Kenyan",
  KG: "Kyrgyzstani",
  KH: "Cambodian",
  KI: "I-Kiribati",
  KM: "Comoran",
  KN: "Kittitian and Nevisian",
  KP: "North Korean",
  KR: "South Korean",
  KW: "Kuwaiti",
  KY: "Caymanian",
  KZ: "Kazakhstani",
  LA: "Laotian",
  LB: "Lebanese",
  LC: "Saint Lucian",
  LI: "Liechtensteiner",
  LK: "Sri Lankan",
  LR: "Liberian",
  LS: "Mosotho / Basotho",
  LT: "Lithuanian",
  LU: "Luxembourgish",
  LV: "Latvian",
  LY: "Libyan",
  MA: "Moroccan",
  MC: "Monégasque",
  MD: "Moldovan",
  ME: "Montenegrin",
  MF: "Saint Martiner",
  MG: "Malagasy",
  MH: "Marshallese",
  MK: "North Macedonian",
  ML: "Malian",
  MM: "Burmese",
  MN: "Mongolian",
  MO: "Macanese",
  MP: "Northern Mariana Islander",
  MQ: "Martiniquais",
  MR: "Mauritanian",
  MS: "Montserratian",
  MT: "Maltese",
  MU: "Mauritian",
  MV: "Maldivian",
  MW: "Malawian",
  MX: "Mexican",
  MY: "Malaysian",
  MZ: "Mozambican",
  NA: "Namibian",
  NC: "New Caledonian",
  NE: "Nigerien",
  NF: "Norfolk Islander",
  NG: "Nigerian",
  NI: "Nicaraguan",
  NL: "Dutch",
  NO: "Norwegian",
  NP: "Nepalese",
  NR: "Nauruan",
  NU: "Niuean",
  NZ: "New Zealander",
  OM: "Omani",
  PA: "Panamanian",
  PE: "Peruvian",
  PF: "French Polynesian",
  PG: "Papua New Guinean",
  PH: "Filipino",
  PK: "Pakistani",
  PL: "Polish",
  PM: "Saint-Pierrais and Miquelonais",
  PN: "Pitcairn Islander",
  PR: "Puerto Rican",
  PS: "Palestinian",
  PT: "Portuguese",
  PW: "Palauan",
  PY: "Paraguayan",
  QA: "Qatari",
  RE: "Réunionnais",
  RO: "Romanian",
  RS: "Serbian",
  RU: "Russian",
  RW: "Rwandan",
  SA: "Saudi",
  SB: "Solomon Islander",
  SC: "Seychellois",
  SD: "Sudanese",
  SE: "Swedish",
  SG: "Singaporean",
  SH: "Saint Helenian",
  SI: "Slovenian",
  SJ: "Svalbard and Jan Mayen",
  SK: "Slovak",
  SL: "Sierra Leonean",
  SM: "Sammarinese",
  SN: "Senegalese",
  SO: "Somali",
  SR: "Surinamese",
  SS: "South Sudanese",
  ST: "São Toméan",
  SV: "Salvadoran",
  SX: "Sint Maartener",
  SY: "Syrian",
  SZ: "Swazi / Liswati",
  TC: "Turks and Caicos Islander",
  TD: "Chadian",
  TF: "French Southern Territorian",
  TG: "Togolese",
  TH: "Thai",
  TJ: "Tajikistani",
  TK: "Tokelauan",
  TL: "Timorese",
  TM: "Turkmen",
  TN: "Tunisian",
  TO: "Tongan",
  TR: "Turkish",
  TT: "Trinidadian and Tobagonian",
  TV: "Tuvaluan",
  TW: "Taiwanese",
  TZ: "Tanzanian",
  UA: "Ukrainian",
  UG: "Ugandan",
  UM: "U.S. Minor Outlying Islander",
  US: "American",
  UY: "Uruguayan",
  UZ: "Uzbekistani",
  VA: "Vatican",
  VC: "Saint Vincentian and Grenadinian",
  VE: "Venezuelan",
  VG: "British Virgin Islander",
  VI: "U.S. Virgin Islander",
  VN: "Vietnamese",
  VU: "Ni-Vanuatu",
  WF: "Wallisian and Futunan",
  WS: "Samoan",
  XK: "Kosovan",
  YE: "Yemeni",
  YT: "Mahoran",
  ZA: "South African",
  ZM: "Zambian",
  ZW: "Zimbabwean",
};

/** Returns the demonym ("British" / "Chinese" / "Indian"); falls back to ISO2 */
export function nationalityFor(iso2: string): string {
  return NATIONALITY[iso2.toUpperCase()] ?? iso2.toUpperCase();
}
