/**
 * Single source of truth for every URL that appears in the sitemap.
 *
 * Returns a deterministic, fully-flat list in a stable order — so the
 * sitemap index and every chunk can be generated by slicing the same
 * array without coordination. Order matters: changing it would shuffle
 * URLs across chunks on the next deploy, which Google interprets as a
 * site-wide content move.
 *
 * Order (don't reorder lightly):
 *   1. Site-level static pages (homepage, about, methodology, etc.)
 *   2. Per-passport: passport index + destination index for that ISO
 *   3. Per-passport: every /[from]/[to] pair + indexed purpose variants
 *   4. Hand-written purpose URLs (transit / family / diplomatic)
 *
 * The homepage URL is emitted as the bare site origin (no trailing
 * slash) so it matches what the homepage canonical emits — Google was
 * seeing `https://visavu.com` (canonical) vs `https://visavu.com/`
 * (sitemap) and counting them as separate candidate URLs.
 *
 * Cardinality (with ~236 passport countries, 250 destinations):
 *   - ~12 static pages
 *   - 236 × 2 = 472 passport/destination index pages
 *   - 236 × 249 × 4 (bare + work/study/business) = ~235,000 pair URLs
 *   - ~hundreds of hand-written purpose URLs
 *   ≈ 236,000 total URLs.
 *
 * At MAX_URLS_PER_CHUNK = 50,000, that's 5 chunks. Google handles
 * larger-but-fewer sitemaps better than many tiny ones.
 */
import {
  COUNTRY_LIST,
  PASSPORT_COUNTRIES,
  issuesPassport,
} from "@/lib/countries";
import { SITE } from "@/lib/site";
import { HAND_WRITTEN_ROUTES } from "@/content/routeAdvice";
import { getCountryPhotoSync } from "@/lib/pexels";
import { getPassportCover } from "@/lib/passportCovers";
import { nameFor } from "@/lib/countries";
import { allMythSlugs } from "@/content/myths";

const MYTH_SLUGS = allMythSlugs();

export type SitemapImage = {
  /** Absolute URL of the image. */
  loc: string;
  /** Plain-text caption shown alongside image-search results. */
  caption?: string;
  /** Title shown by Google Image Search. */
  title?: string;
};

export type SitemapUrl = {
  loc: string;
  changefreq: string;
  priority: string;
  /** Marker so the chunk handler can fill in a DB-derived per-URL
   *  lastmod. The shape is `passport:US`, `destination:JP`, or `static`
   *  — the chunk handler resolves to a real ISO date via the lastmod
   *  maps from lib/sitemapLastmod.ts, falling back to SITEMAP_LASTMOD
   *  when no row exists for that bucket. */
  lastmodKey: "static" | `passport:${string}` | `destination:${string}`;
  /** Optional images attached to this URL. Surfaces them to Google
   *  Image Search via the `xmlns:image` sitemap extension. Including
   *  the hero photo for every passport/destination/pair page boosts
   *  visibility for "Japan visa" image queries etc. */
  images?: SitemapImage[];
};

// Google's hard cap per sitemap is 50,000 URLs / 50 MB. We aim slightly
// under to leave room for accidental growth without breaking the cap.
export const MAX_URLS_PER_CHUNK = 48_000;

// High-search purpose variants that every (passport, destination) pair
// gets in the sitemap. Tourism is INTENTIONALLY omitted — it canonicalises
// to the bare pair URL (`/us/jp`, not `/us/jp/tourism`) so adding the
// tourism URL would create ~60k duplicate-canonical entries that Google
// flags as "Alternate page with proper canonical tag."
const INDEXED_PURPOSES = ["work", "study", "business"] as const;

const HAND_WRITTEN_BY_ORIGIN: Map<
  string,
  Array<{ destination: string; purpose: string }>
> = (() => {
  const map = new Map<string, Array<{ destination: string; purpose: string }>>();
  for (const r of HAND_WRITTEN_ROUTES) {
    if ((INDEXED_PURPOSES as readonly string[]).includes(r.purpose)) continue;
    const list = map.get(r.passport) ?? [];
    list.push({ destination: r.destination, purpose: r.purpose });
    map.set(r.passport, list);
  }
  return map;
})();

let cached: SitemapUrl[] | null = null;

export function getAllSitemapUrls(): SitemapUrl[] {
  if (cached) return cached;
  const urls: SitemapUrl[] = [];

  // 1) Site-level static pages. Homepage is emitted as `SITE.url` with NO
  //    trailing slash so it matches the canonical Next.js emits on `/`.
  const staticPages: Array<[string, string, string]> = [
    ["", "weekly", "1.0"], // homepage
    ["/about", "monthly", "0.4"],
    ["/methodology", "monthly", "0.5"],
    ["/sources", "monthly", "0.4"],
    ["/disclaimer", "monthly", "0.3"],
    ["/changelog", "weekly", "0.4"],
    ["/contact", "monthly", "0.3"],
    ["/find-my-visa", "weekly", "0.7"],
    ["/finder", "weekly", "0.7"],
    ["/passport-rankings", "weekly", "0.7"],
    ["/guides", "weekly", "0.6"],
    ["/services", "weekly", "0.6"],
    ["/services/travel-insurance", "weekly", "0.5"],
    ["/services/health-insurance", "weekly", "0.5"],
    ["/services/vaccinations", "weekly", "0.5"],
    ["/services/biometrics", "weekly", "0.5"],
    ["/services/medical-checks", "weekly", "0.5"],
    ["/services/passport-photos", "weekly", "0.5"],
    ["/services/legal-services", "weekly", "0.5"],
    ["/myths", "weekly", "0.7"],
    ["/chat", "weekly", "0.6"],
  ];

  // Per-myth pages — high-quality SEO content with FAQ JSON-LD.
  for (const slug of MYTH_SLUGS) {
    urls.push({
      loc: `${SITE.url}/myths/${slug}`,
      changefreq: "monthly",
      priority: "0.6",
      lastmodKey: "static",
    });
  }
  for (const [path, freq, prio] of staticPages) {
    urls.push({
      loc: `${SITE.url}${path}`,
      changefreq: freq,
      priority: prio,
      lastmodKey: "static",
    });
  }

  // 2) Passport / destination index pages — per passport-issuing country.
  //    Each URL is bucketed under its own ISO so the chunk handler can
  //    surface the actual MAX(last_verified_at) for that country.
  //    Each URL also carries an `image` reference pointing at the hero
  //    photo for that country — passport cover for /passport/[iso],
  //    Pexels destination photo for /destination/[iso] — which Google
  //    indexes for image search via the xmlns:image extension.
  for (const origin of PASSPORT_COUNTRIES) {
    const lower = origin.iso2.toLowerCase();
    const passportCover = getPassportCover(origin.iso2);
    const destPhoto = getCountryPhotoSync(origin.iso2);
    const countryName = nameFor(origin.iso2);
    urls.push({
      loc: `${SITE.url}/passport/${lower}`,
      changefreq: "weekly",
      priority: "0.7",
      lastmodKey: `passport:${origin.iso2}`,
      images: passportCover
        ? [
            {
              loc: `${SITE.url}${passportCover.url}`,
              title: `${countryName} passport`,
              caption: `${countryName} passport cover (Wikimedia Commons, ${passportCover.licence})`,
            },
          ]
        : undefined,
    });
    urls.push({
      loc: `${SITE.url}/destination/${lower}`,
      changefreq: "weekly",
      priority: "0.7",
      lastmodKey: `destination:${origin.iso2}`,
      images: destPhoto
        ? [
            {
              loc: `${SITE.url}${destPhoto.url}`,
              title: `${countryName} — visa & travel`,
              caption: destPhoto.alt,
            },
          ]
        : undefined,
    });
  }

  // 3) Every passport → destination pair + indexed purpose variants.
  //    Pair URLs use the passport-bucket lastmod (not destination's) —
  //    the route's primary content is the passport-perspective rules
  //    for entering the destination, so the passport's verification
  //    cadence is the right signal for crawl freshness.
  //    The image attached to a pair URL is the DESTINATION's photo —
  //    that's the visual context for the user (where they're going to).
  for (const origin of PASSPORT_COUNTRIES) {
    if (!issuesPassport(origin.iso2)) continue;
    const lowerOrigin = origin.iso2.toLowerCase();
    const passportKey = `passport:${origin.iso2}` as const;
    for (const dest of COUNTRY_LIST) {
      if (dest.iso2 === origin.iso2) continue;
      const lowerDest = dest.iso2.toLowerCase();
      const destPhoto = getCountryPhotoSync(dest.iso2);
      const destName = nameFor(dest.iso2);
      const images = destPhoto
        ? [
            {
              loc: `${SITE.url}${destPhoto.url}`,
              title: `${destName} — visa requirements`,
              caption: destPhoto.alt,
            },
          ]
        : undefined;
      urls.push({
        loc: `${SITE.url}/${lowerOrigin}/${lowerDest}`,
        changefreq: "weekly",
        priority: "0.6",
        lastmodKey: passportKey,
        images,
      });
      for (const purpose of INDEXED_PURPOSES) {
        urls.push({
          loc: `${SITE.url}/${lowerOrigin}/${lowerDest}/${purpose}`,
          changefreq: "weekly",
          priority: "0.5",
          lastmodKey: passportKey,
          images,
        });
      }
    }
  }

  // 4) Hand-written non-INDEXED-purpose URLs (transit / family / etc.).
  for (const [lowerOrigin, entries] of HAND_WRITTEN_BY_ORIGIN) {
    const iso2 = lowerOrigin.toUpperCase();
    for (const { destination, purpose } of entries) {
      urls.push({
        loc: `${SITE.url}/${lowerOrigin}/${destination}/${purpose}`,
        changefreq: "monthly",
        priority: "0.6",
        lastmodKey: `passport:${iso2}`,
      });
    }
  }

  cached = urls;
  return urls;
}

export function getSitemapChunkCount(): number {
  return Math.max(1, Math.ceil(getAllSitemapUrls().length / MAX_URLS_PER_CHUNK));
}

export function getSitemapChunk(id: number): SitemapUrl[] | null {
  const all = getAllSitemapUrls();
  const total = getSitemapChunkCount();
  if (id < 0 || id >= total) return null;
  const start = id * MAX_URLS_PER_CHUNK;
  return all.slice(start, start + MAX_URLS_PER_CHUNK);
}
