/**
 * /updates — auto-generated weekly digest of visa-catalogue changes.
 *
 * Data source: src/data/recent_updates.json, regenerated by
 * src/scripts/buildRecentUpdates.ts (run as part of the nightly
 * GitHub Action). Each entry is a user-facing summary of an adapter
 * change derived from the git commit log, categorised as a fee
 * correction or a catalogue expansion.
 *
 * Why this page exists:
 *   - SEO freshness signal — search engines reward sites that
 *     demonstrably update. A /updates page with rolling 30-day
 *     content tells Google "this isn't a stale wiki".
 *   - Repeat traffic — gives users a reason to come back. Pair with
 *     an email digest later.
 *   - Transparency — accuracy claims become checkable when changes
 *     are listed publicly with the underlying commit SHA.
 *
 * Page is statically rendered; ISR-revalidated once a day so cron-
 * driven updates appear within a day of the workflow committing them.
 */
import Link from "next/link";
import { flagEmoji } from "@/lib/countries";
import { absoluteUrl } from "@/lib/site";
import { MarkUpdatesSeen } from "@/components/UpdatesNavLink";
import data from "@/data/recent_updates.json";

export const metadata = {
  title: "Visa policy updates — what's changed",
  description:
    "Visavu's rolling 30-day log of visa-policy updates, fee corrections, and new visa-catalogue additions. Pulled live from our adapter commits.",
  alternates: { canonical: absoluteUrl("/updates") },
};

export const revalidate = 86400; // 24h ISR

type Update = {
  kind: "adapter_change" | "new_adapter" | "fee_correction";
  date: string;
  destinationIso2: string | null;
  destinationName: string | null;
  title: string;
  detail: string;
  sourceSha?: string;
};

type Payload = {
  generatedAt: string;
  windowDays: number;
  updates: Update[];
};

const KIND_LABEL: Record<Update["kind"], string> = {
  adapter_change: "Catalogue updated",
  new_adapter: "New destination added",
  fee_correction: "Fee corrected",
};

const KIND_TONE: Record<Update["kind"], string> = {
  adapter_change: "bg-blue-50 text-blue-900 border-blue-200 dark:bg-blue-950/40 dark:text-blue-100 dark:border-blue-900",
  new_adapter: "bg-emerald-50 text-emerald-900 border-emerald-200 dark:bg-emerald-950/40 dark:text-emerald-100 dark:border-emerald-900",
  fee_correction: "bg-amber-50 text-amber-900 border-amber-200 dark:bg-amber-950/40 dark:text-amber-100 dark:border-amber-900",
};

function formatHumanDate(iso: string): string {
  return new Date(iso).toLocaleDateString("en-GB", {
    day: "numeric",
    month: "short",
    year: "numeric",
  });
}

export default function UpdatesPage() {
  const payload = data as Payload;
  const sorted = [...payload.updates].sort((a, b) => b.date.localeCompare(a.date));

  return (
    <div className="mx-auto max-w-3xl px-4 py-12">
      {/* Bumps the cookie that drives the nav badge — visiting this page
          clears the "X new updates" pill for the next 90 days. */}
      <MarkUpdatesSeen />
      <header className="mb-10">
        <p className="kicker">Policy updates</p>
        <h1 className="serif-display text-4xl sm:text-5xl mt-2 mb-4">
          What&apos;s changed recently
        </h1>
        <p className="text-[var(--color-ink-muted)] text-lg leading-relaxed">
          The last {payload.windowDays} days of visa-catalogue updates — fee
          corrections, new destinations, and policy changes pulled live from
          our adapter commits. Each entry links back to the source code
          change so the trail is reproducible.
        </p>
        <div className="text-sm text-[var(--color-ink-muted)] mt-3 flex items-center gap-3 flex-wrap">
          <span>Last regenerated: {formatHumanDate(payload.generatedAt)}</span>
          <span className="text-[var(--color-rule-strong)]">·</span>
          <a
            href="/updates.xml"
            className="inline-flex items-center gap-1.5 hover:text-[var(--color-ink)] underline-offset-2 hover:underline"
          >
            <span aria-hidden>📡</span> Subscribe via RSS
          </a>
        </div>
      </header>

      {sorted.length === 0 ? (
        <div className="rounded-xl border border-[var(--color-rule)] bg-[var(--color-paper-elev)] p-8 text-center">
          <p className="text-[var(--color-ink)] font-medium mb-2">
            No catalogue changes in the last {payload.windowDays} days.
          </p>
          <p className="text-sm text-[var(--color-ink-muted)]">
            Visa fees and rules are reasonably stable — most government
            schedules revise once a year. We&apos;ll keep pulling and
            this page will populate as changes land.
          </p>
        </div>
      ) : (
        <ol className="space-y-5">
          {sorted.map((u, i) => (
            <li
              key={`${u.date}-${u.title}-${i}`}
              className="rounded-xl border border-[var(--color-rule)] bg-[var(--color-paper-elev)] p-5 shadow-sm"
            >
              <div className="flex items-start justify-between gap-4 flex-wrap mb-3">
                <div className="flex items-center gap-3">
                  {u.destinationIso2 && (
                    <span className="text-2xl leading-none" aria-hidden>
                      {flagEmoji(u.destinationIso2)}
                    </span>
                  )}
                  <span
                    className={`text-[10px] uppercase tracking-[0.16em] font-semibold px-2 py-1 rounded border ${KIND_TONE[u.kind]}`}
                  >
                    {KIND_LABEL[u.kind]}
                  </span>
                </div>
                <time
                  dateTime={u.date}
                  className="text-xs text-[var(--color-ink-muted)] tabular-nums shrink-0"
                >
                  {formatHumanDate(u.date)}
                </time>
              </div>

              <h2 className="font-semibold text-lg text-[var(--color-ink)] mb-2 leading-snug">
                {u.title}
              </h2>

              <p className="text-sm text-[var(--color-ink-muted)] leading-relaxed mb-3">
                {u.detail}
              </p>

              <div className="flex items-center gap-4 text-xs text-[var(--color-ink-muted)] flex-wrap">
                {u.destinationIso2 && (
                  <Link
                    href={`/destination/${u.destinationIso2.toLowerCase()}`}
                    className="hover:text-[var(--color-ink)] underline-offset-2 hover:underline"
                  >
                    See current {u.destinationName} rules →
                  </Link>
                )}
                {u.sourceSha && (
                  <a
                    href={`https://github.com/bobbysw1/visavu/commit/${u.sourceSha}`}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="font-mono hover:text-[var(--color-ink)] underline-offset-2 hover:underline"
                  >
                    {u.sourceSha}
                  </a>
                )}
              </div>
            </li>
          ))}
        </ol>
      )}

      <div className="mt-12 pt-8 border-t border-[var(--color-rule)] text-sm text-[var(--color-ink-muted)] space-y-2">
        <p>
          Looking for the raw technical change-log (every detected source-record diff)? See{" "}
          <Link href="/changelog" className="underline hover:no-underline">
            /changelog
          </Link>{" "}
          — that page lists every fetch our adapters made, including silent
          no-change runs.
        </p>
        <p>
          This page covers the user-facing summary; /changelog is the
          machine-readable feed.
        </p>
      </div>
    </div>
  );
}
