/**
 * Per-destination per-purpose editorial.
 *
 * Each entry is a 70-120 word factual paragraph naming the actual visa
 * routes, fees, salary thresholds, and bilateral quirks for entering
 * destination X for purpose P. Render on /destination/[iso] when the
 * user picks a purpose tab (so /destination/jp?purpose=work shows the
 * Japan-work content, not the generic destination intro).
 *
 * Scope target: top 20 destinations × 4 most-common purposes
 * (tourism / work / study / family) = 80 entries. For purposes not
 * covered here (business / transit / diplomatic) the page falls back
 * to the destination's general intro.
 *
 * Editorial bar: name specific visa programmes (UK Skilled Worker,
 * Canada Express Entry, Australia Subclass 482), current fees and
 * thresholds, and bilateral exceptions worth knowing. Avoid promising
 * outcomes — describe what's available, not what will work for the
 * reader's case.
 */
import type { Purpose } from "@/lib/types";

export type DestPurposeKey = `${string}:${Purpose}`;

export const DEST_PURPOSE_INTROS: Partial<Record<DestPurposeKey, string>> = {
  // ════════════════════════════════════════════════════════════════
  // UNITED STATES
  // ════════════════════════════════════════════════════════════════
  "US:tourism": `Visiting the United States is gated by either ESTA (the Visa Waiver Program, for ~40 designated nationalities — UK, EU, Japan, South Korea, Singapore, Australia, New Zealand, Israel, Chile, Taiwan and others — 90 days, no extensions) or the B-1/B-2 visitor visa (everyone else, multi-year multi-entry, but each stay capped at six months by CBP officer discretion). VWP requires an e-passport with chip. B-1/B-2 requires an in-person consular interview, $185 fee, evidence of strong home-country ties under Section 214(b)'s presumption of immigrant intent. Land entry from Canada / Mexico uses I-94 issuance. Cannot work or study on either route.`,
  "US:work": `Work in the United States runs through employer sponsorship — the US has no points-based system. Specialty-occupation H-1B (annual cap of 65k regular + 20k masters, lottery, March registration, October start) is the main route for graduates and tech / finance professionals. L-1A/L-1B for intracompany transferees (no cap). O-1 extraordinary-ability for high-achievers. E-2 treaty investor for nationals of ~80 treaty countries (UK, Germany, Japan, etc. — not India or China). TN under USMCA for Canadians and Mexicans in 60+ specified professions. EB-2 / EB-3 employment-based green card paths require labor certification (PERM, ~18 months) then I-140 + I-485 — backlogs are decades for India and China.`,
  "US:study": `Study in the US is the F-1 student visa (academic), M-1 (vocational), or J-1 (exchange visitor — au pairs, summer work travel, postdocs, research scholars). F-1 requires SEVIS I-20 issued by a designated school, proof of financial support for year one ($30k-80k depending on programme), and consular interview. F-1 enables on-campus work (20 hr/week term-time), Curricular Practical Training (CPT) during the programme, and Optional Practical Training (OPT) up to 12 months after graduation — STEM degrees get a 24-month extension (36 months total OPT). H-1B sponsorship is the typical bridge from OPT to long-term work. Tuition at private universities $50k-90k/year; in-state public tuition only for residents.`,
  "US:family": `US family-route visas split by whether the sponsor is a US citizen (no annual caps for immediate relatives — spouse, unmarried children under 21, parents of citizens 21+) or a green-card holder (capped Family Preference categories with multi-year waits). Spouse of US citizen: K-1 fiancé(e) visa (90 days to marry, then adjust status) or IR-1 / CR-1 immigrant visa (process at the consulate, immigrant on arrival). I-130 petition fee $675, NVC processing 6-12 months, consular interview, medical, biometrics. Conditional green card if married less than two years at approval — converts to 10-year card after I-751 joint petition. Affidavit of support I-864 requires income 125% above federal poverty line.`,

  // ════════════════════════════════════════════════════════════════
  // UNITED KINGDOM
  // ════════════════════════════════════════════════════════════════
  "GB:tourism": `Visiting the UK has two tracks. Non-visa nationals (US, EU, Australia, Canada, Japan, South Korea, Singapore, GCC, etc.) need an Electronic Travel Authorisation (ETA, £16, applied online, valid 2 years for multiple visits up to 6 months each) from 2025. Visa nationals (~130 countries including India, Nigeria, China, Russia, Bangladesh, Pakistan) apply for a Standard Visitor visa at a UK Visa Application Centre — £127 base fee, 3-week standard processing, in-person biometrics. Either way: no work permitted (with narrow exceptions for permitted business activities), 6-month maximum stay, must demonstrate intent to leave.`,
  "GB:work": `Work in the UK is dominated by the Skilled Worker visa — employer-sponsored, requires a job offer from a Home Office licensed sponsor, salary threshold £38,700 baseline (£23,200 for new entrants and shortage occupations) from April 2024. Application fee £719-£1,500 depending on length, plus £1,035/year Immigration Health Surcharge. Routes to settlement (ILR) after 5 years. Other routes: Global Talent (no sponsor needed, endorsement-based, fast-track for academics/digital tech/arts), Health and Care Worker (£200 lower threshold, reduced IHS, designed for NHS recruitment), Innovator Founder (£50k+ endorsed startup), Scale-up (high-growth UK employer). Graduate Route gives 2 years (3 for PhD) of unsponsored work after UK study.`,
  "GB:study": `Study in the UK is the Student visa (replaced the Tier 4 in 2020). Requires CAS (Confirmation of Acceptance for Studies) from a licensed sponsor, English proficiency at the level required by the institution (typically IELTS 6.0-7.5), proof of funds for tuition + £1,334/month London / £1,023 outside London for up to 9 months. £490 application fee, £776/year IHS. 20 hours/week term-time work permitted, full-time vacation. Graduate Route (2 years post-study, 3 for PhD) gives unsponsored work rights after graduation. Tuition: international students typically £15k-45k/year depending on university and programme. Routes to settlement via Skilled Worker after switching from Graduate.`,
  "GB:family": `UK family visas are among the most restrictive in Europe. Partner visa (Spouse / Civil Partner / Fiancé(e) / Unmarried Partner) requires the sponsoring partner to earn at least £29,000/year (raised from £18,600 in April 2024, with phased increases to £38,700 deferred). Or savings of £88,500+, or combinations. Plus English-language test at A1 level. 5-year route to settlement on the spouse visa (or 10-year route for those not meeting the requirements). Application fee £1,846, plus £1,035/year IHS. Refusal rate has historically been 15-25%. Parent visa (Adult Dependent Relative) is extraordinarily restrictive — under 100 grants per year out of thousands of applications.`,

  // ════════════════════════════════════════════════════════════════
  // FRANCE
  // ════════════════════════════════════════════════════════════════
  "FR:tourism": `Visiting France for short stays follows the Schengen 90-in-180-day rule for visa-exempt nationalities (US, UK, Australia, Canada, Japan, South Korea, Singapore, GCC, most of Latin America), and a Schengen Type C visa for everyone else. ETIAS authorisation arrives late 2026 for visa-exempt travellers (€7, valid 3 years). EES biometric entry/exit records from late 2025. Type C visa €90 application fee, processed at the local French consulate, requires travel insurance €30,000 minimum, proof of accommodation, return ticket. France's overseas territories (Martinique, Guadeloupe, French Polynesia, New Caledonia) have separate visa regimes outside Schengen.`,
  "FR:work": `Work in France is dominated by the Talent Passport — a 4-year multi-year residence permit for skilled professionals, founders, researchers, artists, investors, and intra-company transfers. Salary thresholds vary by sub-category (typically €43,000+ baseline). The Skilled and Talent (Carte de séjour Salarié) route covers standard sponsored employment. EU Blue Card available for highly-qualified workers earning at least 1.5× the national average gross salary. Long-stay visa VLS-TS for stays over 90 days (one-year initial, then renewable into a multi-year carte de séjour). Carte de résident after 5 years of legal residence. Citizenship after 5 years (2 for spouses of citizens). French language requirement at B1 for the carte de résident.`,
  "FR:study": `Study in France: Long-Stay Student visa VLS-TS étudiant — apply at the local French consulate with Campus France pre-registration (mandatory for ~70 nationalities including US, China, India), proof of admission to an institution, financial resources €615/month minimum, accommodation evidence. Tuition at public universities: €170-380/year licence, €243-601/year master's for non-EU; private grandes écoles €5,000-€20,000+/year. CAF housing subsidy available to students paying rent. 964 hours/year work permitted on student visa. APS (Autorisation Provisoire de Séjour) gives master's-level and PhD graduates 12-24 months of post-study work-search time. French B2 language requirement for master's in French; English-taught programmes increasingly common.`,
  "FR:family": `French family routes: VLS-TS Conjoint de Français for spouses of French citizens (immediate eligibility for 1-year carte de séjour, no income requirement on the French sponsor). Family reunification (Regroupement familial) for spouses and minor children of non-EU residents — requires sponsor to have legally resided in France 18+ months, suitable accommodation, and stable income at SMIC level. Application via OFII. PACS (civil union) recognised as a basis for family residence. Carte de résident for spouses after 3 years on the spouse permit. Naturalisation after 4 years of marriage (with continuous residence) — French language and integration interview required. Schools are free, healthcare via Sécurité Sociale once enrolled.`,

  // ════════════════════════════════════════════════════════════════
  // GERMANY
  // ════════════════════════════════════════════════════════════════
  "DE:tourism": `Germany follows Schengen 90-in-180-day rules — visa-free for ~60 nationalities, Schengen Type C visa (€90) for the rest. ETIAS from late 2026 for the visa-exempt, EES biometric tracking from late 2025. Schengen visa applications via VFS Global centres. Travel insurance €30k mandatory. For longer stays, Germany requires a Type D national long-stay visa before arrival (cannot upgrade from Schengen short-stay). Border officers may ask for proof of accommodation and return ticket.`,
  "DE:work": `Work in Germany is among the most accessible in the EU since the Skilled Immigration Act 2023 reform. Skilled Worker visa for recognised university/vocational qualifications + job offer. Opportunity Card (Chancenkarte, 2024) is a points-based job-seeker visa — no offer required, 12 months in Germany to find work. EU Blue Card for graduates earning ≥ €45,300/year (or €41,000 in shortage occupations), 21-month path to permanent residence with B1 German. Job Seeker visa: 6 months unsponsored. Niederlassungserlaubnis (permanent settlement) after 5 years (33 months on Blue Card with B1, 21 with B2). German citizenship after 5 years (3 with "well-integrated" status) under the 2024 citizenship reform.`,
  "DE:study": `Germany: Student visa for stays over 90 days. Public university tuition is free in most Länder (Baden-Württemberg charges €1,500/semester for non-EU). Application via uni-assist or directly to the university. Blocked account (Sperrkonto) of €11,904 for year one (€992/month). Health insurance ~€120/month for under-30s, more after. German language requirement (DSH or TestDaF) for German-taught programmes; English-taught Master's increasingly common at TU9 universities. 120 full days / 240 half days work permitted/year. Post-study: 18-month job-seeker permit to find work, then switch to Skilled Worker / Blue Card. Many international students stay long-term — Germany's settlement path is among Europe's most accessible.`,
  "DE:family": `German family routes: spouse of German citizen — direct eligibility for residence permit + accelerated naturalisation after 3 years of legal residence + 2 years of marriage. Spouse of skilled-worker / EU Blue Card holder enters under family reunification with A1 German language requirement (waived for highly-qualified residents). Same-sex marriage and civil partnership recognised since 2017. Children under 16 enter freely; 16-18 require A1 German unless joining a parent with Blue Card. Family reunification visa application via the German consulate before arrival. Spouse work rights from day one. Naturalisation routes typically 5 years (3 for "well-integrated") under the 2024 reform.`,

  // ════════════════════════════════════════════════════════════════
  // ITALY
  // ════════════════════════════════════════════════════════════════
  "IT:tourism": `Italy: Schengen 90/180 visa-free for ~60 nationalities (ETIAS from late 2026). Type C visa €90 for visa nationals — process at Italian consulate or via VFS. Travel insurance €30k mandatory. Italian border control regularly checks proof of accommodation and onward ticket. EES biometric tracking from late 2025. Italy's overseas presence is limited; no separate territory visa regimes.`,
  "IT:work": `Italy's work routes: standard Lavoro Subordinato (employer-sponsored) is governed by the annual decreto-flussi quotas — historically restrictive but raised to 165,000 in 2024. Lavoro Autonomo for self-employment / freelancing — capped, requires capital and demonstrating market need. Elective Residence (no work permitted) for passive-income retirees with €31,000+/year proven income. Investor Visa Italy (€500k+ startup / €2M+ government bonds / €1M philanthropic). Digital Nomad Visa launched in 2024 — €28,000+ annual income, registered remote employer. EU Blue Card available. Permesso di soggiorno (residence permit) renewals at the questura. Permanent residence after 5 years; citizenship after 10 years (4 for EU nationals, 3 for spouses of Italian citizens). Italian descent (jure sanguinis) is among the most accessible globally.`,
  "IT:study": `Italy: Student visa requires admission to a recognised institution. Public university tuition €1,000-4,000/year for non-EU (capped to ISEE income). Application via Universitaly portal. Tuscan / Roman / Northern universities popular with international Master's students. Italian-taught programmes require B2 Italian; many Master's in English. 20 hours/week / 1,040 hours/year part-time work permitted. Post-study: 12-month job-search permit then switch to work permit. Italy's stay-back rates are among Europe's highest for STEM postgrads. Tuition assistance via DSU regional bodies for low-income students.`,
  "IT:family": `Italy: Family Reunification (Ricongiungimento Familiare) for non-EU residents — requires Permesso di Soggiorno held 1+ year, suitable housing, income at INPS minimum. Spouse of Italian citizen: immediate family-route eligibility, naturalisation after 2 years (3 outside Italy). Italian descent claims (jure sanguinis) — anyone with an Italian-born ancestor and unbroken citizenship line can claim Italian citizenship by descent (no generational limit on the male line; recent court rulings restrict the female line pre-1948). Major route for Latin American / North American descendants. Comune-level processing (often 2-4 year wait); judicial proceedings to bypass comune backlogs are common. EU long-term resident permit after 5 years.`,

  // ════════════════════════════════════════════════════════════════
  // SPAIN
  // ════════════════════════════════════════════════════════════════
  "ES:tourism": `Spain: Schengen 90/180 visa-free for ~60 nationalities (ETIAS from late 2026, EES from late 2025). Type C visa €90 for visa nationals via VFS Global. Travel insurance €30k mandatory. Spain enforces 90/180 strictly; popular long-stay overstay destinations face border checks on re-entry. Schengen visa applications processed by the Spanish consulate covering your residential area.`,
  "ES:work": `Spain's work routes have expanded substantially. Standard sponsored work (Autorización de residencia temporal y trabajo por cuenta ajena) — employer-sponsored, requires the position not be on the shortage occupation list to qualify. Highly Qualified Worker (Profesionales Altamente Cualificados) — €40,000+/year salary, faster processing. Entrepreneur Visa for innovative startups with state endorsement. Self-Employed Visa (Trabajador por Cuenta Propia) for freelancers / business owners. Digital Nomad Visa launched 2023 — €2,762/month proven income (200% SMI) from foreign sources, 1-year initial, renewable, 5-year track to PR. Non-Lucrative Visa for passive-income retirees — €2,400/month proven income, no work permitted. EU Blue Card available. Permanent residence after 5 years; Spanish citizenship after 10 years standard (2 years for Iberoamerican nationals, Sephardic Jews historically — closed 2024).`,
  "ES:study": `Spain: Student visa (Visado de Estudios) for stays over 90 days. Public university tuition for non-EU: €15-45/credit, full degree ~€1,500-3,000/year — among Europe's cheapest. Private universities €5,000-15,000/year. Apply via the Spanish consulate with admission letter, financial proof €600/month (100% IPREM), health insurance with full coverage. Limited work rights (20 hours/week with separate authorisation). Post-study: 12-month job-search visa, then switch to work or self-employment. Spanish (or English-taught Master's) instruction. CCSE and DELE A2 required for eventual naturalisation after qualifying residence.`,
  "ES:family": `Spain's family routes: Reagrupación Familiar for spouse + minor children of non-EU residents — sponsor must have held permanent residence (or 1+ year temporary with proof of renewal) and suitable housing/income. Spouse of Spanish citizen: immediate eligibility for residence card, naturalisation after just 1 year of legal residence (the shortest in Europe). Pareja de Hecho (civil partnership) recognised at both autonomous-community and national level. EU citizens' family members covered under EU directives — generally easier. Tarjeta de familiar de ciudadano de la Unión. Children's enrolment in public schools free.`,

  // ════════════════════════════════════════════════════════════════
  // CANADA
  // ════════════════════════════════════════════════════════════════
  "CA:tourism": `Canada: Electronic Travel Authorisation (eTA, CA$7, applied online) for ~50 visa-exempt nationalities (UK, EU, Japan, South Korea, Singapore, Australia, etc.) — 6-month stay, multi-entry, valid 5 years. US citizens are exempt from both visa AND eTA — just present a US passport. Visa nationals (most of Africa, Asia, Latin America) need a TRV (Temporary Resident Visa) processed via VFS or VAC at a Canadian visa office abroad. CA$100 application fee. Mexico went from eTA back to TRV in 2024 for most applicants. Stay extension via IRCC online — must apply before status expires.`,
  "CA:work": `Canada's work routes are dominated by Express Entry — points-based federal skilled migration (Federal Skilled Worker, Federal Skilled Trades, Canadian Experience Class). Comprehensive Ranking System scores age + education + language (English IELTS / French TEF) + work experience + Canadian work/study/family ties. Provincial Nominee Programs (each province runs separate streams — Ontario OINP, BC PNP, Alberta AAIP, Saskatchewan SINP, etc.) — provincial nomination adds 600 CRS points, near-guaranteed Express Entry invitation. Atlantic Immigration Program for the 4 Atlantic provinces. Start-up Visa with designated investor / incubator endorsement. Self-Employed Persons (cultural / athletic). Caregiver streams. LMIA-based Temporary Foreign Worker programmes for closed work permits. Open work permit through spouse-of-Canadian / post-graduation routes. PR direct on Express Entry; citizenship after 3 of 5 years physical presence.`,
  "CA:study": `Canada's Study Permit process: admission to a DLI (Designated Learning Institution) → application via IRCC. Required documents: acceptance letter, GIC of CA$20,635 (raised from $10k in 2024 to deter abuse), tuition payment receipt, biometrics. Provincial Attestation Letter (PAL) requirement from January 2024 caps total study-permit issuance. Tuition for international students CA$20,000-60,000/year depending on programme. 24 hours/week off-campus work permitted (raised from 20). Post-Graduation Work Permit (PGWP) for up to 3 years of unsponsored work after graduation from eligible programmes — major bridge to Express Entry. Quebec runs separate system via CAQ + study permit. Healthcare coverage varies by province.`,
  "CA:family": `Canada family sponsorship: spouse / common-law / conjugal partner of citizen / PR — sponsor must demonstrate ability to financially support (no specific income threshold for spouses, unlike many countries). Outland (consular) or Inland (in Canada) processing. Processing time 12-24 months. No conditional PR (Canada removed the 2-year cohabitation requirement in 2017). Parents and Grandparents Program (PGP) — operates as a lottery, with low cap and stringent Minimum Necessary Income requirements for 3 years preceding. Super Visa as an alternative — 10-year multi-entry visitor for parents / grandparents with proof of insurance and income. Dependent children covered to age 22 if dependent on parents.`,

  // ════════════════════════════════════════════════════════════════
  // AUSTRALIA
  // ════════════════════════════════════════════════════════════════
  "AU:tourism": `Australia: Visitor visa options depend on passport. eVisitor (subclass 651) free for EU/EEA/UK nationals, multiple-entry, 12-month validity. ETA (subclass 601) for US, Canada, Japan, South Korea, Singapore, Brunei, Hong Kong, Malaysia, Taiwan — AU$20 fee, app-based, 12-month validity. Everyone else: Visitor visa (subclass 600) — AU$210, processed online or via VFS. Maximum stay 3 months by default, up to 12 months in special cases. No work permitted. Christmas Island, Norfolk Island, Cocos Islands all use the same Australian visa system. Trans-Tasman: NZ citizens get the SCV-444 automatically.`,
  "AU:work": `Australia: Skilled migration is points-based. Skilled Independent (subclass 189) — 65-point minimum, EOI via SkillSelect, no sponsor required, leads directly to PR. Skilled Nominated (subclass 190) — state-nominated, +5 points. Skilled Work Regional (subclass 491) — 5-year provisional, regional area requirement, then 191 PR. Employer-Sponsored: Temporary Skill Shortage (subclass 482, raised TSMIT to AU$73,150 from July 2024 + Annual Market Salary Rate benchmarking), Employer Nomination Scheme (subclass 186) for permanent. Global Talent (subclass 858) for exceptional ability. Investor / Business Innovation (subclass 188 / 888). Working Holiday (417 / 462) for under-35s from 30+ partner countries. Citizenship after 4 years (incl. 12 months as PR).`,
  "AU:study": `Australia's Student visa (subclass 500) requires CoE (Confirmation of Enrolment) from a CRICOS-registered institution. Application AU$1,600 (raised from $710 in 2024 — the highest student visa fee globally). Financial proof: living costs AU$29,710/year + tuition + return airfare. OSHC mandatory (~AU$650/year). Tuition: bachelor's AU$25,000-50,000/year, master's AU$28,000-60,000. 48 hours/fortnight work permitted during term. Temporary Graduate visa (subclass 485) — 2-4 years post-study unsponsored work (longer for regional, STEM, Master's by research, PhD). Common path to PR via Skilled Independent / Skilled Nominated. Critical Technologies and Education streams favoured in current intake reviews.`,
  "AU:family": `Australia family routes: Partner visa (subclass 820/801) — onshore — requires de facto evidence (12+ months together for de facto, or registered relationship), AU$8,850 application fee, 12-30 month processing for 820, then 801 PR after relationship continues. Subclass 309/100 offshore equivalent. Prospective Marriage (subclass 300) for fiancés. Parent visas: Contributory Parent (143/173/884) AU$50,000+ per applicant, 4-7 year wait. Non-contributory Parent (103) AU$5,000 application but 20-30 year wait. Aged Parent and Contributory Aged Parent (similar but 65+). Dependent children: 101/445 offshore/onshore. Citizenship after 4 years of qualifying residence (including 12 months as PR).`,

  // ════════════════════════════════════════════════════════════════
  // JAPAN
  // ════════════════════════════════════════════════════════════════
  "JP:tourism": `Japan: ~70 nationalities visa-free for short stays (most of Europe, the US, UK, Canada, Australia, NZ, Singapore, Hong Kong, South Korea, Israel, most of Latin America). 90 days standard, 30 for select countries (e.g. Indonesia e-passport pre-registered). Visa nationals apply for Temporary Visitor visa at Japanese embassy / consulate (¥3,000-6,000, no fee for several nationalities). Working-holiday agreements with 30+ countries support 12-month work-and-travel for under-30s. Visa-Free Working Holiday distinct from tourism. Visa extension to 90 days possible at Immigration Bureau in limited cases. Japan tightened visa-free for several nationalities in 2024.`,
  "JP:work": `Japan's work routes: Engineer/Specialist in Humanities/International Services for white-collar work (employer-sponsored, requires bachelor's or 10+ years experience). Highly Skilled Professional (HSP, points-based) — 70+ points = 5-year visa, 80+ = 1-year fast-track to PR. J-Find and J-Skip (2023 reforms for graduates of top global universities). Specified Skilled Worker (SSW) Type 1 / Type 2 — blue-collar shortage occupations (caregiving, construction, agriculture, etc.) — Japanese-language test required for SSW. Business Manager visa (¥5M+ capital, real office). Intra-company Transferee. Skilled Labor (specific trades). PR after 10 years on most routes — 1-3 years for HSP. Japan does not allow dual citizenship in most cases.`,
  "JP:study": `Japan's Student visa (College Student visa) requires Certificate of Eligibility from the receiving institution. University tuition: national universities ¥535,800/year + ¥282,000 admission; private universities ¥800k-1.5M/year + ¥250-300k admission. Japanese-language proficiency typically JLPT N2 for undergraduate / N1 for postgraduate (English-taught programmes at SGU universities don't require Japanese). MEXT scholarship covers tuition + ¥143-145k/month stipend. 28 hours/week part-time work permitted with separate authorisation. Post-study: switch to working visa requires job offer at degree-level position. Designated Activities visa for job-search (1-year) post-graduation.`,
  "JP:family": `Japan family routes: Dependent visa for spouses + unmarried minor children of working-visa holders — no work rights (28 hours/week with separate authorisation). Spouse / Child of Japanese National — full work rights, 5-year initial. Spouse / Child of Permanent Resident — full work rights, 5-year initial. PR for spouses after 3 years of marriage (cohabitating in Japan 1+ year). Same-sex marriage NOT recognised as a basis for spouse visa (partnership certificates from some municipalities don't apply nationally). Japan generally does not allow dual citizenship — naturalisation requires renouncing other citizenships. Dependent visa to Specified Activities for spouses of HSP-1 holders allows working full-time.`,

  // ════════════════════════════════════════════════════════════════
  // SOUTH KOREA
  // ════════════════════════════════════════════════════════════════
  "KR:tourism": `South Korea: K-ETA (Korea Electronic Travel Authorisation) required for ~110 visa-exempt nationalities — KRW 10,000, valid 3 years, multi-entry. The K-ETA was temporarily waived for 22 major partner nationalities (US, UK, Canada, Australia, NZ, EU, Japan, etc.) through December 2025 — these travellers can enter visa-free without K-ETA during the waiver. Visa nationals apply for C-3 visa at Korean consulate. Maximum visa-free stay 90 days. Working-holiday H-1 for under-30s from 25+ partner countries. Refunds processed via the K-ETA website (rare).`,
  "KR:work": `South Korea's work visas: E-7 (Specially Designated Activities) — main route for foreign professionals, requires bachelor's + relevant experience + employer sponsorship + salary ≥ 80% Korean average. D-8 (Corporate Investor) for entrepreneurs / company founders. D-10 (Job-Seeker) for graduates of recognised institutions to find work in Korea. F-2 (Resident) and F-5 (Permanent Resident) for long-term residents. F-6 (Marriage) for spouses of Koreans. Highly Skilled Personnel point-based GOLD CARD for STEM specialists. Hi-Korea online portal for most applications. E-9 (Non-Professional) for blue-collar workers from 16 EPS partner countries (subject to annual quotas). PR after 5 years on most routes.`,
  "KR:study": `Korea's student visas: D-2 (Regular Student) for university-level degree programmes. D-4 (General Trainee) for Korean-language students + technical training. KAIST, SNU, POSTECH popular. Tuition: national universities KRW 2-5M/semester for undergrad, private universities KRW 4-12M/semester. Korean Government Scholarship Program (KGSP) covers tuition + KRW 900k-1M/month for selected international students. Topik (Korean language test) typically Level 3+ for Korean-taught programmes; English-taught programmes increasingly common. 20 hours/week work permitted with separate authorisation. D-10 job-search visa for post-study (6 months + renewable to 2 years for top-tier graduates).`,
  "KR:family": `Korea family routes: F-6 (Marriage Migrant) for spouses of Koreans — no minimum income threshold but spouse must guarantee residency. Path to PR (F-5) after 2 years. Naturalisation after 2 years of marriage + Korean language Topik 4 + integration test. F-1 (Visiting / Joining Family) for parents and minor children of Koreans / residents — no work rights without separate authorisation. F-2-1 spouse visa with broader work rights. Same-sex partnerships NOT recognised for visa purposes. Children of mixed marriages get automatic Korean citizenship if either parent is Korean. Korea generally requires renunciation of foreign citizenship for naturalisation (with limited exceptions for elderly / multicultural family registrants).`,

  // ════════════════════════════════════════════════════════════════
  // SINGAPORE
  // ════════════════════════════════════════════════════════════════
  "SG:tourism": `Singapore: 30-day visa-free stay for most nationalities (~160 countries) — extendable to 90 in some cases. Visa nationals (small list including China, India default, most of Africa, several Middle East states) apply for entry visa via authorised local sponsor in Singapore. Indian and Chinese nationals have specific arrangements — China granted 30-day mutual visa-free in February 2024. SG Arrival Card (electronic, free, mandatory within 3 days of arrival) required for ALL visitors regardless of visa status. Singapore enforces overstays strictly — caning is still a stipulated penalty for serious overstays.`,
  "SG:work": `Singapore's work passes: Employment Pass (EP) — minimum salary SGD$5,000/month (raised from $4,500 in 2023, with sector-specific minima for finance), employer-sponsored, points-based COMPASS framework from 2023 (qualifications + diversity + salary + scarcity). S Pass for mid-skilled at SGD$3,150+. Personalised Employment Pass (PEP) for high earners not tied to employer. Tech.Pass for global tech talent (5-year, US$20k+ monthly fixed salary OR product founder credentials). Overseas Networks and Expertise (ONE) Pass — 5-year for SGD$30,000+/month earners. Entrepreneur Pass (EntrePass) for innovative startup founders. PR (PERMANENT RESIDENT) after 2+ years of EP and "stable" employment — heavily discretionary. Citizenship after 2+ years as PR.`,
  "SG:study": `Singapore Student Pass: required for full-time enrolment at IHL (Institute of Higher Learning — NUS, NTU, SMU, SIT, SUSS, SUTD) or registered private schools. Online via SOLAR application. Tuition: NUS / NTU bachelor's around SGD$30-40k/year for international students (lower with Tuition Grant scheme + bond). Tuition Grant Scheme requires 3-year service in Singapore-registered employer post-graduation. NUS / NTU Master's SGD$28-50k/year. 16 hours/week work permitted during term. Post-study: Long-Term Visit Pass (1-year unsponsored job-search) for graduates of approved IHLs. Common path to EP / PR via post-study employment.`,
  "SG:family": `Singapore family passes: Dependant's Pass (DP) for spouses + unmarried children under 21 of EP / S Pass / Tech.Pass holders earning SGD$6,000+ (raised from $5,000). DP holders must obtain Letter of Consent or own work pass to work (rule tightened in 2021). Long-Term Visit Pass (LTVP) for common-law spouses, parents, step-children, handicapped children. Spouse of Singapore citizen → LTVP (1+ year) → PR (typically 2-4 years) → citizenship (2+ years after PR). PR for spouses is heavily case-by-case. Same-sex partners NOT recognised for DP. Section 377A (criminalising sex between men) was repealed in 2022 but marriage equality is not legislated.`,

  // ════════════════════════════════════════════════════════════════
  // CHINA
  // ════════════════════════════════════════════════════════════════
  "CN:tourism": `China expanded visa-free entry substantially in 2024-25. Visa-free tourism for ~50 nationalities including most of EU, UK, Germany (since Nov 2024 — 30 days, mutual), South Korea, Singapore, Thailand, Malaysia, Brazil, Mexico, NZ, AU. US passports still require an L visa applied at the Chinese embassy or consulate. 144-hour Transit Without Visa scheme available at 20+ ports of entry — Beijing, Shanghai, Guangzhou, Chengdu, etc. — for passengers connecting to a third country within 144 hours. Hong Kong and Macau have separate immigration regimes from mainland China.`,
  "CN:work": `China's Z visa (Work Visa) — employer-sponsored, requires recognised degree + 2+ years' experience + clean criminal record + health check. Talent classification A/B/C with corresponding wait times and renewal frequencies. R visa for high-end talent. Foreign Permanent Residence (Green Card) is famously restrictive — historically issued to under 10,000 foreigners. Recent reforms include the Shanghai Free Trade Zone fast-track. Hong Kong runs separate work permits (General Employment Policy, Top Talent Pass Scheme, Quality Migrant Admission Scheme). Macau similar via Labour Affairs Bureau. Mandarin not strictly required but increasingly expected.`,
  "CN:study": `China's X1 (long-term) and X2 (short-term) student visas. Apply via the Chinese embassy with admission notice + JW201/JW202. Tuition at top universities: Tsinghua, Peking ¥30-50k/year for international students, lower at provincial universities. Chinese Government Scholarship covers tuition + RMB 2,500-3,500/month stipend. HSK Level 4+ required for Chinese-taught programmes; English-taught Master's increasingly common at C9 / 985 / 211 universities. Work permitted with separate authorisation. Post-study: switch to work visa requires Z visa application from outside mainland China.`,
  "CN:family": `China's S1 (long-term) / S2 (short-term) family visa for spouses + dependent children of foreign-passport visa holders + Chinese citizens. Q1 / Q2 for family of Chinese citizens / PRs (longer-term). Marriage to a Chinese citizen does not automatically grant citizenship or PR — separate Green Card application required (and PR is rare). Children of foreign-Chinese mixed parentage typically retain foreign citizenship; renunciation paths vary. Same-sex partnerships not recognised. Mainland China generally does not permit dual citizenship — naturalisation requires renouncing other citizenships.`,

  // ════════════════════════════════════════════════════════════════
  // NETHERLANDS
  // ════════════════════════════════════════════════════════════════
  "NL:tourism": `Netherlands: Schengen 90/180 visa-free for ~60 nationalities (US, UK, Australia, Canada, Japan, South Korea, Singapore, GCC, most of Latin America). Type C visa €90 for visa nationals via VFS. ETIAS authorisation from late 2026 for visa-exempt travellers. EES biometric tracking from late 2025. Travel insurance with €30k minimum required. Caribbean Netherlands (Bonaire, Sint Eustatius, Saba) follows separate visa rules; Aruba and Sint Maarten run independent immigration.`,
  "NL:work": `Netherlands work routes: Highly Skilled Migrant (Kennismigrant) is the dominant route — employer must be a recognised sponsor (erkend referent), salary thresholds €5,688/month for ages 30+ or €4,171/month for under-30 (2025 values), 30% Ruling tax benefit common for new arrivals. EU Blue Card alternative for very high earners. Self-Employed Visa requires substantial Dutch business case. Orientation Year for graduates of recognised universities (12 months job-search, then switch). Intra-Company Transfer. Start-up visa for tech founders. PR after 5 years; Dutch citizenship after 5 years standard (3 for spouses, fast-track with B1+ Dutch). Dutch generally does NOT permit dual citizenship for naturalisation outside narrow exceptions.`,
  "NL:study": `Netherlands student visa for non-EU: residence permit + entry visa for stays over 90 days, application via the university (recognised sponsors handle the paperwork). Tuition: bachelor's €8,000-15,000/year for non-EEA, master's €10,000-20,000/year. Cost of living €900-1,200/month outside Amsterdam, more in. 16 hours/week work permitted year-round or full-time June-August. Orientation Year visa (1-year unsponsored job-search post-graduation). English-taught Master's widely available — Dutch language not required. Brexit-era tightening of housing affordability for international students is a current political flashpoint.`,
  "NL:family": `Netherlands family routes: Spouse/Partner visa requires the Dutch sponsor to earn at least 100% of the statutory minimum wage (€2,070+/month gross 2025) for permanent contract / 110% for fixed-term. Civil-fellowship MVV. Partner must pass A1 Dutch language test from abroad (oral + written exam at Dutch embassy) BEFORE the residence permit is issued — unique to Netherlands. Spouse of Dutch citizen: civic integration exam at A2 within 3 years of arrival required for PR. Same-sex marriage and partnership fully recognised. Children of mixed-citizenship couples: Dutch passport at birth if either parent Dutch.`,

  // ════════════════════════════════════════════════════════════════
  // PORTUGAL
  // ════════════════════════════════════════════════════════════════
  "PT:tourism": `Portugal: Schengen 90/180 visa-free for ~60 nationalities (ETIAS from late 2026, EES from late 2025). Type C visa €90 for visa nationals via Portuguese consulate or VFS. Travel insurance €30k required. Portugal enforces 90/180 less strictly than France/Germany but border officers do check. CPLP (Community of Portuguese Speaking Countries) nationals — Brazil, Angola, Mozambique, etc. — have simplified consular procedures for both short-stay and long-stay applications.`,
  "PT:work": `Portugal's long-stay catalogue is among Europe's most accessible: D7 Visa (passive income — proven €820/month + 30% per dependent), D8 Digital Nomad Visa (€3,480+/month income from remote employer, 2023 launch — increased demand since Spain DNV restrictions), D1 Skilled Worker (employer-sponsored), D2 Entrepreneur (innovative business plan + investment), D3 Highly Qualified (€10,800+ annual contract salary, 4× the IAS Index). Tech Visa for IT specialists in certified tech companies. Golden Visa restricted from real estate in October 2023; remains for venture capital (€500k+), arts donation (€250k+), national heritage. Portuguese citizenship after 5 years of legal residence — fastest in Europe.`,
  "PT:study": `Portugal student visa for stays over 90 days: Portuguese university tuition for international students €1,000-7,000/year (medicine, law higher). Application via the Portuguese consulate with admission letter, financial proof €600/month minimum, accommodation evidence. Cost of living €600-1,000/month. English-taught Master's increasingly common at top universities (Lisbon, Porto, Coimbra). Portuguese (or English-taught) instruction. Work permitted with the residence card. Post-study: easy switch to D-class long-stay visa for graduates. Portuguese language eligibility for citizenship: A2 CIPLE test after 5 years.`,
  "PT:family": `Portugal family routes: Reagrupamento Familiar (Family Reunification) for spouses + minor children of residents — application via the Portuguese consulate or in-country. Spouse of Portuguese citizen: residence card via consulate or local SEF / AIMA office. Naturalisation after 5 years of legal residence (3 years for spouses with proof of cohabitation, simplified for CPLP nationals after specific qualifying periods). Sephardic Jewish descent route ended for new applicants in March 2024. Same-sex marriage fully recognised since 2010. CPLP Mobility Agreement (2022) allows Brazilian / Mozambican / Angolan / etc. nationals streamlined residence in Portugal.`,

  // ════════════════════════════════════════════════════════════════
  // UNITED ARAB EMIRATES
  // ════════════════════════════════════════════════════════════════
  "AE:tourism": `UAE: ~80 nationalities get visa-free / visa-on-arrival entry. US, UK, EU, Canada, Australia, Japan, South Korea, Singapore, China, all GCC — visa-free 30-90 days. Indians with US / UK / EU residence permits get visa-on-arrival; ordinary Indian passport needs e-Visa pre-approval. Africa / many Asian / most Middle Eastern nationalities need e-Visa or sponsored visa via UAE-based hotel / company. Tourist visa extends once for 30 days at AED 600. Penalties for overstaying are AED 50/day. Visit visas can be converted to employment/residence visas in-country via GDRFA (Dubai) or ICP (Abu Dhabi).`,
  "AE:work": `UAE work residence: standard 2-year Employment Visa sponsored by a UAE employer (cancelled if employment ends, with 30-day grace to find another sponsor or leave). Golden Visa (5/10-year, no sponsor needed): investors with AED 2M+ property / AED 500k+ business stake, specialists (scientists, doctors, engineers earning AED 30k+/month), executives at top firms, exceptional talents, students with top university grades. Green Visa (5-year freelancer or skilled professional self-sponsored, no employer needed) — university degree + AED 15k+/month income. No personal income tax. Healthcare via employer-provided insurance (mandatory). UAE generally has no path to traditional naturalisation; long-stay status renews via underlying visa.`,
  "AE:study": `UAE: Student visa sponsored by the UAE university — most international degree-seekers at American University of Sharjah, NYU Abu Dhabi, Heriot-Watt Dubai, Mohammed Bin Rashid University. Tuition USD 15,000-50,000/year. Cost of living USD 1,000-2,500/month depending on emirate. Limited part-time work rights; private-sector work permits exist for selected programmes. Post-study: convert to Employment Visa or Golden Visa for top graduates. STEM-degree top graduates from UAE-recognised universities qualify for Golden Visa directly. Many international students transition to long-term residence via employment in Dubai's financial / tech / hospitality sectors.`,
  "AE:family": `UAE family sponsorship: residence-permit holders earning AED 4,000+/month (or AED 3,000+ with accommodation) can sponsor spouse + unmarried children under 18 (girls) / under 18 working in UAE (boys) / unmarried daughters of any age. Spouse residence visa tied to sponsor's employment. Same-sex marriage NOT recognised. Children require attested birth certificates + marriage certificate. Domestic helper / nanny sponsorship requires separate income threshold + Tadbeer service contract. Family routes through Golden Visa pass to spouse + children automatically. Divorce can cancel spouse residence visa.`,

  // ════════════════════════════════════════════════════════════════
  // MEXICO
  // ════════════════════════════════════════════════════════════════
  "MX:tourism": `Mexico: ~70 nationalities visa-free for up to 180 days under the FMM (Forma Migratoria Múltiple). Includes US, UK, Canada, EU, Japan, South Korea, Singapore, Israel, most of Latin America. Visa-required nationals (most of Africa, South Asia, parts of Middle East) apply for B1/B2-equivalent visa at Mexican consulate. Permanent residents of US / Canada / Schengen / UK / Japan can enter visa-free regardless of nationality. INM officers retained discretion at airports — recent reports of shorter stays granted than the 180-day max. FMM is also issued at land borders. Beach destinations are heavily monitored.`,
  "MX:work": `Mexico work routes: Temporary Resident Visa with permission to work (Visa de Residente Temporal con permiso para trabajar) — employer-sponsored or independent profession. Standard issue 1 year, renewable up to 4 years; convertible to Permanent Resident after 4 years. Permanent Resident Visa direct entry for: economic solvency (income ~USD 3,000+/month for 6 months or savings ~USD 50k+ — minimums vary by consulate), retirees, family routes, points-based for skilled workers. NAFTA / USMCA professionals (TN equivalent) for US / Canadian nationals in specific occupations. Mexican citizenship after 5 years of permanent residence (2 for Latin American / Iberian / spouses of Mexicans). Healthcare via IMSS once enrolled.`,
  "MX:study": `Mexico student visa for stays over 180 days: Temporary Resident — Student. Apply at Mexican consulate with acceptance letter from a SEP-recognised institution, financial proof. Tuition: UNAM, ITESM (private), IPN, UDLAP — public university very low cost (~USD 1,000-3,000/year), private universities USD 6,000-25,000/year. CONACYT scholarships available for postgrads. Spanish-language instruction primarily; ITESM and select institutions offer English-taught Master's. Cost of living USD 500-1,200/month depending on city. 1-year + renewable. Limited work rights with student visa; conversion to Resident Temporal with work permission is common post-graduation.`,
  "MX:family": `Mexico family routes: Spouse / partner of Mexican citizen — direct Temporary Resident card application at Mexican consulate, 1-year initial then 4 more years before Permanent Resident eligibility (or accelerated 2 years for spouses). Family Reunification for Temporary / Permanent residents — spouse + minor children + economically dependent parents. Recognised since 2010 same-sex marriage; same-sex couples have full family-route eligibility. Mexican-born children of foreign parents are Mexican citizens automatically (jus soli — one of the most generous in the Americas). Path to naturalisation accelerated to 2 years from PR for spouses, parents of Mexican-born children.`,

  // ════════════════════════════════════════════════════════════════
  // BRAZIL
  // ════════════════════════════════════════════════════════════════
  "BR:tourism": `Brazil: ~90 nationalities visa-free for short stays. EU, UK, Japan, South Korea, Singapore, GCC, most of Latin America. From April 2025 Brazil reintroduced visa requirements for the US, Canada, Australia — eVisa via VFS Global, USD 80, 10-year multi-entry, 90-day stays. China granted reciprocal visa-free in 2024. CPLP nationals (Portuguese-speaking community) get streamlined entry. Mercosur passport holders move on national ID alone. Border officers strict about onward tickets at major airports — São Paulo Guarulhos in particular.`,
  "BR:work": `Brazil work routes: Brazilian work visa via VITEM V or VIPER (employer-sponsored). Government quotas; sponsor must demonstrate roles not available locally. Highly Skilled Foreign Professional visa for VITEM V (1-2 year renewable). MERCOSUR residence permit for Argentine / Uruguayan / Paraguayan / Chilean / Bolivian / Peruvian / Colombian / Ecuadorian nationals (one-shot 2-year + Permanent). Investor visa requires R$500k+ investment in productive activities. Digital nomad visa (VITEM XIV) launched 2022 — proven income USD 1,500/month + remote employer. Citizenship after 4 years (1 year for spouses, Portuguese speakers from CPLP countries, parents of Brazilian children). No dual-citizenship restrictions.`,
  "BR:study": `Brazil student visa VITEM IV for over 90 days: apply at Brazilian consulate with admission letter from a recognised institution (USP, UFRJ, UNICAMP, ITA top-ranked). Public university tuition free for international students at federal universities; private universities R$1,500-8,000/month. Portuguese-language requirement variable — many top Master's are Portuguese-taught. Cost of living R$1,500-3,500/month outside São Paulo / Rio. Part-time work rights limited. Post-study: convert to work / family-route visa. Many international students pursue research collaborations via CAPES / CNPq programmes.`,
  "BR:family": `Brazil family routes: Marriage / civil union to a Brazilian citizen → immediate residence card via consulate or in-country. Same-sex marriage fully recognised since 2013. MERCOSUR Family — non-Mercosur national spouses of Mercosur residents get streamlined permits. Children of Brazilian-born / Brazilian-naturalised parents get Brazilian citizenship at birth even if born abroad (jus sanguinis through parents). Naturalisation accelerated to 1 year for spouses, parents of Brazilian children, CPLP nationals. Brazilian Visa Reform from 2017 simplified family / work routes substantially. Healthcare via SUS (free at point of use for residents).`,

  // ════════════════════════════════════════════════════════════════
  // INDIA
  // ════════════════════════════════════════════════════════════════
  "IN:tourism": `India: e-Tourist Visa (eTV) widely available for ~165 nationalities including US, UK, EU, Canada, Australia, Japan, South Korea, Singapore, GCC, most of Latin America — applied online for INR 1,500-5,000 (depending on validity 30-day / 1-year / 5-year), processed in 72-96 hours, multi-entry. Visa-on-arrival (limited) for UAE / Japan / South Korea + selected others. Visa nationals (Pakistan, Iran, China, several African states) apply for embassy visa. PIO / OCI (Persons of Indian Origin / Overseas Citizen of India) cards for diaspora — quasi-permanent visa-free entry for life. Aadhaar number requested at many hotels.`,
  "IN:work": `India's Employment Visa (E-Visa subclass) for foreign nationals: requires India-registered employer sponsorship, minimum annual salary USD 25,000 (with limited exceptions for ethnic-cuisine chefs / language teachers). One year renewable up to 5 years total typically. Business Visa for advisory / commercial activities (no salary requirement). Internship Visa for graduates. Project Visa for fixed-term construction / engineering projects. PIO / OCI card holders bypass these — automatic right to work, live, study indefinitely with no separate visa. Permanent residence (Permanent Resident Status) introduced 2017 for high-skill / investor profiles but rarely awarded. Indian citizenship by naturalisation typically requires 12 years of residence + Indian-citizen spouse OR 11 years + qualifying connections.`,
  "IN:study": `India's Student Visa: requires admission letter from a UGC-recognised institution. IIT, IIM, IISc, BITS top-ranked. Tuition: public universities INR 50,000-200,000/year, private universities / IIM Master's INR 5-25 lakhs/year. Government of India scholarships (ICCR) available for nationals of partner countries — usually full tuition + monthly stipend. English-medium instruction at most top institutions. SAARC-region students get reduced tuition; many African / SE Asian / Middle Eastern students enrolled in medical / engineering / management programmes. Work permitted with separate authorisation. Post-study: convert to Employment Visa requires Indian-employer sponsorship.`,
  "IN:family": `India's Entry Visa (X-Visa) for spouses, children, parents of Indian citizens / OCI holders / employment-visa holders. Recognised spouse + minor unmarried children. Same-sex marriages are NOT legally recognised in India (Supreme Court ruled 2023 against legalisation, deferring to Parliament). Foreign spouses of Indian citizens become eligible for OCI card after 2 years of marriage — provides indefinite multi-entry, no separate work permit needed, near-permanent residence rights without renouncing original citizenship. Indian-citizen children of foreign-born parents typically retain foreign nationality. India does not permit dual citizenship; OCI is a workaround providing functional equivalence without political rights.`,

  // ════════════════════════════════════════════════════════════════
  // THAILAND
  // ════════════════════════════════════════════════════════════════
  "TH:tourism": `Thailand: visa-exempt entry for 60 days (extended from 30 in 2024) for ~90 nationalities — most of Europe, US, UK, Canada, Australia, NZ, Japan, South Korea, India (2024-25 extension), most of Latin America. Visa-on-arrival for ~20 more nationalities at THB 2,000 (15 days). Visa nationals apply for Tourist Visa at Thai consulate. 60-day visa-exempt stay can be extended once for 30 days at Immigration. Multi-entry tourist visa (METV) valid 6 months, multiple 60-day entries — popular with digital nomads. Overstaying triggers per-day fines + visible record + blacklist for 90+ day overstays.`,
  "TH:work": `Thailand work routes: Non-Imm B + Work Permit issued by Department of Employment (employer-sponsored, minimum salary thresholds by nationality — typically USD 1,500-2,500/month for Western nationals). Long-Term Resident Visa (LTR — 10-year renewable, 4 categories: Wealthy Global Citizens with $80k+ income, Wealthy Pensioners 50+, Work-from-Thailand Professionals with $40k+ working for non-Thai company, Highly-Skilled Professionals). Smart Visa for tech / startup founders / experts. Retirement Visa (Non-Imm O-A, 50+, THB 800k bank deposit or THB 65k monthly income). Destination Thailand Visa (2024) for remote workers — 5-year multi-entry. PR after 3 years on Non-Imm B with strict 100-per-nationality annual quota. Citizenship after PR + 5 years of strict residence.`,
  "TH:study": `Thailand student visa Non-Imm ED for over 90 days: requires admission to an MOE-recognised institution. Chulalongkorn, Mahidol, Thammasat, Kasetsart top-ranked. Tuition: public universities Bt 25,000-120,000/year for international students, private universities Bt 100,000-300,000/year. Tuition for international Master's in English Bt 200,000-500,000/year. Cost of living Bt 15,000-30,000/month. Thai-language requirement for Thai-taught programmes; English-taught Master's increasingly common at top institutions. 20 hours/week part-time work permitted with separate authorisation. Post-study: convert to Non-Imm B (work) typically requires Thai-employer sponsorship.`,
  "TH:family": `Thailand family routes: Non-Imm O for spouses, children, parents of Thai citizens / long-term residents — 1-year visa, renewable. Spouse visa requires marriage registered at Amphoe (district office). Same-sex marriage recognised since January 2025 (Thailand became the first SE Asian country to legalise full marriage equality) — same-sex couples now have full family-route eligibility. Permanent residence (Thai PR) via marriage to Thai citizen after 3 years of legal residence + THB 800k income demonstrated for 3 years. Naturalisation after 5 years of PR with Thai language requirement. Children born in Thailand to foreign parents do NOT receive automatic Thai citizenship (jus sanguinis only, with limited exceptions).`,

  // ════════════════════════════════════════════════════════════════
  // GREECE
  // ════════════════════════════════════════════════════════════════
  "GR:tourism": `Greece: Schengen 90/180 visa-free for ~60 nationalities (ETIAS from late 2026, EES biometric tracking from late 2025). Type C visa €90 for visa nationals via Greek consulate. Travel insurance €30k mandatory. Greek border control regularly checks proof of accommodation and onward ticket. Crete, Rhodes, Santorini, Mykonos peak-season arrivals face higher scrutiny on length-of-stay declarations. Public ferries between Greek islands have no internal immigration checks.`,
  "GR:work": `Greece's long-stay options: Golden Visa (€250k-€800k real-estate threshold depending on region — Attica, Thessaloniki and high-demand islands raised to €800k post-2024 reform; lower-tier regions remain at €250k-€400k), Digital Nomad Visa (~€3,500/month proven income from remote employer, 1-year initial, renewable, leads to PR after 5 years), Financially Independent Person visa (passive income ~€2,000/month), Investor visa (€400k+ in shares/bonds/funds). Standard sponsored work via Skilled Worker (employer-sponsored, points system). Greek descent (jure sanguinis) for descendants of Greek nationals — major route for Greek diaspora in US, AU, CA. Naturalisation after 7 years of legal residence (3 for spouses); B1 Greek language requirement.`,
  "GR:study": `Greece student visa for stays over 90 days. Public university tuition for international students €1,500-3,000/year (some programmes free for EU); private universities €4,000-12,000/year. Apply at the Greek consulate with admission letter, financial proof €600+/month, accommodation evidence. NKUA Athens, AUTH Thessaloniki, University of Crete top-ranked. English-taught Master's increasingly common (Athens Business School, Hellenic Mediterranean Univ). Greek language requirement at A2 for Greek-taught programmes. 20 hours/week work permitted with separate authorisation. Post-study: extendable residence permit to find work then convert to Skilled Worker / Digital Nomad route.`,
  "GR:family": `Greece family routes: Family Reunification (Οικογενειακή Επανένωση) for spouses + minor children of non-EU residents. Sponsor must have held residence permit 2+ years, suitable housing, income at €8,500/year + €15% per dependent. Spouse of Greek citizen: immediate family-route eligibility, naturalisation after 3 years of marriage + 3 years of legal residence (lowest in EU for spouses of citizens). Same-sex marriage recognised since February 2024 (Greece became the first majority-Orthodox state to legalise marriage equality). Children of Greek-citizen parent automatically Greek citizens regardless of birthplace. Greek descent claim (πολιτογράφηση ομογενών) for diaspora — descendants of Greek-born ancestors can claim citizenship.`,

  // ════════════════════════════════════════════════════════════════
  // TÜRKIYE
  // ════════════════════════════════════════════════════════════════
  "TR:tourism": `Türkiye: visa-exempt entry for ~80 nationalities including most of Europe (90 days), South Korea, Japan, Singapore, most of Latin America. Türkiye e-Visa system handles visa-required nationalities (US, UK 30-day, Canada, Australia, others) — typically issued within 24 hours via evisa.gov.tr, USD 50-100. Entry-stamp officers retain discretion at major airports (Istanbul Airport, Sabiha Gökçen). Multi-entry visa-free for many EU nationalities allows up to 90 days in any 180. Türkiye's "tourist visa" is genuinely just for tourism — no work, no business beyond meetings.`,
  "TR:work": `Türkiye's long-stay options: Touristic Residence Permit (1-year renewable, popular with digital nomads and retirees — proven income required), Work Permit (employer-sponsored via Ministry of Family, Labour and Social Services), Student Residence Permit (educational institution sponsorship), Real-Estate Residence Permit (USD 200k+ property purchase, raised from $75k in October 2023). Turkish Citizenship by Investment available with USD 400k+ property purchase (raised from $250k in June 2022) — single most popular CBI program globally. Standard naturalisation after 5 years of continuous legal residence with B1 Turkish + integration interview. Turkish-language requirement is the main filter for most pathways.`,
  "TR:study": `Türkiye student visa: residence permit for stays over 90 days. Public university tuition for international students USD 200-1,000/year — among the cheapest in Europe / Asia border region. Private universities USD 3,000-15,000/year. YÖS (Foreign Student Exam) or SAT/equivalent for undergraduate entry. Boğaziçi, Bilkent, METU, ITU top-ranked. Turkish language requirement TÖMER B1-C1 for Turkish-taught programmes; English-taught Master's increasingly common. Cost of living USD 400-800/month outside Istanbul, more in Istanbul/Bodrum. 24 hours/week part-time work permitted after first year. Post-study residence permit to find work then convert to Work Permit.`,
  "TR:family": `Türkiye family routes: Family Residence Permit (Aile İkamet İzni) for spouses + dependent children of Turkish citizens / residents. Spouse of Turkish citizen: immediate residence permit, naturalisation after 3 years of marriage + continuous residence. Same-sex marriage NOT recognised legally. Children of Turkish-citizen parent automatically Turkish citizens regardless of birthplace; one Turkish parent suffices. Turkish-by-descent (Türk Vatandaşlığı Kanunu) for diaspora — descendants of Turkish nationals can apply for citizenship. Healthcare via SGK (Social Security Institution) once enrolled; emergency care free at state hospitals regardless of status.`,

  // ════════════════════════════════════════════════════════════════
  // INDONESIA
  // ════════════════════════════════════════════════════════════════
  "ID:tourism": `Indonesia: Bali & Greater Indonesia visa-on-arrival (VOA, IDR 500k / ~USD 35) for ~75 nationalities — 30 days, extendable once for another 30 days at the local immigration office. ASEAN members get 30-day visa-free entry. Visa-required nationals apply for B211A visa (tourism/social visit). Onward ticket strictly checked at point of entry — Jakarta Soekarno-Hatta, Bali Denpasar, Surabaya, Yogyakarta. Common gotcha: stamp validity counts from arrival date, not stamp date; misreading the date by a day triggers IDR 1M/day overstay fines. Cannot work or seek employment on tourist visa.`,
  "ID:work": `Indonesia's long-stay catalogue reformed substantially since 2023: Second Home Visa (5-year renewable, USD 130k+ deposit in an Indonesian bank), Investor KITAS (1-2 year, investment-based residence), Working KITAS (employer-sponsored, foreign worker quota system via Manpower Ministry), Family KITAS (spouse of Indonesian, or dependent of foreign KITAS holder), Retirement Visa (55+, USD 18,000+/year proven income, must rent property worth IDR 30M+/month), Remote Worker Visa E33G (launched 2024, 1-year, USD 60k+ annual foreign-employer income required). KITAP (permanent stay) after 5 years on KITAS — converts to indefinite residence with annual reporting. Indonesian citizenship after 5+ years on KITAP, renunciation of foreign citizenship required (Indonesia does not generally permit dual citizenship for adults).`,
  "ID:study": `Indonesia student visa B211B for stays over 90 days. Public university tuition for international students IDR 5-30M/semester (~USD 300-2,000/year). Universitas Indonesia (UI), Institut Teknologi Bandung (ITB), Gadjah Mada (UGM) top-ranked. Bahasa Indonesia language requirement variable — most undergrad in Bahasa, increasingly English-taught Master's at top universities. Darmasiswa (Indonesian government scholarship) covers 1-year Indonesian language + culture study for nationals of partner countries. Cost of living USD 300-800/month depending on city. Limited part-time work rights. Post-study: convert to Work KITAS requires Indonesian-employer sponsorship.`,
  "ID:family": `Indonesia family routes: Family KITAS (1-2 year renewable) for spouses + dependent children of Indonesian citizens or foreign KITAS holders. Spouse of Indonesian citizen: dependent KITAS issued by local immigration office; restrictions on owning property in own name (Indonesian property law restricts foreign ownership). Naturalisation after 5 years of marriage + continuous residence + Bahasa Indonesia + renunciation of foreign citizenship. Same-sex marriage NOT recognised. Children of mixed marriages get dual citizenship until age 18, then must choose one. Indonesia generally does not permit dual citizenship for adults.`,

  // ════════════════════════════════════════════════════════════════
  // SWITZERLAND
  // ════════════════════════════════════════════════════════════════
  "CH:tourism": `Switzerland is in Schengen but NOT in the EU. Visa-free 90/180 for ~60 nationalities (ETIAS from late 2026 since Switzerland is in the ETIAS coverage zone, EES biometric tracking from late 2025). Type C visa €90 for visa nationals via Swiss embassy or VFS. Travel insurance €30k mandatory. Swiss border control checks proof of accommodation, onward ticket, and sufficient funds (~CHF 100/day or proof of host's invitation). Schengen visa issued by another member state is valid for entry to Switzerland.`,
  "CH:work": `Switzerland's work permits operate under a uniquely federal-cantonal system. Two main permit types: L Permit (short-term, 1-year initial, extendable to 24 months total) and B Permit (residence, 1-year initial, renewable, leads to C Permit / settlement after 5-10 years). Federal annual quota (~8,500 L + 4,500 B) for third-country nationals; EU/EFTA nationals covered separately under AFMP. Employer-sponsored, cantonal labour-market priority test required, salary at regional prevailing wage. Mandatory Swiss-recognised health insurance from arrival. C Permit (permanent settlement) at 5 years for preferred-country nationals (US, Canada), 10 years for others, plus B1+ in canton's official language (German, French, Italian, or Romansh). Naturalisation after 10 years of qualifying residence.`,
  "CH:study": `Switzerland student visa for stays over 90 days. Public university tuition for international students CHF 1,000-2,000/semester at most cantons (Zurich, Geneva higher); ETH Zurich and EPFL CHF 760-1,300/semester despite world-class ranking. Apply at the Swiss consulate with admission letter, financial proof CHF 21,000+/year (cost of living), accommodation evidence. German / French / Italian language requirement variable by canton and programme; ETH/EPFL Master's increasingly English-taught. Cost of living among Europe's highest — CHF 1,500-2,500/month. 15 hours/week part-time work permitted after first 6 months. Post-study: 6-month job-search permit then switch to L/B Permit if hired.`,
  "CH:family": `Switzerland family routes: Family Reunification (Familiennachzug) for spouses + minor children of Swiss citizens / C Permit holders / B Permit holders. Sponsor must demonstrate suitable housing + income not on social welfare. Spouse of Swiss citizen: immediate B Permit, fast-track naturalisation (3 years of marriage + 5 of legal residence, vs 10 standard). Same-sex marriage fully recognised since July 2022. Children of Swiss-citizen parent automatically Swiss citizens regardless of birthplace. Switzerland generally permits dual citizenship (unlike historically restrictive German / Japanese / Indian policies). Naturalisation requires B1-B2 in canton language + integration interview + tax compliance for 10 years.`,
};

/** Lookup helper — undefined when no curated entry exists, so the page
 *  can fall back to the general destination intro. */
export function destinationPurposeIntro(iso2: string, purpose: Purpose): string | undefined {
  return DEST_PURPOSE_INTROS[`${iso2.toUpperCase()}:${purpose}` as DestPurposeKey];
}
