/**
 * Hand-curated long-form intros for the highest-traffic destination pages.
 *
 * Mirrors passportIntros.ts but flips perspective: who can enter this
 * country, on what terms, and what long-stay routes does it offer? These
 * intros ship as the SEO-critical unique content on each /destination/[iso]
 * page (200 destinations would otherwise read identically — Google
 * helpful-content penalty territory).
 *
 * Pattern per intro: ~80–140 words, factual, current as of 2026 (ETIAS,
 * EES, UK ETA, etc.), names specific programs and bilateral arrangements,
 * avoids any promise of outcome.
 *
 * For destinations without a curated entry, the page falls back to a
 * generated paragraph driven by live coverage data — see
 * destinationIntroGenerator.ts.
 */
export const DESTINATION_INTROS: Record<string, string> = {
  US: `The United States runs the Visa Waiver Program (ESTA) for ~40 nationalities including the UK, EU members, Japan, South Korea, Singapore, Australia, New Zealand, Israel, Chile, and Taiwan — 90 days, no work permitted. All other nationalities require a B-1/B-2 visitor visa with an in-person consular interview. The US presumes immigrant intent under Section 214(b); applicants must demonstrate strong home-country ties. Long-stay routes are dominated by employer-sponsored work (H-1B annual lottery, L-1 intracompany, O-1 extraordinary ability), study (F-1), family categories, and the diversity lottery. Treaty-investor routes (E-1, E-2) are open to nationals of treaty countries. Green Card-to-citizenship: typically 5 years on most categories.`,

  GB: `The United Kingdom requires the Electronic Travel Authorisation (ETA) for all visa-exempt nationalities from early 2025 — £10, 2-year validity, applied for online before travel. Visa-exempt visitors include EU, US, Canada, Australia, New Zealand, Japan, South Korea, Singapore, and GCC nationals; visa-required nationalities apply for a Standard Visitor visa with documentary evidence of purpose and home-country ties. Long-stay routes include the Skilled Worker visa (employer-sponsored, £38,700 baseline salary from April 2024), Student visa, Family visa (income thresholds rising), Innovator Founder, Global Talent, and the Graduate Route post-study work. Indefinite Leave to Remain after 5 years on most routes; British citizenship 12 months later.`,

  FR: `France welcomes EU/EEA citizens under freedom of movement and admits ~60 visa-exempt nationalities for 90-in-180-day Schengen short stays (US, UK, Canada, Japan, Australia, NZ, Israel, Singapore, South Korea, GCC nationals, most of Latin America). ETIAS authorisation required from late 2026. France runs distinct long-stay routes through the OFII system: the Talent Passport (skilled professionals, founders, researchers, artists), the long-stay VLS-TS (study, work, family), the Salarié Détaché intracompany route, and the long-stay Visitor visa (passive-income retirees, digital nomads). Carte de résident after 5 years; French citizenship 5 years (2 for spouses of citizens). Healthcare under Sécurité Sociale once registered.`,

  ES: `Spain admits Schengen visa-free nationalities for 90-in-180 days and processes long-stay D-class applications at consulates abroad. Headline long-stay routes: the Digital Nomad Visa (€2,762/mo income from foreign sources, 5-year track to PR), the Non-Lucrative Visa (passive-income retirees, ~€2,400/mo), the Highly Qualified Professional visa, the Entrepreneur visa, and the standard Work and Family routes. Bilateral agreements with Iberoamerican states (Argentina, Mexico, Chile, Colombia, Peru, etc.) shorten naturalisation to 2 years of legal residence. ETIAS required for visa-exempt nationals from late 2026; the EU Entry/Exit System (EES) records short-stay entries biometrically from late 2025. Public healthcare via SESPA once enrolled.`,

  IT: `Italy admits Schengen visa-exempt nationalities for 90-in-180 days; ETIAS authorisation arrives late 2026. Italy's long-stay catalogue includes the Lavoro Subordinato work visa (annual decreto-flussi quotas), the Lavoro Autonomo self-employed route, the Elective Residence visa (passive-income retirees, no work permitted), the Investor Visa Italy (€500k+ startup or €2M+ government bonds), the Digital Nomad visa (launched 2024), and Student visas. Italian descent (jure sanguinis) is among the most accessible routes globally — applicants with an Italian-born ancestor and unbroken citizenship line can claim citizenship by descent. EU long-term resident permit after 5 years; Italian citizenship after 10 years (4 for EU nationals, 3 for jure sanguinis spouses).`,

  JP: `Japan admits ~70 nationalities visa-free for 90 days (most of Europe, the US, UK, Canada, Australia, NZ, Singapore, Hong Kong, South Korea, Israel, most of Latin America). Working-holiday agreements with 30+ countries support 12-month work-and-travel for under-30s. Long-stay routes include the Highly Skilled Foreign Professional (HSP) points-based residence, the J-Skip and J-Find post-2023 reforms (graduates of top universities), the standard Engineer/Specialist visa, the Specified Skilled Worker visa (SSW) for blue-collar shortage occupations, Business Manager, and Student. PR after 10 years on most routes — 1–3 years for HSP points-system holders. Japan does not allow dual citizenship in most cases.`,

  TH: `Thailand grants visa-exempt entry for 60 days (extended from 30 in 2024) to ~90 nationalities including most of Europe, the UK, US, Canada, Australia, NZ, Japan, South Korea, and many Asian and Latin American states. Visa-on-arrival is available for an additional ~20 nationalities. Long-stay routes: the Long-Term Resident Visa (LTR — 10-year renewable for skilled professionals, retirees with US$80k+ income, wealthy investors), the Smart Visa, the Education visa, the Retirement visa (50+, financial requirements), and the Destination Thailand Visa for remote workers (launched 2024). PR after 3 years on Non-Imm B with strict annual quota of 100 per nationality.`,

  MX: `Mexico admits ~70 nationalities visa-free for stays up to 180 days under the Forma Migratoria Múltiple (FMM) — most of Europe, the US, Canada, Japan, South Korea, Singapore, Israel, and most of Latin America. All other nationalities apply for a Visitor visa at a Mexican consulate. Long-stay routes: Temporary Resident (1–4 years, requires income evidence ~US$3,000/mo or savings ~US$50k), Permanent Resident (higher financial thresholds or after 4 years on Temporary), Skilled Worker offers via employer sponsorship. Mexican citizenship after 5 years (2 for Latin American/Iberian nationals). USMCA business travel under T-classification. Healthcare via IMSS once enrolled.`,

  TR: `Türkiye admits ~80 nationalities visa-free or visa-on-arrival, including most of Europe (90 days), the US, UK (with e-Visa), Singapore, Japan, South Korea, and most of Latin America. The Turkish e-Visa system handles visa-required nationalities — typically issued within 24 hours. Long-stay routes: the Touristic Residence Permit (1-year renewable, common for digital nomads and retirees), the Work Permit (employer-sponsored), the Student Residence Permit, and the Real-Estate Residence Permit (US$200k+ property purchase from 2024). Turkish citizenship by investment available with US$400k+ property purchase. Standard naturalisation after 5 years of continuous legal residence.`,

  DE: `Germany admits EU/EEA nationals under freedom of movement and Schengen visa-exempt nationalities for 90-in-180 days (ETIAS from late 2026; EES biometrics from late 2025). Long-stay catalogue is among the most developed in Europe: the EU Blue Card (highly qualified workers, €43,800+ salary in 2024 for shortage occupations), the Skilled Workers Act 2.0 (Chancenkarte/Opportunity Card points-system from 2024 for skilled migrants), the Self-Employment visa, the Job Seeker visa, the Student visa, and Family Reunification. Niederlassungserlaubnis (settlement permit) after 5 years (33 months for Blue Card with B1 German). Citizenship reform from June 2024 reduced naturalisation to 5 years (3 with exceptional integration).`,

  GR: `Greece admits Schengen visa-exempt nationalities for 90-in-180 days; ETIAS from late 2026. Long-stay routes: the Golden Visa (€250k–€800k real-estate threshold depending on region, post-2024 reform), the Digital Nomad Visa (~€3,500/mo income, 1-year renewable), the Financially Independent Person visa (passive income), the Investor visa (€400k+ in shares/bonds), and standard Work, Study, and Family categories. Greek citizenship by descent (jure sanguinis) for descendants of Greek nationals. Naturalisation after 7 years of legal residence (3 years for spouses). EU long-term resident permit after 5 years. The 2025 EES rollout records every Schengen entry biometrically.`,

  AU: `Australia admits ~40 nationalities visa-free via the eVisitor (subclass 651, EU/EEA/UK) and ETA (subclass 601, US, Canada, Japan, Korea, Singapore, Brunei, Hong Kong, Malaysia, Taiwan) — both online, free or low fee, multiple-entry, 12-month validity. All other nationalities apply for a Visitor visa (subclass 600). Working-holiday agreements with 30+ countries (subclass 417 for Commonwealth + EU, subclass 462 for Work and Holiday). Long-stay routes: Skilled Independent (189), Skilled Nominated (190), Regional (491), Employer-Sponsored (482, 186), Global Talent (858), Investor (188), Student (500), Partner (820/801). Citizenship after 4 years residence including 12 months on PR.`,

  PT: `Portugal admits Schengen visa-exempt nationalities for 90-in-180 days; ETIAS from late 2026. Long-stay routes are popular with international relocators: D7 (passive income, ~€820/mo plus 30% per dependent), D8 (digital nomads, ~€3,480/mo income), D2 (entrepreneurs and self-employed), D1 (skilled work), D3 (highly qualified), D4 (study), D5 (research). The Non-Habitual Resident (NHR) tax regime was phased out for new applicants in 2024 and replaced by the more limited IFICI regime. Portuguese citizenship after 5 years of legal residence — among the fastest in Europe. Citizenship for descendants of Sephardic Jews ended 2024.`,

  CA: `Canada admits ~50 nationalities visa-free via the Electronic Travel Authorisation (eTA) — CA$7, 5-year validity, applied for online. US citizens are exempt from both visa and eTA. Working-holiday agreements (IEC) with 30+ countries for under-35s. Long-stay routes are dominated by Express Entry (Federal Skilled Worker, CEC, Federal Skilled Trades — points-based with Comprehensive Ranking System), the Provincial Nominee Programs (each province runs its own streams), the Atlantic Immigration Program, the Start-up Visa, the Self-Employed Persons program, the Caregiver streams, and Study Permits with post-graduation work permits. PR direct on Express Entry; citizenship after 3 years physical presence within a 5-year window.`,

  AE: `The UAE admits ~80 nationalities visa-free or visa-on-arrival including the US, UK, EU, Canada, Australia, Japan, South Korea, Singapore, China, and most GCC nationals (free movement). The standard tourist permit is 30–90 days. Long-stay routes: the Golden Visa (5/10-year renewable; investors, specialists, entrepreneurs, exceptional talents, retirees with property holdings), the Green Visa (5-year freelancer/skilled-employee), the Standard Employment Visa (sponsored by a UAE employer), the Family Visa, and Student permits. No personal income tax. The UAE has no path to traditional permanent residence or naturalisation in most cases — long-stay status depends on continuous renewal of the underlying visa.`,

  ID: `Indonesia admits ~75 nationalities to the Bali-and-Greater visa-on-arrival regime (US$35, 30 days, extendable once) and ~10 nationalities visa-free for 30 days (ASEAN members). Long-stay routes have been substantially reformed since 2023: the Second Home Visa (5-year renewable, requires US$130k+ deposit), the Investor KITAS (1–2 yr), the Working KITAS (employer-sponsored), the Family KITAS (married to Indonesian), the Retirement Visa (55+, financial requirements), the Remote Worker Visa "E33G" launched 2024 (1-year, foreign-employer income required). KITAP (permanent stay) after 5 years on KITAS — converts to indefinite residence with annual reporting.`,

  VN: `Vietnam admits ~25 nationalities visa-free including most EU members (45 days), the UK, France, Germany, Italy, Spain (45 days), Japan, South Korea, Russia (45 days), and ASEAN states (varies). All other nationalities use the Vietnam e-Visa (US$25, 90 days single/multiple-entry, online application). Long-stay routes: the Investment Visa (foreign-invested enterprise), the Temporary Resident Card (1–3 yr renewable, common for foreign professionals), the Work Permit (employer-sponsored), the Student visa, and the Spouse/Family visa. PR after 3 years on a Temporary Resident Card with strict eligibility criteria (specialist, scientist, or marriage to Vietnamese citizen).`,

  IN: `India admits Bhutan and Nepal nationals visa-free with biometric ID; all other nationalities require a visa. The e-Visa system handles ~170 nationalities (tourism, business, medical, conference) — typically issued within 72 hours. Long-stay routes: the Employment visa (skilled professionals with US$25k+ annual salary), the Business visa, the Student visa, the Research visa, the Project visa (specific infrastructure work), and the Entry (X) visa (people of Indian origin, spouses of Indian nationals). No formal path to permanent residence for foreign nationals; Persons of Indian Origin (PIO) and Overseas Citizen of India (OCI) cards available for diaspora — both provide long-stay rights but not citizenship.`,

  MA: `Morocco admits ~75 nationalities visa-free for 90 days including most of Europe, the US, UK, Canada, Japan, South Korea, Australia, NZ, and most of Latin America. All other nationalities apply for a visa at a Moroccan consulate. Long-stay routes use the Carte de séjour (residence card) issued by the General Directorate of National Security — categories include work (employer contract required and approved by ANAPEC), retirement (passive income evidence), student, family, and self-employed. Carte de résident (10-year renewable) after 4 years of regular legal residence. Morocco has bilateral agreements with France, Spain, Italy, Belgium, and the Netherlands that support skilled-migration pathways under EU frameworks.`,

  EG: `Egypt admits a small group of nationalities visa-free (Bahrain, Hong Kong residents, Kuwait, Lebanon, Oman, Saudi Arabia, UAE) and offers visa-on-arrival to ~40 nationalities including the US, UK, EU members, Canada, Australia, NZ, Japan, South Korea — US$25, 30 days. Egypt's e-Visa system covers the same group. Long-stay routes: the Work Permit (sponsored by an Egyptian employer, requires labour-market test), the Study visa, the Family visa, the Investor visa (under the Investment Law 72 of 2017), and the Retirement visa (financial-evidence required). PR (Permanent Residence) after 10 years of continuous lawful residence under Law 89 of 1960; investor route shorter.`,

  NL: `The Netherlands admits Schengen visa-exempt nationalities for 90-in-180 days (ETIAS from late 2026; EES from late 2025). Dutch long-stay routes are streamlined through the Highly Skilled Migrant scheme (salary threshold ~€5,331/mo for 30+, ~€3,909/mo under 30, recognised sponsor employer required), the EU Blue Card, the Orientation Year visa (post-study, 1-year job search), the Start-up Visa (1-year + transition to self-employed), the Self-Employed visa (points-based), and the Search Year for international students. Family Reunification under EU rules. Permanent residence after 5 years; Dutch citizenship 5 years (3 for spouses), generally renouncing original nationality.`,

  BE: `Belgium admits Schengen visa-exempt nationalities for 90-in-180 days (ETIAS from late 2026). Long-stay routes use the Combined Permit (single application covering both work and residence) for employer-sponsored work, the EU Blue Card (€60k+ salary), the Self-Employment visa, the Investor visa, and the Researcher visa. The Professional Card is required for self-employed non-EU nationals. Belgium's intra-EU mobility is supported by the freedom-of-movement framework for EU/EEA/Swiss nationals. F+ permit / EU long-term resident permit after 5 years of legal residence. Belgian citizenship after 5 years with integration evidence (or 10 years without).`,

  AT: `Austria admits Schengen visa-exempt nationalities for 90-in-180 days (ETIAS from late 2026). Long-stay routes use the Red-White-Red Card (points-based for skilled workers, very-highly-qualified workers, shortage-occupation specialists, university graduates), the EU Blue Card (€48,438+ salary in 2024), the Settlement Permit (researcher, artist, family), the Self-Employment / Special Cases category, the Student residence permit, and the Job Seeker visa for graduates. The Red-White-Red Card Plus is a more flexible follow-on permit after the initial RWR Card. Daueraufenthalt-EU (EU long-term resident) after 5 years; Austrian citizenship typically after 10 years (6 for exceptional integration), generally renouncing original nationality.`,

  CH: `Switzerland is not in the EU but participates in Schengen short-stay and EFTA — admits Schengen visa-exempt nationalities for 90-in-180 days. EU/EFTA nationals have free movement under bilateral agreements. Long-stay routes for non-EU/EFTA nationals are quota-restricted: Permit B (1-year renewable, employer-sponsored, requires labour-market test and specialist qualification), Permit L (short-term up to 12 months), Permit C (settlement permit after 10 years or 5 yrs for US/Canada/EU/EFTA), the Researcher and Self-Employed categories. Cantonal authorities run the day-to-day issuance with substantial regional variation. Swiss citizenship after 10 years (years 8–18 count double).`,

  IE: `Ireland is not in Schengen but maintains the Common Travel Area with the UK — Irish and British citizens move freely between each other's territories. Ireland admits ~110 nationalities visa-free for 90 days (US, UK, EU, Canada, Australia, NZ, Japan, South Korea, Singapore, GCC, most of Latin America). Long-stay routes: the Critical Skills Employment Permit (CSEP, salary ≥ €38k or ≥ €64k for non-shortage occupations), the General Employment Permit (GEP), the Stamp 0 (long-stay self-sufficient), the Student visa (Stamp 2), the Spouse of Irish National (Stamp 4), and the Investor / Entrepreneur programmes. Stamp 4 + Long-Term Residence after 5 years; Irish citizenship 5 years.`,

  SE: `Sweden admits Schengen visa-exempt nationalities for 90-in-180 days (ETIAS from late 2026). Swedish long-stay routes: the Work Permit (employer-sponsored, salary thresholds raised in November 2023 to SEK 27,360/mo, with further reform reducing low-wage routes), the EU Blue Card (SEK 67,000+/mo), the Self-Employment visa, the Researcher and Student permits, the Family Reunification permit. Swedish naturalisation after 5 years on PR (or 4 yrs for Nordic citizens; 3 for refugees, 2 for spouses). Permanent residence (PUT) requires continuous lawful stay plus self-sufficiency. The 2023–2024 immigration reforms have tightened low-skill work-permit eligibility.`,

  NO: `Norway is outside the EU but inside the EEA — EEA/EFTA nationals have free movement and direct access to the labour market. Norway is in Schengen, so Norway admits Schengen visa-exempt nationalities for 90-in-180 days. Long-stay routes for non-EEA nationals: the Skilled Worker permit (university or vocational qualification + concrete job offer at full Norwegian wages), the Self-Employment permit, the Researcher permit, the Au Pair permit, the Student permit, the Family Immigration permit, the Job Seeker visa for skilled workers (12 months). Permanent residence (PUT) after 3 years on most routes; Norwegian citizenship 7 years (some accelerated routes 3 yrs for Nordic citizens).`,

  DK: `Denmark admits Schengen visa-exempt nationalities for 90-in-180 days (ETIAS from late 2026); Danish opt-outs on EU asylum and home-affairs do not affect short-stay tourism. Long-stay routes use the Positive List (shortage-occupation fast-track), the Pay Limit Scheme (DKK 487,000+/yr in 2024 — fast-track), the EU Blue Card (DKK 530,000+/yr), the Start-up Denmark visa, the Researcher and Guest Researcher permits, the Establishment Card (for international graduates), and the Student permit. Permanent residence after 8 years (4 with Pay Limit + Danish + integration); Danish citizenship 9 years (typically), requires language and integration tests.`,

  FI: `Finland admits Schengen visa-exempt nationalities for 90-in-180 days (ETIAS from late 2026). The Nordic Passport Union allows Finnish residents from Denmark, Iceland, Norway and Sweden to move and work freely. Long-stay routes: the Skilled Worker residence permit (specialist + concrete job offer), the EU Blue Card (≥1.5× average wage threshold), the Self-Employment permit, the Researcher permit, the Job Seeker visa (3–12 months after a specialist qualification), the Student permit, and Family Reunification. Permanent residence (P) after 4 years of continuous legal residence on most A-permits; Finnish citizenship typically 5 years (some accelerated routes).`,

  CZ: `Czechia admits Schengen visa-exempt nationalities for 90-in-180 days (ETIAS from late 2026). Long-stay routes use the Employee Card (combined work and residence, employer-sponsored, central-register procedure), the Blue Card (EU-wide; CZK 91,225+/mo salary in 2024), the Intra-Company Transferee Card, the Long-Term Visa for Business (self-employed under a trade licence — živnostenský list), the Long-Term Visa for Study, and Family Reunification. The Czech-administered Project Programmes (Highly Qualified Employee, Key and Scientific Personnel) accelerate processing for specific roles. Permanent residence after 5 years; Czech citizenship after 5 years on PR (10 years total), generally renouncing original nationality.`,

  HU: `Hungary admits Schengen visa-exempt nationalities for 90-in-180 days (ETIAS from late 2026). Long-stay routes use the Single Permit (combined work + residence, employer-sponsored), the White Card (digital nomads with ≥ €3,000/mo income from outside Hungary), the Guest Worker permit (post-2023 reform — specific shortage occupations), the Highly Qualified Worker permit, the EU Blue Card, the Investor Residency programme (relaunched 2024, US$250k+ government-bond investment route), the Student residence permit, and Family Reunification. National Settlement Permit after 3 years (faster than EU's 5-year long-term resident standard); Hungarian citizenship typically 8 years (3 for spouses, simplified naturalisation for ethnic Hungarians).`,

  PL: `Poland admits Schengen visa-exempt nationalities for 90-in-180 days (ETIAS from late 2026). Long-stay routes are heavily used by Ukrainian and Belarusian nationals; broader categories include the Temporary Residence and Work Card (combined permit, employer-sponsored), the EU Blue Card, the Self-Employment route, the Polish Card (Karta Polaka) for ethnic Polish descendants — providing residency rights and a fast-track to citizenship, the Student visa, and Family Reunification. The Programme Poland.Business Harbour fast-tracks tech professionals from Belarus, Russia, Ukraine, Armenia, Georgia, and Moldova. Permanent residence after 5 years; Polish citizenship after 3 years on PR (5 years total).`,

  HR: `Croatia admits Schengen visa-exempt nationalities for 90-in-180 days — Croatia joined Schengen 2023-01-01 (ETIAS from late 2026; EES from late 2025). Long-stay routes use the Temporary Stay permit (work, study, family, scientific research, secondment), the Digital Nomad Residence Permit (1-year, non-renewable but re-applicable after 6 months out — no Croatian taxation on foreign income), the EU Blue Card, the Long-term residence for self-employed individuals, and Family Reunification. Permanent residence after 5 years of continuous legal residence; Croatian citizenship typically 8 years (5 for spouses of citizens, descent-based naturalisation for ethnic Croats).`,

  IS: `Iceland admits Schengen visa-exempt nationalities for 90-in-180 days (ETIAS from late 2026). The Nordic Passport Union grants Iceland-resident nationals of Denmark, Finland, Norway and Sweden free movement and labour-market access. Long-stay routes for non-EEA/EFTA nationals: the Specialist permit (university qualification + employer sponsorship + labour-market test), the Athlete permit, the Family permit, the Student permit, the Au Pair permit, and the Remote Work permit launched 2020 (1-year, ISK 1M+/mo income from outside Iceland). Permanent residence after 4 years of continuous legal residence; Icelandic citizenship typically 7 years (4 for Nordic citizens, 4 for spouses of Icelandic citizens).`,

  NZ: `New Zealand admits ~60 nationalities visa-free via the NZ Electronic Travel Authority (NZeTA) — NZ$23, 2-year validity (issued in minutes, mandatory before boarding). Australians have indefinite work and residence rights under the Trans-Tasman Travel Arrangement. Working-holiday agreements with ~45 countries for 18–30/35-year-olds. Long-stay routes: the Skilled Migrant Category (SMC) rebuilt under the 2024 reform with a 6-point system, the Accredited Employer Work Visa (AEWV — replaces the older Essential Skills route), the Active Investor Plus (NZ$5M / NZ$15M investor tracks), the Specific Purpose Work visa, the Student visa, and Partner-of-NZer routes. Resident Visa direct from SMC; NZ citizenship after 5 years of physical presence as a resident.`,

  SG: `Singapore admits ~160 nationalities visa-free for 30–90 days. Long-stay routes are merit-based and highly competitive: the Employment Pass (EP, monthly salary from S$5,600 in 2025 + COMPASS points framework), the S Pass (mid-skilled, salary ≥ S$3,150, employer quota-restricted), the Personalised Employment Pass (PEP — for high earners across employers), the Tech.Pass (founders, leaders, technical experts), the Overseas Networks & Expertise Pass (ONE Pass — S$30,000+/mo earners), the EntrePass (for founders backed by recognised VCs), the S-Visa Family Pass, and Student passes. Permanent Residence assessed under MOM/ICA — very selective; Singapore citizenship after 2 years on PR with strict assessment.`,

  KR: `South Korea admits ~110 nationalities to visa-free entry of 30–180 days; most require the K-ETA (Korea Electronic Travel Authorisation) before boarding — KRW 10,000, 3-year validity. Long-stay routes: the D-2 Student visa, the D-10 Job Seeker visa (post-graduation), the E-7 Specifically-Designated Activities visa (most common foreign-professional route, employer-sponsored), the F-2 Long-Term Residence (point-based, after time on E-class), the D-8 Investment visa, the F-5 Permanent Resident (typically after 5 years on F-2), the F-6 Marriage Migrant visa, and the new Workation visa for digital nomads (launched 2024). South Korean citizenship typically requires giving up other nationalities for non-dual cases.`,

  HK: `Hong Kong SAR admits ~170 nationalities visa-free for 7–180 days depending on nationality (US 90 days, UK 6 months, EU members 90 days, Canada/Australia/NZ/Japan 90 days). All visitors complete a Pre-Arrival Registration online. Long-stay routes: the General Employment Policy (GEP, requires confirmed job offer from a HK employer at prevailing salary), the Quality Migrant Admission Scheme (QMAS — points-based), the Top Talent Pass Scheme (TTPS launched 2022 for graduates of top global universities), the Admission Scheme for Mainland Talents and Professionals (ASMTP), and the Student Visa. Right of Abode (effectively HK citizenship) after 7 years of continuous ordinary residence.`,

  TW: `Taiwan admits ~70 nationalities visa-free for 14–90 days. Long-stay routes: the Employment Gold Card (4-in-1 work permit + residence + re-entry + ARC for top-tier foreign professionals across 11 designated fields — most popular post-2018 reform), the Resident Visa via specific employment (employer-sponsored at substantial salary), the Investment Resident Visa, the Student Visa, the Joining Family Resident Visa, and the Spouse-of-Taiwanese-Citizen Visa. APRC (Alien Permanent Resident Certificate) after 5 years of continuous residence on a valid resident permit; Taiwanese citizenship typically requires renunciation of the original nationality.`,

  MY: `Malaysia admits ~160 nationalities visa-free for 14–90 days. Long-stay routes: the Malaysia My Second Home (MM2H) programme — substantially reformed 2023 with higher financial thresholds across three tiers (Silver, Gold, Platinum), the Employment Pass (employer-sponsored across three categories by salary), the Premium Visa Programme (PVIP launched 2022 — MYR 200k+ fixed deposit, 20-year renewable), the Professional Visit Pass, the DE Rantau Nomad Pass (digital nomads, 1-year + 1 renewal), and the Student Pass. PR via MM2H or work track is theoretically possible but heavily restricted; Malaysian citizenship after 12 years residence with substantial discretion.`,

  PH: `The Philippines admits ~150 nationalities visa-free for 14–59 days (US 30, UK 30, EU 30, Japan 30, Canada 30, Australia 30, Singapore 30, Israel 59, ASEAN 30). Long-stay routes: the Special Resident Retiree's Visa (SRRV) — popular passive-income/retirement route with US$10k+ deposit for 35+, multiple tiers; the Special Investor's Resident Visa (SIRV — US$75k+ approved investment); the 9G Pre-Arranged Employment Visa (employer-sponsored work); the 9A Temporary Visitor Visa converted to long-stay; the Student Visa (9F). No traditional PR for non-Filipino nationals; SRRV grants indefinite renewable residence. Philippine citizenship requires renunciation of original nationality in most cases.`,

  BR: `Brazil admits Mercosur full members visa-free under residency agreements; ~95 other nationalities (EU, US since 2025, UK, Canada, Australia, NZ, Japan, South Korea, Singapore, Israel) for 90-in-180 days. All other nationalities apply for an e-Visa or consular visa. Long-stay routes: the VITEM I-XIV resident-visa categories covering scientific research, mission, work, study, retirement, family, investment, and humanitarian. The Digital Nomad VITEM XIV (launched 2022, US$1,500+/mo income or US$18k savings — 1-year renewable). Permanent residence (Permanência) after 4 years on temporary residence (1 yr for family of Brazilian citizens). Brazilian citizenship after 4 years on PR (1 yr for Portuguese, CPLP, Spanish-speaking Iberoamericans).`,

  AR: `Argentina admits Mercosur full members and associates under residency agreements; ~80 other nationalities (EU, US, UK, Canada, Australia, NZ, Japan, South Korea, Singapore, Israel) visa-free for 90 days. Long-stay routes: the Residencia Temporaria (work, student, family, religious, investor, pensionado — passive income), the Residencia Permanente (after 2 years on Temporaria, or directly for Mercosur nationals after 2 years residence), the Digital Nomad visa launched 2022 (180 days extendable). Argentina has one of the most accessible naturalisation regimes globally — Argentine citizenship after 2 years of continuous residence in most cases. Strong descent-based recognition for Italian, Spanish, German, and Eastern European heritage.`,

  CL: `Chile admits ~100 nationalities visa-free for 30–90 days (US, UK, EU, Canada, Australia, NZ, Japan, South Korea, Singapore, Israel, all of Latin America). Chile is the only South American Visa Waiver Program member for US-bound travel. Long-stay routes: the Temporary Residence Visa (Mercosur nationals direct; others via work contract, study, family), the Permanent Residence Permit (after 2 years on Temporary), the Subject-to-Contract work visa, the Professional/Technical visa, the Student visa, the Family visa. Permiso de Residencia Definitiva (PR) typically after 2 years; Chilean citizenship after 5 years of legal continuous residence.`,

  CR: `Costa Rica admits ~100 nationalities visa-free for 30–180 days (US 90, UK 90, EU 90, Canada 90, Australia 30, NZ 90, Japan 90, South Korea 90, Singapore 30). Long-stay routes: the Rentista visa (US$2,500+/mo passive income for 2 years), the Pensionado visa (US$1,000+/mo lifetime pension), the Inversionista visa (US$150k+ investment), the Worker visa (employer-sponsored), the Student visa, the Family visa. The Digital Nomad visa launched 2022 (US$3,000+/mo income, 1-year + 1-year extension). Permanent residence after 3 years on Temporary; Costa Rican citizenship typically after 7 years (5 for Spanish/Latin American/Iberoamerican citizens).`,

  PA: `Panama admits ~90 nationalities visa-free for 90 or 180 days (US, UK, EU, Canada, Australia, NZ, Japan, South Korea, Singapore, Israel, most of Latin America). Long-stay routes are among the most accessible globally: the Friendly Nations Visa (52 designated nationalities — 2-year provisional then PR, requires job, business, or property purchase), the Pensionado visa (US$1,000+/mo pension), the Reforestation Investor visa, the Self-Economic Solvency visa (US$300k+ investment or deposit), the Qualified Investor visa (US$300k+ in real estate/securities), the Italian Special Migration visa, and Work visas. PR direct on several categories; Panamanian citizenship after 5 years of residence (3 for Spanish/Latin American/Iberoamerican citizens).`,

  ZA: `South Africa admits ~80 nationalities visa-free for 30–90 days (most of Europe, the US, Canada, Australia, NZ, Japan, South Korea, Singapore, most of South America). Long-stay routes: the Critical Skills Work Visa (employer-sponsored under a published critical-skills list — heavily reformed 2024), the General Work Visa (requires Department of Labour certification of no local candidate), the Intra-Company Transfer Work Visa, the Business Visa (R5M+ investment), the Retired Person's Visa, the Relative's Visa, and the Study Visa. Permanent Residence after 5 years on Critical Skills or Business; South African citizenship typically after 5 years on PR (1 yr for spouses of citizens).`,

  KE: `Kenya admits East African Community nationals visa-free with the EAC Tourist Visa (Kenya-Rwanda-Uganda combined). All other nationalities use the eTA system launched 2024 (US$32, processed in 3 working days, mandatory before boarding for all visitors). Long-stay routes: the Class D Work Permit (employer-sponsored, requires labour-market test and Critical Skills designation for fast-track), the Class G Investor Permit (US$100k+ business investment), the Class K Retiree/Self-Sufficient Permit (US$24k+/yr documented), the Class M Refugee/Spouse Permit, and the Student visa. Permanent Residence (Class K Residency) after 7 years on a Work Permit; Kenyan citizenship by naturalisation typically after 7 years residence.`,

  IL: `Israel admits ~100 nationalities visa-free for 90 days (most of Europe, the US, UK, Canada, Australia, NZ, Japan, South Korea, Singapore, most of Latin America). Long-stay routes have a unique heritage-based component: the Law of Return grants any Jewish person automatic right to Israeli citizenship (typically processed within months). Non-Jewish long-stay routes: the B/1 Work Visa (employer-sponsored), the A/2 Student Visa, the A/4 Visa for dependents, the B/2 Visitor Visa converted to long-stay, the Investor visa (limited categories), and the Spouse of Israeli Citizen route. PR (Permanent Residency, A/5) is rare for non-Jewish foreigners — typically after substantial continuous residence under another A-class status.`,

  SA: `Saudi Arabia admits ~60 nationalities to the e-Visa or visa-on-arrival regime introduced 2019 — most of Europe, the US, UK, Canada, Australia, NZ, Japan, South Korea, Singapore, Malaysia. SAR 535 + insurance, 90 days per visit, 1-year multiple-entry. Long-stay routes: the Premium Residency (Iqama Saudi flat fee SAR 800k for permanent or SAR 100k/yr renewable — launched 2019, no sponsor required), the Standard Work Visa (employer-sponsored under the kafala-reformed Labour Reform Initiative 2021), the Investor Visa, the Family Visa (dependents of Iqama holders), and the Study Visa. Saudi citizenship is rarely granted to non-Saudi nationals; Premium Residency is the closest equivalent.`,
};

export function destinationIntroFor(iso2: string): string | undefined {
  return DESTINATION_INTROS[iso2.toUpperCase()];
}
