/**
 * Per-(passport, destination) editorial framing paragraphs.
 *
 * These are the 80-100 word narrative blocks that sit at the top of
 * /[passport]/[destination] result pages. They contextualise the route
 * BEFORE the user dives into the structured visa cards — naming the
 * specific bilateral relationship (Common Travel Area, WHTI, Trans-
 * Tasman, ASEAN, Mercosur, etc.), the headline visa-free status, and
 * the typical long-stay routes that bring people from this passport
 * to this destination.
 *
 * This is the LAST mile of editorial — passport intros + destination
 * intros + per-purpose intros are general; this is "what's the story
 * of UK to Spain specifically?" Each pair has its own facts: bilateral
 * agreements, diaspora communities, professional pipelines, tax
 * treaties, common refusal patterns.
 *
 * Coverage target: top 40 highest-traffic pairs. Generator-fallback for
 * the long tail. Expand by appending.
 */

export type PairKey = `${string}:${string}`;

export const PAIR_INTROS: Partial<Record<PairKey, string>> = {
  // ════════════════════════════════════════════════════════════════
  // United Kingdom & Ireland axis
  // ════════════════════════════════════════════════════════════════

  "GB:US": `British citizens travel to the US under the Visa Waiver Program — apply for ESTA online (USD $21, valid 2 years, 90-day stays), no embassy interview required. For longer stays or work, the UK-US relationship runs through specific visa programmes: E-2 Treaty Investor (UK is a treaty country, $100k+ business investment), L-1 for intracompany transfers, the highly-competitive H-1B lottery, O-1 for extraordinary ability, and EB-5 ($800k+) for green-card-by-investment. The UK is one of the largest source countries for US student visas (F-1) and a major recipient of US-to-UK tech / finance / academic relocations under reciprocal programmes.`,

  "US:GB": `US citizens travel to the UK under the new Electronic Travel Authorisation (ETA, £16, valid 2 years for multiple 6-month stays) from 2025. For longer stays, the Skilled Worker visa requires employer sponsorship + £38,700 baseline salary (lower for shortage occupations). The US-UK Mobility Partnership simplifies professional secondments. Other routes: Global Talent (no sponsor required for endorsed academics, tech, arts), High Potential Individual (graduates of ~50 top US universities get 2-3 years of unsponsored work), Innovator Founder for startup founders. Tens of thousands of Americans live in the UK on these routes; London + Edinburgh + Manchester are the main destinations.`,

  "IN:US": `Indian nationals are the largest US visa applicant nationality. The standard pipeline: F-1 (study) → OPT (12 months unsponsored work, +24 months for STEM) → H-1B sponsorship lottery. H-1B has a 65,000 cap + 20,000 advanced-degree exemption, with India taking ~70% of selections. EB-2 / EB-3 green-card backlogs for Indian-born applicants currently exceed a decade due to per-country caps. L-1 intracompany transferees from Indian tech / finance multinationals (TCS, Infosys, Wipro, Deutsche Bank India) bypass the H-1B lottery. Indian tourists need a B-1/B-2 visa — Mumbai / Delhi consulate interview backlogs improved in 2024 but remain weeks.`,

  "IN:GB": `Indian nationals are the largest source of UK Skilled Worker visa applicants, particularly in healthcare (Health and Care Worker visa — discounted fee, reduced Immigration Health Surcharge, lower salary floor for the NHS), technology, and finance. Standard route: bachelor's degree + sponsored job offer (£38,700+ salary, £23,200 for shortage occupations) → Skilled Worker visa → ILR after 5 years → British citizenship after 12 months. UK Student visa applicants from India increased substantially post-2020 with the Graduate Route (2-3 years post-study unsponsored work). Tourist visa: Standard Visitor — Delhi / Mumbai / Chennai application centres; refusal rate has improved to ~13% historically.`,

  "IN:CA": `India is the largest source of new Canadian permanent residents (over 27% of total in 2024). Express Entry via the Federal Skilled Worker / Canadian Experience Class programmes — points-based, CRS scores for Indian applicants typically need to clear 470-500 for invitations. Provincial Nominee Programs (Ontario, BC, Saskatchewan especially) are heavily used by Indian applicants. Study Permits from India spiked but tightened in 2024 with the Provincial Attestation Letter (PAL) requirement and CA$20,635 GIC threshold. Post-Graduation Work Permit + Canadian Experience Class is the dominant student-to-PR path. Canadian-Indian diaspora ~1.8 million.`,

  "IN:AU": `Indian nationals are the largest source country for Australian Subclass 482 (Temporary Skill Shortage) visas and Subclass 500 (Student) applications. Standard work pipeline: bachelor's + sponsored offer + occupation on Skilled Occupation List + meeting TSMIT (AU$73,150 from July 2024) → 482 → Employer Nomination Scheme (subclass 186) → PR. Skilled Independent (189) and Skilled Nominated (190) routes are heavily competed for by Indian applicants in tech / engineering / accounting. Bilateral mobility under the Australia-India Migration and Mobility Partnership Arrangement (MMPA, 2023) includes the MATES programme — early-career Indian graduates of recognised universities get a fast 2-year mobility pathway.`,

  "CN:US": `Chinese nationals require a B-1/B-2 visitor visa for tourism — applied at the US consulate in Beijing / Shanghai / Guangzhou / Shenyang / Chengdu / Wuhan. F-1 student visas to the US have declined post-2018 trade-tensions and the Presidential Proclamation 10043 restricting STEM students from China's "MCF-linked" universities. H-1B sponsorship is common but EB-2/EB-3 backlogs for China-born applicants run several years. EB-5 ($800k+) is heavily used by Chinese investors. Long-stay reversed flow: US citizens to China require a Chinese L visa (no visa-free for US passport, unlike the recent expansion for EU). Hong Kong + Macau have separate visa regimes.`,

  "CN:GB": `Chinese nationals need a Standard Visitor visa for UK tourism — Beijing / Shanghai / Guangzhou / Chongqing visa centres. Refusal rate higher than for visa-exempt nationalities (~12% historically). UK Student visa applications from China remain the second-largest source nationality after India. Skilled Worker route via Chinese-owned UK businesses (HNA, Geely, Tencent UK) or international firms. Investor Tier 1 visa was closed in 2022, leaving Global Talent + Innovator Founder + Skilled Worker as the main long-stay routes. UK-China Mobility Partnership not formalised; routes remain employer-sponsored and points-based. BNO (British National Overseas) holders from Hong Kong have separate, very generous settlement route.`,

  "NG:US": `Nigerian nationals require a B-1/B-2 visa for the US — applied at the Lagos consulate or Abuja embassy. Refusal rates for B-1/B-2 from Nigeria are among the highest globally (40-60% historically) — applicants must demonstrate exceptionally strong home-country ties. Diversity Visa lottery (DV-2025) Nigeria typically caps Nigerian winners at ~50,000 per year due to high participation. F-1 student visas to the US are heavily applied for; many Nigerian students transition via OPT and H-1B (where sponsorship can be found). EB-2 / EB-3 employment-based green-card routes are accessible to Nigerian applicants without the multi-decade backlog India / China face.`,

  "NG:GB": `Nigerian nationals are heavily represented in the UK Skilled Worker pipeline (healthcare via the Health and Care Worker visa, NHS / care-home sponsorship is dominant) and in Student visa applications. Standard tourist route requires a Standard Visitor visa at the Lagos / Abuja visa application centre — refusal rates historically 30-40%, requires substantial documentation of intent to return. UK Ancestry visa available to Nigerians of UK-born grandparent descent (Commonwealth route). The 2024 Skilled Worker reforms — particularly the dependents ban for care workers — affected Nigerian healthcare recruitment substantially.`,

  // ════════════════════════════════════════════════════════════════
  // Anglosphere mobility (AU / NZ / CA / UK / US axis)
  // ════════════════════════════════════════════════════════════════

  "AU:GB": `Australian citizens travel to the UK under the new Electronic Travel Authorisation (ETA, £16, valid 2 years for multiple 6-month stays). For longer stays, Australians have multiple bilateral routes: Youth Mobility Scheme (Tier 5 — under-35s, 3 years, no sponsor needed), UK Ancestry visa (5 years on a sponsor-free work-permitting visa for Commonwealth citizens with a UK-born grandparent — extraordinarily popular with Australian-born descendants of British emigrants), High Potential Individual (graduates of ~50 top universities), Global Talent for endorsed sectors. Skilled Worker requires employer sponsorship + £38,700+ salary. Substantial Australian diaspora in London.`,

  "AU:US": `Australians travel to the US under the Visa Waiver Program (ESTA, USD$21, valid 2 years, 90-day stays). The unique Australian E-3 visa — 10,500 per year, requires bachelor's + speciality occupation + US employer sponsorship — is functionally an Australia-only fast-track H-1B equivalent with no lottery and faster processing. Spouses get full work rights. L-1 intracompany transferees common via Australian multinationals (BHP, CBA, Macquarie, Atlassian). EB-1A / EB-1B for extraordinary ability / outstanding researchers are accessible — Australian academics often qualify. Sydney + Melbourne consulates process the visa interviews.`,

  "AU:NZ": `Australians and New Zealanders move freely between the two countries under the Trans-Tasman Travel Arrangement (1973). Australians entering NZ are automatically granted a Resident visa on arrival — full work, study, and access to NZ healthcare (subject to 2-year residency for public-funded healthcare). NZ Special Category Visa (SCV-444) similarly grants New Zealanders the right to live and work in Australia indefinitely. The arrangement does not include automatic citizenship — Australians naturalise in NZ after 5 years; NZ citizens of 4-year+ continuous Australian residence post-2017 became eligible for an Australian citizenship pathway under the 2023 reforms.`,

  "CA:US": `Canadians enter the US visa-free for tourism / business — neither ESTA nor visa required, just present a Canadian passport (land entry: WHTI-compliant document). I-94 stays for up to 6 months. For work, the USMCA TN visa (formerly NAFTA Professional) covers ~60 listed occupations — degree + job offer = approved at the border, renewable indefinitely, spouses get TD work-eligible. L-1 intracompany transfers, H-1B, E-1/E-2 also available. Canadian-born have no per-country green-card backlog. ~1 million Canadians live in the US; reverse flow ~1 million Americans live in Canada.`,

  "CA:GB": `Canadian citizens travel to the UK under the new Electronic Travel Authorisation (ETA, £16, 2-year multi-entry, 6-month stays). Long-stay routes via Skilled Worker (£38,700 salary threshold, employer sponsorship), High Potential Individual (graduates of ~50 top universities including U Toronto, McGill, UBC, Waterloo), Youth Mobility Scheme (under-35s, 3-year visa via the IEC quota), Global Talent for endorsed sectors. UK Ancestry visa for Canadian-born descendants of UK-born grandparents (Commonwealth route — 5 years work-permitting then ILR). UK-Canada Mobility Partnership simplifies professional secondments.`,

  "NZ:AU": `New Zealanders enter Australia under the Special Category Visa (SCV-444) granted automatically on arrival — unlimited work, study, residence, but historically with limited access to social security and a non-automatic pathway to citizenship. The 2023 Albanese-Hipkins reforms simplified the Citizenship Pathway: NZ citizens continuously resident in Australia for 4+ years post-2017 became eligible to apply directly for Australian citizenship without the intermediate PR step (subclass 189 / 190). Estimated 700k+ New Zealanders live in Australia under this arrangement. Working conditions and tax treatment now substantially harmonised. Healthcare: SCV holders get Medicare access.`,

  "NZ:GB": `New Zealanders travel to the UK under the Electronic Travel Authorisation (ETA, £16, valid 2 years for multiple 6-month stays). For long stays: Youth Mobility Scheme (Tier 5 — under-35s from NZ, 3-year visa, no sponsor required), UK Ancestry (5-year work-permitting for descendants of UK-born grandparents — heavily used by NZ-born Brits), High Potential Individual for graduates of top global universities (Auckland qualifies), Global Talent, Skilled Worker. NZ-UK Free Trade Agreement (in force 2023) deepened mobility for short-term business travel and select professional categories.`,

  // ════════════════════════════════════════════════════════════════
  // Schengen & EU internal — top intra-EU pairs
  // ════════════════════════════════════════════════════════════════

  "DE:US": `Germans travel to the US under the Visa Waiver Program (ESTA, USD$21, 90-day stays). Long-stay routes typically via E-2 Treaty Investor (Germany is a treaty country, $100k+ business investment — popular with German Mittelstand expansion), L-1 intracompany transferees (Daimler, BMW, BASF, SAP), H-1B, O-1 for academics / scientists, EB-2 / EB-3 employment-based green cards. German-American Chamber of Commerce supports many bilateral programmes. ~50,000 German citizens live in the US.`,

  "DE:GB": `German citizens travel to the UK under the new ETA (£16, valid 2 years for 6-month stays). For long stays, Germans lost EU free movement post-Brexit and now need a Skilled Worker visa (employer sponsorship + £38,700+ salary), Global Talent, or other points-based route. EU Settlement Scheme remains open via "reasonable grounds" late applications for pre-2021 UK residents. UK-Germany science cooperation supports Horizon Europe partnerships. Substantial German-British professional community in London + Cambridge + Oxford.`,

  "FR:GB": `French citizens travel to the UK under the new ETA (£16, valid 2 years for 6-month stays). Post-Brexit French migration to the UK requires a Skilled Worker visa or other long-stay route. The traditional French community in London + Kent + South East shrunk substantially post-2020 — many returned to France. Cross-Channel commerce continues via business travel under ETA. UK-France science partnerships under the post-Brexit Horizon Europe association. Eurostar passport-control reciprocity at St Pancras / Gare du Nord operates as before.`,

  "FR:US": `French nationals travel to the US under the Visa Waiver Program (ESTA, USD$21, 90-day stays). Long-stay routes via E-2 Treaty Investor (France is a treaty country), L-1 intracompany transferees (Sanofi, LVMH, BNP Paribas, AXA), H-1B for tech, O-1 for academics, EB-5 for investment-based green cards. France-US Friendship, Commerce, and Navigation Treaty supports the E-1 trader category as well. ~200,000 French citizens live in the US; New York, San Francisco, Miami concentrations.`,

  // ════════════════════════════════════════════════════════════════
  // Latin America → Iberia
  // ════════════════════════════════════════════════════════════════

  "BR:PT": `Brazilians benefit from the deepest bilateral mobility relationship in the Lusophone world. Schengen 90/180 visa-free entry, ETIAS from late 2026. For long stays: D7 (passive income, popular Brazilian retiree route), D8 (digital nomad), Authorisation of Residence for Investment (Golden Visa post-2023 reform — venture capital / arts donation / heritage), CPLP Mobility Agreement (2022) provides streamlined residence for Brazilians beyond standard D-class visas. Naturalisation as Portuguese citizen accelerated to 3 years (was 6) for Brazilians (under the CPLP framework). Substantial Brazilian community in Lisbon + Porto + Algarve, particularly post-2020 tech / freelancer relocations.`,

  "BR:ES": `Brazilians travel to Spain visa-free for short stays under Schengen (90/180), ETIAS from late 2026. Long-stay routes: Non-Lucrative Visa (passive income from foreign sources), Digital Nomad Visa (€2,762/month proven income, 2023 launch), Highly Qualified Worker (€40,000+ salary), Spanish Iberoamerican naturalisation framework — Brazilian citizens become eligible for Spanish citizenship after just 2 years of legal residence (the shortest accelerated path in Europe). Spanish-Portuguese bilateral arrangements simplify recognition of qualifications. Substantial Brazilian community in Madrid + Barcelona + Valencia.`,

  "BR:US": `Brazilians need a B-1/B-2 visitor visa for the US since the 2025 Brazil-US reciprocal visa reintroduction (Brazil had been on the visa-waiver list temporarily 2019-2024). Apply at São Paulo / Rio / Brasília / Recife consulates. Long-stay routes: E-2 Treaty Investor (Brazil is a treaty country), L-1 intracompany transferees (Itaú, Vale, Petrobras, Embraer), H-1B for tech, EB-5 for investment. Substantial Brazilian-American community in Florida + Massachusetts + New Jersey. Brazil-US bilateral relationship remains strong despite visa-waiver lapse.`,

  "MX:US": `Mexicans need a B-1/B-2 visa for US tourism — applied at the Ciudad Juárez / Tijuana / Guadalajara / Hermosillo / Monterrey / Nogales consulates. Border-crossing card (BCC) provides 30-day proximity-zone access (75 miles into US, 30-day stays) for frequent border travellers. USMCA TN visa for Mexican professionals in 60+ listed occupations (degree + job offer = same-day approval at border). H-1B + H-2A (agricultural) + H-2B (seasonal non-agricultural) heavily applied for by Mexicans. The Mexican diaspora in the US is the largest single national-origin community in any country globally (~37 million Mexican-Americans).`,

  // ════════════════════════════════════════════════════════════════
  // Asia → EU / Anglosphere
  // ════════════════════════════════════════════════════════════════

  "PH:US": `Filipinos require a B-1/B-2 visa for US tourism — applied at the Manila or Cebu embassy. Long-stay routes dominated by family reunification (Family Preference categories — IR for spouses of US citizens, F-2A for spouses of green-card holders, F-3 for married children of citizens — Philippines has substantial multi-year wait times due to per-country caps) and Employer-Sponsored work (especially healthcare — H-1B for registered nurses / professionals, EB-3 for skilled workers). Philippine-American community ~4.5 million.`,

  "PH:GB": `Filipino nationals need a Standard Visitor visa for UK tourism (refusal rates ~10-15% historically). UK Skilled Worker visa is heavily used by Filipinos — particularly in healthcare (Health and Care Worker visa for nurses, care workers), hospitality, and shipping (PH is among the world's largest sources of merchant marine officers). UK student visa applications from PH grew substantially post-2020. PH has no Commonwealth ancestry route to UK (was a US territory, not UK). UK-PH Skilled Migration agreement supports targeted recruitment.`,

  "JP:US": `Japanese nationals travel to the US under the Visa Waiver Program (ESTA, USD$21, 90-day stays). Long-stay routes via E-1/E-2 Treaty Trader / Investor (Japan is a treaty country, $100k+ — popular with Japanese SME expansion), L-1 intracompany transferees (Toyota, Sony, SoftBank, Mitsubishi), H-1B for tech, O-1 for arts / sports / academia. Japan-US Status of Forces Agreement covers US military personnel and dependents in Japan; Japanese-American community ~1.5 million. New York + Los Angeles + San Francisco hubs.`,

  "KR:US": `South Koreans travel to the US under the Visa Waiver Program (ESTA, USD$21, 90-day stays). For long stays: E-1/E-2 Treaty Trader/Investor (South Korea is a treaty country, $100k+ — common SME expansion route), L-1 intracompany transferees (Samsung, LG, Hyundai, SK Group), H-1B for tech, O-1 for arts (K-Pop crossover) / academics, EB-5 for investment. Korean-American community ~1.9 million. Bilateral mobility under the KORUS FTA supports specific professional categories. New York + Los Angeles + Chicago Korean concentrations.`,

  // ════════════════════════════════════════════════════════════════
  // Common Travel Area
  // ════════════════════════════════════════════════════════════════

  "GB:IE": `UK and Ireland operate the Common Travel Area (CTA), in primary legislation on both sides — British citizens have full unrestricted rights to enter, live, work, and access social security in Ireland (and vice versa) without any immigration formality, regardless of Brexit. No visa, no ETA, no work permit — just present a UK passport. Family routes, education, healthcare (with reciprocal arrangements), social welfare access. Children born to British / Irish parents in either jurisdiction generally acquire both citizenships.`,

  "IE:GB": `Irish citizens have full unrestricted rights to enter, live, work, and access social security in the UK under the Common Travel Area (CTA, in primary legislation on both sides). No visa, no ETA, no Settled Status registration required (Irish citizens were explicitly excluded from the EU Settlement Scheme post-Brexit because their rights are independent of EU law). Irish nationals in the UK benefit from voting rights in local + parliamentary elections, free secondary education, and full NHS access from day one. Substantial Irish-British community (~600k Irish-born in the UK).`,

  // ════════════════════════════════════════════════════════════════
  // Selected high-traffic family / heritage routes
  // ════════════════════════════════════════════════════════════════

  "IN:NP": `Indians and Nepalis move freely between the two countries under the 1950 Indo-Nepal Treaty of Peace and Friendship. No visa, no work permit, no formal immigration process for either nationality entering the other — just present national ID or passport. Indian nationals work and reside indefinitely in Nepal; Nepalis work and reside indefinitely in India (with the right to own property, run businesses, and access most social services on near-equal footing with citizens). The arrangement is the oldest and deepest bilateral mobility relationship in South Asia.`,

  "BD:GB": `Bangladeshi nationals need a Standard Visitor visa for UK tourism — Dhaka visa application centre, refusal rates 25-40% historically. UK Skilled Worker visa heavily applied for in healthcare / hospitality / IT. The British Bangladeshi community (~600k) is the third-largest South Asian community in the UK after Indians and Pakistanis. Family-reunification routes from Bangladesh to the UK have historically been among the largest immigration categories. Health and Care Worker visa for NHS recruitment remains an active route; the 2024 dependants-ban for care workers affected this materially.`,

  "PK:GB": `Pakistani nationals need a Standard Visitor visa for UK tourism — Islamabad / Karachi / Lahore visa application centres, refusal rates 25-40% historically. UK Skilled Worker visa heavily used in healthcare (Health and Care Worker programme for nurses, doctors, care workers), tech, and hospitality. The British Pakistani community (~1.6 million) is the second-largest South Asian community in the UK after Indians. Family-reunification routes (Partner / Spouse visa under Appendix FM) historically among the largest UK immigration categories.`,

  // ════════════════════════════════════════════════════════════════
  // Tax & residence havens
  // ════════════════════════════════════════════════════════════════

  "GB:PT": `British citizens travel visa-free to Portugal under Schengen 90/180 (ETIAS from late 2026). Long-stay routes among Europe's most accessible: D7 (passive income from UK pensions / dividends / rentals — popular UK-retiree route), D8 Digital Nomad Visa (€3,480+/month income from UK remote employer or self-employment), D2 Entrepreneur (UK-based business expansion), D3 Highly Qualified (£10,800+ annual contract salary). Substantial British community in the Algarve + Lisbon + Madeira. Naturalisation as Portuguese citizen after 5 years of legal residence — among Europe's fastest. Brexit-driven relocation accelerated post-2020.`,

  "GB:ES": `British citizens travel visa-free to Spain under Schengen 90/180 (ETIAS from late 2026, EES biometric tracking from late 2025). Long-stay routes: Non-Lucrative Visa (UK pensioner-favourite, €2,400+/month proven passive income, no work), Digital Nomad Visa (€2,762/month proven income from UK remote employer — 2023 launch), Highly Qualified Worker (€40,000+ salary). Spain's post-Brexit handling of British residents was generous — those resident on 31 December 2020 retained rights under the Withdrawal Agreement. ~300,000 British citizens live in Spain (Costa del Sol, Costa Blanca, Mallorca, Madrid).`,

  "GB:FR": `British citizens travel visa-free to France under Schengen 90/180 (ETIAS from late 2026). Post-Brexit long-stay requires a French national long-stay D-class visa: Long-Stay Visitor (no work, evidence of resources €1,500/month+ or savings equivalent — popular UK-retiree route), Talent Passport for skilled professionals / founders / artists, Long-Stay Salarié for sponsored employment. British residents resident on 31 December 2020 retained rights under the Withdrawal Agreement (TUE — titre de séjour spécifique). ~150,000 British citizens live in France (Dordogne, Brittany, Paris, Provence).`,

  "GB:IT": `British citizens travel visa-free to Italy under Schengen 90/180 (ETIAS from late 2026). Long-stay routes: Elective Residence (passive-income retirees, €31,000+/year proven income, no work permitted — popular UK retiree route), Lavoro Autonomo (self-employment / freelancers), Lavoro Subordinato (employer-sponsored, governed by annual decreto-flussi quotas), Investor Visa Italy (€500k+ startup / €2M+ bonds), Digital Nomad Visa (2024 launch, €28k+/year + remote employer). Substantial British community in Tuscany, Umbria, Le Marche. Italian descent (jure sanguinis) — UK applicants with Italian-born ancestors and unbroken citizenship line can claim Italian citizenship by descent (a major UK route to EU citizenship).`,

  // ════════════════════════════════════════════════════════════════
  // North America → top destinations
  // ════════════════════════════════════════════════════════════════
  "US:PT": `US citizens travel visa-free to Portugal under Schengen 90/180 (ETIAS from late 2026). Portugal has actively courted US tech, finance and remote-work expats since 2020 via the D8 Digital Nomad Visa (USD 3,800+/month proven income from US employer or self-employment) and the (now-restricted) Golden Visa. D7 popular with US retirees on USD 950+/month pensions. Portuguese citizenship after 5 years of legal residence — among Europe's fastest. The non-habitual resident (NHR) tax regime ended for new arrivals in 2024, replaced by the more limited IFICI regime — still appealing for high-earners but less so than the original NHR.`,
  "US:IT": `US citizens travel visa-free to Italy under Schengen 90/180 (ETIAS from late 2026). Long-stay routes: Elective Residence (passive-income, USD 33,000+/year — popular US-retiree route), Investor Visa Italy (US$540k+ startup / $2.2M+ government bonds), Digital Nomad Visa (2024 launch). Italian descent (jure sanguinis) is the single biggest pathway for US citizens — millions of Americans qualify through Italian-born ancestors with unbroken citizenship lines. Major route for US dual-citizenship-seekers (Italian passport offers full EU mobility). Consulate processing is slow (2-5 years); judicial proceedings to bypass comune backlogs are common.`,
  "US:ES": `US citizens travel visa-free to Spain under Schengen 90/180 (ETIAS from late 2026). Long-stay routes: Non-Lucrative Visa (passive income USD 2,650+/month — popular US-retiree route), Digital Nomad Visa (US$3,000+/month proven income, 2023 launch), Highly Qualified Worker (US$44k+ salary). Iberoamerican naturalisation framework does NOT apply to US citizens (US is not on the bilateral list — 10 years naturalisation required, vs 2 for Latin Americans). Substantial US community in Madrid + Barcelona + Valencia + Mallorca. Sephardic Jewish descent route closed for new applicants March 2024.`,
  "US:TH": `US citizens travel visa-free to Thailand for 60 days (extended from 30 in 2024). Long-stay routes: Long-Term Resident Visa (LTR — 10-year renewable; categories include Wealthy Global Citizens with USD 80k+ income, Wealthy Pensioners 50+ with USD 80k passive income, Work-from-Thailand Professionals at USD 40k+, Highly-Skilled Professionals). Smart Visa for tech / startup founders. Retirement Visa (Non-Imm O-A, 50+, USD 800k bank deposit OR USD 1,950/month income, mandatory Thai-recognised health insurance USD 100k/USD 3M). Destination Thailand Visa for remote workers launched 2024. Significant US community in Chiang Mai + Bangkok + Phuket — long-stayers cycle between LTR + tourist + STV permits.`,
  "US:JP": `US citizens travel visa-free to Japan for 90 days. Long-stay routes via Engineer/Specialist visa, Highly Skilled Professional points-based residence (70+ points = 5-year visa, 80+ = 1-year PR fast-track), Business Manager visa (¥5M+ capital, real office). Japan does NOT have an investor-citizenship route. Notable: J-Find and J-Skip post-2023 reforms favour graduates of top global universities (Harvard, Stanford, MIT all qualify). PR after 10 years on most routes — 1-3 years for HSP. Japan generally does not permit dual citizenship; many US citizens take HSP-1 or Spouse routes for residence rather than naturalisation.`,
  "US:KR": `US citizens travel visa-free to South Korea for 90 days. K-ETA temporarily waived for US passport holders through December 2025 — entry is fully visa-free without pre-authorisation during the waiver. Long-stay routes via E-7 specialty-occupation visa (employer-sponsored, requires bachelor's + relevant experience), D-8 corporate investor for entrepreneurs, F-6 marriage visa for spouses of Koreans. PR after 5 years on most working-visa routes. Korea does not generally permit dual citizenship for adult naturalisation.`,
  "US:SG": `US citizens travel visa-free to Singapore for 90 days. Long-stay routes via Employment Pass (USD 4,000+/month — sector minima for finance, COMPASS framework points), Personalised Employment Pass for high earners not tied to a sponsor, Tech.Pass for global tech talent (USD 240k+/year fixed salary OR product founder credentials), Overseas Networks and Expertise (ONE) Pass for USD 360k+/year earners. Singapore PR is discretionary — typically takes 2+ years of EP and "stable" employment. Strong US-SG bilateral mobility under the KORUS-equivalent US-Singapore FTA + Free Trade Professional categories.`,
  "US:CA": `US citizens enter Canada visa-free for tourism / business — no eTA, no visa. I-94 stays for up to 6 months on entry. Long-stay routes via USMCA TN visa (Canadian-employer sponsored work in 60+ listed professions), Skilled Worker via Express Entry (Canadian-Experience-Class points), Family Class sponsorship (spouses, common-law partners, conjugal partners), Provincial Nominee Programs (every province runs streams). Substantial US-to-Canada relocation in tech / finance / academia — Toronto + Vancouver + Montreal hubs. Canada permits dual citizenship; US-Canada dual nationals are common.`,
  "CA:AU": `Canadians travel to Australia under the ETA (subclass 601, multi-entry, 12-month validity, AU$20). Long-stay routes via Subclass 482 (Temporary Skill Shortage, employer-sponsored, TSMIT AU$73,150+ from July 2024), Subclass 189 / 190 (Skilled Independent / Skilled Nominated — points-based, no sponsor required for 189), Working Holiday Visa Subclass 417 for under-35 Canadians (12 months unsponsored work + travel, extendable to 36 months with regional work). Australia-Canada Mobility Arrangement supports professional secondments. Significant Canadian-Australian community in Sydney + Melbourne + Brisbane.`,

  // ════════════════════════════════════════════════════════════════
  // EU passports → top non-EU destinations
  // ════════════════════════════════════════════════════════════════
  "DE:AU": `Germans travel to Australia under the eVisitor (subclass 651) — free, multi-entry, 12-month validity, granted online in minutes. Long-stay routes via Working Holiday Visa Subclass 417 for under-35 Germans (12-36 months work + travel), Subclass 482 (employer-sponsored, TSMIT AU$73,150+), Subclass 189 / 190 (points-based skilled migration), Global Talent Subclass 858 for exceptional ability. German-Australian community concentrated in Melbourne + Sydney; German-language schools and Lufthansa direct routes support frequent travel both ways.`,
  "DE:CA": `Germans travel to Canada under the eTA (CA$7, applied online, 5-year multi-entry, 6-month stays). Long-stay routes via Express Entry (CRS-points for skilled migration), International Experience Canada (IEC) for under-35 Germans (Working Holiday up to 24 months, Young Professionals contract-based, International Co-op work-study). Substantial German community in Kitchener-Waterloo + Toronto + Vancouver. German engineering / automotive talent heavily recruited via PNPs in Ontario + BC.`,
  "DE:JP": `Germans travel to Japan visa-free for 90 days. Long-stay routes via Engineer/Specialist visa (employer-sponsored), Highly Skilled Professional points-based (70+ points = 5-year visa, 80+ = PR fast-track), Working Holiday for under-30 Germans (12 months). Substantial German-Japanese commercial relationship via Mitsubishi-Siemens, BMW, Bosch, Mercedes-Benz Tokyo R&D. German-language schools in Tokyo + Yokohama. Japan generally does not permit dual citizenship.`,
  "FR:CA": `French citizens travel to Canada under the eTA (CA$7, 6-month visa-free stays). Long-stay routes via Express Entry (French + English bilingual scores extra CRS points), Mobilité Francophone via the Canada-France Youth Mobility Arrangement (under-35 French nationals, up to 24 months). Substantial French-Canadian community in Quebec (where French nationals get streamlined provincial selection via CSQ — Quebec Selection Certificate). Montreal + Quebec City concentrations. Quebec runs separate immigration system from federal Canada.`,
  "FR:AU": `French citizens travel to Australia under the eVisitor (subclass 651) — free, multi-entry, 12-month validity. Long-stay routes via Working Holiday Visa Subclass 417 (under-35 French nationals, 12-36 months), Subclass 482 (sponsored work), Subclass 189 / 190 (points-based skilled migration). Australia-France Bilateral Working Holiday Arrangement (1991, expanded multiple times). Substantial French community in Sydney + Melbourne + Brisbane. New Caledonia (French territory in the Pacific) supports easier French-to-Australia commercial travel.`,

  // ════════════════════════════════════════════════════════════════
  // Asia → Asia
  // ════════════════════════════════════════════════════════════════
  "CN:JP": `Chinese nationals travel to Japan visa-free for 30 days following the Nov 2024 visa-free agreement extension. Long-stay routes via Engineer/Specialist visa, Highly Skilled Professional points-based residence, Business Manager visa. Japan-China bilateral mobility was historically constrained but expanded sharply 2024-25 with the visa-free reinstatement for Chinese passport holders. Chinese-Japanese community ~750k in Japan, concentrated in Tokyo / Yokohama / Osaka.`,
  "CN:KR": `Chinese nationals require a C-3 short-stay visa for tourism to South Korea — Korea has not extended visa-free to Chinese passport holders despite the 2024 K-ETA expansion (mainland Chinese passports remain visa-required). Long-stay routes via E-7 (specialty occupation), F-4 (overseas Korean / Korean ancestry — major route for ethnic Korean diaspora in China's northeast). Hong Kong + Taiwan passports get separate visa-free treatment. Substantial Chinese student population in South Korean universities (Seoul National, KAIST, POSTECH).`,
  "CN:SG": `Chinese nationals travel to Singapore visa-free for 30 days under the Feb 2024 China-Singapore reciprocal visa-free arrangement. Long-stay routes via Employment Pass (USD 5,000+/month under COMPASS framework), Tech.Pass for tech specialists, ONE Pass for USD 360k+/year earners. Singapore-China relationship benefits from cultural/linguistic ties (Mandarin is one of Singapore's official languages). Significant Chinese expat community in Singapore — Mandarin-speaking workforce in finance / tech.`,
  "JP:KR": `Japanese nationals travel to South Korea visa-free for 90 days. K-ETA temporarily waived for Japanese passport holders through December 2025 — visa-free without pre-authorisation during the waiver. Long-stay routes via E-7 specialty-occupation, D-8 corporate investor, F-6 marriage visa. Japan-Korea mobility historically constrained by political tensions but has thawed substantially since 2023. Substantial Japanese community in Seoul + Busan; reciprocal Korean community in Tokyo + Osaka.`,
  "KR:JP": `Koreans travel to Japan visa-free for 90 days. Long-stay routes via Engineer/Specialist visa, Highly Skilled Professional points-based, Working Holiday for under-30 Koreans (12 months). Korea-Japan mobility is dense — daily flights between Seoul + Tokyo / Osaka. Korean community in Japan ~430k (largest foreign nationality after Chinese). Many Korean-Japanese dual-heritage families navigate complex nationality status (Japan does not permit dual citizenship for adults).`,

  // ════════════════════════════════════════════════════════════════
  // Mercosur + Latin America internal
  // ════════════════════════════════════════════════════════════════
  "AR:BR": `Argentines travel to Brazil visa-free under the Mercosur framework — Argentine national ID alone sufficient at land borders, no passport required. Mercosur Residence Agreement (1991) grants 2-year residence permit on simple application, then permanent residence. Brazilian citizenship after 1 year of permanent residence + Portuguese language. Massive cross-border movement — Foz do Iguaçu, Uruguaiana, São Borja are major crossings. Substantial Argentine community in São Paulo + Rio + Florianópolis; reciprocal Brazilian community in Buenos Aires.`,
  "BR:AR": `Brazilians travel to Argentina visa-free under the Mercosur framework. Brazilian national ID alone sufficient at land borders. Mercosur Residence Agreement grants 2-year residence on application + permanent residence after. Argentine citizenship after 2 years of legal residence. Substantial Brazilian community in Buenos Aires (around Av Corrientes + Palermo); reciprocal flows for football transfers + financial services.`,
  "MX:CA": `Mexicans needed a TRV (visa) for Canada from 2024 — Canada reintroduced the visa requirement for Mexican passport holders in February 2024. Some eligible MX travellers can still use eTA if they have a 10-year US visa or have held a Canadian visa in the past 10 years. Long-stay routes via Express Entry (Spanish doesn't earn extra CRS points but immigration profile applies normally), Provincial Nominee Programs, Family Class sponsorship. The MX-CA mobility changes since 2024 affected the substantial Mexican community in Toronto + Vancouver + Montreal.`,

  // ════════════════════════════════════════════════════════════════
  // ASEAN internal
  // ════════════════════════════════════════════════════════════════
  "TH:MY": `Thais travel to Malaysia visa-free for 30 days under ASEAN free movement. National ID alone sufficient at the Sadao + Padang Besar land borders. Long-stay routes via Employment Pass (RM 3,000+/month, employer-sponsored). Major Thai community in Penang + Kuala Lumpur. Reciprocal flow: Malaysian passport holders enter Thailand visa-free for 30 days, 90 days for tourists at sea/air ports under the 2024 expansion.`,
  "ID:MY": `Indonesians travel to Malaysia visa-free for 30 days under ASEAN free movement. National ID + onward ticket sufficient. Bahasa Indonesia and Bahasa Melayu are mutually intelligible — substantial Indonesian workforce in Malaysian plantations, construction, domestic service. Long-stay routes via Employment Pass for skilled work or domestic-helper schemes. ~2.5 million Indonesian workers in Malaysia at any time (the largest foreign workforce). Reciprocal flows from Malaysian businesses into Jakarta + Surabaya.`,
  "VN:SG": `Vietnamese nationals travel to Singapore visa-free for 30 days under the 2024 ASEAN bilateral expansion. Long-stay routes via Employment Pass (SGD$5,000+/month, COMPASS framework), Tech.Pass for tech specialists, S Pass for mid-skilled (SGD$3,150+). Substantial Vietnamese community in Singapore — manufacturing, services, finance. Vietnam-Singapore Free Trade Agreement supports business travel.`,

  // ════════════════════════════════════════════════════════════════
  // US / GB outbound — round out top destinations
  // ════════════════════════════════════════════════════════════════
  "US:AU": `Americans travel to Australia under the ETA (subclass 601, AU$20, multi-entry, 12-month validity). Long-stay routes via Subclass E-3 — uniquely available to Australian-nationality applicants in the US, no direct US equivalent for Americans inbound — so US-to-AU work primarily runs via Subclass 482 (employer-sponsored, TSMIT AU$73,150+), Subclass 189/190 (points-based skilled migration), Working Holiday for under-31 Americans (12-36 months). Significant US community in Sydney + Melbourne, particularly in finance / tech / academia. Australia-US Mobility Arrangement supports professional secondments.`,

  "US:NZ": `Americans travel to New Zealand under the NZeTA (NZD$23, valid 2 years, multi-entry, 3-month stays). Long-stay routes via Working Holiday Visa for under-31 Americans (12 months unsponsored), Skilled Migrant Category (points-based, NZD$31.61+/hour median wage benchmark), Accredited Employer Work Visa for sponsored work, Active Investor Plus visa for NZ$5M+ investors. Substantial US-to-NZ relocation in remote-work tech + creative industries since 2020. Auckland + Wellington + Queenstown concentrations. Citizenship after 5 years of legal residence.`,

  "US:DE": `Americans travel visa-free to Germany under Schengen 90/180 (ETIAS from late 2026, EES biometric tracking from late 2025). Long-stay routes via Germany's reformed Skilled Immigration Act 2023: Skilled Worker visa, EU Blue Card (€45,300+ salary), Opportunity Card (Chancenkarte) — points-based job-seeker visa launched 2024, no offer required, 12 months in Germany to find work. Job Seeker visa (6-month unsponsored). Substantial American community in Berlin + Munich + Frankfurt + Hamburg. Germany's 2024 citizenship reform reduced naturalisation to 5 years (3 for "well-integrated") + permits dual citizenship — major shift attracting US-to-DE permanent moves.`,

  "GB:AU": `British citizens travel to Australia under the eVisitor (subclass 651) — free, multi-entry, 12-month validity, granted online in minutes. Long-stay routes via Subclass 482 (sponsored work), Subclass 189/190 (Skilled Independent / Skilled Nominated), UK-Australia FTA Innovation and Investment categories, Working Holiday Visa Subclass 417 for under-35 Brits (12-36 months with regional work extension). Substantial British community in Sydney + Melbourne + Brisbane + Perth (Brits are Australia's largest single foreign-born community at ~1.2M). UK-Australia Free Trade Agreement (in force 2023) deepened mobility for professionals + short-term business travel.`,

  "GB:CA": `British citizens travel to Canada under the eTA (CA$7, applied online, 5-year multi-entry, 6-month stays). Long-stay routes via Express Entry (Canadian-Experience Class + English-language points), International Experience Canada (IEC) for under-35 Brits (Working Holiday 24 months, Young Professionals contract-based), UK-Canada Free Trade Agreement Continuity Agreement (post-Brexit) supporting professional categories. Substantial British community in Toronto + Vancouver + Calgary. Citizenship after 3 of 5 years physical presence — accessible via Express Entry → PR → citizenship path.`,

  "GB:NZ": `British citizens travel to New Zealand under the NZeTA (NZD$23, valid 2 years, multi-entry, 6-month stays). Long-stay routes via Working Holiday Visa for under-31 Brits (12 months + 11-month extension if eligible), Skilled Migrant Category (points-based), Accredited Employer Work Visa, Active Investor Plus visa. UK-NZ Free Trade Agreement (in force 2023) deepened mobility. Substantial British community in Auckland + Wellington + Canterbury. Citizenship after 5 years of legal residence + character + English-language. UK-NZ historical migration links (substantial NZ population descended from British emigrants).`,

  "GB:DE": `British citizens travel visa-free to Germany under Schengen 90/180 (ETIAS from late 2026). Post-Brexit long-stay routes: Skilled Worker visa, EU Blue Card (€45,300+ salary), Opportunity Card (Chancenkarte job-seeker visa launched 2024), Job Seeker visa (6-month unsponsored). Substantial British community in Berlin + Munich + Frankfurt; many continued residence under EU Settlement-equivalent for pre-2021 residents. German 2024 citizenship reform allows dual citizenship — UK-Germany dual nationals can retain British citizenship on German naturalisation, a major shift since pre-2024 forced renunciation.`,

  "GB:JP": `British citizens travel visa-free to Japan for 90 days. Long-stay routes via Engineer/Specialist visa, Highly Skilled Professional points-based residence (70+ points = 5-year visa, 80+ = PR fast-track), Business Manager visa, Working Holiday Visa for under-30 Brits (12 months work + travel). Substantial British-Japanese commercial relationship via Mitsubishi-Rolls Royce, Hitachi-UK, GlaxoSmithKline-Japan. UK-Japan Comprehensive Economic Partnership Agreement supports business travel. Japan generally does not permit dual citizenship.`,

  "GB:TH": `British citizens travel to Thailand visa-exempt for 60 days (extended from 30 in 2024). Long-stay routes via Long-Term Resident (LTR — 10-year visa for Wealthy Global Citizens with $80k+ income, Wealthy Pensioners 50+, Work-from-Thailand Professionals at $40k+, Highly-Skilled Professionals), Smart Visa, Retirement Visa (Non-Imm O-A — 50+, THB 800k bank deposit OR THB 65k monthly income, mandatory Thai-recognised health insurance USD 100k coverage), Destination Thailand Visa for remote workers (2024 launch). Significant British community in Phuket + Chiang Mai + Bangkok — long-stayers cycle between LTR + retirement + tourist permits.`,

  "GB:CN": `British citizens travel to China visa-free for 30 days under the November 2024 China visa-exemption expansion (mutual UK-China 30-day visa-free arrangement). For longer stays, the standard L visa (Tourism) is required, applied at the Chinese consulate or via CVASC. Long-stay routes via Z visa (Work) — employer-sponsored, recognised degree + 2+ years' experience required. R visa for "high-end talent". Foreign Permanent Residence ("Chinese green card") is famously restrictive. Hong Kong + Macau operate separate immigration regimes — substantial British community in HK historically (BNO passport holders now have UK-side BNO settlement route).`,

  // ════════════════════════════════════════════════════════════════
  // India outbound — top routes
  // ════════════════════════════════════════════════════════════════
  "IN:AE": `Indians are the single largest foreign-national group in the UAE (~3.5M, around 35% of the UAE population). Tourism: Indians with US/UK/EU/Schengen/Canada residence permits get visa-on-arrival; ordinary Indian passport requires e-Visa pre-approval. Long-stay routes: standard Employment Visa (employer-sponsored 2-year residence), Golden Visa (5/10-year for investors AED 2M+ property, specialists earning AED 30k+/month, executives, exceptional talents), Green Visa (5-year freelancer / skilled professional, AED 15k+/month), Investor Visa. Indian dependents covered under sponsor's residence. No personal income tax. UAE-India Comprehensive Economic Partnership Agreement supports professional + business travel.`,

  "IN:SG": `Indians need an entry visa for Singapore — visa-required nationals process via local sponsor (Singapore-based authorised agent / hotel / employer). Long-stay routes via Employment Pass (SGD$5,000+/month, COMPASS framework), Tech.Pass for tech specialists, S Pass for mid-skilled (SGD$3,150+), Personalised Employment Pass for high earners. India-Singapore Comprehensive Economic Cooperation Agreement (CECA) supports professional intracompany transfers — major route for Indian IT professionals. Substantial Indian community in Singapore ~700k including 350k Indian-citizen professionals + Singaporean Indian community.`,

  "IN:JP": `Indians require a Temporary Visitor visa for Japan (tourism — ¥3,000) applied at the Japanese embassy in New Delhi / Mumbai / Chennai / Kolkata. Long-stay routes via Engineer/Specialist visa (employer-sponsored), Highly Skilled Professional points-based residence, Specified Skilled Worker (SSW) — blue-collar shortage occupations with Japanese-language test, Business Manager visa. Japan-India Comprehensive Economic Partnership Agreement (CEPA) supports professional mobility. Substantial Indian community in Tokyo + Yokohama (especially in IT — growing post-2020 as Japan tightens immigration for skilled workers).`,

  // ════════════════════════════════════════════════════════════════
  // China outbound
  // ════════════════════════════════════════════════════════════════
  "CN:CA": `Chinese nationals need a TRV (Temporary Resident Visa) for Canada — Beijing / Shanghai / Guangzhou / Chongqing visa centres. Refusal rates have been substantial but improved in 2024. Long-stay routes via Express Entry (CRS-points for skilled migration), Provincial Nominee Programs (Ontario OINP, BC PNP particularly active in Chinese applicants), Family Class sponsorship, Study Permit → PGWP → CEC PR path (heavily used by Chinese students). Substantial Chinese-Canadian community ~1.8M (Toronto + Vancouver + Montreal concentrations). Investor Class / Quebec Investor Programme historically attracted Chinese capital flows.`,

  "CN:AU": `Chinese nationals need an Australian Visitor visa (subclass 600) — applied online via VFS Global Beijing / Shanghai / Guangzhou. Long-stay routes via Subclass 482 (employer-sponsored), Subclass 189/190 (points-based skilled migration), Subclass 500 (Student — Australia is the second-largest study-abroad destination for Chinese students after the US), Significant Investor / Innovation visas (188/888). Substantial Chinese-Australian community ~1.4M (Sydney + Melbourne especially). Australia-China FTA supports business travel + professional categories.`,

  // ════════════════════════════════════════════════════════════════
  // Philippines outbound
  // ════════════════════════════════════════════════════════════════
  "PH:CA": `Filipinos need a TRV (Temporary Resident Visa) for Canada — Manila / Cebu visa centres. Long-stay routes via Caregiver Pathway (Canada's signature Filipino-migration pipeline — Home Child Care Provider + Home Support Worker Pilots leading to PR after 2 years), Express Entry (high CRS scores common for Filipino healthcare professionals + nurses), Provincial Nominee Programs (Manitoba, Saskatchewan particularly active), Family Class sponsorship. Substantial Filipino-Canadian community ~960k (Toronto + Vancouver + Calgary + Winnipeg).`,

  "PH:AU": `Filipinos need an Australian Visitor visa (subclass 600) — Manila visa centre via VFS Global. Long-stay routes via Subclass 482 (employer-sponsored, healthcare + hospitality + trades), Aged Care Industry Labour Agreement (specific stream for Filipino aged-care workers, expanded 2024), Subclass 189/190 (points-based), Working Holiday Subclass 462 for Filipinos with university degree + English. Substantial Filipino-Australian community ~410k. Australia-Philippines bilateral mobility supported by specific labour agreements.`,

  // ════════════════════════════════════════════════════════════════
  // Indonesia + Thailand outbound
  // ════════════════════════════════════════════════════════════════
  "ID:AU": `Indonesians need an Australian Visitor visa (subclass 600) — Jakarta visa centre via VFS Global. Long-stay routes via Subclass 482 (employer-sponsored, mining + hospitality dominant), Subclass 189/190 (points-based skilled migration), Subclass 500 (Student — Australia is among the top destinations for Indonesian students), Working Holiday Subclass 462 for university-educated under-30 Indonesians. Indonesia-Australia Comprehensive Economic Partnership Agreement supports business travel. Substantial Indonesian community in Perth + Darwin + Sydney + Melbourne; Australian-mining-engineer flow into Indonesia substantial reciprocally.`,

  "ID:SG": `Indonesians travel visa-free to Singapore for 30 days under the ASEAN framework. Long-stay routes via Employment Pass (SGD$5,000+/month, COMPASS framework), S Pass for mid-skilled, Domestic Helper scheme (substantial Indonesian workforce in Singapore households — ~150k domestic workers). Indonesia-Singapore Free Trade Agreement supports business travel. Geographic proximity + Bahasa Indonesia / Bahasa Melayu mutual intelligibility supports dense business + tourism flow. Substantial Indonesian community in Singapore — manufacturing, services, finance.`,

  "TH:US": `Thais need a B-1/B-2 visa for US tourism — applied at the Bangkok US embassy or Chiang Mai consulate. Long-stay routes via E-1/E-2 (Thailand is a treaty country — Treaty Trader / Treaty Investor categories), L-1 intracompany transferees, H-1B for tech (limited; not lottery-favoured for Thais), F-1 → OPT → H-1B for student-to-work transition. Thai-American community ~330k (Los Angeles + Bangkok International hub). US-Thailand Treaty of Amity (1966) is unique — supports E-1/E-2 visa categories with simplified business-establishment requirements for Thai nationals in the US.`,

  "TH:JP": `Thais travel visa-free to Japan for 15 days (limited compared to other ASEAN partners). Long-stay routes via Engineer/Specialist visa, Specified Skilled Worker SSW (substantial Thai workforce in Japanese agriculture + manufacturing — bilateral labour agreement), Business Manager visa, Working Holiday for under-30 Thais (12 months). Japan-Thailand Economic Partnership Agreement (JTEPA) supports investment + skilled mobility. Substantial Japanese expat community in Bangkok / Pattaya — reciprocal Thai-Japanese community in Tokyo + Osaka.`,

  // ════════════════════════════════════════════════════════════════
  // Japan + Korea + Singapore outbound (top mobility)
  // ════════════════════════════════════════════════════════════════
  "JP:AU": `Japanese travel to Australia under the ETA (subclass 601, AU$20, 12-month multi-entry). Long-stay routes via Subclass 482 (employer-sponsored), Subclass 189/190 (points-based), Working Holiday Visa for under-30 Japanese (12-36 months). Japan-Australia Economic Partnership Agreement (JAEPA, in force 2015) supports professional + investment mobility. Substantial Japanese expat community in Sydney + Melbourne — manufacturing, finance, education. Major Japanese student population at Australian universities.`,

  "JP:CA": `Japanese travel to Canada under the eTA (CA$7, applied online, 5-year multi-entry, 6-month stays). Long-stay routes via Express Entry, International Experience Canada (IEC) — Working Holiday for under-30 Japanese (12 months), Young Professionals contract-based, International Co-op work-study. Japan-Canada CETA-equivalent supports business mobility. Substantial Japanese expat community in Vancouver + Toronto + Calgary — finance, manufacturing, education.`,

  "KR:GB": `Koreans travel to the UK under the ETA (£16, valid 2 years for multiple 6-month stays). Long-stay routes via Skilled Worker visa (employer-sponsored, £38,700+), Global Talent (endorsed sectors — Korea has substantial K-pop / digital tech crossover), Youth Mobility Scheme (Korea-UK agreement supports under-35 Koreans up to 24 months), Health and Care Worker for nurses, High Potential Individual for graduates of ~50 top universities (Seoul National, KAIST qualify). UK-Korea Free Trade Agreement (in force 2023) supports business travel.`,

  "KR:AU": `Koreans travel to Australia under the ETA (subclass 601, AU$20, 12-month multi-entry). Long-stay routes via Subclass 482 (employer-sponsored), Subclass 189/190 (points-based), Working Holiday Subclass 417 for under-31 Koreans (12-36 months). Australia-Korea Free Trade Agreement (KAFTA, in force 2014) deepened mobility for professionals + business. Substantial Korean community in Sydney + Brisbane + Gold Coast — major student population at Australian universities.`,

  "SG:GB": `Singaporeans travel to the UK under the ETA (£16, valid 2 years for multiple 6-month stays). Long-stay routes via Skilled Worker visa, High Potential Individual for graduates of top Singapore universities (NUS, NTU qualify), Global Talent for endorsed sectors, Innovator Founder for startup founders. UK-Singapore Free Trade Agreement supports professional mobility. Substantial Singaporean community in London (finance + technology). Singapore is one of UK's deepest commercial bilateral relationships outside the EU.`,

  "SG:JP": `Singaporeans travel visa-free to Japan for 90 days. Long-stay routes via Engineer/Specialist visa, Highly Skilled Professional points-based residence (Singaporeans frequently qualify for HSP-1 fast-track 1-year PR path), Business Manager visa. Japan-Singapore Free Trade Agreement supports business + investment mobility. Substantial Singaporean expat community in Tokyo — finance, tech, multinational HQs.`,

  // ════════════════════════════════════════════════════════════════
  // UAE outbound (HNW Indians + GCC connectivity)
  // ════════════════════════════════════════════════════════════════
  "AE:IN": `UAE residence-permit holders (including expatriate Indians and others) get visa-on-arrival in India — 60-day stay. Emirati citizens (Emirati passport holders, distinct from foreign residents) similarly get visa-on-arrival in India. Long-stay routes via Employment Visa (E-class, employer sponsorship), Business Visa, Tourist Visa with multi-year validity for UAE residents. India-UAE Comprehensive Economic Partnership Agreement (in force 2022) supports investment + professional categories. Substantial Indian diaspora in UAE (~3.5M people) creates dense reciprocal commercial + remittance flows.`,

  // ════════════════════════════════════════════════════════════════
  // South Africa outbound
  // ════════════════════════════════════════════════════════════════
  "ZA:GB": `South Africans travel to the UK under the ETA (rollout to South Africa scheduled 2025 — until then Standard Visitor visa required). Long-stay routes via UK Ancestry visa (5-year work-permitting for descendants of UK-born grandparents — major South African route, given the substantial South African-British diaspora), Skilled Worker visa (employer-sponsored), Health and Care Worker visa (heavily used by South African nurses + medical professionals), High Potential Individual for graduates of UCT, Witwatersrand, Stellenbosch (qualifying universities). Substantial South African community in London + Surrey + Brighton.`,

  "ZA:US": `South Africans need a B-1/B-2 visa for the US — applied at the Johannesburg / Cape Town consulates. Long-stay routes via E-2 Treaty Investor (South Africa is a treaty country, $100k+ investment — popular SME-expansion route), L-1 intracompany transferees (Naspers/Tencent, SABMiller, Standard Bank), H-1B for tech, EB-1A/EB-1B for extraordinary ability / outstanding researchers. Significant South African-American community ~120k. Diversity Visa lottery has historically favoured South African applicants.`,

  // ════════════════════════════════════════════════════════════════
  // Brazil outbound (Mercosur + EU diaspora routes)
  // ════════════════════════════════════════════════════════════════
  "BR:CA": `Brazilians travel to Canada under the eTA (CA$7, applied online, 5-year multi-entry, 6-month stays — Brazil granted eTA in 2024). Long-stay routes via Express Entry (high CRS scores for Brazilian skilled-professionals + bilingual Portuguese/English), International Experience Canada (Working Holiday for under-35 Brazilians), Family Class sponsorship. Substantial Brazilian-Canadian community ~125k (Toronto, Vancouver, Montreal — especially in tech + finance services). Canada-Brazil bilateral mobility deepened post-2024 eTA introduction.`,

  // ════════════════════════════════════════════════════════════════
  // Round out top 20 origins → top 20 destinations
  // ════════════════════════════════════════════════════════════════

  // ─── JP outbound ───
  "JP:GB": `Japanese travel to the UK under the ETA (£16, valid 2 years for multiple 6-month stays). Long-stay routes via Skilled Worker visa (employer-sponsored, £38,700+), Global Talent for endorsed sectors, Youth Mobility Scheme (Japan-UK agreement supports under-35 Japanese up to 24 months), High Potential Individual for graduates of top Japanese universities (Tokyo, Kyoto, Osaka, Tohoku qualify). UK-Japan Comprehensive Economic Partnership Agreement supports professional mobility. Substantial Japanese community in London — finance, automotive, tech.`,
  "JP:SG": `Japanese travel visa-free to Singapore for 90 days. Long-stay routes via Employment Pass (SGD$5,000+/month, COMPASS framework), Tech.Pass for tech specialists, Personalised Employment Pass for high earners not tied to a sponsor. Japan-Singapore Free Trade Agreement supports business mobility. Substantial Japanese community in Singapore — manufacturing, finance, regional HQs. Japanese-medium schools support family relocation.`,
  "JP:DE": `Japanese travel visa-free to Germany under Schengen 90/180 (ETIAS from late 2026). Long-stay routes via Germany's reformed Skilled Immigration Act 2023: Skilled Worker visa, EU Blue Card (€45,300+ salary), Working Holiday for under-30 Japanese (12 months). Substantial Japanese-German commercial relationship via Mercedes-Toyota partnerships, Bosch Japan, BASF Japan. Düsseldorf hosts Europe's largest Japanese expat community (~7,000+) supported by Japanese supermarkets, schools, and cultural infrastructure.`,
  "JP:FR": `Japanese travel visa-free to France under Schengen 90/180 (ETIAS from late 2026). Long-stay routes via Talent Passport for skilled professionals / founders / researchers / artists, VLS-TS for sponsored employment, Working Holiday for under-30 Japanese (12 months). Substantial Japanese community in Paris (~30k+) supported by Lycée Français de Tokyo + reciprocal Lycée Seijo Gakuen. Japanese expats in fashion, luxury goods, automotive (Toyota / Nissan-Renault), gastronomy.`,

  // ─── KR outbound ───
  "KR:CA": `Koreans travel to Canada under the eTA (CA$7, applied online, 5-year multi-entry, 6-month stays). Long-stay routes via Express Entry, International Experience Canada — Working Holiday for under-30 Koreans (12-24 months), Young Professionals contract-based, International Co-op. Substantial Korean-Canadian community ~220k (Toronto, Vancouver — especially in tech + small business + restaurants). Korea-Canada FTA (in force 2015) supports business mobility.`,
  "KR:SG": `Koreans travel visa-free to Singapore for 90 days. Long-stay routes via Employment Pass (SGD$5,000+/month, COMPASS), Tech.Pass for tech specialists, S Pass for mid-skilled (SGD$3,150+). Korea-Singapore FTA supports investment + professional mobility. Substantial Korean expat community in Singapore — manufacturing, finance, K-pop / entertainment regional HQ functions.`,
  "KR:AE": `Koreans travel to the UAE under e-Visa pre-approval or via UAE-based hotel/company sponsorship — 30-90 day stays. Long-stay routes via Employment Visa (employer-sponsored 2-year residence), Golden Visa for investors / specialists, Green Visa for skilled freelancers. Korea-UAE Comprehensive Economic Partnership Agreement (in force 2024) supports professional + investment mobility — Korean construction firms (Samsung Engineering, Hyundai E&C) have substantial UAE workforces.`,

  // ─── SG outbound ───
  "SG:AU": `Singaporeans travel to Australia under the ETA (subclass 601, AU$20, 12-month multi-entry). Long-stay routes via Subclass 482 (employer-sponsored, TSMIT AU$73,150+), Subclass 189/190 (points-based skilled migration), Singapore-Australia FTA Professional categories. Substantial Singaporean community in Sydney + Melbourne + Perth. Singapore-Australia Comprehensive Strategic Partnership (2015) supports defence, tech, finance bilateral mobility.`,
  "SG:US": `Singaporeans travel to the US under the Visa Waiver Program (ESTA, USD$21, 90-day stays). Long-stay routes via H-1B1 (Singapore-only special category set aside under the US-Singapore FTA — 5,400 visas/year, separate from H-1B 65k lottery, no draw), E-1/E-2 Treaty Trader/Investor (Singapore is a treaty country), L-1 intracompany transfers (Singapore Airlines, DBS, Temasek-backed companies). H-1B1 is one of the most accessible US work visa categories globally for SG nationals — degree + job offer = approved.`,
  "SG:CA": `Singaporeans travel to Canada under the eTA (CA$7, multi-entry, 6-month stays). Long-stay routes via Express Entry, Provincial Nominee Programs, International Experience Canada (Working Holiday for under-35 Singaporeans). Substantial Singaporean expat community in Toronto + Vancouver. Singapore-Canada partnership supports professional + investment mobility — Singapore is one of Canada's largest single-source investment partners in ASEAN.`,

  // ─── AE outbound ───
  "AE:GB": `UAE citizens travel to the UK under the ETA (£16, valid 2 years for multiple 6-month stays — UAE was one of the early ETA rollout nationalities in Feb 2024). Long-stay routes via Skilled Worker visa, Global Talent, Investor visa (Tier 1 closed 2022; replaced with Innovator Founder), Health and Care Worker for medical professionals. Substantial Emirati student + investor presence in London. UAE-UK CSP (Comprehensive Strategic Partnership) supports investment + professional mobility.`,
  "AE:US": `UAE citizens need a B-1/B-2 visitor visa for the US (UAE not in VWP despite the strong bilateral relationship). Long-stay routes via E-2 Treaty Investor (UAE is a treaty country — popular SME-expansion route for Emirati family offices), L-1 intracompany transferees, H-1B, EB-5 for investment-based green cards. Substantial UAE-US student exchange via Sheikh Mohammed scholarships at MIT, Harvard, Stanford. Foreign-resident Indians + Brits in UAE often travel via 3rd country routes.`,

  // ─── IL outbound (top mobility passport) ───
  "IL:US": `Israelis travel to the US under the Visa Waiver Program (ESTA, USD$21, 90-day stays — Israel joined VWP in late 2023 after meeting the qualifying criteria, making it the latest VWP entrant). Long-stay routes via E-1/E-2 Treaty Trader/Investor (Israel is a treaty country, $100k+ — popular Israeli SME-expansion route), L-1 intracompany transferees (Check Point, Mobileye, Wix, Mellanox-Nvidia), O-1 for extraordinary ability, H-1B. Substantial Israeli-American community ~190k+ (New York, Los Angeles, Boston tech hubs).`,
  "IL:GB": `Israelis travel to the UK under the ETA (£16, valid 2 years for multiple 6-month stays). Long-stay routes via Skilled Worker visa, Global Talent for endorsed sectors (Israeli tech / cybersecurity / fintech profile-fit), Innovator Founder, High Potential Individual for graduates of top Israeli universities (Hebrew University, Tel Aviv University, Technion qualify). UK-Israel bilateral arrangements support business + academic mobility. Substantial Israeli community in London — finance, tech, diamond trade.`,
  "IL:DE": `Israelis travel visa-free to Germany under Schengen 90/180 (ETIAS from late 2026). Long-stay routes via Skilled Worker visa, EU Blue Card (€45,300+ salary), Opportunity Card (Chancenkarte job-seeker visa launched 2024). Substantial Israeli-German community in Berlin (~25k+) — many Israelis have claimed German citizenship under Article 116 Basic Law for descendants of those deprived of citizenship 1933-1945, providing direct EU passport access. Israeli tech firms heavily represented in Berlin's startup ecosystem.`,
  "IL:FR": `Israelis travel visa-free to France under Schengen 90/180 (ETIAS from late 2026). Long-stay routes via Talent Passport, VLS-TS for sponsored employment, Long-Stay Visitor for retirees / passive income. Substantial Israeli-French community in Paris + Nice — France hosts Europe's largest Jewish community (~440k+) with deep historical mobility. Israeli aliyah-from-France (French Jews moving to Israel) reciprocates the flow. French citizenship by descent / through marriage available to dual-heritage families.`,

  // ─── EU internal — Schengen reciprocal ───
  "DE:FR": `German citizens move freely to France under EU free movement and Schengen — no visa, no work permit, no formal residence registration for stays under 90 days. For long stays: register with the local préfecture for a carte de séjour (free, residence card based on EU citizen rights). Full access to French labour market, public healthcare via Carte Vitale, schools, social services. Substantial German community in Strasbourg + Paris + Lyon — frequent commercial + academic + cultural mobility under the Franco-German friendship treaty (Elysée Treaty 1963).`,
  "FR:DE": `French citizens move freely to Germany under EU free movement and Schengen. No visa, no work permit. For stays over 90 days, register with the local Bürgeramt and obtain Anmeldebescheinigung. Full access to German labour market, healthcare via gesetzliche Krankenversicherung, schools, social services. Substantial French community in Berlin + Munich + Frankfurt — frequent business mobility through the Franco-German Council of Ministers + bilateral parliamentary assemblies.`,
  "IT:DE": `Italian citizens move freely to Germany under EU free movement and Schengen. No visa, no work permit. Italian-German community in Stuttgart, Munich, Frankfurt, North Rhine-Westphalia ~610k (one of the largest EU-internal diasporas in Germany — partly heritage from 1960s-70s gastarbeiter recruitment). Full access to German labour market + healthcare + education. Bilateral arrangements support qualification recognition for Italian-trained doctors, engineers, lawyers.`,
  "ES:FR": `Spanish citizens move freely to France under EU free movement and Schengen. No visa, no work permit. Substantial Spanish community in Paris + Bordeaux + Toulouse + the French Basque country. Spain-France border-region commerce is dense — Basque cross-border workers, Pyrenees agricultural / tourism mobility. EU citizens get equivalent treatment in healthcare (CEAM card pre-residency, then Carte Vitale after).`,
  "NL:DE": `Dutch citizens move freely to Germany under EU free movement and Schengen. No visa, no work permit. NL-DE border-region commerce is dense (border crossings at Aachen, Venlo, Enschede). Substantial Dutch community in North Rhine-Westphalia + Lower Saxony. Many Dutch citizens work in Germany while living in the Netherlands (or vice versa), with bilateral arrangements covering tax + social security under the EU coordination regulation 883/2004.`,

  // ─── More IN outbound (huge migration source) ───
  "IN:DE": `Indians need a Schengen Type C visa for tourism + an Auswandert (residence) for long stays. Germany's reformed Skilled Immigration Act 2023 + Opportunity Card 2024 made German skilled-migration much more accessible: Skilled Worker visa for recognised qualifications + job offer, Opportunity Card (Chancenkarte) points-based job-seeker visa — 12 months in Germany to find work, EU Blue Card (€45,300+ salary). India-Germany bilateral mobility agreement supports skilled-worker recruitment. Substantial Indian-German community ~250k+ (Frankfurt + Hamburg + Berlin).`,
  "IN:FR": `Indians need a Schengen Type C visa for French tourism, applied at French consulate in Delhi / Mumbai / Bangalore / Chennai / Pondicherry (the latter being a historic French territory). Long-stay routes via Talent Passport (skilled professionals / founders / researchers), VLS-TS Salarié (sponsored employment), Long-Stay Student visa. Substantial Indian community in Paris + Pondicherry (Pondicherry French nationality available to descendants of pre-1962 residents — unique route). India-France bilateral skilled-migration partnership signed 2022.`,
  "IN:NL": `Indians need a Schengen Type C visa for Dutch tourism. Long-stay routes via Highly Skilled Migrant (Kennismigrant — €5,688+/month for ages 30+, €4,171+ for under-30, plus 30% Ruling tax benefit for new arrivals), EU Blue Card. Substantial Indian community in Amsterdam + Eindhoven + Den Haag + Rotterdam — strong presence at ASML, Philips, ING, Booking.com. India-Netherlands bilateral skilled-migration relationship has deepened substantially since 2018 under the Knowledge Partnership.`,

  // ─── CN outbound to more destinations ───
  "CN:DE": `Chinese nationals need a Schengen Type C visa for German tourism. Long-stay routes via Skilled Worker visa, EU Blue Card (€45,300+ salary), Opportunity Card (Chancenkarte 2024 launch). Substantial Chinese-German community ~150k+ (Frankfurt + Hamburg + Berlin) — strong tech / automotive / finance professional presence (BMW Beijing R&D, Siemens China, Daimler-BAIC). Germany-China bilateral education arrangements support Chinese students at TU9 universities.`,
  "CN:FR": `Chinese nationals need a Schengen Type C visa for French tourism. Long-stay routes via Talent Passport (skilled professionals / founders / artists / investors), VLS-TS Salarié (sponsored employment), Long-Stay Student visa. Substantial Chinese community in Paris (~140k+) — strong presence at Sanofi-Aventis, L'Oréal, LVMH, BNP Paribas. France-China economic partnership supports business + investment mobility.`,

  // ─── More AU / NZ outbound ───
  "AU:JP": `Australians travel visa-free to Japan for 90 days. Long-stay routes via Engineer/Specialist visa, Highly Skilled Professional points-based residence, Business Manager visa, Working Holiday for under-30 Australians (12 months work + travel). Australia-Japan EPA (JAEPA, in force 2015) supports professional + investment mobility. Substantial Australian community in Tokyo + Niseko + Hakuba (Australian ski resort capital). Reciprocal Japanese expat presence in Sydney + Melbourne — automotive, finance, education.`,
  "AU:DE": `Australians travel visa-free to Germany under Schengen 90/180 (ETIAS from late 2026). Long-stay routes via Skilled Worker visa, EU Blue Card, Opportunity Card 2024, Working Holiday for under-30 Australians (12 months). Australia-Germany bilateral mobility supports professional + investment categories. Substantial Australian community in Berlin + Munich — finance, tech, academia. German 2024 citizenship reform allows dual citizenship — major shift for Australian-German dual nationals.`,
  "NZ:CA": `New Zealanders travel to Canada under the eTA (CA$7, 6-month visa-free stays). Long-stay routes via Express Entry, International Experience Canada — Working Holiday for under-35 New Zealanders (12-24 months), Young Professionals, International Co-op. Substantial NZ community in Vancouver + Toronto — many ski-season hospitality + tech professionals. Canada-NZ Mobility Partnership supports professional secondments.`,

  // ─── More EU passports outbound ───
  "IT:US": `Italians travel to the US under the Visa Waiver Program (ESTA, USD$21, 90-day stays). Long-stay routes via E-1/E-2 Treaty Trader/Investor (Italy is a treaty country, $100k+ — popular Italian SME-expansion route), L-1 intracompany transferees (Ferrari, Fiat-Stellantis, Eni, Generali, Unicredit), O-1 for arts/sports/academia (substantial Italian presence in fashion, design, automotive, food), H-1B for tech. ~17M Americans of Italian descent — the largest US ancestry group from any single EU country.`,
  "ES:US": `Spaniards travel to the US under the Visa Waiver Program (ESTA, USD$21, 90-day stays). Long-stay routes via E-1/E-2 Treaty Trader/Investor (Spain is a treaty country, $100k+), L-1 intracompany transferees (Banco Santander, BBVA, Telefónica, Iberdrola, Repsol), O-1 for arts/sports (Spanish chefs + athletes well-represented), H-1B. Substantial Spanish-American community ~830k. Spain's bilateral arrangements with US cover tax + social security under the 1990 Convention.`,
  "NL:US": `Dutch citizens travel to the US under the Visa Waiver Program (ESTA, USD$21, 90-day stays). Long-stay routes via E-1/E-2 Treaty Trader/Investor + E-2 specifically for the Netherlands — leveraging the Dutch-American Friendship Treaty (1956), one of the easiest E-2 routes globally (lower investment threshold expectations in practice). L-1 intracompany transferees (Shell, ASML, Philips, Heineken, ING). Substantial Dutch-American community ~4M+ (Grand Rapids MI, Holland MI, Pella IA — heritage areas).`,
  "PT:GB": `Portuguese citizens travel to the UK under the ETA (£16, valid 2 years for multiple 6-month stays). Post-Brexit long-stay requires a Skilled Worker visa or other route. Substantial Portuguese-British community in London + the Channel Islands (~250k+) — many continued residence under EU Settlement-equivalent for pre-2021 residents. UK-Portugal bilateral relationship deep — Treaty of Windsor (1386) is still in force, making it the world's oldest active alliance.`,
  "GR:GB": `Greek citizens travel to the UK under the ETA (£16, valid 2 years for multiple 6-month stays). Post-Brexit long-stay routes via Skilled Worker visa, Global Talent, High Potential Individual (graduates of NKUA Athens, AUTH Thessaloniki, University of Crete qualify). Substantial Greek community in London + Birmingham + Manchester. UK-Greece bilateral relationship strong via shared shipping / merchant marine sector — Greek-owned + UK-flagged shipping is among the largest commercial fleets globally.`,

  // ─── More MX / BR / AR outbound ───
  "MX:ES": `Mexicans travel visa-free to Spain under Schengen 90/180 (ETIAS from late 2026). Long-stay routes via Non-Lucrative Visa (passive income from foreign sources), Digital Nomad Visa (€2,762/month proven income), Highly Qualified Worker, Iberoamerican naturalisation framework — Mexican citizens become eligible for Spanish citizenship after just 2 years of legal residence (the shortest accelerated path in Europe). Substantial Mexican-Spanish community in Madrid + Barcelona. Mexican students and professionals heavily represented at IE Business School + ESADE.`,
  // ─── ZA / TR / EG ───
  "ZA:AU": `South Africans need an Australian Visitor visa (subclass 600). Long-stay routes via Subclass 482 (employer-sponsored — mining, healthcare especially), Subclass 189/190 (points-based skilled migration), Working Holiday Subclass 462 for university-educated under-31 South Africans. Substantial South African community in Perth + Brisbane + Sydney + Melbourne (~200k+) — heavy mining-engineer flow into Western Australia. South Africa-Australia bilateral migration relationship dense + long-standing.`,
  "TR:DE": `Turkish citizens need a Schengen Type C visa for German tourism (~€90). Long-stay routes via German Skilled Worker visa (employer-sponsored), Opportunity Card 2024, EU Blue Card for highly-qualified, Family Reunification for descendants of Turkish-origin German residents (substantial heritage migration since 1960s gastarbeiter recruitment — Turkish-German community ~2.9M, the largest single-origin foreign community in Germany). German-Turkish dual citizenship now permitted under the 2024 citizenship reform.`,
  "EG:SA": `Egyptians travel to Saudi Arabia via several routes — Hajj/Umrah pilgrimage visa (specific Islamic-religious-tourism route, separately regulated by the Ministry of Hajj and Umrah), tourist e-visa (since 2019 — open to Egyptian passport holders), work residence (Iqama) for employer-sponsored employment. Substantial Egyptian community in Saudi Arabia (~3M+ workers) — construction, healthcare, hospitality, education sectors. Egypt-Saudi bilateral arrangements support skilled + unskilled labour migration.`,

  // ─── NG / KE / GH outbound ───
  "NG:CA": `Nigerians need a TRV (Temporary Resident Visa) for Canada — Lagos / Abuja visa centres. Long-stay routes via Express Entry (high CRS scores for Nigerian skilled-professionals, especially in healthcare, IT, engineering), Provincial Nominee Programs (Saskatchewan, Manitoba particularly active), Family Class sponsorship, Study Permit → PGWP → Canadian Experience Class PR. Substantial Nigerian-Canadian community ~150k+ (Calgary, Toronto, Edmonton — large concentration in oil + gas + healthcare). Canada Express Entry has been a major Nigerian-outbound route since 2015 reforms.`,
  "KE:GB": `Kenyans need a Standard Visitor visa for UK tourism — Nairobi visa centre. Long-stay routes via UK Skilled Worker (healthcare especially — substantial Kenyan nurse + care-worker recruitment via the Health and Care Worker visa), Student visa (Kenya is among the largest African source nationalities for UK universities). Substantial Kenyan-British community in London + Bristol + Birmingham (~150k+). Kenya-UK bilateral economic partnership supports trade + skilled-worker recruitment.`,

  // ─── More PK / BD ───
  "PK:US": `Pakistanis need a B-1/B-2 visa for the US — applied at the Islamabad embassy or Karachi consulate. Long-stay routes via H-1B for tech (substantial Pakistani-American IT presence — heritage migration since the 1990s tech boom), L-1 intracompany transferees, F-1 student → OPT → H-1B pipeline, Family Preference categories (substantial Pakistani-American family-reunification flow). Pakistani-American community ~700k+ — heavy concentration in New York, Houston, Chicago.`,
  "BD:US": `Bangladeshis need a B-1/B-2 visa for the US — applied at the Dhaka embassy. Long-stay routes via H-1B (especially IT + tech), L-1 intracompany transferees, F-1 student → OPT → H-1B pipeline, Diversity Visa lottery (Bangladesh historically a major DV-Lottery winner nationality before recent qualifying-criteria tightening). Substantial Bangladeshi-American community ~200k+ — heavy concentration in New York (Queens, Brooklyn especially).`,

  // ─── TW + HK ───
  "TW:US": `Taiwanese travel to the US under the Visa Waiver Program (ESTA, USD$21, 90-day stays). Long-stay routes via E-1/E-2 Treaty Trader/Investor (Taiwan is a treaty country via the 1948 US-China FCN — uniquely applicable to Taiwan-passport holders), L-1 intracompany transferees (TSMC, Foxconn, Acer, MediaTek), H-1B, EB-5. Substantial Taiwanese-American community ~390k+ — Silicon Valley + Los Angeles concentrations. The US-Taiwan economic + tech partnership runs deep — TSMC Arizona expansion supports substantial professional mobility.`,
  "TW:GB": `Taiwanese travel to the UK under the ETA (£16, valid 2 years for multiple 6-month stays). Long-stay routes via Skilled Worker visa, Global Talent (Taiwanese tech / academic profile-fit), High Potential Individual for graduates of National Taiwan University + National Tsing Hua University. UK-Taiwan economic partnership supports business + technology mobility — particularly semiconductor + financial services. Substantial Taiwanese community in London + Manchester.`,
};

/** Lookup helper — returns the curated intro for this pair, or undefined
 *  if no entry exists (page falls back to the data-driven DirectAnswerCard). */
export function pairIntroFor(passport: string, destination: string): string | undefined {
  return PAIR_INTROS[`${passport.toUpperCase()}:${destination.toUpperCase()}` as PairKey];
}
