/**
 * Hand-curated long-form intros for the highest-traffic passport pages.
 * These ship as primary SEO content — Google rewards genuinely useful prose,
 * and a 40k-page site templated identically reads as thin content.
 *
 * For passports without a curated intro we fall back to a generated paragraph
 * driven by the live coverage data (see passportIntroFallback in
 * src/app/passport/[iso]/page.tsx).
 *
 * Each intro is intentionally factual, current as of 2024–2025, and avoids
 * promising any specific outcome — the disclaimer language in /disclaimer
 * does the legal work; this is the user-helpful narrative.
 */
export const PASSPORT_INTROS: Record<string, string> = {
  US: `The United States passport ranks among the most travel-friendly in the world. US citizens enter most of Europe (Schengen Area), the United Kingdom, Japan, South Korea, Singapore, Australia (with eTA), Canada (with eTA) and most of Latin America without a visa for short stays — typically 30 to 90 days. For longer stays, most countries require an embassy-issued visa. US passport holders are also eligible for many countries' digital-nomad and retirement visa schemes. Note that US citizens applying for visas abroad pay reciprocity fees in many countries; we surface those fee components on each individual route page.`,

  GB: `The United Kingdom passport offers wide visa-free or eTA-only access across the European Union, the United States (ESTA), Canada (eTA), Australia (eVisitor / ETA), Japan, Singapore, and most of South America. Following Brexit, UK citizens lost automatic EU residence rights but retained 90-days-in-180 visa-free travel under the Schengen short-stay regime. From 2026, UK travellers will need ETIAS authorisation for Schengen entry. Long-stay options include Spain's digital-nomad visa, Portugal's D7, France's long-stay visitor visa, and various skilled-worker routes — covered on each destination page.`,

  DE: `The German passport is one of the strongest globally, granting visa-free or eTA-only access to over 180 countries. As an EU member, Germany offers freedom of movement throughout the European Union and EEA, as well as Schengen short-stay access. German citizens travel visa-free to the United States (ESTA), Canada (eTA), Australia (eVisitor), Japan, South Korea, the UAE, and most of Latin America and Southeast Asia. Notable destinations requiring an embassy visa or e-Visa include Russia, China (some routes; Hong Kong / Macau are visa-free), Vietnam (e-Visa), and Saudi Arabia (e-Visa).`,

  CA: `The Canadian passport provides visa-free or eTA-only entry to most major destinations including the European Union (Schengen — 90 days), the United Kingdom, Japan, South Korea, Australia (eVisitor), Singapore, and most of the Americas. Canadians travelling to the United States are exempt from ESTA but still require I-94 entry. Long-stay options vary widely: Australian working holiday visas are available to Canadians under 35; Schengen long-stay national visas (D-class) are issued by individual EU member states; and bilateral working-holiday agreements exist with Japan, South Korea, Ireland, and several others.`,

  AU: `The Australian passport offers strong visa-free access including the European Union (Schengen — 90 days), the United Kingdom (with ETA from 2025), the United States (ESTA), Canada (eTA), Japan, South Korea, and most of Southeast Asia. Australians benefit from working-holiday agreements with the UK, Ireland, Canada, France, Germany, and many other countries — typically allowing 12 to 24 months of work and travel. For permanent migration, most destinations require employer sponsorship or a points-based skilled-worker route; Canada's Express Entry and the UK's Skilled Worker route are common pathways.`,

  IN: `The Indian passport requires advance visa or e-Visa for many destinations. Visa-free or visa-on-arrival countries include Bhutan, Nepal, the Maldives, Mauritius, Indonesia, Thailand (limited), and several Caribbean nations. Most major destinations — the United States, United Kingdom, Schengen Area, Canada, Australia — require an embassy-issued visa. Indian passport holders are heavily represented in the Skilled Worker pipelines for the UK, Canada (Express Entry), and Australia (Subclass 482), and in the United States H-1B program. Student visa volumes to the UK (Tier 4 / Student route), Australia (Subclass 500), Canada, and the US are among the highest globally.`,

  CN: `The Chinese passport requires advance visa for most major Western destinations including the United States, United Kingdom, Schengen, Canada, and Australia. Notable visa-free or visa-on-arrival access includes much of Southeast Asia (Singapore, Thailand, Malaysia for short stays), the Maldives, the UAE, and several countries in the Americas. China's bilateral mutual-visa-exemption agreements have expanded substantially in 2024–2025 — Thailand, Singapore and several European countries now have reciprocal visa-free arrangements. Long-stay routes typically require embassy applications with documents authenticated through China's foreign-affairs ministry.`,

  JP: `The Japanese passport consistently ranks at the top of global mobility indexes, with visa-free or eTA-only access to nearly 190 countries. Japanese citizens travel visa-free to the United States (ESTA), Canada (eTA), Australia (eVisitor), the UK, Schengen Area, and most of Asia and Latin America. For long stays, working-holiday agreements exist with Australia, New Zealand, Canada, the UK, Germany, France, South Korea, and many others. Japanese citizens are also eligible for the US E-2 treaty-investor visa and various professional-class routes globally.`,

  BR: `The Brazilian passport offers visa-free entry to the European Union (Schengen — 90 days), the UK, Japan, and most of Latin America under Mercosur agreements. Brazilians require visas for the United States (B1/B2), Canada, and Australia. Mercosur residency agreements grant Brazilian citizens streamlined residence rights in Argentina, Uruguay, Paraguay, Chile, Bolivia, Colombia, Ecuador, and Peru. Portugal in particular maintains close ties — Brazilians can access D7 (passive income) and digital-nomad routes with simplified document recognition under the CPLP framework.`,

  KR: `The South Korean passport is one of the strongest in the world, providing visa-free or eTA-only entry to nearly 190 destinations including the United States (ESTA), Canada (eTA), the European Union, the United Kingdom, Australia (eVisitor), Japan, and most of Southeast Asia. Working-holiday agreements with Australia, New Zealand, Canada, Ireland, the UK, Germany, France, and several other countries make multi-year travel-and-work options widely available. For permanent migration, employer-sponsored skilled-worker routes (UK Skilled Worker, Canada Express Entry, Australia Subclass 482) are common.`,

  IT: `The Italian passport offers freedom of movement throughout the European Union and EEA, plus visa-free or eTA-only access to the United States (ESTA), Canada (eTA), the UK, Japan, South Korea, Australia (eVisitor), and most of Latin America and Southeast Asia. Italian citizens are uniquely well-positioned for long-stay options through ius sanguinis citizenship recognition, which simplifies family reunification with descendants of Italian emigrants worldwide. Bilateral working-holiday agreements exist with Australia, New Zealand, Canada, Japan, and South Korea.`,

  ES: `The Spanish passport grants EU/EEA freedom of movement plus broad visa-free or eTA-only access to the Americas, the United States (ESTA), Canada (eTA), the UK, Japan, Australia (eVisitor), and most of Asia. Spanish citizens benefit from preferential pathways to several Latin American countries — including streamlined residency in Argentina, Mexico, Chile and Uruguay through bilateral conventions — and from the Iberoamerican naturalization framework. For long-stay outside the EU, the United States E-2 treaty-investor visa is available to Spanish nationals.`,

  NL: `The Dutch passport provides visa-free or eTA-only entry to the entire European Union, the United States (ESTA), Canada (eTA), the UK, Japan, Australia (eVisitor), and most of Latin America and Southeast Asia. The Netherlands is part of the Schengen Area, granting Dutch citizens 90-day visa-free travel across all member states. Bilateral working-holiday agreements with Australia, New Zealand, Canada, Japan, and South Korea provide multi-year work-and-travel options. For permanent migration, the United States offers the E-1 / E-2 treaty-investor and trader categories to Dutch nationals.`,

  RU: `The Russian passport requires visas for many major Western destinations including the United States, the European Union (suspended visa-facilitation since 2022), Canada, the UK, and Australia. Visa-free or visa-on-arrival access remains broad across Latin America, the post-Soviet space, and parts of Asia and Africa. Long-stay options for Russian nationals have narrowed significantly since 2022 — many EU member states have suspended Russian Golden Visa and investor-residence schemes. The UAE, Turkey, Serbia, Georgia, Armenia, and Thailand remain accessible for both short and long-stay residence.`,

  SG: `The Singaporean passport is consistently ranked at the very top of global mobility indexes, with visa-free or eTA-only access to nearly 195 countries. Singaporean citizens enter the United States (ESTA), Canada (eTA), the European Union, the United Kingdom, Australia (ETA), Japan, and South Korea visa-free for short stays. Working-holiday agreements with Australia, New Zealand, Germany, the UK, and several other countries are widely used. Singapore's reciprocal short-stay arrangements within ASEAN provide visa-free entry across Southeast Asia.`,

  AE: `The UAE passport has risen rapidly in global mobility rankings over the past decade, offering visa-free or eTA-only access to over 180 countries. Emirati citizens enter the European Union (Schengen — 90 days, with ETIAS from 2026), the UK (ETA), and most of Asia, Latin America, and Africa visa-free. UAE passport holders benefit from GCC reciprocity for free residence and work across Saudi Arabia, Kuwait, Bahrain, Qatar, and Oman. Long-stay options outside the GCC commonly use embassy-issued visas with bilateral fee waivers.`,

  CH: `The Swiss passport grants Schengen Area free movement, EU labour-market access under bilateral agreements, and visa-free or eTA-only entry to the United States (ESTA), Canada (eTA), the UK, Japan, Australia (eVisitor), and most of Latin America and Southeast Asia. Swiss citizens are eligible for the US E-2 treaty-investor visa, the UK's ETA, and most working-holiday programmes. For non-EU long-stay routes, Switzerland is a popular originating country for the Spain Digital Nomad and Portugal D7 visa programmes.`,

  SE: `The Swedish passport offers EU/EEA free movement, Schengen Area access, and visa-free or eTA-only entry to the United States (ESTA), Canada (eTA), the United Kingdom, Australia (eVisitor), Japan, South Korea, and most of Latin America and Southeast Asia. Working-holiday agreements with Australia, New Zealand, Canada, Japan, and South Korea provide popular gap-year and post-graduate options. Sweden's strong tax-treaty network supports a wide range of long-stay employment-based migrations through E-2 (US), Express Entry (Canada), and EU Blue Card pathways.`,

  BE: `The Belgian passport provides EU/EEA free movement, Schengen short-stay access, and visa-free or eTA-only entry to the United States (ESTA), Canada (eTA), the UK, Japan, Australia (eVisitor), and most of Latin America and Asia. Belgian citizens are eligible for working-holiday schemes in Australia, New Zealand, Canada, and Japan, and for US E-1 / E-2 treaty-investor categories. Long-stay options outside the EU are dominated by employer-sponsored work permits, with Canada Express Entry and Australia Subclass 482 the most common.`,

  PL: `The Polish passport grants EU/EEA freedom of movement plus visa-free or eTA-only access to the United States (ESTA, since 2019), Canada (eTA), the UK, Japan, South Korea, Australia (eVisitor), and most of Latin America and Southeast Asia. Working-holiday agreements with Australia, New Zealand, Canada, Japan, and South Korea support widespread gap-year travel. Polish citizens benefit from large diaspora communities supporting family reunification and citizenship-by-descent pathways in the United States, Canada, the UK, Germany, and Argentina.`,

  ZA: `The South African passport requires visas for many major Western destinations including the United States, Canada, Australia, and most of the European Union (Schengen — Annex I), but offers visa-free or visa-on-arrival access to the United Kingdom (90 days), most of Africa under SADC and ECOWAS arrangements, and parts of Latin America and Southeast Asia. South African passport holders are heavily represented in UK Skilled Worker, Canada Express Entry, and Australia Subclass 482 employer-sponsored migration. Bilateral working-holiday agreements include Australia, New Zealand, Canada, and Ireland.`,

  TR: `The Turkish passport offers visa-free or eTA-only access to most of the Balkans, Latin America, and parts of Africa and Asia, but requires Schengen visas for EU travel and ESTA for US travel. Turkey's recent bilateral agreements have expanded mutual-visa-exemption arrangements with Russia, Ukraine, Azerbaijan, Singapore, and several Latin American countries. Long-stay routes for Turkish nationals into the EU commonly use the EU Blue Card (Germany), Spain Digital Nomad, Portugal D7, and the UK Skilled Worker route.`,

  IE: `The Irish passport grants EU/EEA freedom of movement, full UK Common Travel Area rights (Ireland and the UK retain a special arrangement separate from Schengen), and visa-free or eTA-only access to the United States (ESTA), Canada (eTA), Australia (eVisitor), Japan, and most of Latin America and Southeast Asia. Irish citizens benefit from the US E-3 treaty-trader visa equivalent (J-1 graduate), bilateral working-holiday programmes with Australia, New Zealand, Canada, Japan, and South Korea, and J-1 internships in the United States.`,

  MX: `The Mexican passport offers visa-free or eTA-only access to the European Union (Schengen — 90 days), the United Kingdom, Japan, South Korea, and most of Latin America. Mexicans require visas for the United States (B1/B2), Canada (after 2016 reimposed eTA-with-conditions), and Australia. Mexico's bilateral working-holiday agreements include Canada, France, Germany, New Zealand, South Korea, and Japan. Long-stay routes commonly use Canada Express Entry, Spain Digital Nomad, and Portugal D7 — all open to Mexican applicants.`,
};

export function passportIntroFor(iso2: string): string | undefined {
  return PASSPORT_INTROS[iso2.toUpperCase()];
}
