/**
 * Hand-curated long-form intros for the highest-traffic passport pages.
 * These ship as primary SEO content — Google rewards genuinely useful prose,
 * and a 40k-page site templated identically reads as thin content.
 *
 * For passports without a curated intro we fall back to a generated paragraph
 * driven by the live coverage data (see passportIntroFallback in
 * src/app/passport/[iso]/page.tsx).
 *
 * Each intro is intentionally factual, current as of 2024–2025, and avoids
 * promising any specific outcome — the disclaimer language in /disclaimer
 * does the legal work; this is the user-helpful narrative.
 */
export const PASSPORT_INTROS: Record<string, string> = {
  US: `The United States passport ranks among the most travel-friendly in the world. US citizens enter most of Europe (Schengen Area), the United Kingdom, Japan, South Korea, Singapore, Australia (with eTA), Canada (with eTA) and most of Latin America without a visa for short stays — typically 30 to 90 days. For longer stays, most countries require an embassy-issued visa. US passport holders are also eligible for many countries' digital-nomad and retirement visa schemes. Note that US citizens applying for visas abroad pay reciprocity fees in many countries; we surface those fee components on each individual route page.`,

  GB: `The United Kingdom passport offers wide visa-free or eTA-only access across the European Union, the United States (ESTA), Canada (eTA), Australia (eVisitor / ETA), Japan, Singapore, and most of South America. Following Brexit, UK citizens lost automatic EU residence rights but retained 90-days-in-180 visa-free travel under the Schengen short-stay regime. From 2026, UK travellers will need ETIAS authorisation for Schengen entry. Long-stay options include Spain's digital-nomad visa, Portugal's D7, France's long-stay visitor visa, and various skilled-worker routes — covered on each destination page.`,

  DE: `The German passport is one of the strongest globally, granting visa-free or eTA-only access to over 180 countries. As an EU member, Germany offers freedom of movement throughout the European Union and EEA, as well as Schengen short-stay access. German citizens travel visa-free to the United States (ESTA), Canada (eTA), Australia (eVisitor), Japan, South Korea, the UAE, and most of Latin America and Southeast Asia. Notable destinations requiring an embassy visa or e-Visa include Russia, China (some routes; Hong Kong / Macau are visa-free), Vietnam (e-Visa), and Saudi Arabia (e-Visa).`,

  CA: `The Canadian passport provides visa-free or eTA-only entry to most major destinations including the European Union (Schengen — 90 days), the United Kingdom, Japan, South Korea, Australia (eVisitor), Singapore, and most of the Americas. Canadians travelling to the United States are exempt from ESTA but still require I-94 entry. Long-stay options vary widely: Australian working holiday visas are available to Canadians under 35; Schengen long-stay national visas (D-class) are issued by individual EU member states; and bilateral working-holiday agreements exist with Japan, South Korea, Ireland, and several others.`,

  AU: `The Australian passport offers strong visa-free access including the European Union (Schengen — 90 days), the United Kingdom (with ETA from 2025), the United States (ESTA), Canada (eTA), Japan, South Korea, and most of Southeast Asia. Australians benefit from working-holiday agreements with the UK, Ireland, Canada, France, Germany, and many other countries — typically allowing 12 to 24 months of work and travel. For permanent migration, most destinations require employer sponsorship or a points-based skilled-worker route; Canada's Express Entry and the UK's Skilled Worker route are common pathways.`,

  IN: `The Indian passport requires advance visa or e-Visa for many destinations. Visa-free or visa-on-arrival countries include Bhutan, Nepal, the Maldives, Mauritius, Indonesia, Thailand (limited), and several Caribbean nations. Most major destinations — the United States, United Kingdom, Schengen Area, Canada, Australia — require an embassy-issued visa. Indian passport holders are heavily represented in the Skilled Worker pipelines for the UK, Canada (Express Entry), and Australia (Subclass 482), and in the United States H-1B program. Student visa volumes to the UK (Tier 4 / Student route), Australia (Subclass 500), Canada, and the US are among the highest globally.`,

  CN: `The Chinese passport requires advance visa for most major Western destinations including the United States, United Kingdom, Schengen, Canada, and Australia. Notable visa-free or visa-on-arrival access includes much of Southeast Asia (Singapore, Thailand, Malaysia for short stays), the Maldives, the UAE, and several countries in the Americas. China's bilateral mutual-visa-exemption agreements have expanded substantially in 2024–2025 — Thailand, Singapore and several European countries now have reciprocal visa-free arrangements. Long-stay routes typically require embassy applications with documents authenticated through China's foreign-affairs ministry.`,

  JP: `The Japanese passport consistently ranks at the top of global mobility indexes, with visa-free or eTA-only access to nearly 190 countries. Japanese citizens travel visa-free to the United States (ESTA), Canada (eTA), Australia (eVisitor), the UK, Schengen Area, and most of Asia and Latin America. For long stays, working-holiday agreements exist with Australia, New Zealand, Canada, the UK, Germany, France, South Korea, and many others. Japanese citizens are also eligible for the US E-2 treaty-investor visa and various professional-class routes globally.`,

  BR: `The Brazilian passport offers visa-free entry to the European Union (Schengen — 90 days), the UK, Japan, and most of Latin America under Mercosur agreements. Brazilians require visas for the United States (B1/B2), Canada, and Australia. Mercosur residency agreements grant Brazilian citizens streamlined residence rights in Argentina, Uruguay, Paraguay, Chile, Bolivia, Colombia, Ecuador, and Peru. Portugal in particular maintains close ties — Brazilians can access D7 (passive income) and digital-nomad routes with simplified document recognition under the CPLP framework.`,

  KR: `The South Korean passport is one of the strongest in the world, providing visa-free or eTA-only entry to nearly 190 destinations including the United States (ESTA), Canada (eTA), the European Union, the United Kingdom, Australia (eVisitor), Japan, and most of Southeast Asia. Working-holiday agreements with Australia, New Zealand, Canada, Ireland, the UK, Germany, France, and several other countries make multi-year travel-and-work options widely available. For permanent migration, employer-sponsored skilled-worker routes (UK Skilled Worker, Canada Express Entry, Australia Subclass 482) are common.`,

  IT: `The Italian passport offers freedom of movement throughout the European Union and EEA, plus visa-free or eTA-only access to the United States (ESTA), Canada (eTA), the UK, Japan, South Korea, Australia (eVisitor), and most of Latin America and Southeast Asia. Italian citizens are uniquely well-positioned for long-stay options through ius sanguinis citizenship recognition, which simplifies family reunification with descendants of Italian emigrants worldwide. Bilateral working-holiday agreements exist with Australia, New Zealand, Canada, Japan, and South Korea.`,

  ES: `The Spanish passport grants EU/EEA freedom of movement plus broad visa-free or eTA-only access to the Americas, the United States (ESTA), Canada (eTA), the UK, Japan, Australia (eVisitor), and most of Asia. Spanish citizens benefit from preferential pathways to several Latin American countries — including streamlined residency in Argentina, Mexico, Chile and Uruguay through bilateral conventions — and from the Iberoamerican naturalization framework. For long-stay outside the EU, the United States E-2 treaty-investor visa is available to Spanish nationals.`,

  NL: `The Dutch passport provides visa-free or eTA-only entry to the entire European Union, the United States (ESTA), Canada (eTA), the UK, Japan, Australia (eVisitor), and most of Latin America and Southeast Asia. The Netherlands is part of the Schengen Area, granting Dutch citizens 90-day visa-free travel across all member states. Bilateral working-holiday agreements with Australia, New Zealand, Canada, Japan, and South Korea provide multi-year work-and-travel options. For permanent migration, the United States offers the E-1 / E-2 treaty-investor and trader categories to Dutch nationals.`,

  RU: `The Russian passport requires visas for many major Western destinations including the United States, the European Union (suspended visa-facilitation since 2022), Canada, the UK, and Australia. Visa-free or visa-on-arrival access remains broad across Latin America, the post-Soviet space, and parts of Asia and Africa. Long-stay options for Russian nationals have narrowed significantly since 2022 — many EU member states have suspended Russian Golden Visa and investor-residence schemes. The UAE, Turkey, Serbia, Georgia, Armenia, and Thailand remain accessible for both short and long-stay residence.`,

  SG: `The Singaporean passport is consistently ranked at the very top of global mobility indexes, with visa-free or eTA-only access to nearly 195 countries. Singaporean citizens enter the United States (ESTA), Canada (eTA), the European Union, the United Kingdom, Australia (ETA), Japan, and South Korea visa-free for short stays. Working-holiday agreements with Australia, New Zealand, Germany, the UK, and several other countries are widely used. Singapore's reciprocal short-stay arrangements within ASEAN provide visa-free entry across Southeast Asia.`,

  AE: `The UAE passport has risen rapidly in global mobility rankings over the past decade, offering visa-free or eTA-only access to over 180 countries. Emirati citizens enter the European Union (Schengen — 90 days, with ETIAS from 2026), the UK (ETA), and most of Asia, Latin America, and Africa visa-free. UAE passport holders benefit from GCC reciprocity for free residence and work across Saudi Arabia, Kuwait, Bahrain, Qatar, and Oman. Long-stay options outside the GCC commonly use embassy-issued visas with bilateral fee waivers.`,

  CH: `The Swiss passport grants Schengen Area free movement, EU labour-market access under bilateral agreements, and visa-free or eTA-only entry to the United States (ESTA), Canada (eTA), the UK, Japan, Australia (eVisitor), and most of Latin America and Southeast Asia. Swiss citizens are eligible for the US E-2 treaty-investor visa, the UK's ETA, and most working-holiday programmes. For non-EU long-stay routes, Switzerland is a popular originating country for the Spain Digital Nomad and Portugal D7 visa programmes.`,

  SE: `The Swedish passport offers EU/EEA free movement, Schengen Area access, and visa-free or eTA-only entry to the United States (ESTA), Canada (eTA), the United Kingdom, Australia (eVisitor), Japan, South Korea, and most of Latin America and Southeast Asia. Working-holiday agreements with Australia, New Zealand, Canada, Japan, and South Korea provide popular gap-year and post-graduate options. Sweden's strong tax-treaty network supports a wide range of long-stay employment-based migrations through E-2 (US), Express Entry (Canada), and EU Blue Card pathways.`,

  BE: `The Belgian passport provides EU/EEA free movement, Schengen short-stay access, and visa-free or eTA-only entry to the United States (ESTA), Canada (eTA), the UK, Japan, Australia (eVisitor), and most of Latin America and Asia. Belgian citizens are eligible for working-holiday schemes in Australia, New Zealand, Canada, and Japan, and for US E-1 / E-2 treaty-investor categories. Long-stay options outside the EU are dominated by employer-sponsored work permits, with Canada Express Entry and Australia Subclass 482 the most common.`,

  PL: `The Polish passport grants EU/EEA freedom of movement plus visa-free or eTA-only access to the United States (ESTA, since 2019), Canada (eTA), the UK, Japan, South Korea, Australia (eVisitor), and most of Latin America and Southeast Asia. Working-holiday agreements with Australia, New Zealand, Canada, Japan, and South Korea support widespread gap-year travel. Polish citizens benefit from large diaspora communities supporting family reunification and citizenship-by-descent pathways in the United States, Canada, the UK, Germany, and Argentina.`,

  ZA: `The South African passport requires visas for many major Western destinations including the United States, Canada, Australia, and most of the European Union (Schengen — Annex I), but offers visa-free or visa-on-arrival access to the United Kingdom (90 days), most of Africa under SADC and ECOWAS arrangements, and parts of Latin America and Southeast Asia. South African passport holders are heavily represented in UK Skilled Worker, Canada Express Entry, and Australia Subclass 482 employer-sponsored migration. Bilateral working-holiday agreements include Australia, New Zealand, Canada, and Ireland.`,

  TR: `The Turkish passport offers visa-free or eTA-only access to most of the Balkans, Latin America, and parts of Africa and Asia, but requires Schengen visas for EU travel and ESTA for US travel. Turkey's recent bilateral agreements have expanded mutual-visa-exemption arrangements with Russia, Ukraine, Azerbaijan, Singapore, and several Latin American countries. Long-stay routes for Turkish nationals into the EU commonly use the EU Blue Card (Germany), Spain Digital Nomad, Portugal D7, and the UK Skilled Worker route.`,

  IE: `The Irish passport grants EU/EEA freedom of movement, full UK Common Travel Area rights (Ireland and the UK retain a special arrangement separate from Schengen), and visa-free or eTA-only access to the United States (ESTA), Canada (eTA), Australia (eVisitor), Japan, and most of Latin America and Southeast Asia. Irish citizens benefit from the US E-3 treaty-trader visa equivalent (J-1 graduate), bilateral working-holiday programmes with Australia, New Zealand, Canada, Japan, and South Korea, and J-1 internships in the United States.`,

  MX: `The Mexican passport offers visa-free or eTA-only access to the European Union (Schengen — 90 days), the United Kingdom, Japan, South Korea, and most of Latin America. Mexicans require visas for the United States (B1/B2), Canada (after 2016 reimposed eTA-with-conditions), and Australia. Mexico's bilateral working-holiday agreements include Canada, France, Germany, New Zealand, South Korea, and Japan. Long-stay routes commonly use Canada Express Entry, Spain Digital Nomad, and Portugal D7 — all open to Mexican applicants.`,

  NZ: `The New Zealand passport ranks in the global top tier, with visa-free or eTA-only entry to ~190 destinations including Schengen (ETIAS from late 2026), the UK (ETA), the US (ESTA), Canada (eTA), Japan, South Korea, and Australia (under the Trans-Tasman Travel Arrangement, which grants indefinite work and residence rights). Kiwis qualify for working-holiday agreements with the UK, Ireland, Canada, Germany, France, Japan, and South Korea. New Zealand's bilateral Investor and Skilled Migrant Category routes (rebuilt under SMC 2024) attract reciprocal interest from Canada and Australia.`,

  AT: `The Austrian passport grants EU freedom of movement, full Schengen Area access, and visa-free or eTA-only entry to the US (ESTA), Canada (eTA), the UK, Japan, South Korea, Australia (eVisitor), and most of Latin America and Southeast Asia. Austrians are eligible for the US E-2 treaty-investor visa and working-holiday agreements with Australia, New Zealand, Canada, Japan, South Korea, and Taiwan. From October 2025 the EU Entry/Exit System (EES) records all Schengen entries biometrically, including outbound trips by Austrian residents — though no visa changes apply for Austrian citizens.`,

  FI: `The Finnish passport offers EU/EEA free movement, Schengen access, and visa-free or eTA-only entry to the US (ESTA), Canada (eTA), the UK, Japan, South Korea, Australia (eVisitor), and most of Latin America and Southeast Asia. Finland's Nordic Passport Union grants Finns the right to work and live in Denmark, Iceland, Norway and Sweden without permits. Working-holiday agreements include Australia, New Zealand, Canada, Japan, South Korea, and Argentina. Finnish citizens face no friction at the EU level but should note Russian border crossings remain suspended since 2023.`,

  NO: `Norway is outside the EU but inside the EEA single market — Norwegians work and reside across the EU 27 on the same terms as EU citizens, including in Switzerland through the EFTA agreements. Short-stay mobility includes ESTA entry to the US, eTA entry to Canada, ETA to the UK, eVisitor to Australia, plus K-ETA Korea and visa-free Japan. The Svalbard Treaty admits the world's nationalities to the archipelago without visa — a quirk relevant to nobody else. Working-holiday agreements span Argentina, Australia, Canada, Chile, Japan, South Korea and New Zealand; the 1928 Treaty of Friendship grants US E-2 treaty-investor eligibility.`,

  DK: `The Danish passport grants EU freedom of movement, full Schengen access, and visa-free or eTA-only entry to the US (ESTA), Canada (eTA), the UK, Japan, South Korea, Australia (eVisitor), and most of Latin America and Southeast Asia. Danes benefit from the Nordic Passport Union — free movement to live and work in Finland, Iceland, Norway and Sweden — and from Denmark's opt-outs on EU asylum and home-affairs cooperation (which do not affect Danish citizens' mobility). Working-holiday agreements include Australia, New Zealand, Canada, Chile, Japan, and South Korea.`,

  CZ: `The Czech passport provides EU/EEA free movement, full Schengen access, and visa-free or eTA-only entry to the US (ESTA, granted under the Visa Waiver Program in 2008), Canada (eTA), the UK, Japan, South Korea, Australia (eVisitor), and most of Latin America. Working-holiday agreements include Australia, New Zealand, Canada, Japan, South Korea, Taiwan, and Chile. Czech nationals are eligible for the US E-1/E-2 treaty-investor visas and use Germany's EU Blue Card, the UK Skilled Worker, and Canada Express Entry as common long-stay pathways outside the EU.`,

  GR: `The Greek passport grants EU freedom of movement, Schengen access, and visa-free or eTA-only entry to the US (ESTA), Canada (eTA), the UK, Japan, Australia (eVisitor), South Korea, and most of Latin America. Greeks qualify for the US E-2 treaty-investor visa under the 1954 US-Greece Treaty of Friendship. Working-holiday agreements include Australia, New Zealand, Canada, and Argentina. The Greek diaspora — large in the US, Australia, Canada, and Germany — supports widely-used family reunification and citizenship-by-descent pathways for the next generation.`,

  HU: `The Hungarian passport provides EU/EEA free movement, full Schengen access, and visa-free or eTA-only entry to the US (ESTA, since 2008), Canada (eTA), the UK, Japan, South Korea, Australia (eVisitor), and most of Latin America. Working-holiday agreements include Australia, New Zealand, Canada, Japan, South Korea, Taiwan, Argentina, and Chile. Hungarians are eligible for the US E-2 treaty-investor visa. The Hungarian-descent simplified naturalisation programme has, since 2011, materially expanded the citizenry — relevant to families with grandparents born in the historical Kingdom of Hungary.`,

  RO: `The Romanian passport grants EU/EEA free movement and — since January 2025 — full Schengen Area access (land borders, after air/sea opened March 2024). Romanians enter the US visa-free under ESTA (granted in 2025), Canada (eTA), the UK, Japan, South Korea, Australia (eVisitor), and most of Latin America. Working-holiday agreements include Australia, Canada, Japan, South Korea, and Argentina. Romania is also a popular issuing country for citizenship-by-descent pathways for ethnic Romanians from Moldova, Ukraine, and the historical Romanian-speaking diaspora. Common long-stay routes outside the EU use the UK Skilled Worker, Canada Express Entry, and Germany's EU Blue Card.`,

  HR: `The Croatian passport provides EU/EEA free movement and full Schengen access (Croatia joined Schengen 2023-01-01) plus visa-free or eTA-only entry to the US (ESTA, granted in 2021), Canada (eTA), the UK, Japan, South Korea, Australia (eVisitor), and most of Latin America. Working-holiday agreements include Australia, New Zealand, Canada, Japan, and Argentina. Croatians benefit from the relatively new ESTA access — useful for short business travel — and from EU Blue Card eligibility for skilled work across Germany, France, and the Netherlands.`,

  BG: `The Bulgarian passport grants EU/EEA free movement and — since January 2025 — full Schengen Area access (land borders, after air/sea opened March 2024). Bulgarians enter Canada (eTA), the UK, Japan, South Korea, Australia (eVisitor), and most of Latin America visa-free, but still require a B1/B2 visa for the US (Bulgaria is not in the Visa Waiver Program despite repeated lobbying). Working-holiday agreements are limited; most long-stay routes outside the EU use Canada Express Entry, Australia Subclass 482, or the UK Skilled Worker.`,

  SK: `Since the 1993 dissolution Slovakia has run its own immigration policy, but the practical mobility surface is similar to the Czech Republic: EU and Schengen freedom of movement, US Visa Waiver Program access via ESTA (admitted 2008), Canadian eTA, Korean K-ETA. Slovaks rely heavily on Austria, Germany and Hungary for cross-border labour — Bratislava is the only EU capital where a daily commute to two foreign capitals is feasible. Working-holiday corridors run to Australia, New Zealand, Canada, Japan, South Korea, Taiwan, Argentina and Chile. The Slovak-American Treaty of 1992 carried the E-2 investor route across from the Czechoslovak-US 1928 instrument.`,

  SI: `The Slovenian passport grants EU/EEA free movement, Schengen access, and visa-free or eTA-only entry to the US (ESTA), Canada (eTA), the UK, Japan, South Korea, Australia (eVisitor), and most of Latin America. Slovenes qualify for the US E-1/E-2 treaty-investor visas. Working-holiday agreements include Australia, Canada, Japan, South Korea, and Argentina. Slovenia's strong tax-treaty network supports common long-stay routes via Canada Express Entry, Germany's EU Blue Card, and Australia Subclass 482; the country also borders four Schengen states, making cross-border work routine.`,

  LT: `The Lithuanian passport provides EU/EEA free movement, full Schengen access, and visa-free or eTA-only entry to the US (ESTA, granted in 2008), Canada (eTA), the UK, Japan, South Korea, Australia (eVisitor), and most of Latin America. Working-holiday agreements include Australia, New Zealand, Canada, Japan, South Korea, and Argentina. Lithuanians are eligible for the US E-2 treaty-investor visa. Since 2022 the Lithuanian government has suspended most short-stay visa issuance to Russian and Belarusian nationals at its consulates — relevant context if you hold a second passport or travel onward to those states.`,

  LV: `The Latvian passport grants EU/EEA free movement, full Schengen access, and visa-free or eTA-only entry to the US (ESTA, granted in 2008), Canada (eTA), the UK, Japan, South Korea, Australia (eVisitor), and most of Latin America. Latvians qualify for the US E-2 treaty-investor visa. Working-holiday agreements include Australia, Canada, Japan, and South Korea. As a Baltic state with a large Russian-speaking minority, Latvia maintains separate visa rules for non-citizens (the "alien's passport"); this intro covers ordinary Latvian citizenship documents only.`,

  EE: `The Estonian passport provides EU/EEA free movement, full Schengen access, and visa-free or eTA-only entry to the US (ESTA, granted in 2008), Canada (eTA), the UK, Japan, South Korea, Australia (eVisitor), and most of Latin America. Working-holiday agreements include Australia, New Zealand, Canada, Japan, and South Korea. Estonia is best known internationally for its e-Residency programme (not citizenship) which is widely used by digital nomads — but Estonian citizens enjoy genuine EU Blue Card, US E-2 treaty-investor, and Canada Express Entry access for long-stay routes. Estonia operates an "alien's passport" for stateless residents distinct from this overview.`,

  CY: `The Cypriot passport grants EU/EEA free movement, plus visa-free or eTA-only entry to the UK (under historical Commonwealth arrangements), Canada (eTA), Japan, South Korea, Australia (eVisitor), and most of Latin America. Cyprus is not yet in the Schengen Area — Cypriots enter Schengen visa-free for 90/180 but use the slower non-Schengen lane at airport borders. The US requires a B1/B2 visa for Cypriots (Cyprus is not in the Visa Waiver Program). Cypriot citizens are eligible for US E-2 treaty-investor status and benefit from the Commonwealth working-holiday route into the UK.`,

  MT: `The Maltese passport provides EU/EEA free movement, full Schengen access, and visa-free or eTA-only entry to the US (ESTA, granted in 2008), Canada (eTA), the UK (Commonwealth privileges), Japan, South Korea, Australia (eVisitor), and most of Latin America. Maltese citizens — uniquely among EU members — also retain rights from the Commonwealth, including streamlined UK access. Malta's controversial individual-investor citizenship programme was wound down in 2024 following EU pressure; current ordinary naturalisations follow standard residence-then-citizenship rules. Working-holiday agreements include Australia, New Zealand, and Canada.`,

  LU: `The Luxembourg passport grants EU/EEA free movement, full Schengen access, and visa-free or eTA-only entry to the US (ESTA), Canada (eTA), the UK, Japan, South Korea, Singapore, Australia (eVisitor), and most of Latin America and Southeast Asia. Luxembourgers qualify for the US E-2 treaty-investor visa under the 1962 Treaty of Friendship. Working-holiday agreements include Australia, New Zealand, Canada, Japan, South Korea, and Argentina. Luxembourg's tax-treaty network and dual-citizenship-friendly law (since 2009) make it a common second-passport destination for high-income professionals; ordinary naturalisation requires five years of residence plus Luxembourgish language proficiency.`,

  IS: `Iceland's passport sits in the global top tier — small country, outsized mobility. Holders enter the US (ESTA), Canada (eTA), the UK, the Schengen Area, Japan, South Korea, and Australia (eVisitor) without prior visa, and travel freely within the EEA. The Nordic Passport Union grants Icelanders settled-resident rights in Denmark, Finland, Sweden and Norway from day one. Unique historic ties — the 1944 Treaty of Friendship grants US E-1/E-2 trader/investor eligibility — and the Hoyvík Agreement with the Faroes make Reykjavík–Tórshavn an unusually open route. Working-holiday programmes include Japan, Australia, New Zealand and Canada.`,

  TW: `The Taiwanese passport offers visa-free or eTA-only entry to ~145 destinations including the US (ESTA, granted in 2012), Canada (eTA), the UK, the Schengen Area (with ETIAS from late 2026), Japan, South Korea, Australia (eVisitor), and most of Latin America. China requires a Mainland Travel Permit (台胞证) rather than treating the Taiwan passport as foreign. Taiwanese citizens benefit from working-holiday agreements with Australia, New Zealand, Canada, Germany, France, Japan, South Korea, the UK, and Ireland. Several Latin American allies (Paraguay, Guatemala) provide additional reciprocal preferences.`,

  HK: `The Hong Kong SAR passport offers visa-free or eTA-only entry to ~170 destinations including the UK (6 months visa-free), Schengen (90/180 with ETIAS from late 2026), Japan, South Korea, Singapore, Australia (eVisitor), and most of Southeast Asia. The US requires a B1/B2 visa. Hong Kong residents emigrating to the UK under the BN(O) Visa scheme (launched January 2021) use a separate route grounded in pre-1997 nationality status. China requires a Home Return Permit rather than a Hong Kong SAR passport. Working-holiday agreements include Australia, New Zealand, Canada, Germany, France, Ireland, Japan, and South Korea.`,

  IL: `The Israeli passport ranks high globally with visa-free or eTA-only entry to ~170 destinations including the US (under the Visa Waiver Program since October 2023, with ESTA), Canada (eTA), the UK, Schengen (with ETIAS from late 2026), Japan, South Korea, and most of Latin America. Several Arab and Muslim-majority states refuse entry to Israeli passport holders or to any passport showing an Israeli stamp — Iran, Iraq, Lebanon, Syria, Yemen, Libya, Algeria, and (in practice if not always policy) Saudi Arabia, Bangladesh, Brunei, Malaysia and Pakistan. Always travel with a clean second passport for onward travel via those regions.`,

  SA: `The Saudi Arabian passport has improved significantly in mobility rankings since 2018, offering visa-free or visa-on-arrival entry to ~85 destinations including the UK (6 months visa-free for short stays since 2022 with electronic permit), Schengen (90/180 — visa required), Japan (visa required), Singapore, and most of the GCC. The US and most of Schengen require embassy visas. Saudi nationals benefit from GCC reciprocity — free residence and work across Kuwait, Bahrain, Qatar, the UAE and Oman — and from the unified GCC tourist visa as it rolls out across 2024–2026. Long-stay routes outside the GCC commonly use UAE Golden Visa equivalents.`,

  QA: `The Qatari passport offers visa-free or visa-on-arrival entry to ~110 destinations including the Schengen Area (90/180, with ETIAS from late 2026), the UK (visa-free since 2022 with electronic permit), Singapore, Japan, South Korea, Malaysia, and most of Latin America. The US requires a B1/B2 visa. Qatari nationals benefit from GCC reciprocity (residence and work rights across Bahrain, Kuwait, Oman, Saudi Arabia, and the UAE) and from the rolling-out unified GCC tourist visa as Tier-1 eligibility is confirmed through 2026. Qatar's modest national population and high consular-service investment make passport renewals fast.`,

  KW: `Kuwait was the first GCC state to win Schengen visa-free entry (2014) and reached the same status with Japan (2026 reciprocal arrangement under negotiation). Kuwaiti nationals enter the UK with an electronic permit (from 2024) and travel to Russia, Türkiye, Malaysia, Singapore and Thailand without a visa. The US remains an embassy-application route. Inside the GCC, Kuwaitis work and reside as nationals across Bahrain, Oman, Qatar, Saudi Arabia and the UAE under longstanding reciprocity, and Kuwait's involvement in the rolling unified GCC tourist visa means inbound travel from Tier-1 nationalities streamlines further across 2026.`,

  BH: `The Bahraini passport offers visa-free or visa-on-arrival entry to ~85 destinations including the Schengen Area (90/180, with ETIAS from late 2026), Singapore, Malaysia, and most of Southeast Asia. The UK requires an electronic permit (introduced 2024) and the US requires a B1/B2 visa. Bahraini nationals benefit from GCC reciprocity (free residence and work across Kuwait, Oman, Qatar, Saudi Arabia, and the UAE) and from the rolling-out unified GCC tourist visa for inbound tourism. Long-stay routes outside the GCC commonly use the UK Skilled Worker and Canada Express Entry.`,

  OM: `The Omani passport provides visa-free or visa-on-arrival entry to ~85 destinations including the Schengen Area (90/180, with ETIAS from late 2026), Singapore, Malaysia, the Maldives, and most of Southeast Asia. The UK requires an electronic permit and the US requires a B1/B2 visa. Omani nationals benefit from GCC reciprocity — free residence and work across Bahrain, Kuwait, Qatar, Saudi Arabia, and the UAE — and from the rolling-out unified GCC tourist visa. Oman's bilateral arrangements within East Africa (Tanzania, Zanzibar historical ties) make regional travel routine.`,

  JO: `The Jordanian passport offers visa-free or visa-on-arrival entry to ~50 destinations, with most major destinations requiring an embassy or e-Visa. Jordanians enter Türkiye, Malaysia, Indonesia (visa-on-arrival), and parts of the Caribbean and South America visa-free. Schengen, the US, the UK, Canada, and Australia all require pre-arrival visas. Jordan has a privileged labour-market arrangement with GCC states (especially Saudi Arabia and the UAE) where Jordanian professionals are heavily represented. The 2022 King Abdullah Initiative for the US provides Jordanian nationals with E-2 treaty-investor visa eligibility — an unusual privilege for the region.`,

  EG: `The Egyptian passport requires visas for most major destinations including the US, the UK, Schengen, Canada, and Australia. Visa-free or visa-on-arrival access is limited but includes parts of Latin America (Bolivia, Ecuador, Peru), several Caribbean states, Türkiye (visa-free since 2017 was suspended in 2023; check current rules), and most of Sub-Saharan Africa under bilateral arrangements. Egyptian nationals are heavily represented in GCC labour markets — Saudi Arabia, Kuwait, the UAE — under sponsored work-permit systems. Long-stay routes into the West commonly use the UK Skilled Worker, Canada Express Entry, and Australia Subclass 482.`,

  MA: `The Moroccan passport requires visas for most Western destinations including the US, the UK, Schengen, Canada, and Australia. Visa-free or visa-on-arrival access is concentrated in Latin America (Argentina, Brazil, Chile, Peru), several Caribbean and Central American states, Türkiye, Malaysia, Indonesia, and most of Sub-Saharan Africa. Morocco maintains strong bilateral ties with France and Spain — Moroccan-French and Moroccan-Spanish dual nationality is common — supporting family-reunification and student routes into both. Long-stay options use the EU Blue Card, France's "Talent Passport", Spain's Highly Qualified Professional visa, and Canada Express Entry.`,

  TN: `The Tunisian passport requires visas for most Western destinations including the US, the UK, Schengen, Canada, and Australia. Visa-free or visa-on-arrival access includes Türkiye, Malaysia, Indonesia, several Latin American states (Bolivia, Ecuador, Peru, Honduras), most of Sub-Saharan Africa, and parts of Eastern Europe (Serbia, Belarus, North Macedonia). Tunisian nationals benefit from the EU-Tunisia Mobility Partnership which supports skilled migration to France, Germany, Italy, and Belgium under preferential visa categories. France remains the dominant migration destination historically, with established diaspora communities supporting family-reunification and education-based pathways into the EU.`,

  KE: `The Kenyan passport provides visa-free or visa-on-arrival entry to most of Africa (under the African Continental Free Trade Area and various bilateral arrangements), the East African Community Tourist Visa zone (Kenya–Rwanda–Uganda single visa), several Caribbean and Pacific states, Türkiye, and parts of Southeast Asia. Schengen, the UK, the US, Canada, and Australia all require embassy visas — though UK refusal rates for Kenyan applicants have declined since 2023. Long-stay routes commonly use the UK Skilled Worker (especially for healthcare professionals), Canada Express Entry, and Australia Subclass 482.`,

  NG: `The Nigerian passport requires visas for most destinations and is among the more difficult passports for short-stay travel. Visa-free or visa-on-arrival access is concentrated in ECOWAS member states (free movement, residence, and establishment within the 15-member bloc) and a small number of Caribbean and Pacific states. UK, US, Schengen and Canadian visa applications carry above-baseline refusal rates (30–50% historically) — strong documentation materially improves outcomes. Long-stay routes into the West use the UK Skilled Worker (Nigerian nationals are among the top issuance cohorts), Canada Express Entry, and Australia Subclass 482.`,

  GH: `The Ghanaian passport provides visa-free movement within ECOWAS (free entry, residence, and establishment across 15 West African states) plus visa-free or visa-on-arrival entry to several Caribbean states, parts of East Africa, and a small Asian list (Malaysia, Indonesia visa-on-arrival). Most major destinations — the US, UK, Schengen, Canada, Australia — require embassy visas. Ghana is a high-volume issuing country for the UK Skilled Worker (healthcare especially), Canada Express Entry, and US Diversity Visa Lottery participation. Bilateral working-holiday or youth-mobility agreements are limited.`,

  GY: `The Guyanese passport grants CARICOM Single Market and Economy rights (free movement, residence, and the right to establish a business across 12 member states) plus visa-free or visa-on-arrival entry to the UK (6 months visa-free), the Schengen Area (90/180, with ETIAS from late 2026), most of Latin America, and parts of Southeast Asia. The US requires a B1/B2 visa. Guyana's significant Indian-descent population maintains close ties with India (overseas-citizen card eligible), supporting bilateral cultural and educational exchange. Long-stay routes commonly use Canada Express Entry and the UK Skilled Worker.`,

  JM: `The Jamaican passport provides CARICOM Single Market and Economy rights (free movement and residence across 12 member states), visa-free entry to the UK (6 months), Hong Kong, Singapore, and most of Latin America, plus visa-on-arrival in several African and Asian states. The US, Schengen, Canada and Australia require embassy visas. Jamaica's deep diaspora ties with the UK, the US, and Canada support extensive family-reunification routes. Commonwealth status grants Jamaicans preferential treatment under the UK's Youth Mobility scheme and several historical reciprocal arrangements.`,

  TT: `The Trinidad and Tobago passport grants CARICOM Single Market and Economy rights, visa-free entry to the UK (6 months), the Schengen Area (90/180, with ETIAS from late 2026), Hong Kong, Singapore, Malaysia, and most of Latin America. The US requires a B1/B2 visa. Trinidad and Tobago's mixed Indian-African heritage supports both Indian Overseas Citizen eligibility and dense ties to the African diaspora. Long-stay routes use Canada Express Entry (the largest Trinidadian migration destination), the UK Skilled Worker, and Commonwealth youth-mobility schemes.`,

  DO: `The Dominican Republic passport offers visa-free or visa-on-arrival entry to ~75 destinations including the Schengen Area (90/180, with ETIAS from late 2026), the UK (6 months visa-free), Hong Kong, Singapore (visa-on-arrival), Türkiye, and most of Latin America. The US, Canada and Australia require embassy visas. CAFTA-DR (the Central American Free Trade Agreement) supports business travel preferences with the US. Dominican nationals are heavily represented in US migration via family-sponsorship, and Spain's bilateral conventions (rooted in the Iberoamerican framework) provide simplified naturalisation after two years of legal residence.`,

  CR: `The Costa Rican passport provides visa-free or eTA-only entry to ~150 destinations including the Schengen Area (90/180, with ETIAS from late 2026), the UK (6 months visa-free), Canada (eTA), Hong Kong, Singapore, Japan, South Korea (K-ETA), and most of Latin America. The US requires a B1/B2 visa. Costa Rica's neutrality, lack of a standing army, and stable institutions support strong consular service abroad. CAFTA-DR provides business travel preferences with the US. Spain's Iberoamerican naturalisation framework grants Costa Ricans simplified Spanish citizenship after two years of legal residence.`,

  PA: `The Panamanian passport offers visa-free or eTA-only entry to ~140 destinations including the Schengen Area (90/180, with ETIAS from late 2026), the UK (6 months visa-free), Canada (eTA), Hong Kong, Singapore, Japan, South Korea (K-ETA), and most of Latin America. The US requires a B1/B2 visa. Panama's status as a financial hub means many ordinary passports also hold a second nationality. Spain's Iberoamerican naturalisation framework grants Panamanians simplified Spanish citizenship after two years of legal residence. Bilateral arrangements with Colombia, Costa Rica and Ecuador support border-region commerce.`,

  GT: `The Guatemalan passport offers visa-free or eTA-only entry to ~130 destinations including the Schengen Area (90/180, with ETIAS from late 2026), the UK (6 months visa-free), Hong Kong, Singapore (visa-on-arrival), Japan, South Korea (K-ETA), and most of Latin America under the CA-4 Border Control Agreement (Guatemala–El Salvador–Honduras–Nicaragua free movement of citizens). The US, Canada, and Australia require embassy visas. CAFTA-DR provides business-travel preferences with the US. Spain's Iberoamerican naturalisation framework grants Guatemalans simplified Spanish citizenship after two years of legal residence — a major route into the EU for Guatemalan professionals.`,

  CO: `The Colombian passport grants visa-free or eTA-only entry to ~135 destinations including the Schengen Area (90/180, with ETIAS from late 2026), the UK (6 months visa-free), Canada (eTA, granted in 2022), Hong Kong, Singapore, Japan, South Korea (K-ETA), and most of Latin America. The US requires a B1/B2 visa. Mercosur association membership and the Pacific Alliance support residency rights across Argentina, Brazil, Chile, Mexico, Peru and Uruguay. Spain's bilateral arrangements (and Iberoamerican naturalisation) grant Colombians simplified Spanish citizenship after two years of residence — a major migration route.`,

  PE: `Peru's passport has improved sharply since Schengen visa exemption arrived in 2016 — 135+ destinations now open without prior authorisation, including the UK, Israel, Türkiye, the Russian Federation, and most of Asia from Japan to Malaysia. The US and Canada remain embassy-application destinations. The Andean Community (Peru, Bolivia, Colombia, Ecuador) creates free movement and labour rights across the Andean north of the continent, distinct from Mercosur. Peru's growing Japanese-Peruvian community supports the Nikkei Visa route into Japan — a heritage-based long-stay channel unique to citizens of partial Japanese descent.`,

  CL: `The Chilean passport ranks among the strongest in the Americas, with visa-free or eTA-only entry to ~175 destinations including the US (ESTA, granted in 2014 — the only South American Visa Waiver Program member), Canada (eTA), the Schengen Area (90/180, with ETIAS from late 2026), the UK (6 months visa-free), Australia (eVisitor), Hong Kong, Singapore, Japan, and South Korea (K-ETA). Working-holiday agreements include Australia, New Zealand, Canada, Germany, France, Japan, and South Korea. Pacific Alliance and Mercosur association memberships add Latin American residency rights, and Spain's Iberoamerican naturalisation simplifies Spanish citizenship.`,

  AR: `The Argentine passport provides visa-free or eTA-only entry to ~170 destinations including the Schengen Area (90/180, with ETIAS from late 2026), the UK (6 months visa-free), Canada (eTA, granted in 2022), Hong Kong, Singapore, Japan, South Korea (K-ETA), Australia (eVisitor), and most of Latin America. The US requires a B1/B2 visa (Argentina was in the Visa Waiver Program until 2002). Working-holiday agreements include Australia, New Zealand, Canada, Germany, France, Japan, and South Korea. Mercosur full-member status grants residency rights across Brazil, Paraguay, Uruguay, and associated states.`,

  UY: `Uruguay holds the second-strongest South American passport behind Chile — its tiny size (3.4M people) belies the breadth: 155+ destinations open without prior visa, including Schengen, the UK, Israel, Hong Kong, Singapore, Russia, and an eVisitor route into Australia. Only the US, Canada and a small list of African/Asian destinations require embassy applications. Uruguay's three Mercosur founding partners (Argentina, Brazil, Paraguay) grant near-automatic residency, and Montevideo issues residency to qualifying foreign nationals quickly — an unusual hub for South American expat-citizenship pipelines. Spain's Iberoamerican framework cuts naturalisation to two years.`,

  VE: `The Venezuelan passport requires visas for most major destinations including the US, Canada, and most of Schengen since 2024 (when Spain, Italy and the Netherlands tightened rules in response to migration pressures). Visa-free or visa-on-arrival access remains in most of Latin America under Mercosur association, the Andean Community, and bilateral arrangements; Türkiye, Iran, Russia, and Serbia also remain open. Passport issuing and renewal are severely constrained — many Venezuelans abroad cannot renew. Spain, Argentina, Mexico, Chile, Uruguay, Peru and Colombia operate streamlined regularization programmes for Venezuelan migrants.`,

  PK: `The Pakistani passport sits among the most travel-restricted globally. Visa-free or visa-on-arrival access is limited to a handful of destinations — primarily the Maldives, several Caribbean states, parts of East Africa, and Cape Verde. Most major destinations including the US, the UK, Schengen, Canada, and Australia require embassy visas. Pakistani applicants face above-baseline refusal rates for short-stay visas (30–60% historically). Long-stay routes are dominated by the UK Skilled Worker (especially healthcare), Canada Express Entry, Australia Subclass 482, and the US H-1B — Pakistani nationals are heavily represented in all four programmes.`,

  BD: `The Bangladeshi passport offers visa-free or visa-on-arrival entry to ~40 destinations, primarily in Sub-Saharan Africa, the Caribbean, several Pacific island states, and parts of South and Southeast Asia. Most major destinations — the US, UK, Schengen, Canada, Australia — require embassy visas, with B1/B2 interview waits at the Dhaka US embassy historically running 6–12 months. Bangladeshi nationals are heavily represented in UK Skilled Worker, Canada Express Entry, Australia Subclass 482, US H-1B, and Gulf labour markets (Saudi Arabia, the UAE, Kuwait, Qatar). UK Bangladeshi-heritage family-reunification routes remain among the largest UK immigration categories.`,

  LK: `The Sri Lankan passport offers visa-free or visa-on-arrival entry to ~40 destinations primarily in Sub-Saharan Africa, the Caribbean, several Pacific states, and parts of Southeast Asia. Most major destinations require embassy or e-Visa applications. Bilateral working-holiday agreements with Australia, New Zealand, and Japan are limited. Long-stay routes commonly use the UK Skilled Worker (healthcare and tech), Canada Express Entry, Australia Subclass 482, and the US H-1B. The Sri Lankan diaspora — particularly large in Canada, the UK, and Australia — supports extensive family-reunification migration.`,

  TH: `The Thai passport offers visa-free or visa-on-arrival entry to ~85 destinations including ASEAN free movement (30–90 day stays in Malaysia, Singapore, Indonesia, the Philippines, Vietnam, Laos, Cambodia, Myanmar, Brunei), Hong Kong, Macau, Japan (15 days visa-free), South Korea (K-ETA), Türkiye, Iran, and most of South America. The US, UK, Schengen, Canada, and Australia all require embassy visas. China granted Thai citizens 30-day visa-free entry in 2024 under a reciprocal arrangement. Long-stay options to the West are typically employer-sponsored, especially UK Skilled Worker (hospitality, healthcare), Canada Express Entry, and the US E-2 treaty-investor visa.`,

  MY: `The Malaysian passport ranks among the strongest in Southeast Asia, with visa-free or eTA-only access to ~180 destinations including the US (ESTA — Malaysia is in the Visa Waiver Program), the UK (ETA from 2025), Schengen (90/180, with ETIAS from late 2026), Canada (eTA), Japan, South Korea (K-ETA), and most of Southeast Asia under ASEAN. Working-holiday agreements with Australia and New Zealand are available. Long-stay routes include the UK Skilled Worker, Canada Express Entry, the US H-1B, Australia Subclass 482, and Singapore's Employment Pass. Malaysia's My Second Home (MM2H) programme attracts foreign retirees but is for inbound migration, not outbound.`,

  ID: `The Indonesian passport requires advance visas for most major Western destinations including the US, UK, Schengen, Canada, and Australia. Visa-free or visa-on-arrival access covers ~70 destinations, primarily ASEAN free-movement partners (30 days in Malaysia, Singapore, Thailand, etc.), the Maldives, Hong Kong, Macau, Türkiye, and several African and South American states. Japan grants 15-day visa-free entry to Indonesian e-passport holders who pre-register with the Japanese embassy. Long-stay routes commonly use the UK Skilled Worker (hospitality, healthcare), Australia Subclass 482, US H-1B, Canada Express Entry, and Gulf labour markets (UAE, Saudi Arabia, Qatar) for domestic and skilled work.`,

  PH: `The Philippine passport offers visa-free or visa-on-arrival entry to ~70 destinations including ASEAN free movement (30 days in Singapore, Thailand, Malaysia, Indonesia, Vietnam, Laos, Cambodia, Myanmar, Brunei), Hong Kong, Macau, Brazil, and several Caribbean states. The US, UK, Schengen, Canada, Australia, and Japan all require embassy visas. South Korea is on the K-ETA scheme. Filipino nationals are among the most heavily migrant workforce globally — the OFW (Overseas Filipino Worker) framework supports placement in the Gulf states, Hong Kong, Singapore, Canada, and the US. UK Skilled Worker (healthcare and care work) and Canada Caregiver Pathways are common long-stay routes.`,

  VN: `The Vietnamese passport offers visa-free or visa-on-arrival entry to ~55 destinations, mostly ASEAN free-movement partners (Thailand, Singapore, Malaysia, Indonesia, the Philippines, Laos, Cambodia, Myanmar, Brunei — 14 to 30 days), plus several African and Caribbean states. Most major destinations including the US, UK, Schengen, Canada, Australia, Japan, and South Korea require embassy visas. China was granted reciprocal visa-free access in 2025. Long-stay routes use the UK Skilled Worker (technology and healthcare), Canada Express Entry, Australia Subclass 482, the US H-1B, and South Korean E-7 (foreign professional) and E-9 (employment of non-professionals — EPS) categories.`,

  UA: `The Ukrainian passport, since the 2017 EU visa liberalisation, grants visa-free Schengen entry for 90 days in 180 (ETIAS from late 2026), plus UK (6-month visa-free), Israel, Türkiye, the Western Balkans, and most of Latin America. The US, Canada, Australia and Japan still require visas. Since 2022, Ukrainian citizens have benefited from extraordinary temporary-protection schemes: the EU's Temporary Protection Directive (3-year renewable residence + work right across all member states), the UK's Homes for Ukraine and Ukraine Family Schemes, the US's Uniting for Ukraine humanitarian parole, and Canada's CUAET emergency travel authorisation. Long-stay migration outside these schemes uses Skilled Worker and Express Entry channels.`,

  NP: `The Nepali passport offers visa-free or visa-on-arrival entry to ~40 destinations, primarily in South Asia (India under the 1950 Indo-Nepal Treaty grants near-unlimited right of work and residence), the Maldives, Sri Lanka (visa-on-arrival), and several African states. The US, UK, Schengen, Canada, Australia, and Japan all require embassy visas, with relatively high refusal rates for B1/B2 and Schengen short-stay. Long-stay routes are dominated by Gulf labour migration (especially Saudi Arabia, the UAE, Qatar, Malaysia under labour-export agreements), UK Skilled Worker (hospitality, healthcare), and student visas to Australia, the US, and the UK.`,

  KZ: `The Kazakh passport offers visa-free or visa-on-arrival entry to ~80 destinations, including most of Central Asia under the CIS framework, Türkiye (90 days), Belarus, Russia, Armenia, Kyrgyzstan, Georgia, Israel, the UAE (30 days, expanded 2024), and most of Latin America. The US, UK, Schengen, Canada, Japan and Australia require embassy visas. The Eurasian Economic Union (EAEU) grants Kazakh citizens labour-market access in Russia, Belarus, Armenia, and Kyrgyzstan. Long-stay routes to the West commonly use the UK Skilled Worker, Canada Express Entry, the US H-1B, and Australian Subclass 482, with technical and energy-sector expertise well-represented.`,

  GE: `The Georgian passport — since the 2017 EU visa liberalisation — grants Schengen 90/180 visa-free entry (ETIAS from late 2026), plus the UK (6-month visa-free), Türkiye (90 days), Iran, Israel, and most of South America. The US and Canada require visas. Georgia's "open visa" policy reciprocates extraordinarily generously inbound (over 90 nationalities enter Georgia visa-free for up to 365 days). Outbound long-stay routes use the UK Skilled Worker, Canada Express Entry, the US H-1B, and Germany's Blue Card. Georgia's CETA/EU Association Agreement deepens commercial mobility with the EU.`,

  ET: `The Ethiopian passport offers visa-free or visa-on-arrival entry to ~40 destinations, primarily in Sub-Saharan Africa (East African Community partners — Kenya, Tanzania, Uganda, Rwanda — under the EAC tourist visa framework), the Caribbean (Dominica, Haiti), and a small number of Pacific island states. Most major destinations including the US, UK, Schengen, Canada, Australia, China, and Japan require embassy visas. The substantial Ethiopian diaspora in the US (Washington DC, Minneapolis), the UK, Canada and the Gulf supports family-reunification migration. UK Skilled Worker (healthcare in particular) and Gulf labour markets are dominant employment-based pathways.`,

  UG: `The Ugandan passport offers visa-free or visa-on-arrival entry to ~55 destinations, primarily in East Africa (EAC free movement to Kenya, Tanzania, Rwanda, Burundi, South Sudan) and parts of the Sahel + Indian Ocean. The US, UK, Schengen, Canada, Australia, and most of Asia require embassy visas. UK Health and Care Worker visa is a major route for Ugandan nurses + care workers (NHS / private-care recruitment). Canada Express Entry and Australia Subclass 482 represent additional skilled-migration channels. EAC Single Tourist Visa simplifies tourism within Kenya / Rwanda / Uganda for both inbound and Ugandan-outbound regional travel.`,

  TZ: `The Tanzanian passport offers visa-free or visa-on-arrival entry to ~50 destinations including EAC free movement (Kenya, Uganda, Rwanda, Burundi, South Sudan), SADC tourism arrangements with Southern African states, and several Indian Ocean / Caribbean states. The US, UK, Schengen, Canada, Australia, China require embassy visas. Long-stay routes are dominated by UK Skilled Worker (healthcare especially), Gulf labour markets (Saudi Arabia, UAE, Qatar), Canada Express Entry, and US H-1B / EB-3 channels. Tanzanian-British community ~30,000 — a long-standing diaspora supports family-reunification pipelines.`,

  AO: `The Angolan passport offers visa-free or visa-on-arrival entry to ~50 destinations including SADC partner states, the CPLP Mobility Framework (2021) bilateral arrangements with Portugal, Brazil, Cabo Verde, Mozambique, and Sao Tome, and several Caribbean states. Most major destinations including the US, UK, Schengen, Canada, Australia, and most of Asia require embassy visas. Portugal remains the dominant long-stay destination for Angolans — D7 (passive income), D2 (entrepreneur), and CPLP-streamlined residence permits. Brazil similarly accessible under MERCOSUR-association + CPLP frameworks. UK Skilled Worker (oil + gas, healthcare) is an active employment route.`,

  ZW: `The Zimbabwean passport offers visa-free or visa-on-arrival entry to ~50 destinations primarily in Southern Africa under SADC tourism arrangements (Mozambique, Namibia, Zambia, Malawi, etc.), and several Indian Ocean / Caribbean states. The US, UK, Schengen, Canada, Australia, and Japan require embassy visas. UK Ancestry visa is a major route for Zimbabweans of British-born grandparent descent (Commonwealth route — 5-year work-permitting visa leading to ILR). The substantial Zimbabwean diaspora in the UK (~250k+) supports family-reunification pipelines. South Africa is the dominant labour-market destination for outbound Zimbabwean migration; UK and Australia secondary.`,

  MM: `The Myanmar (Burmese) passport sits among the more travel-restricted documents globally, with visa-free or visa-on-arrival entry to ~40 destinations — primarily ASEAN partner states (Cambodia, Laos, Vietnam, Indonesia, Brunei) and select Indian Ocean states. Most major destinations require embassy visas. Refusal rates for US B-1/B-2 and Schengen short-stay are elevated for Burmese applicants. Long-stay migration via UK Skilled Worker (healthcare), Australia Subclass 482, US H-1B / family-reunification, and Thailand Non-Imm B (substantial Burmese workforce in Thai construction + factories). Myanmar's political situation since 2021 has constrained both inbound and outbound mobility through embassy closures.`,

  KH: `The Cambodian passport offers visa-free or visa-on-arrival entry to ~55 destinations, primarily ASEAN free-movement partners (Thailand, Vietnam, Laos, Myanmar, Indonesia, Brunei, Singapore, Malaysia, Philippines — 14 to 30 days), Hong Kong, Macau, and several African / Caribbean states. The US, UK, Schengen, Canada, Australia, Japan, and South Korea require embassy visas. Long-stay routes use UK Skilled Worker (hospitality, healthcare), Australia Subclass 482, US H-1B, and Korean E-7/E-9 (Employment Permit System for blue-collar workers). The Cambodian-American community ~330k supports family-reunification migration.`,

  LA: `The Lao passport offers visa-free or visa-on-arrival entry to ~50 destinations, primarily ASEAN free-movement partners (Thailand, Vietnam, Cambodia, Myanmar — 14 to 30 days), Hong Kong (90 days visa-free), and several Indian Ocean states. The US, UK, Schengen, Canada, Australia, Japan, and South Korea require embassy visas. Long-stay routes primarily use Thai work permits (substantial Lao workforce in Thai agriculture + construction) and the Korean E-9 EPS. Lao-American community ~262k (descendants of Vietnam War refugees) supports family-reunification migration via I-130 petitions.`,

  AF: `The Afghan passport ranks at or near the bottom of global passport mobility indexes. Visa-free or visa-on-arrival entry covers fewer than 30 destinations, primarily in the post-Soviet space and a small number of Africa and Indian Ocean states. All major Western destinations require embassy visas with very high refusal rates. The 2021 humanitarian crisis triggered extraordinary protection schemes in the US (Operation Allies Welcome / SIV), UK (ARAP / ACRS), Canada (special-measures), Germany (Federal Admission Programme), and Australia (Afghan Locally-Engaged Employees programme). Outside these schemes, long-stay migration is constrained — most Afghans approach via asylum routes.`,

  IR: `The Iranian passport sits among the more travel-restricted documents globally, with visa-free or visa-on-arrival entry to ~40 destinations primarily in Latin America (Venezuela, Bolivia, Ecuador), the Caucasus (Armenia, Georgia until 2024 tightening), and parts of Africa. Most major Western destinations require embassy visas; sanctions-related complications affect Iranian applications for the US (since 2017 travel ban revisions), UK, EU, Canada, Australia, Japan. Long-stay migration via embassy visas faces enhanced scrutiny + extended administrative processing. Substantial Iranian diaspora in the US (Los Angeles especially), Canada (Toronto + Vancouver), Germany, UK, and Australia supports family-reunification routes.`,

  IQ: `The Iraqi passport offers visa-free or visa-on-arrival entry to ~30 destinations, primarily in select Middle Eastern + Latin American states. Most major destinations including the US, UK, Schengen, Canada, Australia, China, and Japan require embassy visas. UK Skilled Worker, Canada Express Entry, US Special Immigrant Visa (SIV — for Iraqi-allied wartime employees), Germany Federal Admission Programme, and Australia humanitarian visas have all been used substantially since 2014. The Iraqi diaspora in the US (Detroit, San Diego), UK, Sweden, Germany, and Jordan supports both family-reunification and humanitarian-resettlement pipelines.`,

  LB: `The Lebanese passport offers visa-free or visa-on-arrival entry to ~40 destinations, primarily Latin America (Venezuela, Brazil, Ecuador), select African states, and a small number of Caribbean and Pacific islands. Most major destinations including the US, UK, Schengen, Canada, Australia, and Japan require embassy visas. The substantial Lebanese diaspora in Brazil (~7M people of Lebanese descent), Argentina, France, the US, Canada, and Australia supports both family-reunification and heritage-citizenship routes. France's Lebanese-French historical ties simplify some long-stay arrangements via Talent Passport + Visiteur visas. UK Skilled Worker (healthcare especially) is an active employment route.`,

  BY: `The Belarusian passport offers visa-free or visa-on-arrival entry to ~70 destinations including the post-Soviet space (Russia, Armenia, Kazakhstan, Kyrgyzstan — labour-market access under EAEU), Türkiye (90 days), Israel, the UAE, and most of South America. The EU suspended visa-free arrangements for Belarus in 2022; Schengen short-stay now requires an embassy visa with extended administrative processing. UK, US, Canada, Australia, and Japan all require embassy visas. Long-stay migration to EU member states (especially Poland and Lithuania, which run extraordinary humanitarian schemes for Belarusian opposition figures), the US, and Canada has accelerated since 2020.`,

  MD: `The Moldovan passport — since the 2014 EU visa liberalisation — grants Schengen 90/180 visa-free entry (ETIAS from late 2026), plus UK (6-month visa-free), Israel, Türkiye, Western Balkans, and most of Latin America. The US, Canada, Australia, and Japan still require embassy visas. Moldova's EU candidacy (granted 2022) has deepened mobility for educational and skilled-worker pipelines into Romania, Poland, Germany, Italy. Romanian citizenship is available to Moldovans on demonstration of Romanian-language proficiency + Romanian-ancestry connection — historically a major route into the EU for ethnic-Romanian Moldovans.`,

  AL: `The Albanian passport — since the 2010 Schengen visa liberalisation — grants 90/180 visa-free entry to the Schengen Area (ETIAS from late 2026), plus the UK (6-month visa-free since 2024 ETA rollout exemption review), Türkiye (90 days), most of the Western Balkans + Latin America. The US, Canada, Australia, and Japan still require embassy visas. Italy in particular has historically been the dominant long-stay destination for Albanians (substantial Italian-Albanian community); Greece + Germany follow. EU candidacy and the Western Balkans 2024 Growth Plan support deepened economic integration. UK Skilled Worker (healthcare, construction) and Canada Express Entry are growing routes.`,

  BA: `The Bosnia and Herzegovina passport — since the 2010 Schengen visa liberalisation — grants 90/180 visa-free entry to the Schengen Area (ETIAS from late 2026), plus the UK (6-month visa-free), Türkiye (90 days), most of the Western Balkans, and most of Latin America. The US, Canada, Australia, and Japan require embassy visas. Germany hosts the largest Bosnian diaspora outside Bosnia (~370k), with Austrian and Slovenian communities also substantial. UK Skilled Worker (healthcare, construction, hospitality) is an active employment route. EU candidacy (granted 2022) is in early stages; mobility deepening expected through accession.`,

  RS: `The Serbian passport — since the 2010 Schengen visa liberalisation — grants 90/180 visa-free entry to Schengen Area (ETIAS from late 2026), plus the UK (6-month visa-free), Türkiye (90 days), Russia (30 days, longstanding bilateral), China (30 days mutual visa-free since 2017 — the only European country with this arrangement), and most of Latin America. The US, Canada, Australia, and Japan require embassy visas. EU candidacy ongoing. Substantial Serbian diaspora in Germany, Austria, Switzerland, Australia, US, and Canada supports family-reunification migration. The unique Russia + China mutual visa-free arrangements make Belgrade a hub for travellers seeking those routes.`,

  MK: `The North Macedonian passport — since the 2010 Schengen visa liberalisation — grants 90/180 visa-free entry to Schengen Area (ETIAS from late 2026), plus the UK (6-month visa-free), Türkiye (90 days), most of the Western Balkans, and most of Latin America. The US, Canada, Australia, and Japan require embassy visas. EU candidacy (since 2005) continues; full accession blocked historically by Greek + Bulgarian disputes (Greek dispute resolved 2019; Bulgarian dispute over historical/linguistic claims pending). The North Macedonian community in Germany, Switzerland, Italy, US, and Australia supports family-reunification migration. UK Skilled Worker (healthcare, construction) is an active route.`,

  AZ: `The Azerbaijani passport offers visa-free or visa-on-arrival entry to ~75 destinations including most of the post-Soviet space (Russia, Belarus, Armenia, Kazakhstan, Kyrgyzstan, Türkiye, Iran, Israel), the GCC states (UAE 30 days), and most of Latin America. The US, UK, Schengen, Canada, Australia, and Japan require embassy visas. CIS labour-market access supports substantial Azerbaijani-Russian working relationships. Long-stay migration to the West uses UK Skilled Worker, Canada Express Entry, the US H-1B, and Germany Blue Card. Azerbaijan's strategic relationships with Türkiye + Israel + UAE support frequent business travel.`,

  BS: `The Bahamian passport offers visa-free or visa-on-arrival entry to ~155 destinations including the Schengen Area (90/180, with ETIAS from late 2026), the UK (6 months visa-free), Canada (eTA), Hong Kong, Singapore, Japan, and most of CARICOM under the Single Market and Economy framework. The US requires a B1/B2 visa despite the geographic proximity. CARICOM Skilled National scheme supports residence + work rights across 12 Caribbean member states. CBI / golden-residence programmes — Bahamas is not a CBI seller but a beneficiary nation for ultra-high-net-worth global mobility. Cayman + Bermuda + BVI labour markets accessible via OCT (Overseas Country and Territory) arrangements.`,
};

export function passportIntroFor(iso2: string): string | undefined {
  return PASSPORT_INTROS[iso2.toUpperCase()];
}
