/**
 * Horizontal-scroll rail of recent visa updates. Surfaces the data
 * from src/data/recent_updates.json (generated by buildRecentUpdates
 * and refreshed nightly) on the homepage so users see at-a-glance
 * "this site is alive + visa rules just changed" rather than having
 * to discover /updates from a footer link.
 *
 * Editorial pattern (like a news ticker but slow + clickable):
 *   - 4-5 cards visible on desktop, snap-scroll horizontally on tablet+
 *   - Each card shows: destination flag, kind (fee fix / new visa /
 *     catalogue change), 1-line headline, date
 *   - Cards link to /destination/{iso2} so the click leads to the
 *     current rules, not just a description of the change
 *   - "See all →" link to /updates closes the rail
 *
 * Returns null gracefully when there are no recent updates — the
 * homepage doesn't show an empty band.
 */
import Link from "next/link";
import { flagEmoji } from "@/lib/countries";
import data from "@/data/recent_updates.json";

type Update = {
  kind: "adapter_change" | "new_adapter" | "fee_correction";
  date: string;
  destinationIso2: string | null;
  destinationName: string | null;
  title: string;
  detail: string;
  sourceSha?: string;
};

type Payload = {
  generatedAt: string;
  windowDays: number;
  updates: Update[];
};

const KIND_LABEL: Record<Update["kind"], string> = {
  adapter_change: "Catalogue updated",
  new_adapter: "New destination",
  fee_correction: "Fee corrected",
};

const KIND_TONE: Record<Update["kind"], string> = {
  adapter_change:
    "bg-blue-50 text-blue-900 dark:bg-blue-950/40 dark:text-blue-100 ring-1 ring-blue-200/50 dark:ring-blue-900",
  new_adapter:
    "bg-emerald-50 text-emerald-900 dark:bg-emerald-950/40 dark:text-emerald-100 ring-1 ring-emerald-200/50 dark:ring-emerald-900",
  fee_correction:
    "bg-amber-50 text-amber-900 dark:bg-amber-950/40 dark:text-amber-100 ring-1 ring-amber-200/50 dark:ring-amber-900",
};

function relativeDay(iso: string): string {
  const d = new Date(iso);
  const now = new Date();
  const days = Math.floor((now.getTime() - d.getTime()) / 86_400_000);
  if (days <= 0) return "today";
  if (days === 1) return "yesterday";
  if (days < 7) return `${days} days ago`;
  if (days < 30) return `${Math.floor(days / 7)} week${Math.floor(days / 7) === 1 ? "" : "s"} ago`;
  return `${Math.floor(days / 30)} month${Math.floor(days / 30) === 1 ? "" : "s"} ago`;
}

export function RecentUpdatesRail() {
  const payload = data as Payload;
  if (!payload.updates || payload.updates.length === 0) return null;

  const recent = [...payload.updates]
    .sort((a, b) => b.date.localeCompare(a.date))
    .slice(0, 8);

  return (
    <section
      aria-labelledby="recent-updates-heading"
      className="border-t border-b border-[var(--color-rule)] bg-[var(--color-muted)]/30 py-8 sm:py-10"
    >
      <div className="mx-auto max-w-6xl px-4">
        <div className="flex items-baseline justify-between gap-4 flex-wrap mb-5">
          <div>
            <p className="kicker">Visa news</p>
            <h2
              id="recent-updates-heading"
              className="serif-display text-xl sm:text-2xl mt-1 font-medium"
            >
              Recent visa-rule changes
            </h2>
            <p className="text-sm text-[var(--color-ink-muted)] mt-1">
              Policy + fee updates from the last 30 days, pulled from our adapter commits.
            </p>
          </div>
          <Link
            href="/updates"
            className="text-sm font-medium text-[var(--color-ink)] hover:opacity-80 underline-offset-2 hover:underline shrink-0"
          >
            See all news →
          </Link>
        </div>

        {/* Horizontal scroll on mobile, grid on desktop. snap-x on touch
            so each card "clicks" into view on swipe; desktop gets 4
            cards visible side-by-side. */}
        <ul
          role="list"
          className="
            flex gap-3 overflow-x-auto snap-x snap-mandatory
            pb-2 -mx-4 px-4
            sm:grid sm:grid-cols-2 lg:grid-cols-4 sm:gap-4 sm:overflow-visible sm:m-0 sm:p-0
          "
        >
          {recent.slice(0, 8).map((u, i) => {
            const href = u.destinationIso2
              ? `/destination/${u.destinationIso2.toLowerCase()}`
              : "/updates";
            return (
              <li
                key={`${u.date}-${u.title}-${i}`}
                className="snap-start shrink-0 w-72 sm:w-auto"
              >
                <Link
                  href={href}
                  className="
                    block h-full rounded-xl border border-[var(--color-rule)]
                    bg-[var(--color-paper-elev)] p-4 shadow-sm
                    hover:border-[var(--color-ink)] hover:shadow-md
                    transition group
                  "
                >
                  <div className="flex items-start justify-between gap-2 mb-2">
                    <span
                      className={`text-[10px] uppercase tracking-[0.14em] font-semibold px-2 py-0.5 rounded ${KIND_TONE[u.kind]}`}
                    >
                      {KIND_LABEL[u.kind]}
                    </span>
                    {u.destinationIso2 && (
                      <span className="text-xl leading-none" aria-hidden>
                        {flagEmoji(u.destinationIso2)}
                      </span>
                    )}
                  </div>
                  <p className="text-sm font-medium text-[var(--color-ink)] leading-snug mb-2 group-hover:underline underline-offset-2 decoration-[var(--color-rule-strong)]">
                    {u.title}
                  </p>
                  <p className="text-xs text-[var(--color-ink-muted)] line-clamp-2 leading-relaxed mb-3">
                    {u.detail}
                  </p>
                  <p className="text-[10px] text-[var(--color-ink-muted)] uppercase tracking-wide tabular-nums">
                    {relativeDay(u.date)}
                  </p>
                </Link>
              </li>
            );
          })}
        </ul>
      </div>
    </section>
  );
}
