/**
 * Destination visa-category coverage — batch 1.
 *
 * Closes the worst gaps in the top-20 coverage audit (audit/COVERAGE_*.md):
 *
 *   EG Egypt (was 10 — 0 work/study/family/business)
 *   MA Morocco (was 7 — 0 work/study/family/business)
 *   MX Mexico (was 9 — 0 family, 2 work)
 *   TR Türkiye (was 10 — 1 work, 0 study, 0 business)
 *   GR Greece (was 10 — 0 study, 0 business)
 *
 * Each destination gets 5–8 hand-curated visa categories with realistic fees,
 * processing times, requirements, and source-document links. Same shape as
 * the in_visa_categories.ts pattern that took JP→IN from 2 to 10 options.
 *
 * Refresh quarterly. Fees + thresholds revise periodically.
 */
import type { Adapter } from "../base/Adapter";
import { buildDestinationAdapter } from "./_destinationCategoryFactory";

// ═══════════════════════════════════════════════════════════════════════════
// EGYPT
// ═══════════════════════════════════════════════════════════════════════════
const EG_SOURCE = "https://www.moiegypt.gov.eg/";
const EG_MFA = "https://www.mfa.gov.eg/";
const EG_EVISA = "https://www.visa2egypt.gov.eg/";
const EG_INVEST = "https://www.gafi.gov.eg/English/";

export const egyptVisaCategoriesAdapter: Adapter = buildDestinationAdapter({
  id: "eg_visa_categories",
  iso2: "EG",
  name: "Egypt visa categories — Work, Student, Family, Business, Investor, Retirement",
  primaryUrls: [EG_SOURCE, EG_MFA, EG_EVISA],
  fixturePath: "src/scrapers/sources/__fixtures__/eg_visa_categories.json",
  categories: [
    {
      label: "Work Permit (Tasreeh Amal) — Egypt",
      finderGoals: ["live_work"],
      purpose: "work",
      status: "embassy_visa",
      maxStayDays: 365,
      validityDays: 365,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      onwardTicketRequired: false,
      proofOfFundsRequired: false,
      proofOfAccommodationRequired: false,
      biometricsRequired: true,
      biometricsLocation: "Egyptian Ministry of Manpower regional office",
      requirements: [
        "Job offer + employment contract from a registered Egyptian employer",
        "Employer's Manpower Office application (Form 6) + commercial registration",
        "Foreign-worker quota verification — 10% cap of total workforce (some sectors 25%)",
        "Notarised + apostilled qualifications + work-experience proof",
        "Negative HIV / Hepatitis B+C test at an approved Egyptian lab",
        "Egyptian residence-permit registration within 7 days of arrival",
      ],
      processingTimeDaysMin: 30,
      processingTimeDaysMax: 90,
      applicationUrl: EG_MFA,
      primarySourceUrl: "https://www.manpower.gov.eg/",
      fees: [
        { amountMinor: 600000, currency: "EGP", label: "Work permit fee (EGP 6,000)" },
        { amountMinor: 300000, currency: "EGP", label: "Residence permit (annual)", kind: "service" },
      ],
      notes: "Work permits are employer-sponsored via the Ministry of Manpower; foreigners can be no more than 10% of an employer's workforce (some sectors permit 25%). Renewable annually. Highest-paid foreign workers are typically in petroleum, gas, education, and tourism management.",
      purposeMetadata: { sponsorshipRequired: true, jobOfferRequired: true, routeToSettlement: false },
    },
    {
      label: "Student Residence Permit — Egypt",
      finderGoals: ["study"],
      purpose: "study",
      status: "embassy_visa",
      maxStayDays: 365 * 4,
      validityDays: 365,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      biometricsLocation: "Mogamma El Tahrir or regional immigration office",
      requirements: [
        "Admission letter from a recognised Egyptian university (Cairo, Alexandria, Ain Shams, AUC, Al-Azhar, GUC)",
        "Proof of financial means — typically USD 5,000–10,000/year tuition + living",
        "Birth certificate + secondary-school certificate, apostilled + translated to Arabic",
        "Renewable annually for the duration of the academic programme",
        "Al-Azhar enrolments process via the Al-Azhar Foreign Students Bureau (separate from general MoHE)",
      ],
      processingTimeDaysMin: 14,
      processingTimeDaysMax: 60,
      applicationUrl: EG_MFA,
      primarySourceUrl: "https://www.mohesr.gov.eg/",
      fees: [
        { amountMinor: 25000, currency: "USD", label: "Student visa (annual, USD 250)" },
      ],
      notes: "Egypt is a major regional education destination — particularly for Arabic-language studies, Islamic studies (Al-Azhar), medicine (English-medium at AUC, GUC), and engineering. Tuition for international undergrad is typically USD 3,000–8,000/year at public universities, USD 10,000–20,000 at private/American universities.",
      purposeMetadata: { financialProofMonthlyMinor: 50000, financialProofCurrency: "USD" },
    },
    {
      label: "Family Reunification Residence — Egypt",
      purpose: "family",
      status: "embassy_visa",
      maxStayDays: 365 * 5,
      validityDays: 365,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      proofOfFundsRequired: true,
      proofOfAccommodationRequired: true,
      biometricsRequired: true,
      requirements: [
        "Marriage certificate (for spouse) OR birth certificate (for child / parent), apostilled + translated to Arabic",
        "Egyptian sponsor must be citizen or holder of permanent residence",
        "Proof of accommodation (rental contract / property deed)",
        "Sponsor's income proof — minimum ~EGP 5,000/month equivalent",
        "5-year residence permit available after 3 years of marriage; permanent residence after 10 years",
      ],
      processingTimeDaysMin: 30,
      processingTimeDaysMax: 90,
      applicationUrl: EG_SOURCE,
      primarySourceUrl: EG_SOURCE,
      fees: [
        { amountMinor: 15000, currency: "USD", label: "Family reunification visa (USD 150)" },
        { amountMinor: 30000, currency: "EGP", label: "Annual residence stamp", kind: "service" },
      ],
      notes: "Egyptian Citizenship Law 26/1975 — foreign wives of Egyptian husbands can naturalise after 2 years of marriage + continuous residence; foreign husbands of Egyptian wives have longer + more restrictive path. Same-sex marriage NOT recognised. Children of mixed marriages: Egyptian father transmits citizenship at birth; Egyptian mother + foreign father since 2004.",
      purposeMetadata: { sponsorIncomeThresholdMinor: 500000, sponsorIncomeCurrency: "EGP", cohabitationProofRequired: true },
    },
    {
      label: "Business / Investor Visa — Egypt",
      finderGoals: ["invest"],
      purpose: "business",
      status: "embassy_visa",
      maxStayDays: 90,
      validityDays: 365,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      requirements: [
        "Letter of invitation from Egyptian business partner / GAFI-registered company",
        "Your employer's letter confirming business purpose, financial responsibility, and your return",
        "Bank statements (last 6 months)",
        "Multi-year (5-year) business visa available for repeat business travellers from major economies",
      ],
      processingTimeDaysMin: 5,
      processingTimeDaysMax: 14,
      applicationUrl: EG_INVEST,
      primarySourceUrl: EG_INVEST,
      fees: [
        { amountMinor: 6000, currency: "USD", label: "Business multi-entry visa (USD 60)" },
      ],
      notes: "GAFI (General Authority for Investment) is the one-stop shop for foreign investors. Major incentives: tax exemptions in Free Zones (Suez Canal Economic Zone, Damietta, Port Said), 100% foreign ownership permitted across most sectors since the 2017 Investment Law.",
    },
    {
      label: "Real-Estate Residence Permit — Egypt",
      finderGoals: ["invest"],
      purpose: "family",
      status: "embassy_visa",
      maxStayDays: 365 * 5,
      validityDays: 365 * 5,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      requirements: [
        "Property purchase value USD 50,000+ (1-year), USD 100,000+ (3-year), USD 200,000+ (5-year)",
        "Property must be registered with the Egyptian Real Estate Publicity Department",
        "USD payment via wire transfer through an Egyptian bank (no cash)",
        "Renewable + extendable based on continued ownership",
        "Naturalisation eligibility: USD 300,000+ deposit OR USD 500,000+ investment + 5 years residence",
      ],
      processingTimeDaysMin: 30,
      processingTimeDaysMax: 90,
      applicationUrl: EG_INVEST,
      primarySourceUrl: EG_INVEST,
      fees: [
        { amountMinor: 3000, currency: "USD", label: "Residence permit fee (USD 30)" },
      ],
      notes: "Egypt's property-residence programme launched 2018 (Cabinet Decree 7/2018), revised 2022 to tier the property thresholds. Particularly popular with Sudanese, Saudi, Emirati, Russian and Italian buyers. Cairo (New Capital, Sheikh Zayed, Maadi), Alexandria, and Red Sea resorts (Hurghada, Sharm El-Sheikh, El Gouna) are the dominant markets.",
    },
  ],
});

// ═══════════════════════════════════════════════════════════════════════════
// MOROCCO
// ═══════════════════════════════════════════════════════════════════════════
const MA_SOURCE = "https://www.dgsn.gov.ma/";
const MA_MFA = "https://www.consulat.ma/";
const MA_INVEST = "https://www.amdie.gov.ma/";

export const moroccoVisaCategoriesAdapter: Adapter = buildDestinationAdapter({
  id: "ma_visa_categories",
  iso2: "MA",
  name: "Morocco visa categories — Salaried Worker, Self-Employed, Student, Family, Retiree, Investor",
  primaryUrls: [MA_SOURCE, MA_MFA, MA_INVEST],
  fixturePath: "src/scrapers/sources/__fixtures__/ma_visa_categories.json",
  categories: [
    {
      label: "Carte de Séjour Salarié (Salaried Worker) — Morocco",
      finderGoals: ["live_work"],
      purpose: "work",
      status: "embassy_visa",
      maxStayDays: 365,
      validityDays: 365,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      biometricsRequired: true,
      biometricsLocation: "Service des Étrangers, Préfecture de Police",
      requirements: [
        "Employment contract approved by ANAPEC (the labour-market priority test must clear — no Moroccan candidate available)",
        "Employer's commercial registration + tax compliance certificate",
        "Notarised + apostilled diplomas + work experience",
        "Health certificate from approved Moroccan clinic",
        "Apply within 90 days of arrival at the Bureau des Étrangers of the local Préfecture",
        "Renewable annually; eligible for 10-year card after 4 years of legal residence",
      ],
      processingTimeDaysMin: 30,
      processingTimeDaysMax: 90,
      applicationUrl: MA_SOURCE,
      primarySourceUrl: "https://www.anapec.org/",
      fees: [
        { amountMinor: 10000, currency: "MAD", label: "Carte de Séjour (annual, MAD 100)" },
        { amountMinor: 30000, currency: "MAD", label: "ANAPEC employment contract approval fee", kind: "service" },
      ],
      notes: "Morocco's labour-market priority test (ANAPEC) is the gating factor — employer must demonstrate they couldn't find a qualified Moroccan within ~30 days. Strategic sectors (offshoring, automotive, aerospace, renewable energy) get expedited approval. Working without a Carte de Séjour Salarié is a deportation offence — overstays trigger MAD 500/day fines.",
      purposeMetadata: { sponsorshipRequired: true, jobOfferRequired: true, routeToSettlement: true },
    },
    {
      label: "Carte de Séjour Étudiant (Student) — Morocco",
      finderGoals: ["study"],
      purpose: "study",
      status: "embassy_visa",
      maxStayDays: 365 * 5,
      validityDays: 365,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      requirements: [
        "Admission letter from a recognised Moroccan institution (Mohammed V University Rabat, Cadi Ayyad Marrakech, Hassan II Casablanca, Al Akhawayn Ifrane, Mundiapolis, ENSA…)",
        "Proof of MAD 5,000+/month equivalent in financial means",
        "Birth certificate apostilled + translated to French or Arabic",
        "Renewable annually for the duration of the academic programme",
        "Limited part-time work permitted via separate authorisation",
      ],
      processingTimeDaysMin: 14,
      processingTimeDaysMax: 60,
      applicationUrl: MA_MFA,
      primarySourceUrl: "https://www.enssup.gov.ma/",
      fees: [
        { amountMinor: 10000, currency: "MAD", label: "Carte de Séjour étudiant (annual, MAD 100)" },
      ],
      notes: "Tuition is among the lowest in the Mediterranean — public universities MAD 3,000–10,000/year (~USD 300–1,000), private universities MAD 30,000–80,000/year. AMCI (Agence Marocaine de Coopération Internationale) scholarships available for Sub-Saharan African students. Al Akhawayn Ifrane is the American-curriculum English-medium private option.",
    },
    {
      label: "Carte de Séjour Conjoint de Marocain (Spouse of Moroccan) — Morocco",
      purpose: "family",
      status: "embassy_visa",
      maxStayDays: 365 * 5,
      validityDays: 365,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      biometricsRequired: true,
      requirements: [
        "Marriage certificate notarised + apostilled + translated to Arabic",
        "Moroccan spouse's identity card (CIN) + family book (Livret de Famille)",
        "Proof of accommodation (rental contract or property deed)",
        "Sponsor's income proof — typically MAD 5,000+/month",
        "10-year card available after 5 years of marriage + continuous residence",
        "Naturalisation: foreign wife of Moroccan citizen after 5 years of marriage; foreign husband after 10 years",
      ],
      processingTimeDaysMin: 30,
      processingTimeDaysMax: 90,
      applicationUrl: MA_SOURCE,
      primarySourceUrl: MA_SOURCE,
      fees: [
        { amountMinor: 10000, currency: "MAD", label: "Family residence permit (annual, MAD 100)" },
      ],
      notes: "Morocco's Family Code (Mudawana) 2004 reform substantially expanded foreign spouses' rights. Same-sex marriage NOT recognised (homosexual acts criminalised under Article 489 of the Penal Code). Children of Moroccan parent (mother since 2007 reform; previously father-only) acquire Moroccan citizenship at birth.",
      purposeMetadata: { sponsorIncomeThresholdMinor: 500000, sponsorIncomeCurrency: "MAD", cohabitationProofRequired: true },
    },
    {
      label: "Carte de Séjour Visiteur — Retiree / Passive Income — Morocco",
      finderGoals: ["retire"],
      purpose: "family",
      status: "embassy_visa",
      maxStayDays: 365 * 10,
      validityDays: 365,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      requirements: [
        "Verifiable passive income: pension / annuity / rental / dividends — MAD 5,000–15,000+/month equivalent",
        "Proof of accommodation (rental contract or property deed)",
        "Private health insurance covering Morocco",
        "Apply at the Préfecture de Police local Bureau des Étrangers within 90 days of arrival",
        "Renewable annually; eligible for 10-year card after 4 years of legal residence",
        "Tax-resident status from day 183 — Morocco grants 50% personal income-tax exemption on foreign pensions remitted (popular with French + Belgian retirees)",
      ],
      processingTimeDaysMin: 30,
      processingTimeDaysMax: 90,
      applicationUrl: MA_SOURCE,
      primarySourceUrl: MA_SOURCE,
      fees: [
        { amountMinor: 10000, currency: "MAD", label: "Visitor residence (annual, MAD 100)" },
      ],
      notes: "Morocco's retirement / passive-income route is a quiet alternative to Spain NLV + Portugal D7 — much cheaper cost of living, French + Spanish + Arabic widely spoken, Mediterranean climate. Marrakech, Essaouira, Tangier, Agadir, Casablanca are the dominant expat enclaves. The 50% pension tax exemption (Code Général des Impôts Article 76) materially boosts net retirement income.",
    },
    {
      label: "Carte de Séjour Travail Indépendant (Self-Employed) — Morocco",
      finderGoals: ["live_work"],
      purpose: "work",
      status: "embassy_visa",
      maxStayDays: 365,
      validityDays: 365,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      requirements: [
        "Registered Moroccan business (SARL — Société à Responsabilité Limitée — typical; or self-employed registration)",
        "Minimum capital MAD 100,000 (SARL) — paid into Moroccan bank",
        "Tax registration with DGI (Direction Générale des Impôts)",
        "CNSS (social security) enrolment",
        "Business plan + projected revenue / employment creation",
        "Renewable annually based on continued business activity",
      ],
      processingTimeDaysMin: 60,
      processingTimeDaysMax: 120,
      applicationUrl: MA_INVEST,
      primarySourceUrl: MA_INVEST,
      fees: [
        { amountMinor: 10000, currency: "MAD", label: "Self-employed residence (annual, MAD 100)" },
        { amountMinor: 600000, currency: "MAD", label: "SARL formation fees (approx)", kind: "service" },
      ],
      notes: "Casablanca Finance City (CFC) status offers Moroccan + foreign professionals + companies in finance / consulting / IT enhanced tax benefits — 20-year 0% corporate-tax holiday for export-oriented operations. Popular with French + Swiss + Spanish independents relocating to Casablanca + Marrakech.",
    },
    {
      label: "Tourism Visit Visa — Morocco (visa nationals)",
      purpose: "business",
      status: "embassy_visa",
      maxStayDays: 90,
      validityDays: 90,
      entriesAllowed: "single",
      passportValidityMonthsRequired: 6,
      onwardTicketRequired: true,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      requirements: [
        "Letter of invitation from Moroccan business partner OR hotel booking confirmation",
        "Bank statements (last 3 months) — minimum MAD 1,000/day of stay equivalent",
        "Return flight ticket",
        "Travel insurance",
      ],
      processingTimeDaysMin: 5,
      processingTimeDaysMax: 14,
      applicationUrl: MA_MFA,
      primarySourceUrl: MA_MFA,
      fees: [
        { amountMinor: 32000, currency: "MAD", label: "Tourist visa (single-entry, MAD 320)" },
        { amountMinor: 48000, currency: "MAD", label: "Multi-entry (MAD 480)", kind: "service" },
      ],
      notes: "For nationalities not on the visa-exempt list (~60 countries are exempt 90 days). Applications via Moroccan consulate or VFS Global. Nationals of most Sub-Saharan African countries + South + Southeast Asian countries + most of Eastern Europe require this.",
    },
  ],
});

// ═══════════════════════════════════════════════════════════════════════════
// MEXICO
// ═══════════════════════════════════════════════════════════════════════════
const MX_SOURCE = "https://www.inm.gob.mx/";
const MX_SRE = "https://www.gob.mx/sre";
const MX_INVEST = "https://www.gob.mx/se";

export const mexicoVisaCategoriesAdapter: Adapter = buildDestinationAdapter({
  id: "mx_visa_categories",
  iso2: "MX",
  name: "Mexico visa categories — Temporary Resident, Permanent Resident, Work, Student, Family, USMCA",
  primaryUrls: [MX_SOURCE, MX_SRE],
  fixturePath: "src/scrapers/sources/__fixtures__/mx_visa_categories.json",
  categories: [
    {
      label: "Residente Temporal (Temporary Resident) — Mexico",
      finderGoals: ["retire"],
      purpose: "family",
      status: "embassy_visa",
      maxStayDays: 365 * 4,
      validityDays: 365,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      biometricsLocation: "INM regional office in Mexico after consular approval",
      requirements: [
        "ECONOMIC SOLVENCY: ~MXN 71,000+/month verified income (~USD 4,200) over 6–12 months OR MXN 1.16M (~USD 68,000) in bank balances over 12 months",
        "OR property in Mexico worth at least MXN 4.6M (~USD 270,000)",
        "OR family link to Mexican citizen / Mexican permanent resident",
        "OR retirement income (pension / annuity) at the same threshold",
        "Apply at Mexican consulate in country of residence (NOT in Mexico on tourist FMM)",
        "Complete CURP + biometrics at INM regional office within 30 days of arrival",
        "1-year initial; renewable up to 4 years total then must convert to Permanent",
      ],
      processingTimeDaysMin: 14,
      processingTimeDaysMax: 30,
      applicationUrl: MX_SRE,
      primarySourceUrl: MX_SOURCE,
      fees: [
        { amountMinor: 4000, currency: "USD", label: "Temporary Resident visa consular fee (USD 40)" },
        { amountMinor: 740000, currency: "MXN", label: "INM Temporary Resident card (1 year, ~MXN 7,400)", kind: "service" },
      ],
      notes: "Mexico's flagship lifestyle-migration route. Most-used by US + Canadian retirees + remote workers. Renewable up to a 4-year total before conversion to Permanent. Work authorisation can be added with employer petition. Convertible to Permanent Resident after 4 years of legal Temporary residence.",
    },
    {
      label: "Residente Permanente (Permanent Resident) — Mexico",
      finderGoals: ["retire"],
      purpose: "family",
      status: "embassy_visa",
      maxStayDays: 365 * 100,
      validityDays: 365 * 100,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      requirements: [
        "Direct route: ~MXN 175,000+/month income (USD 10,300) over 6–12 months OR MXN 3.5M (~USD 207,000) bank balance over 12 months",
        "Family route: spouse / parent / child of Mexican citizen → 2 years married OR child / parent → direct",
        "Conversion route: 4 years of Temporary Resident → Permanent",
        "Citizenship eligibility: 5 years residence (2 years for spouses of Mexican citizens or those with Mexican children)",
        "Indefinite stay + work rights without sponsor + ability to import household goods + vehicle",
      ],
      processingTimeDaysMin: 14,
      processingTimeDaysMax: 30,
      applicationUrl: MX_SRE,
      primarySourceUrl: MX_SOURCE,
      fees: [
        { amountMinor: 5500, currency: "USD", label: "Permanent Resident visa consular fee (USD 55)" },
        { amountMinor: 740000, currency: "MXN", label: "INM Permanent Resident card (~MXN 7,400)", kind: "service" },
      ],
      notes: "Permanent Residency provides indefinite stay + full work rights + path to citizenship. Mexico permits dual citizenship in practice (though the law nominally requires renunciation). Particularly common for retirees who've passed the 4-year Temporary milestone.",
    },
    {
      label: "Permiso de Trabajo (Work Permit) — Mexico",
      finderGoals: ["live_work"],
      purpose: "work",
      status: "embassy_visa",
      maxStayDays: 365 * 4,
      validityDays: 365,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      biometricsRequired: true,
      biometricsLocation: "INM regional office",
      requirements: [
        "Job offer + employment contract from a Mexican company registered as INM-employer (Constancia de Empleador)",
        "Employer's RFC (tax ID) + IMSS (social security) registration",
        "Notarised + apostilled credentials",
        "Renewable up to 4 years total before conversion to Permanent",
        "USMCA TN-equivalent fast-track for US + Canadian citizens in 60+ specified professions (no labour-market test)",
      ],
      processingTimeDaysMin: 14,
      processingTimeDaysMax: 60,
      applicationUrl: MX_SOURCE,
      primarySourceUrl: MX_SOURCE,
      fees: [
        { amountMinor: 4000, currency: "USD", label: "Work-purpose Temporary Resident visa (USD 40)" },
      ],
      notes: "Most foreign workers in Mexico are in automotive (Toyota / Honda / Nissan / Mazda Bajío region), aerospace (Querétaro), tourism (Yucatán / Quintana Roo), finance (CDMX / Monterrey), and tech (Guadalajara). Tech-sector salaries are MXN 50,000–200,000/month typical.",
      purposeMetadata: { sponsorshipRequired: true, jobOfferRequired: true, routeToSettlement: true },
    },
    {
      label: "Visa de Estudiante (Student) — Mexico",
      finderGoals: ["study"],
      purpose: "study",
      status: "embassy_visa",
      maxStayDays: 365 * 4,
      validityDays: 365,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      requirements: [
        "Admission letter from a recognised Mexican institution (UNAM, Tec de Monterrey, IPN, Universidad Iberoamericana, ITAM, Anáhuac)",
        "Proof of financial means — typically USD 800+/month",
        "Birth certificate + previous-degree certificate, apostilled + translated to Spanish",
        "Renewable annually for the duration of the programme",
        "Limited part-time work permitted via separate authorisation",
      ],
      processingTimeDaysMin: 14,
      processingTimeDaysMax: 30,
      applicationUrl: MX_SRE,
      primarySourceUrl: "https://www.gob.mx/sep",
      fees: [
        { amountMinor: 4000, currency: "USD", label: "Student Temporary Resident visa (USD 40)" },
      ],
      notes: "Mexican universities are popular with Latin American + Spanish + French students. Tec de Monterrey + UNAM are the top-ranked institutions in the LatAm Times Higher Education rankings. Tuition: public universities ~free (UNAM), private USD 10,000–25,000/year.",
      purposeMetadata: { financialProofMonthlyMinor: 80000, financialProofCurrency: "USD" },
    },
    {
      label: "USMCA Business Visitor — Mexico (US + Canadian citizens only)",
      purpose: "business",
      status: "visa_free",
      maxStayDays: 180,
      validityDays: 180,
      entriesAllowed: "single",
      passportValidityMonthsRequired: 6,
      onwardTicketRequired: true,
      requirements: [
        "US or Canadian citizenship",
        "USMCA-defined business activity: meetings, conferences, contract negotiations, intra-company training, technical assistance, after-sales service",
        "PROHIBITED: paid employment, delivery of services to Mexican clients, work for Mexican employer",
        "Stays up to 180 days under FMM (Forma Migratoria Múltiple) — issued at the border",
      ],
      applicationUrl: MX_SOURCE,
      primarySourceUrl: MX_SOURCE,
      fees: [
        { amountMinor: 0, currency: "USD", label: "FMM (free at land borders / included in airfare)" },
      ],
      notes: "USMCA preserved the NAFTA framework for North American business travel — US + Canadians can enter Mexico for permitted business activities for up to 180 days under the standard FMM with no separate visa. For productive work, switch to Work Permit.",
      nationalityFilter: (p) => p === "US" || p === "CA",
    },
    {
      label: "Visa de Negocios (Business) — Mexico (visa-required nationals)",
      purpose: "business",
      status: "embassy_visa",
      maxStayDays: 180,
      validityDays: 180,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      onwardTicketRequired: true,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      requirements: [
        "Letter of invitation from Mexican business partner / company",
        "Your employer's letter confirming business purpose + financial responsibility + return",
        "Bank statements (last 3 months)",
      ],
      processingTimeDaysMin: 5,
      processingTimeDaysMax: 14,
      applicationUrl: MX_SRE,
      primarySourceUrl: MX_SRE,
      fees: [
        { amountMinor: 5000, currency: "USD", label: "Business visa (USD 50)" },
      ],
      notes: "For nationalities not on Mexico's visa-exempt list (~70 nationalities are exempt 180 days under the FMM). Indians, Chinese, Russians, most of Africa + Middle East apply via consulate.",
    },
  ],
});

// ═══════════════════════════════════════════════════════════════════════════
// TÜRKIYE
// ═══════════════════════════════════════════════════════════════════════════
const TR_SOURCE = "https://www.goc.gov.tr/";
const TR_MFA = "https://www.mfa.gov.tr/";
const TR_NVI = "https://www.nvi.gov.tr/";

export const turkeyVisaCategoriesAdapter: Adapter = buildDestinationAdapter({
  id: "tr_visa_categories",
  iso2: "TR",
  name: "Türkiye visa categories — Work, Student, Family, Property Residence, Touristic Residence, Business",
  primaryUrls: [TR_SOURCE, TR_MFA, TR_NVI],
  fixturePath: "src/scrapers/sources/__fixtures__/tr_visa_categories.json",
  categories: [
    {
      label: "Work Permit (Çalışma İzni) — Türkiye",
      finderGoals: ["live_work"],
      purpose: "work",
      status: "embassy_visa",
      maxStayDays: 365,
      validityDays: 365,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      biometricsRequired: true,
      biometricsLocation: "Provincial Directorate of Migration Management",
      requirements: [
        "Job offer + employment contract from Türkiye-registered employer",
        "Employer applies via the Ministry of Family, Labour and Social Services e-Permit system",
        "Foreign-worker quota — typically 1 foreign per 5 Turkish employees (some sectors exempted)",
        "Minimum salary thresholds vary by occupation — typically 1.5×–6.5× minimum wage",
        "Notarised + apostilled credentials",
        "Renewable annually; long-term work permit (5+ years) after 8 years of continuous work permits",
      ],
      processingTimeDaysMin: 30,
      processingTimeDaysMax: 60,
      applicationUrl: "https://ecalisma.csgb.gov.tr/",
      primarySourceUrl: "https://www.csgb.gov.tr/",
      fees: [
        { amountMinor: 76000, currency: "TRY", label: "Work permit (annual, ~TRY 760)" },
      ],
      notes: "Türkiye's work-permit system is employer-sponsored via the Ministry of Family, Labour and Social Services. Common foreign-worker sectors: tourism (Antalya / Bodrum), education (English teachers), construction, healthcare. EU+US+UK+Japan+Korea expatriate professionals concentrated in Istanbul finance + corporate roles.",
      purposeMetadata: { sponsorshipRequired: true, jobOfferRequired: true, routeToSettlement: true },
    },
    {
      label: "Student Residence Permit — Türkiye",
      finderGoals: ["study"],
      purpose: "study",
      status: "embassy_visa",
      maxStayDays: 365 * 5,
      validityDays: 365,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      requirements: [
        "Admission letter from a recognised Turkish institution (Boğaziçi, Bilkent, METU, ITU, Koç, Sabancı)",
        "Pass YÖS (Foreign Student Exam) OR SAT / equivalent for undergrad",
        "Health insurance covering Türkiye",
        "Proof of financial means — TRY 6,000–10,000/month equivalent (~USD 400–700)",
        "Türkiye Bursları (national scholarship) available for international students from select countries",
        "Renewable annually for the duration of the programme",
      ],
      processingTimeDaysMin: 14,
      processingTimeDaysMax: 60,
      applicationUrl: TR_SOURCE,
      primarySourceUrl: "https://www.yok.gov.tr/",
      fees: [
        { amountMinor: 20000, currency: "TRY", label: "Student residence permit (annual)" },
      ],
      notes: "Tuition at public universities: USD 200–1,000/year for international students. Private universities (Bilkent, Koç, Sabancı) USD 5,000–15,000/year. Many programmes in English. Türkiye is a major education destination for African + Central Asian + Balkan students under Türkiye Bursları.",
      purposeMetadata: { financialProofMonthlyMinor: 40000, financialProofCurrency: "USD" },
    },
    {
      label: "Family Residence Permit (Aile İkamet İzni) — Türkiye",
      purpose: "family",
      status: "embassy_visa",
      maxStayDays: 365 * 5,
      validityDays: 365 * 2,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      proofOfFundsRequired: true,
      proofOfAccommodationRequired: true,
      biometricsRequired: true,
      requirements: [
        "Marriage certificate notarised + apostilled + translated to Turkish",
        "Turkish sponsor must be citizen or holder of long-term residence",
        "Proof of accommodation (rental contract or property deed)",
        "Sponsor's income proof — minimum TRY 10,000+/month equivalent",
        "Health insurance",
        "3 years of marriage + continuous residence → naturalisation eligibility",
      ],
      processingTimeDaysMin: 30,
      processingTimeDaysMax: 60,
      applicationUrl: TR_SOURCE,
      primarySourceUrl: TR_NVI,
      fees: [
        { amountMinor: 80000, currency: "TRY", label: "Family residence permit (2-year)" },
      ],
      notes: "Türkiye's family-route is among the most foreigner-friendly in the region. Spouse of Turkish citizen: immediate family residence + naturalisation after 3 years of marriage. Same-sex marriage NOT recognised legally. Children of Turkish-parent automatically Turkish citizens.",
      purposeMetadata: { sponsorIncomeThresholdMinor: 1000000, sponsorIncomeCurrency: "TRY", cohabitationProofRequired: true },
    },
    {
      label: "Touristic Residence Permit — Türkiye",
      finderGoals: ["retire"],
      purpose: "family",
      status: "embassy_visa",
      maxStayDays: 365 * 2,
      validityDays: 365 * 2,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      requirements: [
        "Proof of income — typically USD 500+/month per applicant",
        "Health insurance covering Türkiye",
        "Proof of accommodation (rental contract or property deed)",
        "Apply at Provincial Directorate of Migration Management within 60 days of arrival",
        "Renewable initially 1-year, then 2-year; eligible for long-term residence after 8 years",
      ],
      processingTimeDaysMin: 30,
      processingTimeDaysMax: 60,
      applicationUrl: TR_SOURCE,
      primarySourceUrl: TR_SOURCE,
      fees: [
        { amountMinor: 60000, currency: "TRY", label: "Touristic residence permit (annual, ~TRY 600)" },
      ],
      notes: "Türkiye's quiet retirement / digital-nomad route. Particularly popular with Russian, Iranian, Iraqi, Pakistani, Afghan applicants since 2022. Antalya, Bodrum, Istanbul, Alanya, Mersin are the dominant expat enclaves. NOTE: Restrictions on touristic residence permits in select neighbourhoods (closed districts) since 2022 — verify with the local Migration office.",
    },
    {
      label: "Real-Estate Residence Permit — Türkiye",
      finderGoals: ["invest"],
      purpose: "family",
      status: "embassy_visa",
      maxStayDays: 365 * 2,
      validityDays: 365 * 2,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      requirements: [
        "Property purchase USD 200,000+ (raised from $75,000 in October 2023)",
        "Property valuation by SPK-licensed firm",
        "Title deed (Tapu) with annotation restricting sale for 3 years",
        "Renewable + extendable based on continued ownership",
        "Convertible to CBI (Turkish citizenship) at USD 400,000+ + 3-year hold",
      ],
      processingTimeDaysMin: 30,
      processingTimeDaysMax: 60,
      applicationUrl: TR_SOURCE,
      primarySourceUrl: "https://www.tkgm.gov.tr/",
      fees: [
        { amountMinor: 60000, currency: "TRY", label: "Real-estate residence permit (annual)" },
      ],
      notes: "Real-estate residence permit is a stepping stone to the CBI program — both require SPK valuation + 3-year sale restriction. Particularly common with Iranian, Iraqi, Russian, Chinese, Ukrainian buyers. Istanbul (Beyoğlu, Şişli, Kadıköy, Beylikdüzü), Antalya, Bodrum dominate.",
    },
    {
      label: "Business Visit Visa — Türkiye",
      purpose: "business",
      status: "embassy_visa",
      maxStayDays: 90,
      validityDays: 180,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      onwardTicketRequired: true,
      proofOfFundsRequired: true,
      requirements: [
        "Letter of invitation from Türkiye business partner / Türkiye-registered company",
        "Bank statements (last 3 months)",
        "Travel insurance",
      ],
      processingTimeDaysMin: 5,
      processingTimeDaysMax: 14,
      applicationUrl: TR_MFA,
      primarySourceUrl: TR_MFA,
      fees: [
        { amountMinor: 10000, currency: "USD", label: "Business visa (multi-entry, USD 100)" },
      ],
      notes: "For nationalities not on Türkiye's visa-exempt list (~80 countries visa-free 90 days). Türkiye's geographic position at the EU-MENA-Central Asia crossroads makes Istanbul a major regional business hub — Bagcilar, Maslak, Levent corporate districts.",
    },
  ],
});

// ═══════════════════════════════════════════════════════════════════════════
// GREECE
// ═══════════════════════════════════════════════════════════════════════════
const GR_SOURCE = "https://migration.gov.gr/";
const GR_MFA = "https://www.mfa.gr/";
const GR_INVEST = "https://www.enterprisegreece.gov.gr/";

export const greeceVisaCategoriesAdapter: Adapter = buildDestinationAdapter({
  id: "gr_visa_categories",
  iso2: "GR",
  name: "Greece visa categories — Skilled Worker, Student, Family, Financially Independent, Digital Nomad, Business",
  primaryUrls: [GR_SOURCE, GR_MFA, GR_INVEST],
  fixturePath: "src/scrapers/sources/__fixtures__/gr_visa_categories.json",
  categories: [
    {
      label: "Skilled Worker Visa — Greece",
      finderGoals: ["live_work"],
      purpose: "work",
      status: "embassy_visa",
      maxStayDays: 365 * 2,
      validityDays: 365,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      biometricsRequired: true,
      biometricsLocation: "Greek consulate / Decentralised Administration Office in Greece",
      requirements: [
        "Job offer from Greek-registered employer",
        "Labour-market priority test approval — no EU candidate available for the role",
        "Salary at or above Greek minimum wage for the occupation",
        "Notarised + apostilled credentials",
        "Initial 1-year permit, renewable",
        "Long-term residence after 5 years; Greek citizenship after 7 years",
      ],
      processingTimeDaysMin: 30,
      processingTimeDaysMax: 90,
      applicationUrl: GR_SOURCE,
      primarySourceUrl: GR_SOURCE,
      fees: [
        { amountMinor: 15000, currency: "EUR", label: "Skilled worker permit (annual, EUR 150)" },
      ],
      notes: "Greece's skilled-worker route is employer-sponsored. EU/EEA labour-market priority means most non-EU applicants need a specialist skill profile. Heavy demand in tourism + hospitality (Crete, Rhodes, Mykonos, Santorini), shipping, and IT.",
      purposeMetadata: { sponsorshipRequired: true, jobOfferRequired: true, routeToSettlement: true },
    },
    {
      label: "Student Residence Permit — Greece",
      finderGoals: ["study"],
      purpose: "study",
      status: "embassy_visa",
      maxStayDays: 365 * 5,
      validityDays: 365,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      requirements: [
        "Admission letter from a recognised Greek institution (NKUA Athens, AUTH Thessaloniki, NTUA, Crete)",
        "Proof of EUR 600+/month financial means",
        "Health insurance covering Greece",
        "Birth certificate + diplomas apostilled + translated to Greek",
        "Renewable annually for the duration of the programme",
        "20 hours/week part-time work permitted with separate authorisation",
      ],
      processingTimeDaysMin: 14,
      processingTimeDaysMax: 60,
      applicationUrl: GR_MFA,
      primarySourceUrl: "https://www.minedu.gov.gr/",
      fees: [
        { amountMinor: 15000, currency: "EUR", label: "Student residence permit (annual)" },
      ],
      notes: "Public Greek universities are tuition-free for EU students. Non-EU students pay EUR 1,500–3,000/year at public universities; EUR 4,000–12,000/year at private institutions (Hellenic American University, Mediterranean College). English-taught programmes increasingly common at master's level.",
      purposeMetadata: { financialProofMonthlyMinor: 60000, financialProofCurrency: "EUR" },
    },
    {
      label: "Family Reunification Residence — Greece",
      purpose: "family",
      status: "embassy_visa",
      maxStayDays: 365 * 5,
      validityDays: 365 * 2,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      proofOfFundsRequired: true,
      proofOfAccommodationRequired: true,
      biometricsRequired: true,
      requirements: [
        "Marriage certificate notarised + apostilled + translated to Greek",
        "Greek sponsor must be citizen or holder of permanent residence permit (2+ years held)",
        "Proof of accommodation (rental contract or property deed)",
        "Sponsor's income proof — EUR 8,500/year + EUR 15% per dependent",
        "Spouse of Greek citizen: immediate eligibility, naturalisation after 3 years of marriage + 3 years residence",
      ],
      processingTimeDaysMin: 30,
      processingTimeDaysMax: 60,
      applicationUrl: GR_SOURCE,
      primarySourceUrl: GR_SOURCE,
      fees: [
        { amountMinor: 15000, currency: "EUR", label: "Family residence permit (annual)" },
      ],
      notes: "Greece reformed its family-route in 2014 (Law 4251/2014) and again in 2023 to align with EU Family Reunification Directive. Same-sex marriage recognised since February 2024 — Greece is the first majority-Orthodox state to legalise marriage equality. Greek-descent claim (πολιτογράφηση ομογενών) for diaspora.",
      purposeMetadata: { sponsorIncomeThresholdMinor: 850000, sponsorIncomeCurrency: "EUR", cohabitationProofRequired: true },
    },
    {
      label: "Financially Independent Person (FIP) — Greece",
      finderGoals: ["retire"],
      purpose: "family",
      status: "embassy_visa",
      maxStayDays: 365 * 3,
      validityDays: 365 * 2,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      requirements: [
        "Verifiable passive income — pension / annuity / rental / dividends — minimum EUR 2,000/month for principal applicant (+ 20% per dependent adult, + 15% per child)",
        "Greek bank account with deposit of annual income equivalent",
        "Health insurance covering Greece",
        "Clean criminal record from country of origin",
        "Renewable; eligible for long-term residence after 5 years",
      ],
      processingTimeDaysMin: 30,
      processingTimeDaysMax: 90,
      applicationUrl: GR_SOURCE,
      primarySourceUrl: GR_SOURCE,
      fees: [
        { amountMinor: 100000, currency: "EUR", label: "FIP residence permit (EUR 1,000)" },
      ],
      notes: "Greece's FIP visa is the local Spain-NLV / Portugal-D7 equivalent. Particularly popular with British post-Brexit retirees + American + Australian early retirees seeking the Greek-island lifestyle. Crete, Corfu, Rhodes, the Cyclades are the dominant expat enclaves.",
    },
    {
      label: "Digital Nomad Visa — Greece",
      finderGoals: ["remote_work"],
      purpose: "work",
      status: "embassy_visa",
      maxStayDays: 365 * 2,
      validityDays: 365,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      requirements: [
        "Remote-work contract with foreign employer OR foreign self-employed business",
        "Minimum income EUR 3,500/month gross",
        "Greek-tax-resident treatment from day 183 — 50% income-tax exemption for first 7 years (Law 4758/2020 Article 5C)",
        "Health insurance covering Greece",
        "Renewable to 2-year permit; convertible to long-term residence after 5 years",
      ],
      processingTimeDaysMin: 14,
      processingTimeDaysMax: 60,
      applicationUrl: GR_SOURCE,
      primarySourceUrl: GR_SOURCE,
      fees: [
        { amountMinor: 100000, currency: "EUR", label: "Digital Nomad Visa (EUR 1,000)" },
      ],
      notes: "Greece's Digital Nomad Visa launched 2021 with substantial tax incentives — the 50% personal-income-tax exemption under Article 5C of Law 4758/2020 makes it among the most attractive in the EU. Particularly popular for relocators leaving high-tax UK / France / Germany.",
    },
    {
      label: "Business Visit Visa — Greece (Schengen)",
      purpose: "business",
      status: "embassy_visa",
      maxStayDays: 90,
      validityDays: 180,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 3,
      onwardTicketRequired: true,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      requirements: [
        "Letter of invitation from Greek business partner",
        "Travel insurance EUR 30,000 minimum",
        "Bank statements + employer letter",
        "Multi-entry Schengen visas available (up to 5 years) for frequent business travellers with prior travel history",
      ],
      processingTimeDaysMin: 10,
      processingTimeDaysMax: 21,
      applicationUrl: GR_MFA,
      primarySourceUrl: GR_MFA,
      fees: [
        { amountMinor: 9000, currency: "EUR", label: "Schengen Type C visa (EUR 90)" },
      ],
      notes: "For nationalities not on the Schengen visa-exempt list. Greece's main business hubs: Athens (shipping + finance), Piraeus (Europe's 4th-largest port by tonnage — heavy shipowner presence), Thessaloniki (manufacturing + tech).",
    },
  ],
});
