/**
 * Destination visa-category coverage — batch 2.
 *
 * Closes the next round of top-20 gaps after batch 1:
 *
 *   FR France (was 11 — 0 family, 3 work)
 *   IT Italy (was 11 — 0 business, 1 family)
 *   ID Indonesia (was 11 — 0 family, 0 business, 2 work)
 *   ES Spain (was 12 — 0 business, 1 study, 1 family)
 *   DE Germany (was 13 — 0 business, 1 study, 1 family)
 *
 * Each destination gets 5–7 hand-curated categories filling the missing
 * purpose buckets. Labels are intentionally distinct from existing
 * adapters (Passeport Talent, EU Blue Card, NLV, DNV, Chancenkarte,
 * Skilled Worker, Elective Residence) to avoid duplicate-label collisions
 * with the merge layer.
 *
 * Refresh quarterly. Fees + thresholds revise periodically.
 */
import type { Adapter } from "../base/Adapter";
import { buildDestinationAdapter } from "./_destinationCategoryFactory";

// ═══════════════════════════════════════════════════════════════════════════
// FRANCE
// ═══════════════════════════════════════════════════════════════════════════
const FR_SOURCE = "https://france-visas.gouv.fr/";
const FR_INTERIOR = "https://www.immigration.interieur.gouv.fr/";
const FR_SERVICE = "https://www.service-public.fr/";

export const franceVisaCategoriesAdapter: Adapter = buildDestinationAdapter({
  id: "fr_visa_categories",
  iso2: "FR",
  name: "France visa categories — Salarié, Étudiant, Conjoint, Regroupement Familial, Visiteur, Profession Libérale",
  primaryUrls: [FR_SOURCE, FR_INTERIOR, FR_SERVICE],
  fixturePath: "src/scrapers/sources/__fixtures__/fr_visa_categories.json",
  categories: [
    {
      label: "VLS-TS Salarié (Salaried Worker) — France",
      finderGoals: ["live_work"],
      purpose: "work",
      status: "embassy_visa",
      maxStayDays: 365,
      validityDays: 365,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      biometricsRequired: true,
      biometricsLocation: "French consulate / VFS Global centre",
      requirements: [
        "Job offer + employment contract from French-registered employer",
        "DREETS labour-market priority test approval (no EU candidate available)",
        "Notarised + apostilled credentials",
        "Salary at or above SMIC (~EUR 1,802/month minimum) — typically 1.5×–2× for skilled roles",
        "OFII registration within 3 months of arrival",
        "Long-stay visa equivalent to titre de séjour for first year (VLS-TS) — pas de carte to obtain",
        "Renewable to multi-year card after 1 year; eligible for Carte de Résident after 5 years",
      ],
      processingTimeDaysMin: 30,
      processingTimeDaysMax: 90,
      applicationUrl: FR_SOURCE,
      primarySourceUrl: "https://www.demarches-simplifiees.fr/",
      fees: [
        { amountMinor: 9900, currency: "EUR", label: "VLS-TS Salarié (EUR 99)" },
        { amountMinor: 20000, currency: "EUR", label: "OFII tax (annual)", kind: "service" },
      ],
      notes: "France's standard sponsored work visa, distinct from Passeport Talent (higher-end). Particularly common in retail, hospitality, healthcare, manufacturing roles. Naturalisation eligibility after 5 years of legal residence + B1 French + integration interview.",
      purposeMetadata: { sponsorshipRequired: true, jobOfferRequired: true, routeToSettlement: true },
    },
    {
      label: "VLS-TS Étudiant (Student) — France",
      finderGoals: ["study"],
      purpose: "study",
      status: "embassy_visa",
      maxStayDays: 365 * 5,
      validityDays: 365,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      requirements: [
        "Campus France pre-registration (mandatory for ~70 nationalities incl. US, China, India, Brazil)",
        "Admission letter from a recognised French institution (Sorbonne, Sciences Po, Polytechnique, HEC, ENS, INSEAD)",
        "Proof of financial means — EUR 615/month minimum (Campus France benchmark)",
        "Accommodation evidence (Crous, private rental, or host attestation)",
        "Birth certificate + diploma apostilled + translated to French",
        "Renewable annually; APS (Autorisation Provisoire de Séjour) gives 12-24 months post-study work-search",
        "964 hours/year part-time work permitted",
      ],
      processingTimeDaysMin: 14,
      processingTimeDaysMax: 60,
      applicationUrl: FR_SOURCE,
      primarySourceUrl: "https://www.campusfrance.org/",
      fees: [
        { amountMinor: 9900, currency: "EUR", label: "VLS-TS Étudiant (EUR 99)" },
      ],
      notes: "Public university tuition: EUR 170–380/year (licence), EUR 243–601/year (master's) for non-EU. Private grandes écoles EUR 5,000–20,000+/year. CAF housing subsidy available. French B2 typically required for master's in French; English-taught programmes increasingly common.",
      purposeMetadata: { financialProofMonthlyMinor: 61500, financialProofCurrency: "EUR" },
    },
    {
      label: "VLS-TS Conjoint de Français (Spouse of French Citizen) — France",
      purpose: "family",
      status: "embassy_visa",
      maxStayDays: 365 * 5,
      validityDays: 365,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      biometricsRequired: true,
      requirements: [
        "Marriage certificate notarised + apostilled + translated to French",
        "Proof of cohabitation / communauté de vie (utility bills, joint bank statements, rental contract)",
        "French spouse's ID + family book (Livret de Famille)",
        "Immediate eligibility for 1-year carte de séjour — no French income requirement on the sponsor",
        "Carte de Résident (10-year) after 3 years on the spouse permit",
        "Naturalisation by marriage (Article 21-2): 4 years marriage + continuous residence + B1 French + integration",
      ],
      processingTimeDaysMin: 30,
      processingTimeDaysMax: 90,
      applicationUrl: FR_SOURCE,
      primarySourceUrl: FR_INTERIOR,
      fees: [
        { amountMinor: 22500, currency: "EUR", label: "VLS-TS Conjoint de Français (EUR 225)" },
      ],
      notes: "France's most accessible family route — no income threshold for the sponsoring French spouse (vs UK £29k spouse-visa threshold). Same-sex marriage recognised since 2013. PACS (civil union) also accepted as a basis for residence. Children of mixed marriages get French citizenship at birth if at least one parent is French.",
      purposeMetadata: { cohabitationProofRequired: true },
    },
    {
      label: "Regroupement Familial (Family Reunification) — France",
      purpose: "family",
      status: "embassy_visa",
      maxStayDays: 365 * 5,
      validityDays: 365,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      proofOfAccommodationRequired: true,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      requirements: [
        "Non-EU sponsor must have legally resided in France 18+ months",
        "Suitable accommodation evidence (rental contract + min. surface per occupant)",
        "Stable income at SMIC level (~EUR 1,802/month)",
        "Application via OFII (Office français de l'immigration et de l'intégration)",
        "Spouses + minor children only — adult children + parents excluded",
        "Carte de Résident eligibility after 3 years on the family permit",
      ],
      processingTimeDaysMin: 60,
      processingTimeDaysMax: 180,
      applicationUrl: FR_SOURCE,
      primarySourceUrl: "https://www.ofii.fr/",
      fees: [
        { amountMinor: 30000, currency: "EUR", label: "Regroupement familial (EUR 300)" },
      ],
      notes: "For non-EU residents bringing spouse + minor children. The 18-month prior-residence requirement filters out new arrivals — settled long-term residents only. Refusal grounds: insufficient accommodation surface area (per departmental decree), income below SMIC, public order / national security concerns.",
      purposeMetadata: { sponsorIncomeThresholdMinor: 180200, sponsorIncomeCurrency: "EUR" },
    },
    {
      label: "VLS-TS Visiteur (Long-Stay Visitor / Retirement) — France",
      finderGoals: ["retire"],
      purpose: "family",
      status: "embassy_visa",
      maxStayDays: 365 * 5,
      validityDays: 365,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      requirements: [
        "Verifiable passive income at or above SMIC (~EUR 1,802/month)",
        "Private health insurance covering France",
        "Proof of accommodation (rental contract or property deed)",
        "Engagement de ne pas exercer d'activité professionnelle salariée (commitment not to work as employee)",
        "Renewable annually; Carte de Séjour pluriannuelle after 1 year",
        "Carte de Résident eligibility after 5 years",
      ],
      processingTimeDaysMin: 30,
      processingTimeDaysMax: 90,
      applicationUrl: FR_SOURCE,
      primarySourceUrl: FR_SERVICE,
      fees: [
        { amountMinor: 9900, currency: "EUR", label: "VLS-TS Visiteur (EUR 99)" },
      ],
      notes: "France's retirement / passive-income route. Particularly popular with British, American, Canadian, Belgian retirees relocating to Provence, Côte d'Azur, Aquitaine, Île-de-France. The Visiteur visa explicitly prohibits employed work — for self-employed or remote work, use Profession Libérale or Passeport Talent.",
    },
    {
      label: "VLS-TS Profession Libérale (Self-Employed / Independent) — France",
      finderGoals: ["live_work"],
      purpose: "work",
      status: "embassy_visa",
      maxStayDays: 365,
      validityDays: 365,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      requirements: [
        "Business plan + financial-viability evidence (projected revenue ≥ SMIC)",
        "Professional qualifications recognised for the proposed activity",
        "INSEE / SIRET registration for the French business",
        "URSSAF + tax registration",
        "Substantial initial investment (typically EUR 30,000+ documented)",
        "Renewable annually based on continued activity",
      ],
      processingTimeDaysMin: 60,
      processingTimeDaysMax: 120,
      applicationUrl: FR_SOURCE,
      primarySourceUrl: FR_SERVICE,
      fees: [
        { amountMinor: 9900, currency: "EUR", label: "VLS-TS Profession Libérale (EUR 99)" },
      ],
      notes: "France's freelancer / self-employed long-stay route, distinct from Passeport Talent Entrepreneur (more capital-intensive). Common for consultants, artists, writers, designers, IT freelancers, remote workers with foreign clients.",
    },
    {
      label: "Schengen Type C Business Visa — France",
      purpose: "business",
      status: "embassy_visa",
      maxStayDays: 90,
      validityDays: 180,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 3,
      onwardTicketRequired: true,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      requirements: [
        "Letter of invitation from French business partner + meeting agenda",
        "Travel insurance EUR 30,000 minimum",
        "Bank statements + employer letter",
        "Multi-entry Schengen visas (up to 5 years) for regular business travellers with prior travel history",
      ],
      processingTimeDaysMin: 10,
      processingTimeDaysMax: 21,
      applicationUrl: FR_SOURCE,
      primarySourceUrl: FR_SOURCE,
      fees: [
        { amountMinor: 9000, currency: "EUR", label: "Schengen Type C (EUR 90)" },
      ],
      notes: "For nationalities not on the Schengen visa-exempt list (Indians, Chinese, Russians, most of Africa + Middle East + South Asia). France is the most-used Schengen entry point — Paris-Charles de Gaulle is Europe's second-busiest hub.",
    },
  ],
});

// ═══════════════════════════════════════════════════════════════════════════
// ITALY
// ═══════════════════════════════════════════════════════════════════════════
const IT_SOURCE = "https://vistoperitalia.esteri.it/home/en";
const IT_INTERNO = "https://www.interno.gov.it/it/temi/immigrazione-e-asilo";

export const italyVisaCategoriesAdapter: Adapter = buildDestinationAdapter({
  id: "it_visa_categories",
  iso2: "IT",
  name: "Italy visa categories — Lavoro Subordinato, Studente, Coesione Familiare, Lavoro Autonomo, Digital Nomad, Schengen Business",
  primaryUrls: [IT_SOURCE, IT_INTERNO],
  fixturePath: "src/scrapers/sources/__fixtures__/it_visa_categories.json",
  categories: [
    {
      label: "Visto Tipo D Lavoro Subordinato (Salaried Worker) — Italy",
      finderGoals: ["live_work"],
      purpose: "work",
      status: "embassy_visa",
      maxStayDays: 365 * 2,
      validityDays: 365,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      biometricsRequired: true,
      biometricsLocation: "Italian consulate / Sportello Unico per l'Immigrazione",
      requirements: [
        "Decreto Flussi annual quota (~100,000–500,000 places per year, varies)",
        "Employer's nulla osta from the Sportello Unico per l'Immigrazione (SUI)",
        "Job offer + employment contract from Italian-registered employer",
        "INPS + tax registration",
        "Permesso di soggiorno application within 8 days of arrival at Questura",
        "Renewable up to 2 years; convertible to long-term EU residence after 5 years",
      ],
      processingTimeDaysMin: 60,
      processingTimeDaysMax: 180,
      applicationUrl: IT_SOURCE,
      primarySourceUrl: IT_INTERNO,
      fees: [
        { amountMinor: 11600, currency: "EUR", label: "Permesso di soggiorno (EUR 116)" },
      ],
      notes: "Italy's standard sponsored work route operates via the annual Decreto Flussi quota system — quota slots are released in waves (the 'Click Day') and are oversubscribed within minutes. Strategic sectors (agriculture, tourism, hospitality, caregiving) get preferential allocations. EU Blue Card + Passaporto Talento are higher-end alternatives.",
      purposeMetadata: { sponsorshipRequired: true, jobOfferRequired: true, routeToSettlement: true },
    },
    {
      label: "Visto Tipo D Studio (Student) — Italy",
      finderGoals: ["study"],
      purpose: "study",
      status: "embassy_visa",
      maxStayDays: 365 * 5,
      validityDays: 365,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      requirements: [
        "Pre-enrolment via Universitaly portal + admission letter from a recognised Italian institution (Bocconi, Politecnico Milano, Sapienza, Bologna, Torino)",
        "Proof of EUR 467+/month financial means (~EUR 6,079/year)",
        "Health insurance (private or SSN registration EUR 700/year)",
        "Apostilled + Italian-translated diploma + Dichiarazione di Valore (DV)",
        "Permesso di soggiorno per studio at Questura within 8 days of arrival",
        "Renewable annually; convertible to work visa post-graduation",
      ],
      processingTimeDaysMin: 14,
      processingTimeDaysMax: 60,
      applicationUrl: IT_SOURCE,
      primarySourceUrl: "https://www.studiare-in-italia.it/",
      fees: [
        { amountMinor: 5000, currency: "EUR", label: "Visto Studio (EUR 50)" },
        { amountMinor: 11600, currency: "EUR", label: "Permesso di soggiorno", kind: "service" },
      ],
      notes: "Public university tuition for international students EUR 500–4,000/year (varies by region — lower in southern Italy). Bocconi, Politecnico, LUISS private tuition EUR 15,000–25,000/year. English-taught Master's increasingly common at Bocconi + Politecnico + LUISS. 20 hours/week part-time work permitted.",
      purposeMetadata: { financialProofMonthlyMinor: 46700, financialProofCurrency: "EUR" },
    },
    {
      label: "Visto Tipo D Coesione Familiare (Family Cohesion) — Italy",
      purpose: "family",
      status: "embassy_visa",
      maxStayDays: 365 * 5,
      validityDays: 365 * 2,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      proofOfAccommodationRequired: true,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      requirements: [
        "Sponsor must be Italian citizen / EU national / long-term resident",
        "Income: annual social allowance + EUR 5,989 per dependent",
        "Suitable accommodation evidence (idoneità alloggiativa from local authority)",
        "Marriage certificate / birth certificate apostilled + translated",
        "Spouse of Italian: immediate carta di soggiorno, naturalisation after 2 years marriage + Italian residence (3 years if abroad)",
        "Family Reunification (Ricongiungimento) for spouses + minor children + dependent parents (over 65)",
      ],
      processingTimeDaysMin: 30,
      processingTimeDaysMax: 90,
      applicationUrl: IT_SOURCE,
      primarySourceUrl: IT_INTERNO,
      fees: [
        { amountMinor: 11600, currency: "EUR", label: "Permesso di soggiorno coesione familiare (EUR 116)" },
      ],
      notes: "Italy's family-reunification route is uniquely broad — covers dependent parents over 65 (vs most EU states limiting to minor children + spouse). Spouse-of-Italian path is fastest naturalisation route in the EU (2 years marriage + Italian residence vs 4 in France, 5 in Germany). Same-sex marriage recognised since 2016 via civil unions.",
      purposeMetadata: { sponsorIncomeThresholdMinor: 598900, sponsorIncomeCurrency: "EUR", cohabitationProofRequired: true },
    },
    {
      label: "Visto Tipo D Lavoro Autonomo (Self-Employed) — Italy",
      finderGoals: ["live_work"],
      purpose: "work",
      status: "embassy_visa",
      maxStayDays: 365,
      validityDays: 365,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      requirements: [
        "Business plan + financial-viability evidence",
        "Decreto Flussi quota allocation (limited annual slots)",
        "Camera di Commercio business registration",
        "INPS social-security enrolment",
        "Proof of resources for first year ~EUR 8,500+",
        "Renewable annually based on continued business activity",
      ],
      processingTimeDaysMin: 60,
      processingTimeDaysMax: 180,
      applicationUrl: IT_SOURCE,
      primarySourceUrl: IT_INTERNO,
      fees: [
        { amountMinor: 11600, currency: "EUR", label: "Permesso di soggiorno lavoro autonomo (EUR 116)" },
      ],
      notes: "Italy's self-employed visa is quota-constrained (Decreto Flussi). Common for artists / craftsmen / restaurateurs / consultants / freelance journalists. Investor Visa Italy (separate adapter) is the EUR 250k–2M alternative for capital-intensive applicants.",
    },
    {
      label: "Visto Tipo D Lavoratori Mobili Internazionali (Digital Nomad) — Italy",
      finderGoals: ["remote_work"],
      purpose: "work",
      status: "embassy_visa",
      maxStayDays: 365,
      validityDays: 365,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      requirements: [
        "Annual gross income from foreign employer ~EUR 28,000+ (3× minimum required for permesso)",
        "Health insurance covering Italy",
        "Accommodation in Italy",
        "Clean criminal record",
        "Renewable annually; convertible to long-term residence after 5 years",
        "Italian tax residence from day 183",
      ],
      processingTimeDaysMin: 30,
      processingTimeDaysMax: 90,
      applicationUrl: IT_SOURCE,
      primarySourceUrl: IT_INTERNO,
      fees: [
        { amountMinor: 11600, currency: "EUR", label: "Permesso di soggiorno DNV (EUR 116)" },
      ],
      notes: "Italy's Digital Nomad Visa launched April 2024 (Decree 71/2022, implementation regulations 2024). Particularly attractive due to Italy's Impatriate Regime (Regime degli Impatriati) — 50% income-tax reduction for first 5 years for new fiscal residents who haven't been tax-resident in Italy in prior 3 years.",
    },
    {
      label: "Schengen Type C Business Visa — Italy",
      purpose: "business",
      status: "embassy_visa",
      maxStayDays: 90,
      validityDays: 180,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 3,
      onwardTicketRequired: true,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      requirements: [
        "Letter of invitation from Italian business partner",
        "Trade-fair attendance evidence (Milan Fashion Week, Vinitaly Verona, EICMA Milan, MICAM)",
        "Travel insurance EUR 30,000 minimum",
        "Multi-entry Schengen visas (up to 5 years) for regular business travellers",
      ],
      processingTimeDaysMin: 10,
      processingTimeDaysMax: 21,
      applicationUrl: IT_SOURCE,
      primarySourceUrl: IT_SOURCE,
      fees: [
        { amountMinor: 9000, currency: "EUR", label: "Schengen Type C (EUR 90)" },
      ],
      notes: "For visa-required nationalities. Italy has dense bilateral business chambers — Camera di Commercio Italo-Americana, Italo-Britannica, Italo-Giapponese. Milan + Rome are the major business hubs; Verona + Bologna + Padova lead in trade fairs.",
    },
  ],
});

// ═══════════════════════════════════════════════════════════════════════════
// INDONESIA
// ═══════════════════════════════════════════════════════════════════════════
const ID_SOURCE = "https://www.imigrasi.go.id/";
const ID_EVISA = "https://evisa.imigrasi.go.id/";
const ID_BKPM = "https://www.bkpm.go.id/";

export const indonesiaVisaCategoriesAdapter: Adapter = buildDestinationAdapter({
  id: "id_visa_categories",
  iso2: "ID",
  name: "Indonesia visa categories — Working KITAS, Spouse KITAS, Retirement, Remote Worker E33G, Investor KITAS, B211 Business, Student",
  primaryUrls: [ID_SOURCE, ID_EVISA, ID_BKPM],
  fixturePath: "src/scrapers/sources/__fixtures__/id_visa_categories.json",
  categories: [
    {
      label: "Family KITAS (Spouse / Dependent of Indonesian) — Indonesia",
      purpose: "family",
      status: "embassy_visa",
      maxStayDays: 365 * 2,
      validityDays: 365 * 2,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 12,
      proofOfAccommodationRequired: true,
      biometricsRequired: true,
      biometricsLocation: "Imigrasi regional office in Indonesia",
      requirements: [
        "Marriage certificate notarised + apostilled + translated to Indonesian",
        "Indonesian sponsor's KTP (national ID) + Kartu Keluarga (family card)",
        "Sponsor's bank reference + employment letter",
        "Proof of accommodation (rental contract or property held under nominee)",
        "Initial 1-year permit, renewable to 2-year then 5-year cards",
        "KITAP (permanent stay) after 3 years on Family KITAS + continuous marriage",
      ],
      processingTimeDaysMin: 14,
      processingTimeDaysMax: 30,
      applicationUrl: ID_EVISA,
      primarySourceUrl: ID_SOURCE,
      fees: [
        { amountMinor: 15000, currency: "USD", label: "Family KITAS (USD 150)" },
      ],
      notes: "Indonesia's family route — substantially easier than the work KITAS. Indonesia does NOT generally permit dual citizenship for adults (Constitutional Court ruling 2022 limited dual citizenship to children up to 18). Foreign spouses CAN naturalise after 5 years of legal residence + Bahasa Indonesia + renunciation of foreign citizenship.",
      purposeMetadata: { cohabitationProofRequired: true },
    },
    {
      label: "Retirement Visa (Lansia / Non-Imm) — Indonesia",
      finderGoals: ["retire"],
      purpose: "family",
      status: "embassy_visa",
      maxStayDays: 365 * 5,
      validityDays: 365,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 18,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      requirements: [
        "Aged 55 or older at application",
        "Verifiable pension or annuity income — minimum USD 18,000/year",
        "Property rental contract worth IDR 30M+/month equivalent (~USD 1,900/month)",
        "Private health + life insurance covering Indonesia",
        "Indonesian sponsor (travel agent or sponsor company)",
        "Cannot work; must employ one Indonesian household helper",
        "Initial 1-year permit, renewable up to 5-year cumulative",
      ],
      processingTimeDaysMin: 14,
      processingTimeDaysMax: 30,
      applicationUrl: ID_EVISA,
      primarySourceUrl: ID_SOURCE,
      fees: [
        { amountMinor: 30000, currency: "USD", label: "Retirement Visa (annual, USD 300)" },
      ],
      notes: "Indonesia's retirement visa is popular with Australian, European, Singaporean retirees relocating to Bali (Ubud, Canggu, Sanur, Seminyak), Lombok, Bintan, Yogyakarta. The IDR 30M/month property requirement is the main filter — informal rental arrangements don't qualify.",
    },
    {
      label: "Remote Worker Visa E33G (Digital Nomad) — Indonesia",
      finderGoals: ["remote_work"],
      purpose: "work",
      status: "embassy_visa",
      maxStayDays: 365,
      validityDays: 365,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      requirements: [
        "Annual income from FOREIGN employer minimum USD 60,000",
        "Bank balance minimum USD 2,000 maintained throughout stay",
        "Employment contract / business ownership outside Indonesia",
        "Health insurance covering Indonesia",
        "Sponsor company in Indonesia (typical for E33G application)",
        "PROHIBITED: any work for Indonesian employer or paid services to Indonesian clients",
      ],
      processingTimeDaysMin: 14,
      processingTimeDaysMax: 30,
      applicationUrl: ID_EVISA,
      primarySourceUrl: ID_SOURCE,
      fees: [
        { amountMinor: 30000, currency: "USD", label: "E33G Remote Worker Visa (USD 300)" },
      ],
      notes: "Launched 2024 to attract digital nomads to Bali + Bandung + Yogyakarta. Renewable annually for up to 5 years. Convertible to KITAP (permanent stay) after 5 years. Specifically excludes Indonesian-employer work — for that you need Working KITAS.",
    },
    {
      label: "Investor KITAS — Indonesia",
      finderGoals: ["invest"],
      purpose: "work",
      status: "embassy_visa",
      maxStayDays: 365 * 2,
      validityDays: 365 * 2,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 18,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      requirements: [
        "Investment in an Indonesian PT PMA (Perseroan Terbatas Penanaman Modal Asing — Foreign Investment Limited Liability Company)",
        "Minimum capital IDR 10B (~USD 650,000) + IDR 1B paid-up capital",
        "BKPM (Investment Coordinating Board) registration",
        "Director-level position in the PT PMA + ID of incorporation",
        "1-year or 2-year permit, renewable",
        "Includes work authorisation in the registered PT PMA",
      ],
      processingTimeDaysMin: 30,
      processingTimeDaysMax: 60,
      applicationUrl: ID_BKPM,
      primarySourceUrl: ID_BKPM,
      fees: [
        { amountMinor: 30000, currency: "USD", label: "Investor KITAS (2-year, USD 300)" },
      ],
      notes: "PT PMA is the standard legal vehicle for foreigners to own Indonesian businesses. Sectors with Foreign Ownership Restrictions (DNI — Daftar Negatif Investasi) include cabotage shipping, basic media, traditional retail; most other sectors permit up to 100% foreign ownership. Common with Australian, Singaporean, Chinese, Japanese investors.",
    },
    {
      label: "B211B Business Visa — Indonesia",
      purpose: "business",
      status: "e_visa",
      maxStayDays: 60,
      validityDays: 180,
      entriesAllowed: "single",
      passportValidityMonthsRequired: 6,
      onwardTicketRequired: true,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      biometricsLocation: "On arrival at Indonesian airport",
      requirements: [
        "Letter of invitation from Indonesian business partner / sponsor",
        "Bank statements (last 3 months) — minimum USD 2,000",
        "Apply online at evisa.imigrasi.go.id",
        "60-day initial stay, extendable in-country twice (total 180 days)",
        "Permitted: meetings, conferences, trade fairs, exploratory business research, contract negotiations",
        "PROHIBITED: paid work / delivery of services / employment in Indonesia",
      ],
      processingTimeDaysMin: 4,
      processingTimeDaysMax: 14,
      applicationUrl: ID_EVISA,
      primarySourceUrl: ID_EVISA,
      fees: [
        { amountMinor: 15000, currency: "USD", label: "B211B Business e-Visa (USD 150)" },
      ],
      notes: "Indonesia's main business-visit visa, distinct from the visa-on-arrival (VOA, 30-day tourist). Permits longer stays for business activities + can be extended twice. For productive work, switch to Working KITAS or Investor KITAS via PT PMA.",
    },
    {
      label: "Student Visa B211B (Pelajar) — Indonesia",
      finderGoals: ["study"],
      purpose: "study",
      status: "embassy_visa",
      maxStayDays: 365 * 5,
      validityDays: 365,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 12,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      requirements: [
        "Admission letter from a recognised Indonesian institution (Universitas Indonesia, ITB, UGM, ITS, IPB, Universitas Airlangga)",
        "Proof of financial means USD 300+/month",
        "Bahasa Indonesia evidence (or English-medium programme enrolment)",
        "Health insurance",
        "Renewable annually for the duration of the programme",
        "Darmasiswa scholarship available for 1-year Indonesian language + culture study",
      ],
      processingTimeDaysMin: 14,
      processingTimeDaysMax: 30,
      applicationUrl: ID_EVISA,
      primarySourceUrl: ID_SOURCE,
      fees: [
        { amountMinor: 15000, currency: "USD", label: "Student visa (annual, USD 150)" },
      ],
      notes: "Public university tuition for international students: IDR 5–30M/semester (~USD 300–2,000/year). Universitas Indonesia (UI), ITB, UGM are the top-ranked institutions. Bahasa Indonesia language proficiency is variable across programmes — most undergrad in Bahasa, increasingly English-taught Master's at top universities.",
      purposeMetadata: { financialProofMonthlyMinor: 30000, financialProofCurrency: "USD" },
    },
  ],
});

// ═══════════════════════════════════════════════════════════════════════════
// SPAIN
// ═══════════════════════════════════════════════════════════════════════════
const ES_SOURCE = "https://extranjeros.inclusion.gob.es/";
const ES_MFA = "https://www.exteriores.gob.es/";

export const spainVisaCategoriesAdapter: Adapter = buildDestinationAdapter({
  id: "es_visa_categories",
  iso2: "ES",
  name: "Spain visa categories — Estudios, Trabajo por Cuenta Ajena, Cuenta Propia, Reagrupación, Cónyuge, Schengen Business",
  primaryUrls: [ES_SOURCE, ES_MFA],
  fixturePath: "src/scrapers/sources/__fixtures__/es_visa_categories.json",
  categories: [
    {
      label: "Visado de Estudios (Student) — Spain",
      finderGoals: ["study"],
      purpose: "study",
      status: "embassy_visa",
      maxStayDays: 365 * 5,
      validityDays: 365,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      requirements: [
        "Admission letter from a recognised Spanish institution (Universidad Complutense Madrid, Universidad Autónoma Barcelona, ESADE, IE, IESE, Pompeu Fabra)",
        "Proof of financial means — 100% of IPREM (~EUR 600/month) for principal, +75% per dependent",
        "Health insurance covering Spain (private or SSN)",
        "Apostilled + Spanish-translated diploma",
        "TIE (Tarjeta de Identidad de Extranjero) at Comisaría within 30 days of arrival",
        "Renewable annually; 20 hours/week part-time work permitted with separate authorisation",
        "Post-study residence permit for 12-24 months to find work",
      ],
      processingTimeDaysMin: 14,
      processingTimeDaysMax: 60,
      applicationUrl: ES_MFA,
      primarySourceUrl: "https://www.universidades.gob.es/",
      fees: [
        { amountMinor: 6000, currency: "EUR", label: "Student visa (EUR 60)" },
      ],
      notes: "Public university tuition for international undergrad: EUR 1,000–2,500/year (varies by region). Master's: EUR 2,000–5,000/year. Private universities + business schools (IE, IESE, ESADE) EUR 20,000–60,000/year for MBA. English-taught Master's increasingly common at IE, ESADE, IESE, Pompeu Fabra.",
      purposeMetadata: { financialProofMonthlyMinor: 60000, financialProofCurrency: "EUR" },
    },
    {
      label: "Visado de Trabajo por Cuenta Ajena (Salaried Worker) — Spain",
      finderGoals: ["live_work"],
      purpose: "work",
      status: "embassy_visa",
      maxStayDays: 365 * 2,
      validityDays: 365,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      biometricsRequired: true,
      biometricsLocation: "Spanish consulate / VFS centre",
      requirements: [
        "Job offer from Spanish-registered employer (alta en Seguridad Social)",
        "Labour-market priority test approval (Catálogo de Ocupaciones de Difícil Cobertura — list of shortage occupations)",
        "Notarised + apostilled credentials",
        "TIE registration within 30 days of arrival",
        "Renewable up to 2 years; long-term residence after 5 years",
      ],
      processingTimeDaysMin: 30,
      processingTimeDaysMax: 90,
      applicationUrl: ES_MFA,
      primarySourceUrl: ES_SOURCE,
      fees: [
        { amountMinor: 10000, currency: "EUR", label: "Trabajo por Cuenta Ajena (EUR 100)" },
      ],
      notes: "Spain's standard sponsored work route, distinct from the Highly Qualified Professional (HQP) path. The Catálogo de Ocupaciones de Difícil Cobertura (shortage occupations list) is the gating filter — most healthcare + IT + engineering + agricultural roles qualify.",
      purposeMetadata: { sponsorshipRequired: true, jobOfferRequired: true, routeToSettlement: true },
    },
    {
      label: "Visado de Trabajo por Cuenta Propia (Self-Employed) — Spain",
      finderGoals: ["live_work"],
      purpose: "work",
      status: "embassy_visa",
      maxStayDays: 365,
      validityDays: 365,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      requirements: [
        "Business plan + financial-viability evidence",
        "Professional qualifications recognised for the activity",
        "Investment evidence — typically EUR 50,000+ documented",
        "Autónomo registration (RETA — Régimen Especial de Trabajadores Autónomos)",
        "Renewable annually based on continued activity + tax compliance",
      ],
      processingTimeDaysMin: 60,
      processingTimeDaysMax: 120,
      applicationUrl: ES_MFA,
      primarySourceUrl: ES_SOURCE,
      fees: [
        { amountMinor: 10000, currency: "EUR", label: "Trabajo por Cuenta Propia (EUR 100)" },
      ],
      notes: "Spain's self-employed long-stay route, distinct from the Digital Nomad Visa (foreign-employer-paid). Common for consultants, restaurateurs, artists, freelancers establishing a Spanish business. Beckham Law tax regime NOT applicable to autónomos (unlike employed expats).",
    },
    {
      label: "Visado de Reagrupación Familiar (Family Reunification) — Spain",
      purpose: "family",
      status: "embassy_visa",
      maxStayDays: 365 * 5,
      validityDays: 365,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      proofOfFundsRequired: true,
      proofOfAccommodationRequired: true,
      biometricsRequired: true,
      requirements: [
        "Sponsor has held Spanish residence permit 1+ year (renewed)",
        "Sponsor's income — 150% IPREM (~EUR 900/month) + 50% per dependent",
        "Suitable accommodation evidence (rental contract or property + informe de viviendas)",
        "Marriage / birth certificates apostilled + translated to Spanish",
        "Spouses + minor children only (parents over 65 in specific cases)",
        "Long-term residence after 5 years on family permit",
      ],
      processingTimeDaysMin: 30,
      processingTimeDaysMax: 90,
      applicationUrl: ES_MFA,
      primarySourceUrl: ES_SOURCE,
      fees: [
        { amountMinor: 10000, currency: "EUR", label: "Reagrupación familiar (EUR 100)" },
      ],
      notes: "Spain's family-reunification route for non-EU sponsors. Spouse of Spanish citizen has a faster route via the Régimen Comunitario (EU Community Regime). Same-sex marriage recognised since 2005 (Spain was the third country globally to legalise marriage equality).",
      purposeMetadata: { sponsorIncomeThresholdMinor: 90000, sponsorIncomeCurrency: "EUR" },
    },
    {
      label: "Visado de Cónyuge de Español / Régimen Comunitario (Spouse of Spanish citizen) — Spain",
      purpose: "family",
      status: "embassy_visa",
      maxStayDays: 365 * 5,
      validityDays: 365 * 5,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      biometricsRequired: true,
      requirements: [
        "Marriage certificate notarised + apostilled + translated to Spanish",
        "Spanish spouse's DNI + Libro de Familia",
        "Proof of cohabitation",
        "Tarjeta de Residencia de Familiar de Ciudadano de la UE (5-year card) on arrival",
        "Permanent residence after 5 years (10-year card)",
        "Naturalisation after 1 year of marriage + Spanish residence (the FASTEST naturalisation route in the EU)",
      ],
      processingTimeDaysMin: 30,
      processingTimeDaysMax: 60,
      applicationUrl: ES_MFA,
      primarySourceUrl: ES_SOURCE,
      fees: [
        { amountMinor: 1200, currency: "EUR", label: "Régimen Comunitario card fee (EUR 12)" },
      ],
      notes: "Spain has the FASTEST naturalisation-by-marriage route in the EU — 1 year of marriage + Spanish residence. Plus simplified naturalisation (2 years) for nationals of Spain + Portugal + Andorra + Filipinos + Sephardic Jews + Iberoamerican states (1955 Convention) + Equatoguineans + descendants of Spaniards exiled during the Franco regime.",
      purposeMetadata: { cohabitationProofRequired: true },
    },
    {
      label: "Schengen Type C Business Visa — Spain",
      purpose: "business",
      status: "embassy_visa",
      maxStayDays: 90,
      validityDays: 180,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 3,
      onwardTicketRequired: true,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      requirements: [
        "Letter of invitation from Spanish business partner",
        "Trade-fair attendance (Mobile World Congress Barcelona, FITUR Madrid, ARCO, IMEX)",
        "Travel insurance EUR 30,000 minimum",
        "Multi-entry Schengen visas (up to 5 years) for regular business travellers",
      ],
      processingTimeDaysMin: 10,
      processingTimeDaysMax: 21,
      applicationUrl: ES_MFA,
      primarySourceUrl: ES_MFA,
      fees: [
        { amountMinor: 9000, currency: "EUR", label: "Schengen Type C (EUR 90)" },
      ],
      notes: "For visa-required nationalities. Spain has dense bilateral business chambers — particularly strong with Latin America (Casa de América + Cámaras de Comercio Iberoamericanas). Madrid + Barcelona are the major business hubs.",
    },
  ],
});

// ═══════════════════════════════════════════════════════════════════════════
// GERMANY
// ═══════════════════════════════════════════════════════════════════════════
const DE_SOURCE = "https://www.make-it-in-germany.com/en/";
const DE_BMI = "https://www.bmi.bund.de/EN/topics/migration/skilled-immigration/skilled-immigration-node.html";
const DE_BAMF = "https://www.bamf.de/EN/Themen/MigrationAufenthalt/";

export const germanyVisaCategoriesAdapter: Adapter = buildDestinationAdapter({
  id: "de_visa_categories",
  iso2: "DE",
  name: "Germany visa categories — Student, Researcher, Family Reunification, Spouse, Freiberufler, Schengen Business",
  primaryUrls: [DE_SOURCE, DE_BMI, DE_BAMF],
  fixturePath: "src/scrapers/sources/__fixtures__/de_visa_categories.json",
  categories: [
    {
      label: "Student Visa (Visum zu Studienzwecken) — Germany",
      finderGoals: ["study"],
      purpose: "study",
      status: "embassy_visa",
      maxStayDays: 365 * 5,
      validityDays: 365,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 12,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      requirements: [
        "Admission letter from a recognised German institution (TU9 universities, Humboldt, LMU Munich, Heidelberg, FU Berlin)",
        "Sperrkonto (blocked account) of EUR 11,904 for year one (= EUR 992/month)",
        "Health insurance — public ~EUR 120/month for under-30s, private otherwise",
        "Apply via uni-assist OR directly with the university",
        "German DSH / TestDaF for German-taught programmes; English-taught Master's increasingly common at TU9",
        "120 full days / 240 half days work permitted per year",
        "Post-study 18-month job-seeker permit then Skilled Worker / Blue Card conversion",
      ],
      processingTimeDaysMin: 30,
      processingTimeDaysMax: 90,
      applicationUrl: DE_SOURCE,
      primarySourceUrl: DE_BAMF,
      fees: [
        { amountMinor: 7500, currency: "EUR", label: "Student visa (EUR 75)" },
      ],
      notes: "Public university tuition is FREE in most Länder (Baden-Württemberg charges EUR 1,500/semester for non-EU). Many programmes English-taught at master's level. Sperrkonto is the key financial-proof mechanism (Deutsche Bank, Expatrio, Fintiba).",
      purposeMetadata: { financialProofMonthlyMinor: 99200, financialProofCurrency: "EUR" },
    },
    {
      label: "Researcher Visa (Forschungsaufenthalt) — Germany",
      finderGoals: ["study"],
      purpose: "study",
      status: "embassy_visa",
      maxStayDays: 365 * 4,
      validityDays: 365 * 2,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 12,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      requirements: [
        "Hosting agreement (Aufnahmevereinbarung) with a recognised German research institution (Max Planck, Fraunhofer, Helmholtz, Leibniz, DAAD, TU9 universities)",
        "Funding evidence — typically EUR 1,400+/month",
        "Health insurance",
        "REST Directive route — EU mobility provisions for researchers from other Member States",
        "Long-term EU residence after 5 years",
      ],
      processingTimeDaysMin: 30,
      processingTimeDaysMax: 90,
      applicationUrl: DE_SOURCE,
      primarySourceUrl: DE_BAMF,
      fees: [
        { amountMinor: 7500, currency: "EUR", label: "Researcher visa (EUR 75)" },
      ],
      notes: "Germany's research visa is the dedicated route for PhD candidates + post-docs at recognised research orgs (Max Planck network, Fraunhofer, Helmholtz). Faster + simpler than the Skilled Worker route. The REST Directive enables short-stay mobility to other EU states without separate visas.",
    },
    {
      label: "Family Reunification (Familiennachzug) — Germany",
      purpose: "family",
      status: "embassy_visa",
      maxStayDays: 365 * 5,
      validityDays: 365 * 3,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 12,
      proofOfAccommodationRequired: true,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      requirements: [
        "Sponsor is German citizen / Blue Card / Skilled Worker / settlement permit holder",
        "Suitable housing evidence",
        "Sponsor income sufficient to support family without state aid",
        "A1 German language for spouse (waived for Blue Card spouses + nationals of US, JP, AU, CA, NZ, IL, KR, GB)",
        "Children under 16 enter freely; 16-18 require A1 German unless joining Blue Card holder",
        "Eligible for accelerated naturalisation under 2024 citizenship reform (3 years for well-integrated)",
      ],
      processingTimeDaysMin: 60,
      processingTimeDaysMax: 180,
      applicationUrl: DE_SOURCE,
      primarySourceUrl: DE_BAMF,
      fees: [
        { amountMinor: 7500, currency: "EUR", label: "Family reunification visa (EUR 75)" },
      ],
      notes: "Germany reformed family reunification under the 2024 citizenship + skilled-immigration laws. A1 German waiver extends to nationals of select countries + Blue Card spouses (recognising the high-skill demographic). Naturalisation now possible after 5 years (3 for well-integrated) with dual citizenship permitted.",
      purposeMetadata: { cohabitationProofRequired: true },
    },
    {
      label: "Spouse of German Citizen (Ehegattennachzug) — Germany",
      purpose: "family",
      status: "embassy_visa",
      maxStayDays: 365 * 5,
      validityDays: 365 * 3,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 12,
      biometricsRequired: true,
      requirements: [
        "Marriage certificate notarised + apostilled + translated to German",
        "A1 German language proof (waived for nationals of US, JP, AU, CA, NZ, IL, KR, GB + EU + EEA)",
        "German spouse's ID + family book (Familienstammbuch)",
        "Immediate Niederlassungserlaubnis eligibility for spouses after 3 years marriage + 2 years German residence",
        "Naturalisation: 3 years marriage + 2 years legal residence (faster than standard 5)",
      ],
      processingTimeDaysMin: 30,
      processingTimeDaysMax: 90,
      applicationUrl: DE_SOURCE,
      primarySourceUrl: DE_BAMF,
      fees: [
        { amountMinor: 7500, currency: "EUR", label: "Spouse visa (EUR 75)" },
      ],
      notes: "Germany's accelerated naturalisation for spouses of German citizens (3 years marriage + 2 years residence) is among the fastest in the EU. Same-sex marriage recognised since 2017. The 2024 citizenship reform now permits dual citizenship for most nationalities (removed the long-standing renunciation requirement).",
      purposeMetadata: { cohabitationProofRequired: true },
    },
    {
      label: "Freiberufler Visa (Self-Employed Professional) — Germany",
      finderGoals: ["live_work"],
      purpose: "work",
      status: "embassy_visa",
      maxStayDays: 365 * 3,
      validityDays: 365,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 12,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      requirements: [
        "Self-employed in a 'free profession' (Freier Beruf) — artists, writers, consultants, IT freelancers, doctors, lawyers, journalists, teachers",
        "Two letters from prospective German clients confirming engagement",
        "Business plan + projected income",
        "Health insurance (private mandatory above income threshold)",
        "Tax registration with Finanzamt",
        "Renewable annually based on continued activity; settlement after 3 years",
      ],
      processingTimeDaysMin: 60,
      processingTimeDaysMax: 120,
      applicationUrl: DE_SOURCE,
      primarySourceUrl: DE_BAMF,
      fees: [
        { amountMinor: 7500, currency: "EUR", label: "Freiberufler visa (EUR 75)" },
      ],
      notes: "Germany's Freiberufler route is uniquely friendly to creative + intellectual professionals. Berlin is the major hub for international creative-class Freiberufler (artists, writers, designers, developers). Distinct from Selbständige (commercial business owners) which requires substantial investment.",
    },
    {
      label: "Schengen Type C Business Visa — Germany",
      purpose: "business",
      status: "embassy_visa",
      maxStayDays: 90,
      validityDays: 180,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 3,
      onwardTicketRequired: true,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      requirements: [
        "Letter of invitation from German business partner (Verpflichtungserklärung if hosting)",
        "Trade-fair attendance (Hannover Messe, Frankfurt Book Fair, CeBIT, IFA Berlin, IAA Mobility)",
        "Travel insurance EUR 30,000 minimum",
        "Multi-entry Schengen visas (up to 5 years) for regular business travellers",
      ],
      processingTimeDaysMin: 10,
      processingTimeDaysMax: 21,
      applicationUrl: DE_SOURCE,
      primarySourceUrl: DE_SOURCE,
      fees: [
        { amountMinor: 9000, currency: "EUR", label: "Schengen Type C (EUR 90)" },
      ],
      notes: "For visa-required nationalities. Germany hosts the densest trade-fair ecosystem in Europe — Messe Frankfurt, Messe Berlin, Hannover Messe, Messe München handle ~150 major exhibitions annually. Frankfurt + Munich + Berlin + Düsseldorf are the major business hubs.",
    },
  ],
});
