/**
 * Destination visa-category coverage — batch 3.
 *
 * Closes the remaining top-20 + adjacent gaps after batches 1-2:
 *
 *   PT Portugal (was 13 — D7 / DNV exist, missing student/family/business)
 *   CA Canada (was 14 — Express Entry / PNP exist, missing student/family detail)
 *   VN Vietnam (was 13 — missing work / family / business depth)
 *   NZ New Zealand (thin — missing student/family/SMC detail)
 *   CH Switzerland (thin beyond ch_skilled_worker)
 *   IL Israel (thin beyond Aliyah myth)
 *
 * Each destination gets 5-6 hand-curated categories filling the missing
 * purpose buckets. Labels intentionally distinct from existing
 * adapters (D7 / D8 / NLV / Skilled Migrant / B+L Permit / Aliyah)
 * to avoid duplicate-label collisions.
 */
import type { Adapter } from "../base/Adapter";
import { buildDestinationAdapter } from "./_destinationCategoryFactory";

// ═══════════════════════════════════════════════════════════════════════════
// PORTUGAL
// ═══════════════════════════════════════════════════════════════════════════
const PT_SOURCE = "https://www.aima.gov.pt/";
const PT_MFA = "https://www.portaldascomunidades.mne.gov.pt/";

export const portugalVisaCategoriesAdapter: Adapter = buildDestinationAdapter({
  id: "pt_visa_categories",
  iso2: "PT",
  name: "Portugal visa categories — Student, Family Reunification, Spouse, Work Job-Seeker, Business",
  primaryUrls: [PT_SOURCE, PT_MFA],
  fixturePath: "src/scrapers/sources/__fixtures__/pt_visa_categories.json",
  categories: [
    {
      label: "Visto de Estudos (Student) — Portugal",
      finderGoals: ["study"],
      purpose: "study",
      status: "embassy_visa",
      maxStayDays: 365 * 5,
      validityDays: 365,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      requirements: [
        "Admission letter from a recognised Portuguese institution (Universidade do Porto, NOVA Lisbon, ISCTE, Católica, Coimbra, U.Minho)",
        "Proof of financial means — EUR 760+/month for principal + 50% per dependent (~12× IAS)",
        "Health insurance covering Portugal",
        "Apostilled + Portuguese-translated diploma + Comprovativo de Equivalência",
        "Residence Authorisation (Autorização de Residência) at AIMA within 30 days of arrival",
        "Renewable annually for the duration of the programme",
        "20 hours/week part-time work permitted",
        "Post-study residence permit for 12-24 months to find work",
      ],
      processingTimeDaysMin: 14,
      processingTimeDaysMax: 60,
      applicationUrl: PT_MFA,
      primarySourceUrl: "https://www.dges.gov.pt/",
      fees: [
        { amountMinor: 9000, currency: "EUR", label: "Student visa (EUR 90)" },
      ],
      notes: "Portugal's public university tuition for international undergrads is EUR 1,500-3,000/year; private + business schools EUR 5,000-15,000/year. English-taught Master's increasingly common at NOVA, Católica, ISCTE.",
      purposeMetadata: { financialProofMonthlyMinor: 76000, financialProofCurrency: "EUR" },
    },
    {
      label: "Reagrupamento Familiar (Family Reunification) — Portugal",
      purpose: "family",
      status: "embassy_visa",
      maxStayDays: 365 * 5,
      validityDays: 365 * 2,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      proofOfAccommodationRequired: true,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      requirements: [
        "Sponsor has held Portuguese residence permit 12+ months",
        "Sponsor income: 100% IAS (~EUR 509/month) for principal + 50% per dependent adult + 30% per child",
        "Suitable accommodation evidence (rental contract or property deed)",
        "Marriage / birth certificates apostilled + translated to Portuguese",
        "Spouses + minor children + dependent parents over 65 + dependent adult children eligible",
        "Permanent residence eligibility after 5 years on family permit",
        "Citizenship after 5 years of legal residence + A2 Portuguese + clean criminal record",
      ],
      processingTimeDaysMin: 30,
      processingTimeDaysMax: 90,
      applicationUrl: PT_SOURCE,
      primarySourceUrl: PT_SOURCE,
      fees: [
        { amountMinor: 9000, currency: "EUR", label: "Family reunification visa (EUR 90)" },
      ],
      notes: "Portugal's family-reunification route is broader than most EU member states — covers dependent parents over 65 + dependent adult children. Same-sex marriage recognised since 2010. The 2024 citizenship reform reduced general naturalisation from 6 to 5 years.",
      purposeMetadata: { sponsorIncomeThresholdMinor: 50900, sponsorIncomeCurrency: "EUR" },
    },
    {
      label: "Visto Tipo D Cônjuge de Português (Spouse of Portuguese Citizen) — Portugal",
      purpose: "family",
      status: "embassy_visa",
      maxStayDays: 365 * 5,
      validityDays: 365 * 5,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      biometricsRequired: true,
      requirements: [
        "Marriage certificate notarised + apostilled + translated to Portuguese",
        "Portuguese spouse's Cartão de Cidadão + Atestado de Residência",
        "Proof of cohabitation",
        "Autorização de Residência (5-year card) on arrival at AIMA",
        "Permanent residence eligibility after 5 years",
        "Naturalisation: 3 years of marriage + Portuguese residence (faster than the 5-year general route)",
      ],
      processingTimeDaysMin: 30,
      processingTimeDaysMax: 60,
      applicationUrl: PT_MFA,
      primarySourceUrl: PT_SOURCE,
      fees: [
        { amountMinor: 9000, currency: "EUR", label: "Spouse visa (EUR 90)" },
      ],
      notes: "Portuguese spouse-route is uniquely fast: 3 years of marriage + residence → naturalisation. Plus CPLP nationals (Brazilian, Angolan, Mozambican, Cape Verdean, etc.) get streamlined treatment under the Special Mobility Convention.",
      purposeMetadata: { cohabitationProofRequired: true },
    },
    {
      label: "Job Seeker Visa — Portugal",
      finderGoals: ["live_work"],
      purpose: "work",
      status: "embassy_visa",
      maxStayDays: 365,
      validityDays: 120,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      requirements: [
        "Annual job-seeker visa for highly-qualified candidates (introduced 2022)",
        "Proof of financial means — EUR 5,400 minimum (~3× minimum wage)",
        "120-day initial entry visa to seek employment in Portugal",
        "Once employment secured, convertible to Skilled Worker residence permit",
        "Health insurance covering Portugal",
        "Application via Portuguese consulate in country of residence",
      ],
      processingTimeDaysMin: 30,
      processingTimeDaysMax: 60,
      applicationUrl: PT_MFA,
      primarySourceUrl: PT_SOURCE,
      fees: [
        { amountMinor: 9000, currency: "EUR", label: "Job-seeker visa (EUR 90)" },
      ],
      notes: "Portugal launched the Job Seeker Visa in October 2022 to attract qualified workers. 120-day single-entry initial visa; if employment found, converts to a 2-year work residence permit. Particularly used by qualified non-EU professionals from Brazil, India, Russia, Ukraine.",
      purposeMetadata: { sponsorshipRequired: false, jobOfferRequired: false },
    },
    {
      label: "D3 Highly-Qualified Activity Visa — Portugal",
      finderGoals: ["live_work"],
      purpose: "work",
      status: "embassy_visa",
      maxStayDays: 365 * 2,
      validityDays: 365 * 2,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      biometricsRequired: true,
      requirements: [
        "Job offer + employment contract from Portuguese employer in a 'highly qualified' activity",
        "Salary at or above 1.5× Portuguese average salary",
        "Apostilled + Portuguese-translated credentials",
        "EU Blue Card alternative for non-EU highly-qualified workers",
        "Renewable; convertible to long-term residence after 5 years",
      ],
      processingTimeDaysMin: 30,
      processingTimeDaysMax: 90,
      applicationUrl: PT_MFA,
      primarySourceUrl: PT_SOURCE,
      fees: [
        { amountMinor: 9000, currency: "EUR", label: "D3 visa (EUR 90)" },
      ],
      notes: "Portugal's D3 is the local EU Blue Card equivalent for highly-qualified workers. Particularly active in tech (Lisbon hub), finance, biotech, engineering. Tax-residency interaction with IFICI (Tax Regime for Scientific Research and Innovation) regime can be substantial.",
      purposeMetadata: { sponsorshipRequired: true, jobOfferRequired: true, routeToSettlement: true },
    },
    {
      label: "Schengen Type C Business Visa — Portugal",
      purpose: "business",
      status: "embassy_visa",
      maxStayDays: 90,
      validityDays: 180,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 3,
      onwardTicketRequired: true,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      requirements: [
        "Letter of invitation from Portuguese business partner",
        "Trade-fair attendance (Web Summit Lisbon, Modtissimo Porto, EXPO Lisboa)",
        "Travel insurance EUR 30,000 minimum",
        "Multi-entry Schengen visas (up to 5 years) for regular business travellers",
      ],
      processingTimeDaysMin: 10,
      processingTimeDaysMax: 21,
      applicationUrl: PT_MFA,
      primarySourceUrl: PT_MFA,
      fees: [
        { amountMinor: 9000, currency: "EUR", label: "Schengen Type C (EUR 90)" },
      ],
      notes: "Portugal has dense bilateral business chambers — particularly strong with Brazil + Angola + Mozambique (CPLP) + UK (post-Brexit Trade Continuity Agreement) + Spain (Iberian peninsula corridor). Lisbon + Porto are the major business hubs.",
    },
  ],
});

// ═══════════════════════════════════════════════════════════════════════════
// CANADA
// ═══════════════════════════════════════════════════════════════════════════
const CA_IRCC = "https://www.canada.ca/en/services/immigration-citizenship.html";
const CA_EDU = "https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada.html";

export const canadaVisaCategoriesAdapter: Adapter = buildDestinationAdapter({
  id: "ca_visa_categories",
  iso2: "CA",
  name: "Canada visa categories — Study Permit, Work Permit, Spouse, Family Sponsorship, Visitor, Business",
  primaryUrls: [CA_IRCC, CA_EDU],
  fixturePath: "src/scrapers/sources/__fixtures__/ca_visa_categories.json",
  categories: [
    {
      label: "Study Permit — Canada",
      finderGoals: ["study"],
      purpose: "study",
      status: "embassy_visa",
      maxStayDays: 365 * 8,
      validityDays: 365 * 4,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      biometricsLocation: "VFS Global / Canadian visa application centre",
      requirements: [
        "Letter of Acceptance from a Designated Learning Institution (DLI)",
        "Proof of financial means — CAD $20,635/year + tuition (raised from $10,000 in January 2024)",
        "PAL (Provincial Attestation Letter) — required since January 2024 for most undergrad/college applications",
        "Medical examination if from a designated country OR if intending to study in a healthcare-adjacent field",
        "20 hours/week part-time work permitted off-campus (since November 2022 expansion)",
        "Post-Graduation Work Permit (PGWP) for 1-3 years after graduation depending on programme length",
      ],
      processingTimeDaysMin: 28,
      processingTimeDaysMax: 84,
      applicationUrl: CA_IRCC,
      primarySourceUrl: CA_EDU,
      fees: [
        { amountMinor: 15000, currency: "CAD", label: "Study Permit (CAD $150)" },
        { amountMinor: 8500, currency: "CAD", label: "Biometrics (CAD $85)", kind: "biometrics" },
      ],
      notes: "Canada's 2024 cap (~360,000 study permits) materially reduced approvals. PAL requirement (Jan 2024) made provincial-level attestation mandatory. Healthcare students + master's/doctoral programmes have priority within the cap.",
      purposeMetadata: { financialProofMonthlyMinor: 172000, financialProofCurrency: "CAD" },
    },
    {
      label: "Work Permit (Employer-Specific) — Canada",
      finderGoals: ["live_work"],
      purpose: "work",
      status: "embassy_visa",
      maxStayDays: 365 * 4,
      validityDays: 365 * 2,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      biometricsRequired: true,
      biometricsLocation: "VFS Global / Canadian visa application centre",
      requirements: [
        "Positive Labour Market Impact Assessment (LMIA) from employer OR LMIA-exempt category (USMCA TN, CETA, GATS, IMP)",
        "Job offer letter from Canadian employer",
        "Employer's compliance fee (CAD $1,000 to ESDC)",
        "Notarised + apostilled credentials",
        "Medical exam if from designated country OR healthcare/childcare role",
        "Closed work permit tied to specific employer; convertible via LMIA-exempt categories",
      ],
      processingTimeDaysMin: 28,
      processingTimeDaysMax: 112,
      applicationUrl: CA_IRCC,
      primarySourceUrl: CA_IRCC,
      fees: [
        { amountMinor: 15500, currency: "CAD", label: "Work Permit (CAD $155)" },
        { amountMinor: 100000, currency: "CAD", label: "LMIA processing fee (employer pays, CAD $1,000)", kind: "service" },
      ],
      notes: "Canada's standard sponsored work route. International Mobility Program (IMP) exempts USMCA + CETA + GATS + intra-company transfers from LMIA. Renewable; convertible to PR via Canadian Experience Class after 1 year of full-time skilled work.",
      purposeMetadata: { sponsorshipRequired: true, jobOfferRequired: true, routeToSettlement: true },
    },
    {
      label: "Spousal / Common-Law Sponsorship — Canada",
      purpose: "family",
      status: "embassy_visa",
      maxStayDays: 365 * 100,
      validityDays: 365 * 100,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 12,
      biometricsRequired: true,
      requirements: [
        "Sponsor must be Canadian citizen or permanent resident, 18+",
        "Sponsor agrees to financially support spouse for 3 years",
        "No minimum income requirement (waived for spouse / common-law / conjugal partners — unlike most family classes)",
        "Marriage certificate OR cohabitation evidence (common-law) OR conjugal evidence",
        "Outland sponsorship via Canadian consulate OR inland sponsorship if spouse already in Canada",
        "Permanent residence on approval; citizenship after 3 years of physical presence",
      ],
      processingTimeDaysMin: 365,
      processingTimeDaysMax: 365 * 2,
      applicationUrl: CA_IRCC,
      primarySourceUrl: CA_IRCC,
      fees: [
        { amountMinor: 119500, currency: "CAD", label: "Spousal sponsorship (CAD $1,195 total)" },
      ],
      notes: "Canada's spousal sponsorship has NO income requirement for the sponsor (unique among major destinations). Common-law (12+ months continuous cohabitation) + conjugal (extraordinary circumstances) treated equivalently to married. Same-sex spouses recognised since 2003.",
      purposeMetadata: { cohabitationProofRequired: true },
    },
    {
      label: "Parent / Grandparent Sponsorship (PGP) — Canada",
      purpose: "family",
      status: "embassy_visa",
      maxStayDays: 365 * 100,
      validityDays: 365 * 100,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 12,
      biometricsRequired: true,
      requirements: [
        "Sponsor must be Canadian citizen / PR, 18+",
        "Sponsor income — Minimum Necessary Income (MNI) + 30% for 3 prior tax years",
        "Annual lottery — limited spots (~10,000-30,000/year, varies)",
        "Sponsor signs 20-year sponsorship undertaking (financial responsibility)",
        "Super Visa alternative: 10-year multi-entry visitor visa, 5-year continuous stay per entry (no annual lottery)",
      ],
      processingTimeDaysMin: 365 * 2,
      processingTimeDaysMax: 365 * 3,
      applicationUrl: CA_IRCC,
      primarySourceUrl: CA_IRCC,
      fees: [
        { amountMinor: 117500, currency: "CAD", label: "PGP sponsorship (CAD $1,175 total)" },
      ],
      notes: "PGP is annual-lottery-based — only sponsors who win the lottery can submit applications. Super Visa is the year-round alternative for parents/grandparents without permanent-residence intent.",
    },
    {
      label: "Visitor Visa (TRV) — Canada (visa-required nationals)",
      purpose: "tourism",
      status: "embassy_visa",
      maxStayDays: 180,
      validityDays: 365 * 10,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      onwardTicketRequired: false,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      requirements: [
        "Required for nationals of ~150 countries not eligible for eTA (Indians, Chinese, Russians, most of Africa + South Asia + Latin America)",
        "Bank statements (last 3 months)",
        "Letter of invitation if visiting family / friends in Canada",
        "Travel itinerary + accommodation evidence",
        "Multi-entry visa valid up to 10 years (one stay max 6 months)",
        "Indians + Chinese with US visa + prior Canadian visa eligible for streamlined CAN+ programme",
      ],
      processingTimeDaysMin: 14,
      processingTimeDaysMax: 60,
      applicationUrl: CA_IRCC,
      primarySourceUrl: CA_IRCC,
      fees: [
        { amountMinor: 10000, currency: "CAD", label: "Visitor Visa (CAD $100)" },
        { amountMinor: 8500, currency: "CAD", label: "Biometrics (CAD $85)", kind: "biometrics" },
      ],
      notes: "Canada's standard tourist visa for visa-required nationals. CAN+ programme (since 2018) gives 10-day priority processing for repeat travellers from China, India + recently expanded to Mexico (post-Feb 2024) for those with prior Canadian or US visas.",
    },
  ],
});

// ═══════════════════════════════════════════════════════════════════════════
// VIETNAM
// ═══════════════════════════════════════════════════════════════════════════
const VN_SOURCE = "https://www.imigrasi.go.id/";
const VN_EVISA = "https://evisa.xuatnhapcanh.gov.vn/";
const VN_DOLISA = "https://www.molisa.gov.vn/";

export const vietnamVisaCategoriesAdapter: Adapter = buildDestinationAdapter({
  id: "vn_visa_categories",
  iso2: "VN",
  name: "Vietnam visa categories — Work Permit + LB Visa, Student, Family, Business e-Visa, Temporary Residence Card",
  primaryUrls: [VN_SOURCE, VN_EVISA, VN_DOLISA],
  fixturePath: "src/scrapers/sources/__fixtures__/vn_visa_categories.json",
  categories: [
    {
      label: "Work Permit + LB Visa (Salaried Worker) — Vietnam",
      finderGoals: ["live_work"],
      purpose: "work",
      status: "embassy_visa",
      maxStayDays: 365 * 2,
      validityDays: 365 * 2,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      biometricsRequired: true,
      requirements: [
        "Work Permit from DOLISA (Department of Labour, War Invalids and Social Affairs) — employer-sponsored",
        "Apostilled + Vietnamese-translated qualifications (degree + work experience certificate)",
        "Notarised criminal-record check (Phieu Ly Lich Tu Phap Số 2) from home country",
        "Medical certificate from Vietnamese-approved hospital",
        "Annual employer quota approval from provincial People's Committee",
        "LB visa issued after Work Permit; convertible to Temporary Residence Card (TRC) for 2-year stay",
      ],
      processingTimeDaysMin: 30,
      processingTimeDaysMax: 60,
      applicationUrl: VN_DOLISA,
      primarySourceUrl: VN_DOLISA,
      fees: [
        { amountMinor: 600_000, currency: "VND", label: "Work Permit (~VND 600k)" },
        { amountMinor: 95_00, currency: "USD", label: "LB visa (~USD $95)", kind: "service" },
      ],
      notes: "Vietnam's labour-market priority test (no qualified Vietnamese candidate available) is the gating filter. Strategic sectors (education, healthcare, engineering, IT) get expedited approval. Many expats work in HCMC + Hanoi tech/finance + Da Nang tourism.",
      purposeMetadata: { sponsorshipRequired: true, jobOfferRequired: true, routeToSettlement: false },
    },
    {
      label: "Student Visa (DH) — Vietnam",
      finderGoals: ["study"],
      purpose: "study",
      status: "embassy_visa",
      maxStayDays: 365 * 5,
      validityDays: 365,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      requirements: [
        "Admission letter from a recognised Vietnamese institution (VNU Hanoi, HCMC University of Science, RMIT Vietnam, BUV, FTU)",
        "Proof of financial means — USD 500+/month",
        "Vietnamese language proficiency (VSL test or equivalent) for Vietnamese-medium programmes; English-taught Master's increasingly common at RMIT + BUV",
        "Apostilled + Vietnamese-translated diplomas",
        "Renewable annually for the duration of the programme",
        "Temporary Residence Card (TRC) issued after enrolment",
      ],
      processingTimeDaysMin: 14,
      processingTimeDaysMax: 30,
      applicationUrl: VN_EVISA,
      primarySourceUrl: VN_SOURCE,
      fees: [
        { amountMinor: 60_00, currency: "USD", label: "Student visa (USD $60)" },
      ],
      notes: "Public university tuition for international students: USD 500-3,000/year. RMIT Vietnam + BUV (British University Vietnam) are the major English-medium private options (USD 8,000-20,000/year). ASEAN scholarship programmes available for select nationalities.",
      purposeMetadata: { financialProofMonthlyMinor: 50_00, financialProofCurrency: "USD" },
    },
    {
      label: "Family TT Visa (Spouse / Dependent of Vietnamese) — Vietnam",
      purpose: "family",
      status: "embassy_visa",
      maxStayDays: 365 * 3,
      validityDays: 365 * 3,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      biometricsRequired: true,
      requirements: [
        "Marriage certificate notarised + apostilled + translated to Vietnamese",
        "Vietnamese sponsor's National ID / Citizen ID + Family Book (Sổ hộ khẩu)",
        "Sponsor's income proof",
        "Initial 1-year visa, renewable to 3-year card",
        "Convertible to TRC (Temporary Residence Card, 3 years) after 1 year",
        "Permanent Residence after 3 years on TRC + continuous residence",
      ],
      processingTimeDaysMin: 14,
      processingTimeDaysMax: 30,
      applicationUrl: VN_SOURCE,
      primarySourceUrl: VN_SOURCE,
      fees: [
        { amountMinor: 145_00, currency: "USD", label: "TT visa (USD $145)" },
      ],
      notes: "Vietnam's family-route for spouses of Vietnamese citizens. Same-sex marriage NOT recognised legally. Children of Vietnamese-parent automatically Vietnamese citizens (jus sanguinis). Substantial Việt Kiều (overseas Vietnamese) using family-route to return / reconnect with family.",
      purposeMetadata: { cohabitationProofRequired: true },
    },
    {
      label: "Investor Visa (DT) — Vietnam",
      finderGoals: ["invest"],
      purpose: "work",
      status: "embassy_visa",
      maxStayDays: 365 * 5,
      validityDays: 365 * 5,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      requirements: [
        "Investment in a Vietnamese company (LLC, JSC, etc.) — minimum varies by tier (DT1-DT4)",
        "DT1: USD $4M+ investment → 5-year visa + accelerated TRC",
        "DT2: USD $2-4M → 5-year visa",
        "DT3: USD $1-2M → 3-year visa",
        "DT4: <USD $1M → 1-year visa",
        "Investment Registration Certificate + Enterprise Registration Certificate",
        "Includes work authorisation in the registered company",
      ],
      processingTimeDaysMin: 30,
      processingTimeDaysMax: 60,
      applicationUrl: VN_EVISA,
      primarySourceUrl: VN_SOURCE,
      fees: [
        { amountMinor: 145_00, currency: "USD", label: "DT visa (USD $145)" },
      ],
      notes: "Vietnam's investor-visa tiers since the Investment Law 2020 reform. Particularly popular with Korean, Japanese, Singaporean, Chinese, Taiwanese investors. Foreign ownership in most sectors permitted up to 100% (some sectors with caps).",
    },
    {
      label: "Vietnam Business e-Visa — multi-entry (top-tier nationalities)",
      purpose: "business",
      status: "e_visa",
      maxStayDays: 90,
      validityDays: 365,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      onwardTicketRequired: true,
      requirements: [
        "Available online to ~80 nationalities at evisa.xuatnhapcanh.gov.vn",
        "Multi-entry 90-day visa (since August 2023 expansion from 30-day single-entry)",
        "Photo + scan of passport bio-page",
        "Permitted: meetings, conferences, trade fairs, contract negotiations, market research",
        "PROHIBITED: paid work for Vietnamese employer (requires Work Permit + LB visa)",
        "Stays up to 90 days per entry; extendable in-country",
      ],
      processingTimeDaysMin: 3,
      processingTimeDaysMax: 7,
      applicationUrl: VN_EVISA,
      primarySourceUrl: VN_EVISA,
      fees: [
        { amountMinor: 50_00, currency: "USD", label: "Multi-entry e-Visa (USD $50)" },
      ],
      notes: "Vietnam's August 2023 e-Visa expansion (single-entry 30-day → multi-entry 90-day) materially eased business travel. ~80 eligible nationalities including all major economies. For longer stays or work, switch to Work Permit + LB visa.",
    },
  ],
});

// ═══════════════════════════════════════════════════════════════════════════
// NEW ZEALAND
// ═══════════════════════════════════════════════════════════════════════════
const NZ_INZ = "https://www.immigration.govt.nz/";
const NZ_GREEN = "https://www.immigration.govt.nz/new-zealand-visas/preparing-a-visa-application/working-in-nz/qualifications-for-work/work-to-residence";

export const newZealandVisaCategoriesAdapter: Adapter = buildDestinationAdapter({
  id: "nz_visa_categories",
  iso2: "NZ",
  name: "New Zealand visa categories — AEWV, Skilled Migrant Cat, Student, Partner, Parent, Investor",
  primaryUrls: [NZ_INZ, NZ_GREEN],
  fixturePath: "src/scrapers/sources/__fixtures__/nz_visa_categories.json",
  categories: [
    {
      label: "Accredited Employer Work Visa (AEWV) — New Zealand",
      finderGoals: ["live_work"],
      purpose: "work",
      status: "embassy_visa",
      maxStayDays: 365 * 5,
      validityDays: 365 * 3,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      biometricsRequired: true,
      requirements: [
        "Accredited Employer status — employer must hold AEW accreditation from INZ",
        "Job Check approval — employer must pass labour-market test for the role",
        "Job offer at or above the median wage (NZD $29.66/hour as of 2024)",
        "OR Green List occupation (Tier 1 = Straight-to-Residence; Tier 2 = Work-to-Residence after 24 months)",
        "English language requirement (typically IELTS 6.0)",
        "Apostilled + English-translated credentials",
      ],
      processingTimeDaysMin: 30,
      processingTimeDaysMax: 90,
      applicationUrl: NZ_INZ,
      primarySourceUrl: NZ_INZ,
      fees: [
        { amountMinor: 750_00, currency: "NZD", label: "AEWV (NZD $750)" },
      ],
      notes: "NZ's standard work visa since the July 2022 AEWV reform replaced the older Essential Skills + Talent visas. Green List occupations (engineering, healthcare, IT, construction trades, education) get fast-tracked residence pathways. Convertible to Resident Visa via Skilled Migrant Category or Green List route.",
      purposeMetadata: { sponsorshipRequired: true, jobOfferRequired: true, routeToSettlement: true },
    },
    {
      label: "Student Visa (Fee-Paying) — New Zealand",
      finderGoals: ["study"],
      purpose: "study",
      status: "embassy_visa",
      maxStayDays: 365 * 5,
      validityDays: 365 * 4,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 3,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      requirements: [
        "Letter of Acceptance from a Code-of-Practice-signatory NZ institution (Auckland, Victoria Wellington, Otago, Canterbury, AUT, Massey)",
        "Proof of financial means — NZD $20,000/year + tuition",
        "Health insurance covering NZ",
        "Apostilled + English-translated diplomas",
        "20 hours/week part-time work permitted; full-time during scheduled breaks + summer",
        "Post-study Work Visa for 1-3 years after graduation",
      ],
      processingTimeDaysMin: 28,
      processingTimeDaysMax: 84,
      applicationUrl: NZ_INZ,
      primarySourceUrl: NZ_INZ,
      fees: [
        { amountMinor: 380_00, currency: "NZD", label: "Student Visa (NZD $380)" },
      ],
      notes: "NZ public university tuition for international students: NZD $25,000-45,000/year for undergrad, $30,000-50,000 for postgrad. Code-of-Practice signatory requirement is the gating quality filter for institutions.",
      purposeMetadata: { financialProofMonthlyMinor: 167000, financialProofCurrency: "NZD" },
    },
    {
      label: "Partner of a New Zealander Resident Visa — New Zealand",
      purpose: "family",
      status: "embassy_visa",
      maxStayDays: 365 * 100,
      validityDays: 365 * 100,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      biometricsRequired: true,
      requirements: [
        "Sponsor: NZ citizen or resident, with 12+ months together as partners (married, civil union, or de facto)",
        "Evidence of relationship — joint finances, photos, communication, family/friends declarations",
        "Sponsor must accept legal responsibility for support",
        "Two-stage process — partner work visa first (1-year), then partner resident visa after 12 months together",
        "Permanent Resident Visa after 2 years on the resident visa with NZ residence",
      ],
      processingTimeDaysMin: 90,
      processingTimeDaysMax: 365,
      applicationUrl: NZ_INZ,
      primarySourceUrl: NZ_INZ,
      fees: [
        { amountMinor: 2270_00, currency: "NZD", label: "Partner Resident Visa (NZD $2,270)" },
      ],
      notes: "NZ recognises married, civil-union, and de facto (cohabitation 12+ months) partnerships equivalently — including same-sex since 2013 marriage equality. De facto relationships outside marriage are particularly recognised in NZ migration law.",
      purposeMetadata: { cohabitationProofRequired: true },
    },
    {
      label: "Active Investor Plus Visa — New Zealand",
      finderGoals: ["invest"],
      purpose: "work",
      status: "embassy_visa",
      maxStayDays: 365 * 4,
      validityDays: 365 * 4,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      requirements: [
        "Investment NZD $5M in 'direct investment' (qualifying private equity or venture-capital funds, or NZ-listed shares)",
        "OR NZD $15M in 'broader investment' (managed funds, bonds, philanthropic donations, residential property development)",
        "Investment held for 3-4 years (varies by tier)",
        "Physical presence in NZ — at least 117 days over 4 years (or 365 days for broader investments)",
        "Convertible to Resident Visa on completion of investment requirements",
      ],
      processingTimeDaysMin: 60,
      processingTimeDaysMax: 180,
      applicationUrl: NZ_INZ,
      primarySourceUrl: NZ_INZ,
      fees: [
        { amountMinor: 27290_00, currency: "NZD", label: "Active Investor Plus (NZD $27,290)" },
      ],
      notes: "NZ's Active Investor Plus launched September 2022, replaced the older Investor 1 + Investor 2 categories. Aims for productive investment in NZ businesses + economy. Common with Chinese, US, UK, Singaporean HNW investors.",
    },
    {
      label: "Skilled Migrant Category (SMC) Resident Visa — New Zealand",
      finderGoals: ["live_work"],
      purpose: "work",
      status: "embassy_visa",
      maxStayDays: 365 * 100,
      validityDays: 365 * 100,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      biometricsRequired: true,
      requirements: [
        "Points-based system — minimum 6 points (under October 2023 reform, replacing the old 180-point system)",
        "Points from: NZ Skilled Employment (3-6 pts), Qualifications (3-6 pts), Occupational Registration (3 pts), Income (3-6 pts), Age (10-15 pts for under-30)",
        "Expression of Interest (EOI) → Invitation to Apply → Application",
        "AEWV-route option: 3+ years on AEWV with the same employer → automatic eligibility",
        "Permanent residence on grant; NZ citizenship after 5 years of physical presence",
      ],
      processingTimeDaysMin: 90,
      processingTimeDaysMax: 365,
      applicationUrl: NZ_GREEN,
      primarySourceUrl: NZ_INZ,
      fees: [
        { amountMinor: 4640_00, currency: "NZD", label: "SMC Resident Visa (NZD $4,640)" },
      ],
      notes: "NZ's flagship skilled-migration route. October 2023 reform simplified the points system (6 points minimum vs the previous 180). Healthcare, engineering, IT, trades, construction occupations have priority + Green List fast-track.",
      purposeMetadata: { sponsorshipRequired: false, jobOfferRequired: false, routeToSettlement: true },
    },
  ],
});

// ═══════════════════════════════════════════════════════════════════════════
// SWITZERLAND
// ═══════════════════════════════════════════════════════════════════════════
const CH_SEM = "https://www.sem.admin.ch/sem/en/home.html";

export const switzerlandVisaCategoriesAdapter: Adapter = buildDestinationAdapter({
  id: "ch_visa_categories",
  iso2: "CH",
  name: "Switzerland visa categories — Student, Family Reunification, Spouse, Self-Employed, Researcher, Schengen Business",
  primaryUrls: [CH_SEM],
  fixturePath: "src/scrapers/sources/__fixtures__/ch_visa_categories.json",
  categories: [
    {
      label: "Student Permit (Aufenthaltsbewilligung für Studierende) — Switzerland",
      finderGoals: ["study"],
      purpose: "study",
      status: "embassy_visa",
      maxStayDays: 365 * 5,
      validityDays: 365,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      requirements: [
        "Admission letter from a Swiss institution (ETH Zurich, EPFL Lausanne, University of Geneva / Zurich / Bern / Basel)",
        "Proof of financial means — CHF 21,000+/year (cost of living benchmark)",
        "Swiss-recognised health insurance from arrival",
        "Apostilled + German/French/Italian translated diplomas (depending on canton)",
        "Cantonal residence permit after arrival — process varies by canton",
        "15 hours/week part-time work permitted after first 6 months",
        "Post-study 6-month job-search permit; convertible to L/B Permit if hired",
      ],
      processingTimeDaysMin: 30,
      processingTimeDaysMax: 90,
      applicationUrl: CH_SEM,
      primarySourceUrl: CH_SEM,
      fees: [
        { amountMinor: 100_00, currency: "CHF", label: "Student visa (CHF 100)" },
      ],
      notes: "Swiss public university tuition for international students CHF 1,000-2,000/semester at most cantons. ETH Zurich + EPFL CHF 760-1,300/semester despite world-class ranking. Cost of living among Europe's highest (CHF 1,500-2,500/month).",
      purposeMetadata: { financialProofMonthlyMinor: 175000, financialProofCurrency: "CHF" },
    },
    {
      label: "Family Reunification (Familiennachzug) — Switzerland",
      purpose: "family",
      status: "embassy_visa",
      maxStayDays: 365 * 5,
      validityDays: 365 * 5,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      proofOfAccommodationRequired: true,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      requirements: [
        "Sponsor must be Swiss citizen / C Permit / B Permit holder",
        "Suitable housing evidence + income not dependent on social welfare",
        "A1 German/French/Italian (canton-dependent) for spouse",
        "Children under 12 enter freely; 12-18 face stricter conditions",
        "Cantonal migration office processes (each canton has its own rules within federal framework)",
      ],
      processingTimeDaysMin: 60,
      processingTimeDaysMax: 180,
      applicationUrl: CH_SEM,
      primarySourceUrl: CH_SEM,
      fees: [
        { amountMinor: 150_00, currency: "CHF", label: "Family reunification permit (CHF 150)" },
      ],
      notes: "Switzerland's family-reunification rules are uniquely strict — cantonal-level discretion creates significant variation. EU/EFTA family members enjoy AFMP free movement; non-EU members face the standard family-reunification process. Same-sex marriage recognised since July 2022.",
      purposeMetadata: { cohabitationProofRequired: true },
    },
    {
      label: "Spouse of Swiss Citizen — Switzerland",
      purpose: "family",
      status: "embassy_visa",
      maxStayDays: 365 * 5,
      validityDays: 365 * 5,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      biometricsRequired: true,
      requirements: [
        "Marriage certificate notarised + apostilled + translated to German / French / Italian",
        "Swiss spouse's ID (Swiss ID card)",
        "Cantonal residence permit (B Permit) immediately on arrival",
        "Settlement permit (C Permit) after 5 years",
        "Fast-track naturalisation: 3 years of marriage + 5 years of residence (vs 10 years standard)",
      ],
      processingTimeDaysMin: 60,
      processingTimeDaysMax: 120,
      applicationUrl: CH_SEM,
      primarySourceUrl: CH_SEM,
      fees: [
        { amountMinor: 150_00, currency: "CHF", label: "Spouse visa (CHF 150)" },
      ],
      notes: "Switzerland's spouse-route is one of the slower naturalisation paths in Europe (8 years total). Cantonal discretion can extend or restrict — Geneva, Vaud, Zurich are generally faster than rural cantons. Dual citizenship permitted.",
      purposeMetadata: { cohabitationProofRequired: true },
    },
    {
      label: "Self-Employed / Entrepreneur Permit — Switzerland",
      finderGoals: ["live_work"],
      purpose: "work",
      status: "embassy_visa",
      maxStayDays: 365 * 5,
      validityDays: 365,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      requirements: [
        "Substantial investment in a Swiss business (typically CHF 250,000-1,000,000+, varies by canton)",
        "Business plan demonstrating economic benefit to Switzerland (job creation, tax revenue, sector contribution)",
        "Cantonal pre-approval — varies by canton (Zug + Schwyz historically business-friendly; Zurich + Geneva stricter)",
        "Federal annual quota for self-employed non-EU/EFTA: limited",
        "Renewable annually based on continued business activity",
      ],
      processingTimeDaysMin: 90,
      processingTimeDaysMax: 180,
      applicationUrl: CH_SEM,
      primarySourceUrl: CH_SEM,
      fees: [
        { amountMinor: 200_00, currency: "CHF", label: "Self-employed permit (CHF 200)" },
      ],
      notes: "Switzerland's self-employed permit for non-EU/EFTA nationals is restrictive — cantonal economic-benefit test is the gating filter. EU/EFTA nationals enjoy AFMP free movement for self-employment.",
    },
    {
      label: "Schengen Type C Business Visa — Switzerland",
      purpose: "business",
      status: "embassy_visa",
      maxStayDays: 90,
      validityDays: 180,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 3,
      onwardTicketRequired: true,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      requirements: [
        "Letter of invitation from Swiss business partner",
        "Trade-fair attendance (Watches and Wonders Geneva, Art Basel, Baselworld successor events, Geneva Motor Show)",
        "Travel insurance EUR 30,000 minimum",
        "Multi-entry Schengen visas (up to 5 years) for regular business travellers",
      ],
      processingTimeDaysMin: 10,
      processingTimeDaysMax: 21,
      applicationUrl: CH_SEM,
      primarySourceUrl: CH_SEM,
      fees: [
        { amountMinor: 9000, currency: "EUR", label: "Schengen Type C (EUR 90)" },
      ],
      notes: "Switzerland is in Schengen + ETIAS coverage. Zurich + Geneva + Basel are the major business hubs. Watches and Wonders Geneva (annual) + Art Basel (June) are the marquee international business events.",
    },
  ],
});

// ═══════════════════════════════════════════════════════════════════════════
// ISRAEL
// ═══════════════════════════════════════════════════════════════════════════
const IL_INTERIOR = "https://www.gov.il/en/departments/units/population_and_immigration_authority";
const IL_MOF = "https://www.gov.il/en/departments/ministry_of_foreign_affairs";

export const israelVisaCategoriesAdapter: Adapter = buildDestinationAdapter({
  id: "il_visa_categories",
  iso2: "IL",
  name: "Israel visa categories — B-1 Work, A-5 Family, A-2 Student, B-2 Tourist (visa nationals), Researcher, Business",
  primaryUrls: [IL_INTERIOR, IL_MOF],
  fixturePath: "src/scrapers/sources/__fixtures__/il_visa_categories.json",
  categories: [
    {
      label: "B-1 Work Visa — Israel",
      finderGoals: ["live_work"],
      purpose: "work",
      status: "embassy_visa",
      maxStayDays: 365,
      validityDays: 365,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 12,
      biometricsRequired: true,
      requirements: [
        "Job offer from Israeli employer registered with the Population and Immigration Authority",
        "Foreign Workers Bureau (PIBA) approval for the specific role + applicant",
        "Notarised + apostilled credentials",
        "Health insurance covering Israel",
        "Renewable annually; convertible to permanent residence after 5 years of continuous B-1",
        "Tech/expert workers in priority sectors (R&D, engineering) get streamlined processing",
      ],
      processingTimeDaysMin: 30,
      processingTimeDaysMax: 90,
      applicationUrl: IL_INTERIOR,
      primarySourceUrl: IL_INTERIOR,
      fees: [
        { amountMinor: 1410_00, currency: "ILS", label: "B-1 Work Visa (ILS 1,410)" },
      ],
      notes: "Israel's B-1 is the standard sponsored work visa. Tech sector (R&D especially) has dedicated streams + faster processing — Israel's startup ecosystem actively imports international tech talent. Non-Jewish workers can convert to permanent residence (A-5) after 5 years.",
      purposeMetadata: { sponsorshipRequired: true, jobOfferRequired: true, routeToSettlement: true },
    },
    {
      label: "A-5 Permanent Residence (Non-Jewish Spouse / Long-Term Resident) — Israel",
      purpose: "family",
      status: "embassy_visa",
      maxStayDays: 365 * 100,
      validityDays: 365 * 100,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 12,
      biometricsRequired: true,
      requirements: [
        "Spouse of Israeli citizen (non-Jewish) — graduated process through B-1 + A-5 phases",
        "OR long-term resident (typically 7-10 years on consecutive work permits)",
        "Marriage certificate notarised + apostilled + translated to Hebrew",
        "Proof of relationship + ongoing residence in Israel",
        "5-year graduated process: B-1 (year 1-4) → A-5 (year 5-7) → Citizenship eligibility",
        "Convertible to Israeli citizenship (jus matrimonii) after 4.5 years on the gradual process",
      ],
      processingTimeDaysMin: 90,
      processingTimeDaysMax: 180,
      applicationUrl: IL_INTERIOR,
      primarySourceUrl: IL_INTERIOR,
      fees: [
        { amountMinor: 1430_00, currency: "ILS", label: "A-5 Permanent Residence (ILS 1,430)" },
      ],
      notes: "Israel's non-Aliyah family-route for non-Jewish spouses of Israelis. Distinct from Aliyah (Law of Return) which applies to Jews + descendants. Same-sex marriages performed abroad are recognised for family-reunification purposes (Supreme Court 2006 ruling) though Israeli rabbinate doesn't perform them.",
      purposeMetadata: { cohabitationProofRequired: true },
    },
    {
      label: "A-2 Student Visa — Israel",
      finderGoals: ["study"],
      purpose: "study",
      status: "embassy_visa",
      maxStayDays: 365 * 5,
      validityDays: 365,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 12,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      requirements: [
        "Admission letter from a Council for Higher Education-recognised Israeli institution (Hebrew U, Tel Aviv U, Technion, Weizmann, Ben-Gurion, Bar-Ilan, IDC)",
        "Proof of financial means — USD 800+/month",
        "Health insurance covering Israel",
        "Apostilled + Hebrew-translated diplomas + Yeshiva-specific letter (for Yeshiva students)",
        "Renewable annually for the duration of the programme",
        "MASA program scholarships available for Jewish students aged 18-30 (10-month programmes)",
      ],
      processingTimeDaysMin: 14,
      processingTimeDaysMax: 60,
      applicationUrl: IL_MOF,
      primarySourceUrl: "https://www.gov.il/en/departments/ministry_of_education",
      fees: [
        { amountMinor: 175_00, currency: "ILS", label: "Student visa (ILS 175)" },
      ],
      notes: "Israel's universities + Yeshivas attract international students globally — particularly Jewish-diaspora MASA participants, US/Canadian/Latin American gap-year students, and STEM/medicine programmes at Technion + Hebrew U + Tel Aviv U. English-medium programmes increasingly common.",
      purposeMetadata: { financialProofMonthlyMinor: 80_00, financialProofCurrency: "USD" },
    },
    {
      label: "Volunteer / Religious Visa (A-4) — Israel",
      purpose: "family",
      status: "embassy_visa",
      maxStayDays: 365,
      validityDays: 365,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      proofOfFundsRequired: false,
      biometricsRequired: true,
      requirements: [
        "Sponsorship from Israeli religious institution OR volunteer organisation (Yeshiva, Kibbutz, NGO)",
        "Defined volunteer / religious activity duration",
        "Health insurance covering Israel",
        "Renewable; common for Christian missionaries, Jewish gap-year students (MASA), Kibbutz volunteers",
      ],
      processingTimeDaysMin: 14,
      processingTimeDaysMax: 60,
      applicationUrl: IL_INTERIOR,
      primarySourceUrl: IL_INTERIOR,
      fees: [
        { amountMinor: 175_00, currency: "ILS", label: "A-4 Volunteer visa (ILS 175)" },
      ],
      notes: "Israel's A-4 covers religious vocations + organised volunteer programmes. Particularly common for: Christian Zionist pilgrimage volunteers, ultra-Orthodox Yeshiva students, Kibbutz volunteer programme participants (~30k/year peak).",
    },
    {
      label: "Schengen-Type Business Tourist Visa — Israel (visa nationals)",
      purpose: "business",
      status: "embassy_visa",
      maxStayDays: 90,
      validityDays: 180,
      entriesAllowed: "multiple",
      passportValidityMonthsRequired: 6,
      onwardTicketRequired: true,
      proofOfFundsRequired: true,
      biometricsRequired: true,
      requirements: [
        "For nationalities not on Israel's visa-exempt list (~100 countries are exempt 90 days)",
        "Letter of invitation from Israeli business partner",
        "Travel insurance",
        "Bank statements + employer letter",
        "Multi-entry visas (up to 5 years) for regular business travellers",
      ],
      processingTimeDaysMin: 10,
      processingTimeDaysMax: 21,
      applicationUrl: IL_MOF,
      primarySourceUrl: IL_MOF,
      fees: [
        { amountMinor: 215_00, currency: "ILS", label: "Business Visit Visa (ILS 215)" },
      ],
      notes: "For nationalities not on Israel's visa-exempt list (most of Sub-Saharan Africa, parts of South Asia, Caucasus, some Latin American). Israel's startup ecosystem + diaspora business networks drive substantial inbound business travel — Tel Aviv is the major business hub.",
    },
  ],
});
