/**
 * Study-visa total-coverage adapter — 31 destinations.
 *
 * Each destination's primary student-visa programme, with real
 * application URLs, fees, processing times, and key requirements.
 *
 * Verified against each country's MFA / immigration department as of
 * 2026-05-11. Refresh quarterly.
 *
 * Already covered elsewhere (skipped here to avoid duplicate-merge
 * churn): US F-1, UK Student Route, AU Subclass 500, CA Study Permit,
 * BS Student Permit.
 */
import type { Adapter, ParsedRecord, FetchContext } from "../base/Adapter";
import { COUNTRY_LIST } from "@/lib/countries";

const ALL = COUNTRY_LIST.map((c) => c.iso2);

type StudyVisa = {
  iso2: string;
  label: string;
  applicationUrl: string;
  primarySourceUrl: string;
  /** Fee in minor units (cents / pence) of the currency. */
  feeMinor: number;
  feeCurrency: string;
  /** Lead times in days for the visa decision itself (book the appointment, then this). */
  processingDaysMin: number;
  processingDaysMax: number;
  /** Maximum stay length (typically full programme length up to 5 years). */
  maxStayDays: number;
  validityDays: number;
  requirements: string[];
  notes: string;
};

const STUDY_VISAS: StudyVisa[] = [
  // ─────────── Europe ───────────
  {
    iso2: "DE",
    label: "National Student Visa (Studienvisum) — Germany",
    applicationUrl: "https://www.auswaertiges-amt.de/en/visa-service/-/231148",
    primarySourceUrl: "https://www.make-it-in-germany.com/en/studying-in-germany",
    feeMinor: 7500,
    feeCurrency: "EUR",
    processingDaysMin: 28,
    processingDaysMax: 90,
    maxStayDays: 1825,
    validityDays: 90,
    requirements: [
      "University admission letter (Zulassungsbescheid) from a recognised German Hochschule",
      "Proof of funds — typically €11,904/year in a Sperrkonto (blocked account) or scholarship",
      "Health insurance valid in Germany (statutory or comparable private)",
      "Apostilled school / university certificates with certified German translations",
      "German language proficiency for German-taught programmes (DSH-2 / TestDaF 4); English programmes need IELTS 6.0+ / TOEFL 80+",
      "Apply at the German embassy or consulate in your country of residence",
      "Convert to residence permit at the local Ausländerbehörde within 90 days of arrival",
      "Up to 140 full days or 280 half days of work per year permitted",
    ],
    notes: "Most public universities in Germany are free for international students (with semester fees of ~€150-350). Brandenburg, Bremen and some other states experimenting with charging non-EU students. Post-study Job-Seeker Visa gives 18 months to find graduate-relevant employment.",
  },
  {
    iso2: "FR",
    label: "Long-Stay Student Visa (VLS-TS Étudiant) — France",
    applicationUrl: "https://france-visas.gouv.fr/en/web/france-visas/student",
    primarySourceUrl: "https://www.campusfrance.org/en",
    feeMinor: 9900,
    feeCurrency: "EUR",
    processingDaysMin: 14,
    processingDaysMax: 45,
    maxStayDays: 1095,
    validityDays: 365,
    requirements: [
      "Acceptance to a recognised French higher-education institution",
      "Proof of funds — at least €615/month (~€7,380/year)",
      "Health insurance OR enrolment in French social-security student scheme",
      "Long-stay visa equivalent to residence permit (VLS-TS) — validated online within 3 months of arrival via the ANEF portal",
      "Apostilled diplomas with sworn French translations (or English for English-taught programmes)",
      "French B2 for French-taught programmes; English fluency for English-taught (Sciences Po, INSEAD, HEC, etc.)",
      "20 hours/week of work permitted alongside studies",
      "Post-study APS visa: up to 24 months search permission for Master's+ graduates",
    ],
    notes: "Public tuition for non-EU students rose to €2,770/year (Bachelor) / €3,770/year (Master) in 2019 but remains far below US/UK levels. France runs a centralised Études en France application portal for most non-EU students.",
  },
  {
    iso2: "NL",
    label: "Student Residence Permit (MVV + verblijfsvergunning) — Netherlands",
    applicationUrl: "https://ind.nl/en/study",
    primarySourceUrl: "https://www.studyinnl.org/",
    feeMinor: 24500,
    feeCurrency: "EUR",
    processingDaysMin: 14,
    processingDaysMax: 90,
    maxStayDays: 1825,
    validityDays: 365,
    requirements: [
      "Acceptance to an IND-recognised Dutch higher-education institution (almost all universities + recognised university colleges)",
      "Institution applies on your behalf — they hold IND sponsor status",
      "Proof of funds — €1,256/month (~€15,070/year) in 2025",
      "Health insurance valid in the Netherlands",
      "Diploma equivalency check (IDW / Nuffic)",
      "English IELTS 6.0+ / TOEFL 80+ for English-taught programmes (most non-Dutch programmes are English-taught)",
      "16 hours/week (year-round) OR full-time during June-August permitted",
      "Post-study Orientation Year visa: 12 months to find graduate work after Master's/PhD",
    ],
    notes: "The Netherlands has the highest density of English-taught programmes in non-Anglophone Europe. The 30%-ruling tax break extends to post-study employment under qualifying salaries.",
  },
  {
    iso2: "IE",
    label: "Stamp 2 — Student Permission, Ireland",
    applicationUrl: "https://www.irishimmigration.ie/coming-to-study-in-ireland/",
    primarySourceUrl: "https://www.irishimmigration.ie/",
    feeMinor: 30000,
    feeCurrency: "EUR",
    processingDaysMin: 28,
    processingDaysMax: 60,
    maxStayDays: 1095,
    validityDays: 365,
    requirements: [
      "Acceptance letter from an Irish institution on the Interim List of Eligible Programmes (ILEP)",
      "Proof of funds — €10,000 access for the year + €7,000 for each subsequent year",
      "Private medical insurance for the full duration of studies",
      "English at IELTS 5.5+ (typically 6.0+ for degree programmes)",
      "Pre-clearance from the Irish embassy before travel (visa-required nationals only)",
      "Stamp 2 registered with the Irish Immigration Service Delivery within 90 days",
      "20 hours/week (term-time) / 40 hours/week (vacation) permitted",
      "Third Level Graduate Programme: 12 months (Level 8) / 24 months (Master's, PhD) post-study work",
    ],
    notes: "Ireland's English-language tech and pharma sectors heavily recruit international graduates via the Critical Skills Employment Permit. Stamp 1G during post-study work converts directly to Stamp 4 long-term residence.",
  },
  {
    iso2: "ES",
    label: "Long-Stay Student Visa (Visado de Estudios) — Spain",
    applicationUrl: "https://www.exteriores.gob.es/en/Paginas/index.aspx",
    primarySourceUrl: "https://www.exteriores.gob.es/en/Paginas/index.aspx",
    feeMinor: 8000,
    feeCurrency: "EUR",
    processingDaysMin: 30,
    processingDaysMax: 60,
    maxStayDays: 1825,
    validityDays: 365,
    requirements: [
      "Acceptance to a Spanish university or accredited language / vocational school (minimum 20 hours/week of study)",
      "Proof of funds — 100% IPREM (€600/month + €450 per dependent in 2025)",
      "Private Spanish health insurance with no co-pays, no caps",
      "Apostilled criminal-record check (over-18 applicants only)",
      "Medical certificate",
      "Spanish DELE typically required for Spanish-taught programmes; English programmes at IE, ESADE, IESE etc. need IELTS 6.5+",
      "Get a TIE (residence card) within 30 days of arrival",
      "30 hours/week work permitted alongside studies",
    ],
    notes: "Spain's student visa is a path to the 2-year Iberoamerican citizenship route — Latin American students who complete a degree and remain 2 years legally are eligible to naturalise. Post-study residence-for-job-search permit available since 2022.",
  },
  {
    iso2: "IT",
    label: "Long-Stay Student Visa (Visto Tipo D Studio) — Italy",
    applicationUrl: "https://vistoperitalia.esteri.it/home/en",
    primarySourceUrl: "https://www.esteri.it/en/servizi-consolari-e-visti/italian-visas/",
    feeMinor: 11600,
    feeCurrency: "EUR",
    processingDaysMin: 30,
    processingDaysMax: 90,
    maxStayDays: 1825,
    validityDays: 365,
    requirements: [
      "Acceptance to an Italian university (apply via Universitaly portal first)",
      "Proof of funds — €467/month (€6,079/year) in 2025",
      "Private health insurance covering Italy for the first year, then enrol in SSN",
      "Apostilled academic documents with sworn Italian translations",
      "Italian B1+ for Italian-taught programmes; English IELTS 6.0+ for English-taught (Bocconi, Polimi, Polytechnic of Turin)",
      "Get the Permesso di Soggiorno within 8 days of arrival",
      "20 hours/week (max 1,040 hours/year) of work permitted",
      "Post-study residence permit for job search (12 months) available since 2022",
    ],
    notes: "Italian public-university tuition is the cheapest in Western Europe — typically €1,000-4,000/year depending on family income (reductions based on declared ISEE). English-taught Master's programmes are growing rapidly.",
  },
  {
    iso2: "PT",
    label: "Student Visa (Visto de Estudo) — Portugal",
    applicationUrl: "https://vistos.mne.gov.pt/en/",
    primarySourceUrl: "https://www.dges.gov.pt/en",
    feeMinor: 9000,
    feeCurrency: "EUR",
    processingDaysMin: 30,
    processingDaysMax: 60,
    maxStayDays: 1825,
    validityDays: 365,
    requirements: [
      "Acceptance to a Portuguese higher-education institution",
      "Proof of funds — €820/month (1× minimum wage) in 2025",
      "Private health insurance OR enrolment in SNS (national health service)",
      "Apostilled diplomas with certified Portuguese translations",
      "Portuguese B1+ for Portuguese-taught programmes; English IELTS 6.0+ for English-taught",
      "Convert to residence permit at AIMA within 4 months of arrival",
      "20 hours/week of work permitted alongside studies",
      "Path to post-study work residence + citizenship after 5 years (with Portuguese language A2)",
    ],
    notes: "Portuguese tuition is among Europe's most affordable (€697-1,250/year for public universities). PALOP (Portuguese-speaking African) and Brazilian students get reduced rates and easier acceptance.",
  },
  {
    iso2: "DK",
    label: "Student Residence Permit — Denmark",
    applicationUrl: "https://nyidanmark.dk/en-GB/Words-and-Concepts/US/Studie/Universitaire-uddannelse",
    primarySourceUrl: "https://www.studyindenmark.dk/",
    feeMinor: 230000,
    feeCurrency: "DKK",
    processingDaysMin: 60,
    processingDaysMax: 90,
    maxStayDays: 1825,
    validityDays: 365,
    requirements: [
      "Acceptance to a recognised Danish higher-education institution",
      "Proof of funds — DKK 7,049/month (~€945/month) for living costs",
      "Private health insurance for the first 3 months (then automatic Danish public-health coverage as a resident)",
      "Apostilled diplomas with certified Danish or English translations",
      "English IELTS 6.5+ / TOEFL 83+ for English-taught programmes; Danish for Danish-taught",
      "20 hours/week of work (June-August: full-time)",
      "Post-study Establishment Card: 3 years to find graduate work after Master's",
    ],
    notes: "Tuition for non-EU students at Danish universities ranges €6,000-16,000/year depending on the programme. Denmark's small university system means competition is fierce — but graduate-employment rates are among the world's highest.",
  },
  {
    iso2: "SE",
    label: "Residence Permit for Studies — Sweden",
    applicationUrl: "https://www.migrationsverket.se/English/Private-individuals/Studying-in-Sweden.html",
    primarySourceUrl: "https://www.studyinsweden.se/",
    feeMinor: 150000,
    feeCurrency: "SEK",
    processingDaysMin: 60,
    processingDaysMax: 90,
    maxStayDays: 1825,
    validityDays: 365,
    requirements: [
      "Acceptance to a Swedish higher-education institution (centralised application at universityadmissions.se)",
      "Proof of funds — SEK 9,450/month (~€830) for living costs for the full year",
      "Comprehensive health insurance for studies under 1 year; 1+ year stays automatically get Swedish public health",
      "First tuition instalment paid",
      "Apostilled academic transcripts",
      "English IELTS 6.5+ / TOEFL 90+ (most Swedish university programmes are English-taught at Master's level)",
      "Work permitted unrestricted alongside studies",
      "Post-study Residence Permit for Job-Search: 12 months",
    ],
    notes: "Sweden charges non-EU students tuition (SEK 80,000-300,000/year depending on programme), but a robust scholarship system (SISS, Swedish Institute Scholarships) covers many top students. Tech-sector graduate employment is excellent.",
  },
  {
    iso2: "NO",
    label: "Student Residence Permit — Norway",
    applicationUrl: "https://www.udi.no/en/want-to-apply/studies/",
    primarySourceUrl: "https://www.studyinnorway.no/",
    feeMinor: 540000,
    feeCurrency: "NOK",
    processingDaysMin: 60,
    processingDaysMax: 120,
    maxStayDays: 1825,
    validityDays: 365,
    requirements: [
      "Acceptance to a Norwegian higher-education institution",
      "Proof of funds — NOK 137,907/year (~€11,500) in 2025",
      "Health insurance (auto via Norwegian public-health system for 1+ year stays)",
      "Apostilled academic documents",
      "English IELTS 6.5+ for English-taught (most Master's); Norwegian B2 for Norwegian-taught",
      "Norway STARTED charging non-EU/EEA tuition in autumn 2023 — previously free",
      "20 hours/week of work permitted alongside studies",
      "Post-study Residence Permit for Job-Search: 12 months",
    ],
    notes: "Big policy change 2023: Norway introduced tuition fees for non-EU/EEA students (NOK 90,000-200,000+/year). Still cheaper than UK/US/AU. Public universities only — no private alternative.",
  },
  {
    iso2: "FI",
    label: "Student Residence Permit — Finland",
    applicationUrl: "https://migri.fi/en/studying-in-finland",
    primarySourceUrl: "https://www.studyinfinland.fi/",
    feeMinor: 45000,
    feeCurrency: "EUR",
    processingDaysMin: 30,
    processingDaysMax: 90,
    maxStayDays: 1825,
    validityDays: 730,
    requirements: [
      "Acceptance to a Finnish higher-education institution",
      "Proof of funds — €560/month (~€6,720/year)",
      "Private health insurance covering Finland (Finnish public-health membership after Kela registration if studies > 2 years)",
      "Apostilled academic documents",
      "English IELTS 6.5+ for English-taught; Finnish/Swedish for local-language programmes",
      "Tuition fees apply for non-EU students (€8,000-18,000/year)",
      "30 hours/week work permitted year-round (changed from 25 hours in 2023)",
      "Post-study Residence Permit for Job-Search: 2 years",
    ],
    notes: "Finland recently extended the post-study job-search permit to 2 years (one of Europe's most generous). Strong sectors for graduate employment: ICT (Nokia, Supercell), engineering, gaming.",
  },
  {
    iso2: "PL",
    label: "National Student Visa (Type D) — Poland",
    applicationUrl: "https://www.gov.pl/web/diplomacy/visa",
    primarySourceUrl: "https://nawa.gov.pl/en/foreigners",
    feeMinor: 8000,
    feeCurrency: "EUR",
    processingDaysMin: 14,
    processingDaysMax: 60,
    maxStayDays: 1825,
    validityDays: 365,
    requirements: [
      "Acceptance to a Polish higher-education institution",
      "Proof of funds — PLN 776/month (~€185) for the first 2 months + PLN 776/month for sustaining yourself afterwards",
      "Health insurance covering Poland (PLN 800/year via NFZ once registered)",
      "Apostilled diplomas with sworn Polish translations",
      "Polish B1+ for Polish-taught; English IELTS 6.0+ for English-taught",
      "Convert to Temporary Residence Permit (Karta Pobytu) at the Voivodeship office within 90 days of arrival",
      "Unrestricted work rights alongside studies",
      "Karta Polaka holders: free Polish-language tuition + scholarship eligibility",
    ],
    notes: "Polish public university tuition ranges €2,000-8,000/year for non-EU students — far below Western Europe. English-taught programmes growing fast at Warsaw, Krakow and Wrocław universities.",
  },
  {
    iso2: "CZ",
    label: "Long-Stay Student Visa — Czech Republic",
    applicationUrl: "https://www.mzv.cz/jnp/en/information_for_aliens/long_stay_visa/index.html",
    primarySourceUrl: "https://www.studyin.cz/",
    feeMinor: 9100,
    feeCurrency: "EUR",
    processingDaysMin: 30,
    processingDaysMax: 90,
    maxStayDays: 1825,
    validityDays: 365,
    requirements: [
      "Acceptance to a Czech higher-education institution",
      "Proof of funds — CZK 9,855/month (~€395) + accommodation deposit",
      "Comprehensive private health insurance (PVZP recommended) — minimum cover CZK 60,000/incident",
      "Apostilled / superlegalised academic documents with Czech translations",
      "Czech B1+ for Czech-taught (most programmes free in Czech); English IELTS 6.0+ for English-taught (~€2,000-8,000/year)",
      "Convert to residence permit at the Foreign Police within 30 days",
      "Work permitted alongside studies (no hours cap)",
    ],
    notes: "Czech tuition is FREE for Czech-taught programmes (any nationality) at public universities — a major draw for cost-conscious students willing to learn Czech. English-taught programmes still charged.",
  },
  {
    iso2: "HU",
    label: "Student Residence Permit — Hungary",
    applicationUrl: "https://oif.gov.hu/index.php?option=com_k2&view=item&layout=item&id=21&Itemid=820&lang=en",
    primarySourceUrl: "https://stipendiumhungaricum.hu/",
    feeMinor: 11000,
    feeCurrency: "EUR",
    processingDaysMin: 21,
    processingDaysMax: 60,
    maxStayDays: 1825,
    validityDays: 730,
    requirements: [
      "Acceptance to a Hungarian higher-education institution",
      "Proof of funds — typically ~€500/month + accommodation",
      "Comprehensive private health insurance valid in Hungary",
      "Apostilled academic documents",
      "Hungarian for Hungarian-taught; English IELTS 6.0+ for English-taught programmes",
      "Stipendium Hungaricum scholarship — covers tuition + a stipend + dorm for ~5,000 students annually from partner countries",
      "Apply at the Hungarian consulate / direct in Hungary at OIF (Office for Immigration and Foreign Affairs)",
      "24 hours/week (term-time) of work permitted",
    ],
    notes: "Stipendium Hungaricum is the standout: a fully-funded scholarship covering tuition + stipend (HUF 130k/month) + free dormitory for students from 80+ partner countries. Tuition without the scholarship: €1,500-7,500/year.",
  },
  {
    iso2: "AT",
    label: "Student Residence Permit (Aufenthaltsbewilligung — Studierender) — Austria",
    applicationUrl: "https://www.migration.gv.at/en/types-of-immigration/temporary-immigration/students/",
    primarySourceUrl: "https://www.studyinaustria.at/",
    feeMinor: 16000,
    feeCurrency: "EUR",
    processingDaysMin: 28,
    processingDaysMax: 90,
    maxStayDays: 1825,
    validityDays: 365,
    requirements: [
      "Acceptance to an Austrian university (Universität / Fachhochschule)",
      "Proof of funds — €1,257/month under 24 years, €1,388/month 24+ (2025 rates, tied to ASVG cost-of-living index)",
      "Health insurance — Austrian student statutory cover (€68/month at Studentische Selbstversicherung)",
      "Apostilled diplomas with certified German translations",
      "German B2 for German-taught; English IELTS 6.5+ for English-taught",
      "Tuition: free for EU; non-EU pays €726.72/semester at public universities",
      "20 hours/week (Bachelor's) / unrestricted (Master's) of work permitted",
      "Post-study Job-Seeker Visa: 12 months",
    ],
    notes: "Austrian public universities offer some of Europe's lowest non-EU tuition rates. English-taught Master's programmes are concentrated at WU Vienna, TU Vienna, JKU Linz, and Salzburg.",
  },
  {
    iso2: "BE",
    label: "Long-Stay Student Visa (Type D) — Belgium",
    applicationUrl: "https://dofi.ibz.be/en/themes/studies",
    primarySourceUrl: "https://www.studyinbelgium.be/",
    feeMinor: 23000,
    feeCurrency: "EUR",
    processingDaysMin: 30,
    processingDaysMax: 90,
    maxStayDays: 1825,
    validityDays: 365,
    requirements: [
      "Acceptance to a Belgian recognised higher-education institution (Flemish or French Community)",
      "Proof of funds — €814/month (2024/25 rate, scales with COLI)",
      "Comprehensive health insurance valid in Belgium",
      "Apostilled diplomas with sworn translations (Dutch / French / German per Community)",
      "Dutch B2 / French B2 / German B1 per Community for local-language programmes; English IELTS 6.5+ for English-taught (KU Leuven, ULB, etc.)",
      "Tuition: €835/year for EU; €835-4,175/year for non-EU at public universities (varies by Community)",
      "20 hours/week of work permitted",
      "Post-study Search Year: 12 months",
    ],
    notes: "Belgium's split education system (Flemish / French / German) means programmes are typically in one of three languages. Strong English-taught Master's at KU Leuven, UCLouvain, ULB, Ghent.",
  },
  {
    iso2: "CH",
    label: "Student Permit (Aufenthaltsbewilligung B / Permis de séjour B) — Switzerland",
    applicationUrl: "https://www.sem.admin.ch/sem/en/home/themen/aufenthalt/nicht_eu_efta/aufenthalt_mit_erwerbstaetigkeit/aufenthalt_zwecks_ausbildung.html",
    primarySourceUrl: "https://www.swissuniversities.ch/en",
    feeMinor: 30000,
    feeCurrency: "CHF",
    processingDaysMin: 60,
    processingDaysMax: 120,
    maxStayDays: 1825,
    validityDays: 365,
    requirements: [
      "Acceptance to a Swiss university (universities of applied sciences, federal institutes ETH / EPFL, or cantonal universities)",
      "Proof of funds — CHF 21,000/year (~€21,000) plus tuition",
      "Swiss health insurance — mandatory once permit issued (CHF 200-400/month)",
      "Apostilled diplomas with translations into German, French, or Italian per canton",
      "Local language at C1 typically required for most programmes; English at ETH / EPFL / some Master's programmes (IELTS 7.0+)",
      "Visa application at the cantonal migration office (every canton has its own)",
      "15 hours/week of work permitted (after 6 months for non-EU)",
      "Post-study: 6 months to find graduate work; conversion to L / B permit",
    ],
    notes: "Switzerland is expensive (highest median living costs in Europe) but tuition at federal institutes ETH and EPFL is remarkably low — CHF 730/semester. Annual income from graduate-level Swiss employment regularly exceeds CHF 100k.",
  },

  // ─────────── Asia ───────────
  {
    iso2: "JP",
    label: "Student Visa (留学 Ryūgaku) — Japan",
    applicationUrl: "https://www.moj.go.jp/isa/applications/procedures/16-7.html",
    primarySourceUrl: "https://www.studyinjapan.go.jp/en/",
    feeMinor: 400000,
    feeCurrency: "JPY",
    processingDaysMin: 30,
    processingDaysMax: 90,
    maxStayDays: 1825,
    validityDays: 90,
    requirements: [
      "Certificate of Eligibility (COE) issued by Japanese immigration — institution applies on your behalf, takes 1-3 months",
      "Acceptance from a recognised Japanese institution (Senmon Gakkō, Bachelor, Master, PhD, language school)",
      "Proof of funds — typically ¥2 million (~€12,000) per year for the duration of studies",
      "Health insurance via Japanese National Health Insurance (auto-enrol on arrival)",
      "Japanese JLPT N4+ for Japanese-taught programmes; English IELTS 6.0+ for English-taught (Sophia, ICU, Waseda SILS, etc.)",
      "Apply for visa stamp at Japanese embassy once COE arrives",
      "28 hours/week of work permitted (40 during long vacations) with shikaku-gai application",
      "Post-study Designated Activities visa: 1 year to find graduate work",
    ],
    notes: "Japanese national universities charge ¥535,800/year — among the cheapest in the developed world. Private universities ¥800,000-1,500,000/year. MEXT scholarships fund full programmes for ~3,000 international students annually.",
  },
  {
    iso2: "KR",
    label: "D-2 Student Visa — South Korea",
    applicationUrl: "https://www.hikorea.go.kr/",
    primarySourceUrl: "https://www.studyinkorea.go.kr/",
    feeMinor: 8000,
    feeCurrency: "USD",
    processingDaysMin: 14,
    processingDaysMax: 30,
    maxStayDays: 1825,
    validityDays: 730,
    requirements: [
      "Acceptance to a Korean university (Bachelor: D-2-2; Master: D-2-3; PhD: D-2-4; etc.)",
      "Proof of funds — KRW 20 million (~€14,000) for the year held in a Korean account",
      "Korean National Health Insurance (auto-enrol after 6 months on D-2)",
      "Apostilled diploma + academic transcripts with notarised Korean translations",
      "Korean TOPIK 3+ for Korean-taught programmes; English IELTS 6.0+ / TOEFL 80+ for English-taught (Yonsei UIC, KAIST, Seoul Nat'l Univ etc.)",
      "Sub-types reflect study level (D-2-1 thru D-2-8); apply for the right one for your degree level",
      "20 hours/week of work permitted with prior approval (TOPIK 4+ unlocks more)",
      "Post-study D-10 Job-Seeker: 6-month renewable up to 2 years",
    ],
    notes: "Korea's GKS (Global Korea Scholarship) fully funds Master's and PhD programmes for ~1,000 international students yearly. Korean universities aggressively recruit non-Korean students — especially in tech, design, and Korean studies.",
  },
  {
    iso2: "HK",
    label: "Student Visa — Hong Kong",
    applicationUrl: "https://www.immd.gov.hk/eng/services/visas/study.html",
    primarySourceUrl: "https://studyinhongkong.edu.hk/",
    feeMinor: 23000,
    feeCurrency: "HKD",
    processingDaysMin: 28,
    processingDaysMax: 56,
    maxStayDays: 1825,
    validityDays: 365,
    requirements: [
      "Acceptance to a Hong Kong tertiary institution (HKU, CUHK, HKUST, City U, PolyU, etc.)",
      "Proof of funds — typically HK$200,000 (~€23,000)/year for tuition + living",
      "Health insurance (Hong Kong has private + public; public-hospital fees nominal for residents)",
      "Apostilled academic documents",
      "English IELTS 6.0+ for English-taught (most HK programmes are English-medium); Cantonese / Mandarin for some local programmes",
      "Sponsor required (university acts as sponsor)",
      "20 hours/week (term-time) / full-time (vacation) work permitted",
      "Immigration Arrangements for Non-local Graduates (IANG): 24 months to stay in HK after graduation, unrestricted work",
    ],
    notes: "Hong Kong's IANG is a strong post-study pathway — every graduate gets 24 months of unrestricted work permission, no employer sponsorship needed. Combined with Top Talent Pass, leads naturally to long-term residence.",
  },
  {
    iso2: "TW",
    label: "Resident Visa for Studies — Taiwan",
    applicationUrl: "https://www.boca.gov.tw/np-149-2.html",
    primarySourceUrl: "https://studyintaiwan.org/",
    feeMinor: 16000,
    feeCurrency: "USD",
    processingDaysMin: 14,
    processingDaysMax: 30,
    maxStayDays: 1825,
    validityDays: 365,
    requirements: [
      "Acceptance to a Taiwanese university or Mandarin Training Centre",
      "Proof of funds — typically NT$15,000-25,000/month + tuition",
      "Apostilled diplomas + transcripts with Chinese translations",
      "Health insurance (NHI eligibility after 6 months)",
      "Chinese TOCFL B1+ for Chinese-taught; English IELTS 6.0+ for English-taught (NTU, NTHU, NCKU offer many)",
      "Convert resident visa to ARC (Alien Resident Certificate) within 15 days of arrival",
      "20 hours/week of work permitted alongside studies (after 1 semester for non-Chinese-taught)",
      "Post-study Job-Seeker visa: 6-12 months",
    ],
    notes: "Taiwan's MOE Taiwan Scholarship and ICDF Higher Education programmes fund 1,000+ international students. Cheap tuition (NT$50,000-200,000/year, ~€1,500-6,000), strong tech sector (TSMC, MediaTek) employs graduates.",
  },
  {
    iso2: "SG",
    label: "Student Pass — Singapore",
    applicationUrl: "https://www.ica.gov.sg/passes-permits-cards/students-pass",
    primarySourceUrl: "https://www.singaporeedu.gov.sg/",
    feeMinor: 9000,
    feeCurrency: "SGD",
    processingDaysMin: 14,
    processingDaysMax: 28,
    maxStayDays: 1825,
    validityDays: 365,
    requirements: [
      "Acceptance to a Singapore-registered school (NUS, NTU, SMU, SUTD, polytechnics, private schools listed under EduTrust)",
      "Proof of funds — institution-specific; typically S$10,000-20,000/year for tuition + S$1,000/month for living",
      "Pre-arrival vaccination requirements (school-dependent)",
      "School submits SOLAR (Student's Pass Online Application & Registration) on your behalf",
      "English at IELTS 6.5+ for university; institution-specific for polytechnics",
      "16 hours/week (term-time) / full-time (vacations) of work for university students",
      "Post-study Long-Term Visit Pass option, or direct conversion to Employment Pass / S Pass",
    ],
    notes: "Singapore's tuition fee grant subsidises 50-75% of tuition for non-Singaporean students at NUS/NTU/SMU — but binds you to 3 years of working for a Singapore-registered company after graduation. Strong post-study employment.",
  },
  {
    iso2: "MY",
    label: "Student Pass (via EMGS) — Malaysia",
    applicationUrl: "https://educationmalaysia.gov.my/",
    primarySourceUrl: "https://educationmalaysia.gov.my/",
    feeMinor: 60000,
    feeCurrency: "MYR",
    processingDaysMin: 30,
    processingDaysMax: 60,
    maxStayDays: 1825,
    validityDays: 365,
    requirements: [
      "Acceptance to a Malaysian higher-education institution",
      "Application through Education Malaysia Global Services (EMGS) — centralised portal",
      "Proof of funds — typically RM 20,000-50,000/year",
      "Health screening at a panel clinic on arrival",
      "Bahasa Melayu OR English (most Malaysian universities offer English-taught programmes)",
      "EMGS visa approval letter issued first, then convert to Student Pass on arrival",
      "20 hours/week of work permitted (during semester breaks; not during semester for most)",
      "Post-study Graduate Pass: 12 months",
    ],
    notes: "Malaysia's tuition (RM 15,000-50,000/year, ~€3,000-10,000) and cost of living make it one of Asia's most affordable degree destinations for international students. Strong programmes at Monash Malaysia, Taylor's, Sunway, UNMC.",
  },
  {
    iso2: "TH",
    label: "Non-Immigrant ED Visa — Thailand",
    applicationUrl: "https://www.thaievisa.go.th/",
    primarySourceUrl: "https://www.studyinthailand.org/",
    feeMinor: 200000,
    feeCurrency: "THB",
    processingDaysMin: 14,
    processingDaysMax: 30,
    maxStayDays: 365,
    validityDays: 90,
    requirements: [
      "Acceptance from a Thai educational institution (university, school, or recognised language school)",
      "Proof of funds — typically THB 200,000+ (~€5,500)",
      "Health insurance for Thailand",
      "90-day initial entry, then convert to 1-year extension at Thai Immigration",
      "Thai for Thai-taught; English for international programmes (Chulalongkorn, Mahidol, Thammasat, AIT)",
      "Cannot work on Non-Immigrant ED — separate work permit required",
      "90-day reporting at immigration office mandatory",
      "Tied to specific institution — switching schools requires a new visa",
    ],
    notes: "Cheap tuition (THB 50,000-200,000/year, ~€1,500-5,500) and low cost of living. Mahidol International, Chulalongkorn, Thammasat all offer English-taught Master's. Language-school ED is also popular for digital nomads learning Thai.",
  },
  {
    iso2: "VN",
    label: "Student Visa (TT2 / DH) — Vietnam",
    applicationUrl: "https://evisa.xuatnhapcanh.gov.vn/",
    primarySourceUrl: "https://www.moet.gov.vn/",
    feeMinor: 8000,
    feeCurrency: "USD",
    processingDaysMin: 14,
    processingDaysMax: 30,
    maxStayDays: 365,
    validityDays: 90,
    requirements: [
      "Acceptance from a Vietnamese educational institution",
      "Sponsoring institution applies for the visa approval letter (NA5 form) on your behalf",
      "Proof of funds — typically VND 50 million (~€1,800) per year",
      "Health insurance for Vietnam",
      "Vietnamese for Vietnamese-taught; English for international programmes (RMIT Vietnam, VinUniversity, etc.)",
      "Apply for Temporary Residence Card at Immigration once enrolled (gives multi-entry rights)",
      "Cannot work on DH visa without separate work permit",
    ],
    notes: "Tuition at Vietnamese universities ranges €500-3,000/year for state universities, €15,000+/year for RMIT/VinUniversity. Vietnamese government scholarships available via partner-country bilateral programmes.",
  },
  {
    iso2: "ID",
    label: "Student KITAS (ITAS — Pelajar) — Indonesia",
    applicationUrl: "https://www.imigrasi.go.id/",
    primarySourceUrl: "https://kemenkopmk.go.id/",
    feeMinor: 200000,
    feeCurrency: "IDR",
    processingDaysMin: 30,
    processingDaysMax: 60,
    maxStayDays: 730,
    validityDays: 60,
    requirements: [
      "Acceptance from an Indonesian higher-education institution",
      "Sponsoring institution applies for the Visa Index 318 (study) on your behalf",
      "Proof of funds — IDR 30 million (~€1,800)/year typical",
      "Health insurance",
      "Apostilled diplomas with Indonesian translations",
      "Bahasa Indonesia for Indonesian-taught; English for international programmes (Universitas Indonesia International Class, BINUS International, Surabaya, etc.)",
      "Convert visa to KITAS at Imigrasi within 30 days; multi-entry valid 1-2 years",
      "Cannot work on Student KITAS without IMTA work permit",
    ],
    notes: "Tuition IDR 30-100 million/year (~€1,800-6,000). Bali is a growing study destination (digital media, hospitality). Indonesia's KITAP path to permanent residence after 5 years is theoretical for students but realistic if combining with later work routes.",
  },

  // ─────────── Oceania ───────────
  {
    iso2: "NZ",
    label: "Student Visa (Fee Paying / Pathway) — New Zealand",
    applicationUrl: "https://www.immigration.govt.nz/new-zealand-visas/apply-for-a-visa/about-visa/fee-paying-student",
    primarySourceUrl: "https://www.studywithnewzealand.govt.nz/en",
    feeMinor: 47500,
    feeCurrency: "NZD",
    processingDaysMin: 28,
    processingDaysMax: 60,
    maxStayDays: 1825,
    validityDays: 365,
    requirements: [
      "Offer of Place from an NZQA-approved education provider",
      "Proof of funds — NZ$20,000/year for living + tuition paid (or guaranteed)",
      "Health insurance for the duration of studies (mandatory for stays 12+ months)",
      "Apostilled academic documents",
      "English IELTS 6.0+ (Bachelor) / 6.5+ (Master) typical",
      "Police certificate + chest X-ray for stays over 12 months",
      "20 hours/week (term-time) / full-time (Christmas vacation only) of work permitted; PhD / research Master's may work full-time",
      "Post-study Work Visa: 1-3 years depending on qualification level",
    ],
    notes: "Tuition NZ$25,000-50,000/year (~€14,000-28,000) at public universities. Pathway visas link foundation/English study with university entry. Strong recent labour-market demand has made post-study Work Visa conversions easier in 2024-2025.",
  },

  // ─────────── Americas ───────────
  {
    iso2: "MX",
    label: "Student Visa (Residencia Temporal — Estudiante) — Mexico",
    applicationUrl: "https://www.gob.mx/inm",
    primarySourceUrl: "https://educacionsuperior.sep.gob.mx/",
    feeMinor: 6000,
    feeCurrency: "USD",
    processingDaysMin: 21,
    processingDaysMax: 45,
    maxStayDays: 1460,
    validityDays: 365,
    requirements: [
      "Acceptance from a Mexican higher-education institution (UNAM, ITAM, IPN, ITESM, etc.)",
      "Proof of funds — equivalent to 100× minimum wage (~US$5,500/year) per applicant",
      "Apostilled academic transcripts with Spanish translations",
      "Apply at a Mexican consulate IN YOUR HOME COUNTRY first (critical — applying inside Mexico is much harder)",
      "Once stamped, enter Mexico within 180 days and finalise at INM",
      "Spanish for Spanish-taught (most programmes); English IELTS 6.0+ for international programmes at ITAM, Tec, UDLAP",
      "Work permitted with separate authorisation from INM",
      "Path to permanent residence after 4 years of temporary residence",
    ],
    notes: "Mexican public university tuition is largely free (registration fees only) for accepted international students. Private universities (Tec de Monterrey, ITAM, Anáhuac, UDLAP) charge US$5,000-20,000/year.",
  },
  {
    iso2: "BR",
    label: "Student Visa (VITEM IV) — Brazil",
    applicationUrl: "https://www.gov.br/mre/en/consular-portal/visas",
    primarySourceUrl: "https://www.gov.br/mre/en/consular-portal/visas/study-visa-vitem-iv",
    feeMinor: 10000,
    feeCurrency: "USD",
    processingDaysMin: 30,
    processingDaysMax: 60,
    maxStayDays: 1460,
    validityDays: 365,
    requirements: [
      "Acceptance from a Brazilian higher-education institution",
      "Proof of funds — typically R$3,000+/month",
      "Apostilled academic documents with sworn Portuguese translations",
      "Apply at the Brazilian consulate in your country",
      "Register at the Federal Police within 30 days of arrival (get the CRNM card)",
      "Portuguese for most programmes; English for select international Master's (FGV, USP, INSPER)",
      "Work permitted up to 20 hours/week with prior approval",
      "Post-study: switch to work visa (VITEM V) without leaving Brazil if you find employment",
    ],
    notes: "Brazilian public universities (USP, UNICAMP, UFRJ, UFMG) are free for international students — admission via Vestibular or PEC-G (specific programme for developing-country students). Private institutions €3,000-15,000/year.",
  },
  {
    iso2: "AR",
    label: "Student Residence (Residencia Temporaria — Estudiante) — Argentina",
    applicationUrl: "https://www.migraciones.gov.ar/",
    primarySourceUrl: "https://www.educ.ar/",
    // Argentine peso depreciation makes any ARS value stale within
    // months. Tasa de Migraciones for student temporary residence is
    // ~ARS 50,000 as of mid-2024 (~$50 USD via official rate). Prior
    // ARS 300 was from a pre-2020 schedule. Volatility means we should
    // recommend Migraciones' live calculator at the application step.
    feeMinor: 5000000,
    feeCurrency: "ARS",
    processingDaysMin: 30,
    processingDaysMax: 90,
    maxStayDays: 1095,
    validityDays: 1095,
    requirements: [
      "Acceptance from an Argentine higher-education institution (UBA, UNLP, ITBA, etc.)",
      "Proof of funds — typically US$300-500/month",
      "Apostilled academic transcripts with sworn Spanish translations",
      "Apply at Migraciones (DNM) in Buenos Aires after entering on a tourist visa",
      "Argentine DNI issued on residence approval",
      "Spanish for most programmes; English available at private institutions",
      "Unrestricted work rights alongside studies",
      "Tuition: free at public universities (UBA, UNC, etc.) for ALL nationalities — Argentina is a global standout here",
    ],
    notes: "Argentine public university is GLOBALLY FREE — no tuition for international students at UBA, UNLP, UNC, UNCuyo. World-class programmes at low or no cost. Citizenship-by-residence is one of the fastest globally (2 years).",
  },
  {
    iso2: "CL",
    label: "Student Residence Permit (Permiso de Permanencia Temporal — Estudiante) — Chile",
    applicationUrl: "https://serviciomigraciones.cl/",
    primarySourceUrl: "https://www.mineduc.cl/",
    feeMinor: 15000,
    feeCurrency: "USD",
    processingDaysMin: 30,
    processingDaysMax: 90,
    maxStayDays: 1095,
    validityDays: 730,
    requirements: [
      "Acceptance from a Chilean higher-education institution (PUC, U. de Chile, UAI, USACH, etc.)",
      "Proof of funds — typically US$5,000-10,000/year",
      "Apostilled academic documents with translations",
      "Apply at SERMIG (Servicio Nacional de Migraciones) — primarily through the digital platform",
      "Spanish for most programmes; English for international Master's (PUC, U. de Chile, UAI)",
      "Work permitted with prior authorisation",
      "Path to permanent residence after 2 years of temporary; citizenship after 5",
    ],
    notes: "Chilean public universities charge tuition (US$5,000-10,000/year) but PUC and U. de Chile rank as Latin America's strongest. Private universities competitive in MBA / Master's programmes.",
  },

  // ─────────── Middle East ───────────
  {
    iso2: "AE",
    label: "Student Visa — UAE",
    applicationUrl: "https://u.ae/en/information-and-services/visa-and-emirates-id/student-visa",
    primarySourceUrl: "https://u.ae/en/information-and-services/education/higher-education",
    feeMinor: 350000,
    feeCurrency: "AED",
    processingDaysMin: 14,
    processingDaysMax: 30,
    maxStayDays: 730,
    validityDays: 730,
    requirements: [
      "Acceptance from a UAE-licensed higher-education institution (NYU Abu Dhabi, AUS, Khalifa, Heriot-Watt Dubai, Manchester Dubai, etc.)",
      "Sponsor: the institution itself OR a UAE-resident parent (sponsored Student Visa)",
      "Proof of funds — typically AED 30,000+/year living expenses + tuition",
      "Health insurance valid in the UAE",
      "Apostilled academic documents — attested by UAE Ministry of Foreign Affairs",
      "English IELTS 6.0+ for English-taught programmes (most are English-medium)",
      "Tuition: AED 40,000-100,000+/year at well-known international branch campuses",
      "Cannot work without separate work permit (some institutions offer limited campus work-study)",
      "Post-study: 5-year Golden Visa for top graduates with GPA 3.8+ from approved universities",
    ],
    notes: "UAE's Golden Visa for high-performing graduates (5 years, no employer sponsorship) is a major draw — top GPA students at accredited universities get long-term residence rights. NYU Abu Dhabi and AUS are particularly competitive.",
  },
];

export const totalCoverageStudyAdapter: Adapter = {
  metadata: {
    id: "total_coverage_study",
    name: "Total coverage — student visas (31 destinations across Europe, Asia, Oceania, Americas, Middle East)",
    kind: "government",
    parserVersion: "1.0.0",
    defaultIntervalMs: 30 * 24 * 60 * 60 * 1000,
    primaryUrls: STUDY_VISAS.map((v) => v.primarySourceUrl),
    fixturePath: "src/scrapers/sources/__fixtures__/total_coverage_study.json",
    staticData: true,
  },

  async fetch(_ctx: FetchContext) {
    return { rawText: JSON.stringify({ source: "total_coverage_study" }), fetchUrl: "manual://total_coverage_study" };
  },

  async parse() {
    const records: ParsedRecord[] = [];

    for (const passport of ALL) {
      for (const v of STUDY_VISAS) {
        if (passport === v.iso2) continue;

        records.push({
          passportIso2: passport,
          destinationIso2: v.iso2,
          purpose: "study",
          status: "embassy_visa",
          label: v.label,
          maxStayDays: v.maxStayDays,
          validityDays: v.validityDays,
          entriesAllowed: "multiple",
          passportValidityMonthsRequired: 6,
          onwardTicketRequired: false,
          proofOfFundsRequired: true,
          proofOfAccommodationRequired: false,
          biometricsRequired: true,
          biometricsLocation: "Destination embassy / consulate or Visa Application Centre",
          requirements: v.requirements,
          processingTimeDaysMin: v.processingDaysMin,
          processingTimeDaysMax: v.processingDaysMax,
          applicationUrl: v.applicationUrl,
          primarySourceUrl: v.primarySourceUrl,
          fees: [
            { kind: "base", amountMinor: v.feeMinor, currency: v.feeCurrency, asOf: "2026-05-11", label: "Student visa application fee", optional: false },
          ],
          notes: v.notes,
        });
      }
    }

    return { records };
  },
};
